p4lang/p4c

tools/gen-unified-makefile.py

The recipe for creating new back-ends calls for creating symlinks in the folder `extensions`.

Makefile generator has to follow symlinks

---

tools/gen-unified-makefile.py

Python does not have argument "symlinks" in os.walk(), should be "followlinks"

use followlinks instead of symlinks in tools/gen-unified-makefile.py

---

backends/bmv2/jsonconverter.cpp

This patch marks the scalars header instance that we synthesize in the BMV2 JSON converter as "pi_omit". The plan is to not expose the scalars in PI, since they're an implementation detail and it doesn't really make sense to interact with them via PI directly.

Mark BMV2 JSON scalars as 'pi_omit' so they won't be exposed in PI

---

backends/bmv2/jsonconverter.cpp
backends/bmv2/jsonconverter.h
testdata/p4_16_samples/action_profile-bmv2.p4
testdata/p4_16_samples/action_profile-bmv2.stf
testdata/p4_16_samples_outputs/action_profile-bmv2-first.p4
testdata/p4_16_samples_outputs/action_profile-bmv2-frontend.p4
testdata/p4_16_samples_outputs/action_profile-bmv2.p4

A recent bmv2 update changes how action profile are represented in the
JSON, this commit updates the bmv2 backend accordingly.

Update jsonconverter to use most recent format

---

backends/bmv2/jsonconverter.cpp
backends/bmv2/jsonconverter.h

The bmv2 JSON now includes a __meta__ entry, which for now only includes
version information (version number for JSON format). This commit makes
sure the bmv2 backend includes this entry in the JSON, as some tools
consumming the JSON may start performing a version check.

Add version information to bmv2 JSON

---

ir/node.h

There are no overrides for Node::getNode(), and it seems to me that it would have rather unintuitive results if there were, so unless we have a specific reason to support this, let's mark getNode() final. This has the side benefit of helping the compiler devirtualize the call.

Mark Node::getNode() final

---

backends/bmv2/jsonconverter.cpp

fb654c2 excluded some but not all scalars from PI. We should finish the job and exclude the rest. This will keep the BMV2 JSON -> PI path consistent with p4c's new PI generation path.

More thoroughly exclude scalars from the BMV2 JSON -> PI path

---

backends/bmv2/jsonconverter.cpp

As requested in review for PR #234

Replace BUG_CHECK with error in bmv2 backend

---

backends/bmv2/jsonconverter.cpp
backends/bmv2/jsonconverter.h
testdata/p4_16_samples/verify-bmv2.p4
testdata/p4_16_samples_outputs/verify-bmv2-first.p4
testdata/p4_16_samples_outputs/verify-bmv2-frontend.p4
testdata/p4_16_samples_outputs/verify-bmv2-midend.p4
testdata/p4_16_samples_outputs/verify-bmv2.p4

Added support for error constants in all expressions (not just verify
statements). Also the verify statement in bmv2 now accepts arbitrary
expressions, which enables us to have more general support.

More general support for errors in bmv2 backend

---

backends/bmv2/bmv2.cpp
backends/bmv2/jsonconverter.cpp
backends/bmv2/jsonconverter.h
backends/bmv2/midend.cpp
backends/bmv2/midend.h
midend/convertEnums.h

Starting with version 2.3, the bmv2 JSON supports declaring enums. See
https://github.com/p4lang/behavioral-model/pull/270 for more
information.
The bmv2 backend was already converting enums to integers (under certain
conditions). In this PR, we simply reteieve the mapping enums -> int and
dump it to the JSON file. In order to do this, the ConvertEnums midend
pass had to be slightly modified to give the backend access to the
produced mapping.

Add support for enums in bmv2 backend

---

.travis.yml
Dockerfile
README.md

This PR adds two things:
- A Dockerfile for p4c. The Dockerfile builds against Ubuntu 14.04, which the oldest version we support. It allows us to build and test p4c in a 100% reproducible way and ensure that we don't sneak any unexpected dependencies into the build or accidentally break compatibility with older versions of GCC or Ubuntu. This is handy, but its impact will really be felt only if we run automated tests against this image, which is why this PR also includes...
- Travis CI integration. The included `.travis.yml` builds and runs p4c via Docker, so if there are test failures they'll be 100% reproducible locally. Currently Travis is configured to run the `make check` test suite. Once we clean things up so that `make cpplint` comes back clean, we should enable that in …

Add a Dockerfile and Travis CI integration for p4c

---

frontends/common/resolveReferences/resolveReferences.cpp
frontends/common/resolveReferences/resolveReferences.h
frontends/p4-14/p4-14-parse.ypp
frontends/p4-14/typecheck.cpp
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h
frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeChecker.h
frontends/p4/typeChecking/typeUnification.cpp
ir/base.def
ir/ir.cpp
ir/type.cpp
ir/type.def
ir/v1.cpp
ir/v1.def
ir/visitor.cpp
ir/visitor.h

This fixes a bunch of issues that come up with P4_14 code that use more complex extern objects when translating to P4_16.  Part of the issue is that P4_14 externs may be more capable that P4_16 externs; I'm not completely sure.  The code does not currently try to convert P4_14 extern attributes to constructor arguments, as that seems tough in general, and has difficulty with optional attributes.

P4_14 extern features fixes

---

backends/bmv2/bmv2stf.py
backends/bmv2/run-bmv2-test.py
backends/ebpf/run-ebpf-sample.py
backends/p4test/run-p4-sample.py

The Travis build is failing right now. The cause is that we're running our tests with a timeout, but time behaves strangely in VMs (which is where Travis runs our tests), and so we get timeouts that we don't get locally.
The best bet is to disable the timeouts and rely on Travis's built-in timeout. To make that happen, I've add a `configure` option to disable the test timeouts, updated all of the test running scripts to use it, and added it to the `Dockerfile`.
I tested this in my fork and it fixed the Travis build.

Increase test timeouts to fix the Travis build

---

Dockerfile

This PR updates the Dockerfile to include the behavioral model, which enables the full suite of BMV2 tests to run on Travis.
It will be straightforward to change the repo and tag used to clone `behavior-model` from in the future by modifying the appropriate `ENV` variables. I've used my fork for the time being because I discovered some issues on the `behavioral-model` side while setting this up, but once Antonin merges  p4lang/behavioral-model#277 we can switch over to his repo. (Or we can just wait and update the PR; we'll get it taken care of quickly either way.)

Run p4c tests that require the behavioral model in Travis

---

.travis.yml
Dockerfile

Since we only get two cores on Travis, it makes sense to only use two make jobs. For local builds, IMO we should still default to 8, as that will be the best choice for most developers' machines.
Note that we use `ENV` to persist `MAKEFLAGS` in the Docker image, so the `MAKEFLAGS` value passed to `docker build` will also apply to the `docker run` invocations in `.travis.yml`.
Before merging this, we should verify that it doesn't have a negative effect on our build times on Travis.

Use only two make jobs on Travis

---

.travis.yml
Dockerfile

This PR makes this repo's Dockerfile inherit from the `behavioral-model` Dockerfile. This should speed up the tests considerably, since `behavioral-model` and its dependencies will no longer have to be built as part of the testing process.
The Dockerfile has also been changed to use a style consistent with that used in the `third-party` and `behavioral-model` repos.

Make our Docker image inherit from the behavioral-model Docker image

---

frontends/p4/tableKeyNames.cpp

Changes suggested by @ChrisDodd

Use cstring() instead of the empty cstring

---

ir/visitor.cpp

Ran into this one trying to fix another bug.  Visitor is the common (dynamic, virtual) base class of ControlFlowVisitor and Inspector, so this static_cast should be an unnecessary noop, but clang seems to have a bug in its complex inheritance handling.

Work around dynamic_cast bug in clang

---

lib/cstring.h
lib/gc.h
lib/n4.h
lib/set.h

These dependencies were flagged by a tool chain that is fussier about such things.

Add missing include dependencies in lib files

---

backends/bmv2/jsonconverter.h
frontends/common/name_gateways.h
frontends/p4/frontend.cpp
frontends/p4/p4-parse.h
frontends/p4/parameterSubstitution.h

Add in more missing include dependencies detected by our build environment.

Add missing frontends/backends direct include dependencies

---

frontends/common/options.cpp

You can't run p4c without installing it on macOS right now. The cause is that when searching for the P4 include files, on macOS we attempt to use the approach where we treat `argv[0]` as a relative path, but we don't insert a directory separator. The result is that when you run `./p4c-bm2-ss`, we act as if the compiler is located at a path like `/Users/sfowler/p4c/build./p4c-bm2-ss`, which is obviously wrong. This prevents us from finding the include files, and we can't compile anything. This patch solves this problem. The patch is agnostic as to whether `getcwd()` returns a path with a directory separator at the end; I'm not sure whether this is consistent across platforms.

Provide a directory separator if needed when converting a relative to an absolute path

---

frontends/p4-14/typecheck.cpp
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/programStructure.cpp
ir/ir.def
ir/visitor.h
testdata/p4_14_samples_outputs/selector0-frontend.p4
testdata/p4_14_samples_outputs/selector0-midend.p4
testdata/p4_14_samples_outputs/selector0.p4
testdata/p4_14_samples_outputs/selector1-frontend.p4
testdata/p4_14_samples_outputs/selector1-midend.p4
testdata/p4_14_samples_outputs/selector1.p4
testdata/p4_14_samples_outputs/selector2-frontend.p4
testdata/p4_14_samples_outputs/selector2-midend.p4
testdata/p4_14_samples_outputs/selector2.p4
testdata/p4_14_samples_outputs/selector3-frontend.p4
testdata/p4_14_samples_outputs/selector3-midend.p4
testdata/p4_14_samples_outputs/selector3.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4

- IR::P4Table::getConstProp to get a constant property
- IR::KeyElement::transform_visit to visit a KeyElement and possibly
split it into multiple KeyElements.
These are useful utility functions for backends that need to do things with Table Properties.

Support functions for TableProperties

---

control-plane/p4RuntimeSerializer.cpp

This fixes #308 using the temporary workaround we discussed of reduplicating actions with the same id. As discussed in the code, this will probably need to be revisited, but it's a pragmatic solution for now. Changes in the way naming works in P4-16 may well end up rendering this issue moot.

Deduplicate serialized actions with the same id. Fixes #308

---

control-plane/p4RuntimeSerializer.cpp

Right now p4RuntimeSerializer doesn't correctly handle the `valid` match type (or `isValid()` in P4-16). There were several issues:
- We serialized the synthesized valid field inconsistently; in one place, we used `_valid`, while in the other place, we used `$valid$`.
- We didn't append the synthesized valid field when serializing exact match keys.
- We appended it at the wrong *time* when serializing ternary match keys, which caused a crash.
All of this would've easily been avoided with a proper unit test suite. =\ I need to hurry up and add gtest to p4c.

Desugar valid matches correctly in p4RuntimeSerializer

---

control-plane/p4RuntimeSerializer.cpp
frontends/Makefile.am
frontends/p4/externInstance.cpp
frontends/p4/externInstance.h

This PR adds support for direct counters and direct meters in p4RuntimeSerializer and addresses something other existing issues along the way.
455c196 fixes #302 by adding an ExternInstance help class, akin to MethodInstance, which provides information about the extern instance referenced by an expression. It handles both PathExpressions which refer to a Declaration_Instance by name and ConstructorCallExpressions which create an anonymous extern instance. These are the two common cases that we need to support in p4RuntimeSerializer, though it's possible that in the future there would be others which would be useful to add.
3d3ce5c fixes #311 by actually adding support for serializing direct counters and meters in p4RuntimeSerializer. A little bit of metaprogramming is used to make this …

Support direct counters and direct meters in p4RuntimeSerializer

---

control-plane/p4RuntimeSerializer.cpp
frontends/p4/fromv1.0/programStructure.cpp
testdata/p4_14_samples_outputs/bridge1-frontend.p4
testdata/p4_14_samples_outputs/bridge1-midend.p4
testdata/p4_14_samples_outputs/bridge1.p4
testdata/p4_14_samples_outputs/instruct5-frontend.p4
testdata/p4_14_samples_outputs/instruct5-midend.p4
testdata/p4_14_samples_outputs/instruct5.p4
testdata/p4_14_samples_outputs/parser_dc_full-frontend.p4
testdata/p4_14_samples_outputs/parser_dc_full-midend.p4
testdata/p4_14_samples_outputs/parser_dc_full.p4

In #309, we noticed two issues:
* The P4Runtime output we're generating has way too many `NoAction` entries.
* If a table has *any* default action, we serialize it as a `const_default_action_id` in P4Runtime, even if the default action isn't const.
These two things turn out to be related.
Explicit P4-14 default actions are all "const" from a P4-16 perspective. They're fixed at compile time, and the control plane can't change them. (The control plane may be able to change the associated *action data*, though, but that's a separate issue.)
The P4-16 non-const default action is more or less equivalent to not specifying a default action at all in P4-14. The only difference is that P4-16 allows you to set the initial state of the default action, while in P4-14, the initial state is always …

Handle const default actions correctly in P4-14 and P4Runtime serialization

---

backends/bmv2/jsonconverter.cpp
backends/bmv2/jsonconverter.h
frontends/p4/fromv1.0/v1model.h
testdata/p4_16_samples/issue297-bmv2.p4
testdata/p4_16_samples_outputs/issue297-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue297-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue297-bmv2.p4

that this fix allows action_profile objects to be declared outside tables. As a side-effect, this change will enable the sharing of an action_profile between multiple tables.
Note that this fix does not allow action_selectors to be declared outside tables, just action_profiles.

Fix for issue #297

---

frontends/p4-14/typecheck.cpp
frontends/p4-14/typecheck.h
ir/v1.cpp
testdata/p4_14_samples_outputs/copy_to_cpu.p4
testdata/p4_14_samples_outputs/packet_redirect-frontend.p4
testdata/p4_14_samples_outputs/packet_redirect-midend.p4
testdata/p4_14_samples_outputs/packet_redirect.p4
testdata/p4_14_samples_outputs/packet_redirect.p4-stderr
testdata/p4_14_samples_outputs/simple_nat.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch.p4
testdata/p4_14_samples_outputs/switch_20160226/switch.p4-stderr
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4-stderr

We infer different types for action parameters than `p4c-bm` on a number of our internal test cases. I investigated, and it turns out that there are a few different issues in the P4-14 type inference algorithm that contribute to this problem. This PR fixes those issues.
ef71fd6 adds type inference information for the `clone_spec` operand of the various `clone` primitives. Previously, this operand was defaulting to `Type_Unknown`.
This didn't fix most of my test cases, and the reason turned out to be that the P4-14 type inference passes are Modifiers. This implies that, by default, they only visit each node once. However, TypeCheck::Pass1, we replace all references to an action argument with the ActionArg node they refer to. This means that only the first reference the type inference …

Infer types correctly for P4-14 action parameters and clone primitives

---

ir/visitor.cpp
ir/visitor.h

Somewhat messy way of avoiding compile time warnings for various build settings.

clean up override warning for NDEBUG builds

---

backends/bmv2/jsonconverter.cpp
frontends/p4/fromv1.0/v1model.h
testdata/p4_16_samples/action_selector_shared-bmv2.p4
testdata/p4_16_samples/action_selector_shared-bmv2.stf
testdata/p4_16_samples_outputs/action_selector_shared-bmv2-frontend.p4
testdata/p4_16_samples_outputs/action_selector_shared-bmv2-midend.p4
testdata/p4_16_samples_outputs/action_selector_shared-bmv2.p4

In the bmv2 backend. We basically added a pass to the backend which
ensures that when several match tables share the same action_selector,
the selector input is the same across all tables.

Enable sharing an action_selector between tables

---

lib/cstring.cpp
lib/cstring.h
lib/stringref.h

I was writing some cstring-heavy code recently and this prompted me to take a look at cstring.h. I was glad I did, because it turned out I hadn't quite understood how cstring was intended to behave! Though I know there is documentation of cstring elsewhere, I felt like this was a sign that it'd be good to have some documentation in the code. 70c2aa3 contains everything I've learned about cstring so far; if I've misunderstood or missed anything, let me know! fa5adaf builds on that with a little bit of cleanup.
In the course of putting cstring under the lens I noticed a couple of minor issues that I've also fixed in this PR.
c21f56f adds a cstring constructor which takes a pair of iterators; this is necessary for many STL and Boost algorithms to work.
3fa944e removes a performance gotcha …

cstring spring cleaning

---

control-plane/p4RuntimeSerializer.cpp

This PR brings p4c's p4RuntimeSerializer code up to date with the latest P4Info changes. The update adds some new features, but the main story is that it's the beginning of a refactoring that will eventually result in removal of header fields and header field lists from the P4Info schema. To accomplish the switch, the plan is to generate P4Info that supports both the old and the new approaches simultaneously, and then phase out the old approach. This PR begins that process by adding support for the main features of the new approach.
5e04f2c updates p4c's submodule to the newest revision of the PI repo.
af47c9f adds support for aliases, which give an additional, shorter name to P4 objects. The way that aliases interact with the existing set of annotations needs some thought, so I took an …

Update P4Runtime to begin the phase-out of header fields

---

frontends/common/options.cpp
frontends/common/options.h
frontends/common/parseInput.cpp

Add an option to skip preprocessing in p4c, to give user the flexibility to separate preprocessing from compilation. Driver may choose to call cpp directly without going through p4c.

add option to skip preprocess

---

backends/bmv2/bmv2stf.py

Changes the interface variable into an integer, so that it avoids alphabetical order which results in a BMV2 deadlock.
Fixes #373

support for double digit ports

---

backends/bmv2/bmv2stf.py
backends/bmv2/run-bmv2-test.py
frontends/p4/frontend.cpp
frontends/p4/frontend.h
testdata/p4_14_samples/misc_prim.p4
testdata/p4_14_samples_outputs/misc_prim-frontend.p4
testdata/p4_14_samples_outputs/misc_prim-midend.p4
testdata/p4_14_samples_outputs/misc_prim.p4

These relate to #367, in that they are minor cleanups that help with it, plus a test case that is problematic.
The ability to disable the SideEffectOrdering pass is a bit of a hack -- it is problematic in that it introduces too many unneeded copies that are too hard to get rid of, and isn't really necessary for most targets.  It should probably be a midend pass rather than a frontend pass in the first place.

Three minor changes

---

frontends/p4/def_use.cpp
lib/ordered_set.h

Fixed a non-determinism issue for a large switch profile.  Essentially iteration over a set was not ordered.

Non Determinism Issue in Def_Use passes

---

control-plane/p4RuntimeSerializer.cpp

As discussed in #395, this patch removes leading dots from control plane names in the P4Runtime serializer.
Although currently special behavior for leading dots in `@name` is only implemented for actions, I've gone ahead and implemented this feature for all object types. (Doing otherwise seems a bit error-prone.)

Strip leading dot from control plane names in p4RuntimeSerializer

---

Makefile.am
configure.ac
control-plane/Makefile.am

Some snafus in our build system have resulted in warnings not being enabled for much of the codebase. This PR fixes this.
I'd love to enable `-Werror` for at least some classes of warnings, but there are currently too many warnings in the codebase to do that. We can work to fix them, and then enable `-Werror` to ensure more don't show up.

Enable warnings globally

---

backends/bmv2/jsonconverter.cpp
backends/bmv2/lower.h
backends/bmv2/midend.cpp
backends/ebpf/ebpfType.h
control-plane/p4RuntimeSerializer.cpp
frontends/common/options.cpp
frontends/p4-14/typecheck.cpp
frontends/p4/def_use.h
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/v1model.h
lib/crash.cpp
midend/simplifySelectList.h

This PR fixes all warnings reported on master by clang. (Including one which was introduced by me just today, doh!) There may still be some GCC-only warnings remaining, but this moves us closer to where we want to be.

Fix all warnings reported by clang-800.0.42.1

---

midend/removeReturns.cpp
testdata/p4_16_samples/bfd_offload.p4
testdata/p4_16_samples_outputs/bfd_offload-first.p4
testdata/p4_16_samples_outputs/bfd_offload-frontend.p4
testdata/p4_16_samples_outputs/bfd_offload.p4
testdata/p4_16_samples_outputs/bfd_offload.p4-stderr

- BlockStatements in the initializers of Delcaration_Instances, whicha re not under controls or actions.

avoid crashing in removeReturns for BlockStatements

---

frontends/common/resolveReferences/referenceMap.cpp

The `BUG_CHECK` indicates that `result` may be `NULL`, but the log message dereferences it.  This PR guards the log message against that case.

Guard against a possible null pointer dereference.

---

frontends/common/constantFolding.cpp
testdata/p4_16_errors/issue401.p4
testdata/p4_16_errors_outputs/issue401.p4
testdata/p4_16_errors_outputs/issue401.p4-stderr

The IR::Cast case had a bug where it assumed that a constant was either a boolean or numeric literal. This pull request adds an extra case to handle list literals.
Fixes #401.

Handle list literals in IR::Cast case in constantFolding.cpp

---

backends/bmv2/Makefile.am
backends/bmv2/jsonconverter.cpp
backends/bmv2/midend.cpp
backends/p4test/Makefile.am
frontends/p4/fromv1.0/converters.cpp
frontends/p4/tableKeyNames.cpp
ir/expression.def
midend/simplifyKey.h
testdata/p4_14_samples/exact_match_mask1.p4
testdata/p4_14_samples/exact_match_mask1.stf
testdata/p4_14_samples_outputs/exact_match_mask1-first.p4
testdata/p4_14_samples_outputs/exact_match_mask1-frontend.p4
testdata/p4_14_samples_outputs/exact_match_mask1.p4

This fixes the P4_14->P4_16 converted to not generate completely invalid code for this case, but it still causes problems in the typechecker when the mask is disjoint.
Trying to split such disjoint masks into multiple key elements would be possible, but its not clear how the name/API should be managed for the result.  Easiest would be if P4_16 supported mask expressions in keys like P4_14 -- see issue #404

Fix slice generation for table keys in P4_14->16 conversion

---

control-plane/p4RuntimeSerializer.cpp

It has been decided to stop using 0 in ids for action parameters and
table match fields. This is because in protobuf 3, 0 is the default
value for integers and there is an ambiguity between an id that has been
set to 0 and an id that wasn't set. Additionally this is more
consistent with the way ids used to be allocated (0 was used exclusively
as an invalid id).

Stop using 0 for params and match fields ids

---

frontends/p4-14/p4-14-lex.l

Trivial fix for a corner case -- a bare `@pragma` by itself on a line, or something like `@pragma !$#%`, which will become the annotation `@pragma("!$#%")`

handle bare @pragma line in P4_14 (convert to @pragma annotation)

---

.dockerignore
.travis.yml
Dockerfile

This PR makes several changes to the Dockerfile to bring it in sync with changes made in upstream repos:
- It's now based on Ubuntu 16.04.
- It's built from the `stable` tag of `behavioral-model`.
- It supports different image variants for normal builds and testing. This lets downstream repos which don't need to run the tests use a smaller version of the image. (To support this, we need to install p4c globally in the Dockerfile, so we now run `make install`.) The approach is the same one we used in the `behavioral-model` repo.
- Just as in upstream repos, we're now excluding unneeded files via a `.dockerignore` file.

Update the Dockerfile for stable, Ubuntu 16.04-based builds

---

backends/bmv2/bmv2.cpp
control-plane/p4RuntimeSerializer.cpp
control-plane/p4RuntimeSerializer.h
frontends/common/options.cpp
frontends/common/options.h

This is an alternative to the JSON format for debugging / testing /
manual editing. Because we now support 3 formats: binary, json and text,
it made sense to update the command line options support to use a
choice-type argument instead of having a flag for each format. Therefore
this introduces '--p4runtime-format' and deprecates
'--p4runtime-as-json'.

Add support for writing P4Runtime in text format

---

ir/visitor.cpp

The ChangeTracker class kept state in two ways: Internally to the ChangeTracker object, and in change_t objects returned to clients for each object being tracked.
The change_t objects mostly just pointed to the internal ChangeTracker state.  Presumably things were set up this way to allow more sophisticated visitor behavior, where the handle to the original node might be lost but could be recovered through the change_t tracker.  However, this doesn't seem to be used, and it complicates the code.
This PR removes change_t objects and replaces them with calls to the ChangeTracker object.  It also adds documentation and removes many of the "first"/"second" names that made the code hard to read.

Refactor and document change tracker

---

configure.ac

This patch adds a check in configure.ac that p4c is being built with a supported compiler version. I check for GCC 4.9 or Clang 3.3.

Check compiler version in configure.ac

---

test/gtest/gtestp4c.cpp
test/gtest/helpers.cpp
test/gtest/helpers.h

In P4 programs or program fragments embedded in GTests, we'd often like to use the standard P4 headers. We have a mechanism for doing this for `core.p4` right now, but it's inefficient (we reread `core.p4` every time) and it adds visual noise to the test. This PR improves on the existing mechanism by:
- Adding a global test environment that caches the contents of `core.p4` and `v1model.p4`, so we don't need to reread them for every test that uses them.
- Merging the functionality for prepending the contents of these headers into the `P4_SOURCE` macro we're already using. This reduces visual noise and also lets us reduce the number of string copies we perform.

Easily and efficiently use standard P4 headers in GTests

---

Makefile.am

Here's the fix for the `make recheck` bug that some team members have been encountering. For details, please check the comment in the patch.
If there's a nicer way to handle this, I'd love to hear about it. =)

Work around automake bug related to recheck

---

test/gtest/arch_test.cpp
test/gtest/midend_test.cpp

Here's the fix for #480. Just a search and replace.
It's an unfortunate issue with GTest, especially since they did it *deliberately*, but it's not too bad to use `ASSERT_TRUE` for null checks instead.

Use ASSERT_TRUE when checking nullness in GTests

---

Dockerfile

In p4lang/third-party#7 we'll stop persisting MAKEFLAGS in the environment in upstream images. That means we need to add a MAKEFLAGS build arg to this Dockerfile if we want to retain parallel builds.

Add a build arg to p4c's Dockerfile to specify MAKEFLAGS

---

control-plane/p4RuntimeSerializer.cpp
ir/ir.def

This PR implements P4Runtime serializer support for annotations on action parameters and match keys.
I had to make KeyElement implement IAnnotated; this is just an oversight of the current code, since KeyElement already contains a list of annotations.

Support annotations for actions params and match keys. (#463)

---

Dockerfile

We can't run PTF/P4Runtime tests without having P4Runtime available. I suspect we'll eventually want to do that in p4c, but before we get to that point we have a more immediate need for both p4c and P4Runtime in downstream images.
Once we make this change, we could just grab the installed P4Runtime protobuf headers and get rid of the PI submodule. The tradeoff for doing that is that people who want to build p4c will also need to build and install P4Runtime. That seemed like too complicated an issue to decide in this PR, so for now I've left the PI submodule in place.

Inherit from the PI docker image

---

control-plane/p4RuntimeSerializer.cpp

In reaction to the following PI update: https://github.com/p4lang/PI/pull/135

Add support for new ActionRef message in p4runtime

---

backends/bmv2/jsonconverter.cpp
testdata/p4_16_samples/table-entries-valid-bmv2.p4
testdata/p4_16_samples_outputs/table-entries-valid-bmv2-first.p4
testdata/p4_16_samples_outputs/table-entries-valid-bmv2-frontend.p4
testdata/p4_16_samples_outputs/table-entries-valid-bmv2-midend.p4
testdata/p4_16_samples_outputs/table-entries-valid-bmv2.p4

Trivial fix to print the json boolean value.

writes out json boolean values for valid match keys.

---

backends/bmv2/jsonconverter.cpp
frontends/p4-14/typecheck.cpp
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/programStructure.cpp
midend/validateProperties.h
testdata/p4_14_samples_outputs/instruct1-first.p4
testdata/p4_14_samples_outputs/instruct1-frontend.p4
testdata/p4_14_samples_outputs/instruct1-midend.p4
testdata/p4_14_samples_outputs/instruct1.p4
testdata/p4_14_samples_outputs/instruct5-first.p4
testdata/p4_14_samples_outputs/instruct5-frontend.p4
testdata/p4_14_samples_outputs/instruct5-midend.p4
testdata/p4_14_samples_outputs/instruct5.p4
testdata/p4_14_samples_outputs/parser_dc_full-first.p4
testdata/p4_14_samples_outputs/parser_dc_full-frontend.p4
testdata/p4_14_samples_outputs/parser_dc_full-midend.p4
testdata/p4_14_samples_outputs/parser_dc_full.p4
testdata/p4_14_samples_outputs/port_vlan_mapping-first.p4
testdata/p4_14_samples_outputs/port_vlan_mapping-frontend.p4
testdata/p4_14_samples_outputs/port_vlan_mapping-midend.p4
testdata/p4_14_samples_outputs/port_vlan_mapping.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4

- support for direct registers
- support for registers with layout instead of width

P4_14 register related fixes

---

frontends/p4/resetHeaders.cpp
frontends/p4/resetHeaders.h

Also format `DoResetHeaders::generateResets` signature to be less than 80 characters wide.

Add Doxygen comments for the ResetHeaders pass.

---

backends/bmv2/bmv2.cpp
backends/ebpf/p4c-ebpf.cpp
backends/p4test/p4test.cpp
lib/exceptions.h
test/unittests/exception_test.cpp

Adds a new type of P4Exception: CompilerUnimplemented to replace
instances where we use BUG/BUG_CHECK as a placeholder for features
that we have not yet implemented.
Also adds exception catching in the compiler drivers, such that the
compiler exits cleanly.

adds an unimplemented exception and exception catching in drivers

---

README.md

Looks like the anchors Github generates for Markdown sections are in all lower-case, which prevents the internal links in README.md from working.

Fix internal links in README.md

---

control-plane/p4RuntimeSerializer.cpp

GCC warns that P4RuntimeSymbol::piResourceType() may fail to return a value on all code paths, which is not true - the switch block is exhaustive. (As clang correctly recognizes.) This PR adds a BUG statement to make GCC happy.

Work around spurious GCC warning in P4RuntimeSymbolTable::piResourceType()

---

backends/bmv2/jsonconverter.cpp
testdata/p4_16_samples/action_selector_unused-bmv2.p4
testdata/p4_16_samples_outputs/action_selector_unused-bmv2-first.p4
testdata/p4_16_samples_outputs/action_selector_unused-bmv2-frontend.p4
testdata/p4_16_samples_outputs/action_selector_unused-bmv2-midend.p4
testdata/p4_16_samples_outputs/action_selector_unused-bmv2.p4
testdata/p4_16_samples_outputs/action_selector_unused-bmv2.p4-stderr

When an action selector is declared as a control local but never
referenced by a table, the compiler cannot figure out the selector
input, which means the action selector cannot be included in the bmv2
JSON.

Fix bmv2 backend crash for unused action selectors

---

frontends/parsers/p4/p4parser.ypp
frontends/parsers/v1/v1parser.ypp

The version requirement for the grammars was set conservatively, but these grammars should work on any Bison 3.x release. This PR lowers the requirement.

Lower Bison version requirement

---

.travis.yml

Since we stopped persisting the `MAKEFLAGS` environment variable in the image, we need to pass it in manually when running the tests. Failing to do this was doubling the length of time our tests took to run.

Run tests with MAKEFLAGS=-j2

---

Dockerfile
README.md
configure.ac

This PR makes a few improvements to the dependency checks in `configure.ac`:
- We now explicitly depend on `libfl-dev`. For some reason Debian (and thus Ubuntu) decided to split out some of the files included with flex, including `FlexLexer.h` which we depend on, into a separate package. This issue wasn't noticed until Mihai ran into it because the package is installed as a dependency of something else in our Docker CI environment. No change is necessary on macOS; a full flex installation comes with the system by default.
- We don't depend `constraint_solver.h` (which is from Google OR-Tools), so we shouldn't be checking for it.
- We don't need to check for ranlib; `LT_INIT` takes care of it. The `AC_PROG_RANLIB` check was triggering warnings from autoconf.

Improve dependency checks in configure.ac

---

frontends/common/constantFolding.cpp
frontends/common/constantFolding.h
frontends/p4/frontend.cpp
testdata/p4_16_errors/stack3.p4
testdata/p4_16_errors_outputs/stack3.p4
testdata/p4_16_errors_outputs/stack3.p4-stderr
testdata/p4_16_samples/stack2.p4
testdata/p4_16_samples_outputs/stack-first.p4
testdata/p4_16_samples_outputs/stack2-first.p4
testdata/p4_16_samples_outputs/stack2-frontend.p4
testdata/p4_16_samples_outputs/stack2-midend.p4
testdata/p4_16_samples_outputs/stack2.p4
testdata/p4_16_samples_outputs/struct-first.p4
testdata/p4_16_samples_outputs/struct1-first.p4

Do not merge yet! 
Submitting this pull request for comments. More documentation and tidying are needed 
The current version of constant folding has two bugs:
1. It does not fold constants in all cases, or check that declaration constants are initialized with genuine constants. For example, on the input program,
```
const T t = { 32s10, 32s20 };
const S s = { { 32s15, 32s25}, t };
const int<32> x = t.t1;
const int<32> y = s.s1.t2;
const int<32> w = .t.t1;
const T t1 = (T)s.s1;
```
constant folding (with type information) yields:
```
const T t = { 32s10, 32s20 };
const S s = { { 32s15, 32s25 }, t };
const int<32> x = 32s10;
const int<32> y = 32s25;
const int<32> w = 32s10;
const T t1 = { 32s15, 32s25 };
```
Note that the RHS of the declaration of `s` is not a constant -- it contains the …

constant folding streamlining, bugfixes, and Doxygen comments

---

ir/node.cpp
lib/source_file.cpp

- Also fix off-by-one error tracking stdin line number
I think there are more off-by-one errors in the linenumber tracking code, combined with various +1/-1 adjustments in random places to correct for them.  Much of this comes from #line directives containing the line number of the next line, not the line number of the #line directive itself.

Don't use an invalid srcInfo to construct json source info.

---

frontends/common/resolveReferences/referenceMap.h
frontends/common/resolveReferences/resolveReferences.cpp
frontends/common/resolveReferences/resolveReferences.h

Also, refactor so that all booleans used to control forward resolution
are oriented in the same direction.

Add Doxygen documentation for ResolveReferences

---

backends/bmv2/JsonObjects.cpp
backends/bmv2/expression.cpp
backends/bmv2/extern.h
backends/bmv2/helpers.cpp
backends/bmv2/helpers.h
backends/bmv2/midend.cpp
backends/bmv2/parser.cpp
backends/bmv2/parser.h
backends/ebpf/codeGen.cpp
backends/ebpf/codeGen.h
backends/ebpf/ebpfProgram.h

Some users compile this code with their own build system. Recent changes in the bmv2 backend have broken non-unified builds (`max-chunk-size` set to 1 in `bootstrap.sh`).

Fix non unified build

---

backends/ebpf/ebpfType.cpp
control-plane/p4RuntimeSerializer.cpp
frontends/p4/def_use.cpp
frontends/p4/def_use.h
frontends/p4/methodInstance.cpp
frontends/p4/methodInstance.h
frontends/p4/resetHeaders.cpp
frontends/p4/toP4/toP4.h
frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeChecker.h
frontends/p4/validateParsedProgram.cpp
frontends/p4/validateParsedProgram.h
frontends/parsers/p4/p4parser.ypp
ir/type.def
midend/interpreter.cpp
testdata/p4_16_errors/issue561-1.p4
testdata/p4_16_errors_outputs/issue561-1.p4
testdata/p4_16_errors_outputs/issue561-1.p4-stderr
testdata/p4_16_samples/issue561.p4
testdata/p4_16_samples/struct.p4
testdata/p4_16_samples_outputs/issue561-first.p4
testdata/p4_16_samples_outputs/issue561-frontend.p4
testdata/p4_16_samples_outputs/issue561-midend.p4
testdata/p4_16_samples_outputs/issue561.p4
testdata/p4_16_samples_outputs/issue561.p4-stderr
testdata/p4_16_samples_outputs/struct-first.p4
testdata/p4_16_samples_outputs/struct-frontend.p4
testdata/p4_16_samples_outputs/struct.p4

I renamed the IR node to header_union, in case we ever get a real union. Most changes are due to this renaming.
Def-use analysis now handles unions; not many changes were required.
Also, changed the grammar to allow empty list expressions - good for initializing empty structs.

Front-end support for header_unions

---

backends/ebpf/codeGen.cpp
backends/ebpf/ebpfParser.cpp
frontends/p4/def_use.cpp
frontends/p4/simplifyDefUse.cpp
frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/unusedDeclarations.cpp
ir/expression.def
ir/ir.def
ir/v1.def
ir/visitor.h
midend/inlining.cpp
midend/local_copyprop.cpp
midend/moveConstructors.cpp
midend/removeReturns.cpp

I'm of mixed feelings about whether this makes things easier, or more obscure.
The change adds overloads to Visitor so that visit_children routines need only call `visit` (or `parallel_visit`) for each field, rather than calling `visit` for non-inline fields and `visit_children` for inline fields.  It simplifies things in that you don't have to think as much about whether a field is inline or not but is a little more obscure in that you may not notice when a field is inline.  When you have an inline field, you never actually visit the field object instance at all -- that's the whole point of inline: a level of indirection goes away and all the children act as if they were direct children of the containing object.

Visitor additions to clean up custom visitor routines a bit.

---

backends/bmv2/control.cpp

In the bmv2 JSON, a match-table can indicate that its default action is
constant (using 'action_const') and that the default action entry
(action + action parameter values) is constant (using
'action_entry_const'). `action_entry_const == true => action_const ==
true`. The bmv2 backend was setting 'action_entry_const' correctly, but
'action_const' was always set to false. Note that P4_16 does not make a
difference between the 2, the presence of `const` in the P4_16 source
implies that both attributes should be true.

Minor change in bmv2 backend: set action_const

---

frontends/p4/typeChecking/typeChecker.cpp
p4include/core.p4

The P4-16 spec has removed the two-argument emit method of packet_out.

Fix for issue #629

---

.travis.yml
Makefile.am
tools/cpplint.py

I am not sure this is the best way to do this, but it seems to work.

Fix for issue #619

---

Makefile.am
backends/bmv2/Makefile.am
control-plane/p4RuntimeSerializer.cpp
ir/visitor.h
lib/error.h
test/Makefile.am
test/gtest/gtestp4c.cpp

This PR adds a number of facilities that make it easier to write GTests. I'm using these features in other PRs (which haven't landed yet, obviously) and they've been quite helpful. The changes included:
- Helpers for writing simple IR traversals using lambdas. `forAllMatching`, which behaves like a postorder Inspector which only matches a single node type, was already being used in the `p4RuntimeSerializer` code; I've just moved it to `visitor.h` so other code can use it. I also added Modifier and Transform variations of the concept.
- I reworked the Makefile a little bit to make it easier to link additional libraries into the GTest executable. This is necessary to cleanly add GTests in extensions.
- I generalized the types that you can pass to `BUG()` a little bit.
- I added a helper to …

Add utilities that make writing GTests easier

---

frontends/parsers/p4/p4parser.ypp

This PR fixes a (harmless) instance of undefined behavior in `p4parser.ypp`. See the comment in the patch for more details.

Fix undefined behavior in p4parser.ypp

---

backends/p4test/p4test.cpp
ir/indexed_vector.h
ir/ir-inline.h
ir/ir.h
ir/json_loader.h
ir/namemap.h
ir/node.cpp
ir/vector.h
test/unittests/dumpjson.cpp
tools/ir-generator/irclass.cpp

Here's a PR I've summoned from an old branch.
p4c takes a long time to compile, and one of the biggest factors is duplicate template instantiations in different translation units. We've worked around this to some degree with unified builds, but it'd be much better to resolve the underlying problem.
This patch takes one small step in that direction by eliminating the need to include `json_loader.h` in `ir.h`. This is accomplished by adding forward declarations for `JSONLoader` where needed (including in `ir-generated.cpp`) and moving the code that references `JSONLoader` from `ir-inline.h` into `json_loader.h` itself.
I had tried to do the same for `json_generator.h`, but while I have a patch that does it, it requires some icky explicit template instantiations. Getting rid of it cleanly …

Don't include json_loader.h in ir.h

---

backends/bmv2/control.cpp
backends/bmv2/simpleSwitch.h
frontends/p4/fromv1.0/v1model.h

It is IMO architecturally incorrect to have a frontend file include a
header from a specific backend. It also does not seem to be needed.

Remove bmv2 header include from P4_14 frontend

---

backends/bmv2/sharedActionSelectorCheck.cpp
testdata/p4_16_bmv_errors/issue679-bmv2.p4

Selector input fields should appear in the same order in all tables.
fixes #679

Fix bmv2 inspector which validates selector sharing

---

Makefile.am

As the number of tests increases, we're starting to hit a problem on Linux where "make check" fails with "Argument list too long" due to the way in which it recursively invokes make.  This change avoids the problem, and doesn't appear to introduce other problems or break parallel makes or recheck or other things.
It still has the problem that it needs to rebuild everything if you touch any Makefile.am file, which is annoying but not fatal.

Fix "Argument list too long" make check errors on Linux

---

Makefile.am
backends/bmv2/Makefile.am
backends/ebpf/Makefile.am
backends/p4test/Makefile.am
lib/Makefile.am
test/Makefile.am
tools/ir-generator/Makefile.am

We ran into some trouble recently with libtool being unable to track dependencies of our convenience libraries correctly. This was partially because the dependencies weren't set up correctly, but an additional issue is that we aren't using libtool for some libraries. Let's switch things over to consistently use libtool everywhere.
A small but nice win is that now backends do not have to explicitly link against `libp4ctoolkit`, since libtool understands the dependencies and can handle that for them.

Use libtool for all p4c convenience libraries

---

test/Makefile.am

We've observed `gtestp4c` crashing on Linux recently. It was pretty clear that the issue was a bad interaction between GTest's TLS implementation and libgc, and I tried to fix the problem in d38a37cf69 by setting GTest feature flags that disable threading-related features.
Unfortunately that didn't resolve the problem completely. Those feature flags do indeed fix the problem, but applying them to `gtestp4c` isn't enough - they need to be applied when we build `libgtest.la` as well. In fact, it's safest to just set those flags globally, just in case GTest code finds its way into any other executables or libraries - the headers are available globally, after all, since they need to be to make `gtest_prod.h` available.
This PR does just that: the feature flags from d38a37cf69 are added to …

Apply GTest feature flags globally in AM_CPPFLAGS

---

backends/bmv2/bmv2stf.py
backends/bmv2/control.cpp
backends/bmv2/helpers.cpp
backends/bmv2/helpers.h
control-plane/p4RuntimeSerializer.cpp
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/v1model.h

Fix (partly) issue #461 
A good example why obfuscating string constants behind `static constexpr` "names" is a bad idea -- makes the code harder to read and maintain and makes it easier for bugs to creep in.
Arguably we should add a check for `count` calls on counters that are not named in the table attributes.  Whether that should be an error or should implicitly add said counter attribute is unclear.

Fix counters attribute name

---

tools/driver/p4c.in

This PR fixes an issue when using a different exec_prefix, for example, when installing architecture specific binaries in separate directories, while sharing the arch independent files.
It is unfortunate that automake/autoconf does not fully substitute the path in these variables ...

relative path from binary to artifacts when exec_prefix != prefix

---

tools/driver/p4c.in

The driver is intended to invoke all the required tools for each backend.
It is used in two scenarios, developer and installed version, and the
tool binaries may be located in different directories. We set an env
variable to identify in which scenario is the script invoked, and this
env var can be used in the configuration file to set the correct
paths.

adds build type env variable to driver script

---

frontends/common/parseInput.cpp
frontends/common/parseInput.h
frontends/common/resolveReferences/resolveReferences.cpp
frontends/p4-14/typecheck.cpp
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h
frontends/parsers/p4/p4parser.ypp
frontends/parsers/v1/v1parser.ypp
ir/v1.def
tools/ir-generator/irclass.cpp

Extern types in P4 are by definition architecture specific -- different architectures will support different ones.  In addition, they will often need to be different between P4_14 and P4_16 as P4_16 has more and different capabilities.  So when converting code from P4_14 there's a need to convert externs as well, but that cannot be done in an architecture-neutral way in general.
This change adds a interface hook to the P4_14->P4_16 converter that allows a backend/architecture to supply a custom extension for converting externs from P4_14 to P4_16 rather than just copying them through unchanged.

Interface for architecture-specific conversion of P4_14 externs to P4_16

---

backends/bmv2/JsonObjects.cpp

Backend::convert was inserting json->meta into jsonTop, but that pointer
would later get overwritten in add_meta_info.

Fix memory error when building bmv2 JSON

---

frontends/common/programMap.h
frontends/p4/typeChecking/typeChecker.cpp

Old bug revealed by new versions of gcc -- calling a non-virtual method on a nullptr that just calls dynamic_cast used to work fine, but it is technically undefined behavior.

avoid crashing on null pointers

---

lib/bitvec.cpp
lib/bitvec.h

Just added a continuous function to bitvec.  I needed something in the Barefoot backend, but the function is useful for any bitvec.
Not optimized for speed, but is correct.  Could be optimized if that is a major concern for people.

Added contiguous function to bitvec

---

Dockerfile

We need to make a few changes to the Dockerfile to run PD-based PTF tests.
We need to use scapy-vxlan instead of Ubuntu's scapy package - here we're relying on scapy-vxlan being present in the upstream third-party image. (see p4lang/third-party#11)
We also need `p4runtime-to-pd` available in the Docker image, so I've enabled it. That requires us to install the `tenjin` Python package.
Finally, I noticed while making these changes that the `||` in the `RUN` statement makes `docker build` succeed even if `bootstrap.sh` returns an error. Multistage builds will eliminate the need for these huge shell expressions, but it may take as long as two weeks for us to be able to use them, it's worth fixing the problem now.

Prepare the Dockerfile for running PD-based PTF tests

---

midend/local_copyprop.cpp
midend/local_copyprop.h
testdata/p4_14_samples_outputs/test_config_23_same_container_modified-midend.p4
testdata/p4_16_samples_outputs/hit_ebpf-midend.p4
testdata/p4_16_samples_outputs/pred2-midend.p4

Note: This PR is addressing the same bug as #716 with the required changes to code and the test outputs (I added other commits in that PR by mistake, so created a new one with only my commits).  
The LocalCopyPropagation pass in midend checks and removes assignment statements of the form:
`modify_field(metadata.port, metadata.port)`
However, these statements were not removed in practice because the check was comparing the IR nodes (which were different for the same variable), and thus, none of the no-op assignment statements were eliminated. This PR fixes that bug by adding an function to check equivalence of two IR::Expression objects for 1) Variables 2) Array references 3) Packet header/metadata fields (struct). 
This PR changes the testdata outputs because some of the sample programs …

Fix bug in LocalCopyPropagation pass in midend

---

backends/bmv2/synthesizeValidField.cpp
backends/bmv2/synthesizeValidField.h
backends/p4test/p4test.cpp
frontends/common/options.h
ir/Makefile.am
ir/ir-inline.h
ir/json_parser.cpp
ir/json_parser.h
ir/visitor.cpp

Here's a patch I've had lingering for a while now that speeds up the build a little bit by moving some code from `.h` files to `.cpp` files. The biggest win is moving some code out of `ir-inline.h`; at least on clang, that code is pretty expensive to compile.
In my environment, a full rebuild of master (`time make -j8`) takes this long:
```
107.69 real 623.43 user 22.66 sys
```
With this patch:
```
95.80 real 544.69 user 22.00 sys
```
That's an 11% speedup. Not bad.

Speed up the build by reducing the amount of headers we're including

---

lib/bitvec.cpp

Essentially, when the sz requested in getslice is 0, the bitvec returned should be empty.  This was not happening correctly.

Simple bitvec bug fix.

---

backends/bmv2/synthesizeValidField.cpp
control-plane/p4RuntimeSerializer.cpp

Otherwise they can show up in the p4Runtime output.

Annotate bmv2 $valid$ fields as hidden

---

ir/type.def

This correctly gets the width of the type underneath the typedef, rather than the typedef itself.

Bug on Type_Typedef width bits

---

frontends/p4-14/typecheck.cpp
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/typeChecking/typeChecker.cpp
ir/v1.def
ir/visitor.cpp
ir/visitor.h
midend/local_copyprop.cpp
midend/local_copyprop.h

So using `visitDagOnce = false` in a Transform (or Modifier) seems to be a sure source of hard to track bugs.  Its far too easy for the Transform to inadvertently clone something that is referenced mulitple places, which seems to be ok at first, but leads to problems down the line.
This change dusts off an old change I've had sitting on a branch for awhile to add some new Visitor functions (`visitAgain()` and `visitOnce()`) that override the `visitDagOnce` flag on a per-node basis.  Any pre- or postorder function can call `visitAgain()` and it result in node being visited again if it is found as a child elsewhere in the IR Dag instead of reusing the results of the first call (as if `visitDagOnce = false`, but just for that node).  Similarly `visitOnce()` treats the node as if `visitDagOne …

Fix typechecking MakeImplicitCastExplicit to work properly with dags

---

backends/p4test/p4test.cpp
ir/json_generator.h
ir/node.cpp
ir/node.h

This patch embeds the SourceInfo data in the p4test JSON output.
This makes it accessible to any post-processing tool using this output.
The format of data is compatible with Andy's patch (which is only used in the BMV2 backend).
The commit also includes a minor tweak - cleaning up the trailing space following the "," in JSON nodes.

Include SourceInfo in the JSON output of p4test.

---

backends/p4test/p4test.cpp

This allows p4test to emit the JSON for the full unprocessed P4 source.
This JSON is useful for tools that would like to deal directly with the source code (e.g. IDEs).
For complete functionality, the JSON should include SourceInfo data (pull request #749).

Add --parse-only option to p4test.

---

frontends/common/parseInput.cpp
frontends/common/parseInput.h
frontends/p4-14/typecheck.cpp
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h
frontends/p4/typeChecking/typeChecker.cpp
ir/ir.cpp

This reworks my previous ExternConverter change to be both simpler and more flexible.  Now instead of having a single ExternConverter passed into the frontend, you can register multiple ExternConverter subclass instances on a per extern type basis -- the converter will manage them and call the correct one.  This allows better mixing and matching of extern converters for related targets.  Most of the change is actually undoing the previous change to the frontend API.
There's also yet another P4_14 typechecking fix with getting the right implicit conversions inserted as explicit conversions.

Rework ExternConverter to be simpler and more flexible

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h

Initial ideas for an extensible primitive P4_14->16 conversion framework.  The goal is to be able to easily support target architecture specific primitives, rather than having everything ties to v1model.
This ends up requiring some duplication of code in the conversion routines (for example, all of the simple binop conversions); it would be nice to figure out a way to reduce that.
This also has the disadvantage of being statically built into the executable, which will make it difficult to support mutiple targets in a single executable.  At the moment we're using separate executables for each target, so this is not an issue.

extensible PrimitveConverter framework

---

frontends/common/resolveReferences/resolveReferences.cpp
frontends/common/resolveReferences/resolveReferences.h
frontends/p4/fromv1.0/converters.cpp
testdata/p4_14_samples_outputs/issue604.p4-stderr

- this code was to support P4_14-style externs with attributes and is no
longer needed now that we have ExternConverters to convert those P4_14
extern_types to P4_16 properly.

Strip out p4_14 extern support code in ResolveReferences

---

frontends/common/options.cpp
frontends/p4/fromv1.0/programStructure.cpp

Install and developer builds provide different paths to the include files.
In the current configuration, we hardcode the p4include path to some
directory decided at configuration time, which makes the compiler
non-relocatable. However, this issue has been addressed in the driver,
which sets environment variables for both the P4 14 and 16 include
paths. With this change, the compiler no longer needs to hardcode the
path.

adjusts the paths for the include files to the env variable set by p4c driver

---

.travis.yml
CMakeLists.txt

This allows it to run in parallel with all the other tests and fail at
leisure.
Also switched travis to ctest and increased the parallel load to 4.

adds cpplint as a test

---

README.md
cmake/P4CUtils.cmake

Adds a new macro to add a single test to the test suite and provide
additional arguments to the test on the command line. Can be used to
specialize tests, e.g., have the same test run with different profiles.

cmake macro to add an individual test with arguments

---

lib/bitvec.cpp
test/CMakeLists.txt
test/gtest/Makefile.am
test/gtest/bitvec_test.cpp

Essentially this was failing on the border of bits_per_unit.  The size should always be at least 1 in the calculation.

Fixed a small bug in the bitvec >>= function

---

frontends/p4/fromv1.0/programStructure.h

making these two methods public to be used in other translation passes.

make createTypes() and createExterns() in P4V1::ProgramStructure public

---

control-plane/p4RuntimeSerializer.cpp

Rather than generating a default name. Until now the default name was
the name of the property itself (e.g. 'implementation'). This is a
problem when multiple tables have anonymous properties, but also because
a) the name can be surprising to the control-plane programmer, and b)
backends can generate their own names for these which may not match
(which is what the bmv2 backend is doing). Taking that into account, it
seems better to just raise an error in the P4RuntimeSerializer.

In P4Runtime, reject anonymous table properties

---

ir/json_generator.h
ir/json_loader.h
tools/ir-generator/ir-generator.ypp

Does what it says on the tin. `boost::optional` is, in my view, anything but optional.
The patch to the IR generator grammar is needed because of a lexical ambiguity, since "optional" is also a keyword in IR generator .def files. With this change, "optional" is also permitted as a type name as long as it's qualified by a namespace. (i.e., you can have fields of type "boost::optional", but using just "optional" will still result in "optional" being parsed as a keyword)

Add support for IR node fields of boost::optional type

---

control-plane/p4RuntimeSerializer.cpp

This fixes commit 9b4e0db15fe9578be5f74052b993c010cbe8f454. For table
properties, the name annotation is on the property name, not the value.

Fix typo in P4Runtime

---

tools/driver/p4c_src/main.py

Passing the -D option through the -Xpreprocessor and -Xp4c options
is cumbersome and seems to interact fairly badly with Python's
argparse (or I didn't spend enough time to figure it out).

adds -D option to the driver

---

frontends/common/resolveReferences/resolveReferences.cpp
frontends/p4/def_use.cpp
frontends/p4/specialize.cpp
frontends/p4/validateParsedProgram.h
ir/base.def
ir/ir.def
ir/type.def
midend/inlining.cpp
midend/parserUnroll.cpp

The IR has `getConstructorParameters` and `getTypeParameters`, but not `getApplyParameters` which makes the IR API asymmetrical.
One thing I am not sure about in this commit is the `table.apply()` does not allow apply parameter in P4-16. Hence, `getApplyParameters()` on table will return a `nullptr`. We do the same for the `getP4Type()` function in `type.def`.

add getApplyParameters() method to IApply interface

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_errors/issue816-1.p4
testdata/p4_16_errors/issue816.p4
testdata/p4_16_errors/param.p4
testdata/p4_16_errors_outputs/issue816-1.p4
testdata/p4_16_errors_outputs/issue816-1.p4-stderr
testdata/p4_16_errors_outputs/issue816-first.p4
testdata/p4_16_errors_outputs/issue816.p4
testdata/p4_16_errors_outputs/issue816.p4-stderr
testdata/p4_16_errors_outputs/param.p4
testdata/p4_16_errors_outputs/param.p4-stderr

The fix enforces the following:
- packages can only be passed as arguments to other packages
- controls, parsers, packages and externs cannot be passed as parameter with a direction

Fix for issue #816

---

backends/p4test/CMakeLists.txt
midend/eliminateTuples.h
testdata/p4_16_samples_outputs/tuple0-first.p4
testdata/p4_16_samples_outputs/tuple0-frontend.p4
testdata/p4_16_samples_outputs/tuple0-midend.p4
testdata/p4_16_samples_outputs/tuple0.p4

The compiler was inserting the tuple replacement type after its first use.
The fix consists in realizing that tuples can appear in method or extern declarations too.

Fix for issue #759

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
testdata/p4_14_samples/issue846.p4
testdata/p4_14_samples_outputs/issue846-first.p4
testdata/p4_14_samples_outputs/issue846-frontend.p4
testdata/p4_14_samples_outputs/issue846-midend.p4
testdata/p4_14_samples_outputs/issue846.p4
testdata/p4_14_samples_outputs/issue846.p4-stderr

Convert the expression `(boolExpr == constExpr)` to either
`(boolExpr)` or `(! boolExpr)` depending on the value of the
constant. Similarly for `(boolExpr != constExpr)` and permutations of
the expressions.

converts boolean expressions comparing bools to ints

---

ir/ir.cpp
ir/ir.def
ir/json_loader.h
ir/vector.h
lib/gc.cpp

This PR contains a number of small improvements and fixes that didn't seem worthy of their own individual PRs.
- `InstantiatedBlock::getParameterValue()` calls `BUG()` if the parameter doesn't exist. This PR adds `InstantiatedBlock::findParameterValue()` for cases where the parameter may not exist; it returns null on failure.
- It's a common idiom in p4c to take a Node and either append it to a Vector or, if it is itself a Vector, append its content to the Vector. Now this idiom is captured in the new method `Vector::pushBackOrAppend()`.
- Calling `LOG()` macros, which may allocate memory, is unsafe in `gc_callback()`. I've seen this trigger stack overflows, but not anymore, because the issue is fixed in this PR.
- Sometimes it's both more convenient and more efficient to return a value …

Improve InstantiatedBlock, Vector, and JSONLoader APIs, and fix a GC bug

---

backends/bmv2/backend.cpp
backends/bmv2/simpleSwitch.cpp
backends/bmv2/simpleSwitch.h
ir/ir.def

Compiling a program for a wrong model with p4c-bm2-ss causes the compiler to crash.
Now the compiler will just report an error and terminate whenever the model does not match.
This mostly entails converting BUG_CHECK to ifs.

Do not crash if wrong model is used

---

backends/bmv2/expression.cpp
backends/bmv2/expression.h
backends/bmv2/simpleSwitch.cpp
testdata/p4_16_samples/constant-in-calculation-bmv2.p4
testdata/p4_16_samples/constant-in-calculation-bmv2.stf
testdata/p4_16_samples_outputs/constant-in-calculation-bmv2-first.p4
testdata/p4_16_samples_outputs/constant-in-calculation-bmv2-frontend.p4
testdata/p4_16_samples_outputs/constant-in-calculation-bmv2-midend.p4
testdata/p4_16_samples_outputs/constant-in-calculation-bmv2.p4

This fixes a bug reported by @jnfoster 
This was caused by an omission in the bmv2 JSON format doc, which I fixed this morning: https://github.com/p4lang/behavioral-model/pull/426

Bmv2 backend calculations const fix

---

CMakeLists.txt

Note: CMAKE_CXX_STANDARD was not introduced until 3.1

Update CMakeLists.txt to support CMake 3.0.2

---

CMakeLists.txt

I couldn't figure out a way of having this happen only when the include files change, but the copy is fast enough that it probably doesn't matter.

Update include files whe rebuilding

---

backends/ebpf/CMakeLists.txt
backends/ebpf/codeGen.h
backends/ebpf/lower.cpp
backends/ebpf/lower.h
backends/ebpf/midend.cpp
testdata/p4_16_samples/issue870_ebpf.p4
testdata/p4_16_samples_outputs/issue870_ebpf-first.p4
testdata/p4_16_samples_outputs/issue870_ebpf-frontend.p4
testdata/p4_16_samples_outputs/issue870_ebpf-midend.p4
testdata/p4_16_samples_outputs/issue870_ebpf.p4

Some of this code is copied from the bmv2 back-end.
Arguably, some of this code should be moved into a mid-end pass.

Fix for issue #870: support slice and concat in ebpf back-end

---

backends/bmv2/CMakeLists.txt
backends/p4test/CMakeLists.txt
testdata/p4_16_samples/checksum1-bmv2.p4
testdata/p4_16_samples/checksum1-bmv2.stf

It does not test the verify_checksum implementation.

Add test of v1model update_checksum implementation

---

CPPLINT.cfg
tools/cpplint.py

Currently, cpplint forbids the construct `int(foo)`, insisting that you use `static_cast<int>(foo)`. This check really makes no sense. `int(foo)` is a perfectly good C++-style explicit conversion. It's quite distinct from the C-style cast `(int)foo`, which should indeed be banned. Banning this kind of explicit conversion is exactly the same thing as saying that you should write this:
```c++
auto vec_with_ten_elements = std::vector(10);
```
like this:
```c++
auto vec_with_ten_elements = static_cast<std::vector>(10);
```
Both of those work (believe it or not!) but I think few would argue that the latter is more readable.

Remove unreasonable cpplint casting check

---

frontends/p4/substitution.cpp
frontends/p4/substitution.h
frontends/p4/substitutionVisitor.cpp
frontends/p4/substitutionVisitor.h
frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_samples/issue871.p4
testdata/p4_16_samples_outputs/issue871-first.p4
testdata/p4_16_samples_outputs/issue871-frontend.p4
testdata/p4_16_samples_outputs/issue871-midend.p4
testdata/p4_16_samples_outputs/issue871.p4

In a type variable substitution one has to look-up variables until reaching a fix-point; it is not enough to look up a variable once.

Fix for issue #871

---

CMakeLists.txt
frontends/CMakeLists.txt

On a build where ccache gets a lot of hits, the linker rapidly becomes the bottleneck. Let's use the gold linker when it's available; it's much faster than the standard ld. It comes with binutils, so all we really need to do is flip it on, at least on recent Linux distros.
Unfortunately the compatibility situation between gold and clang (and symmetrically, between lld and gcc) doesn't seem to be perfect, so I hesitate to enable it when building with clang. We can add support for lld in a future PR.

Use the gold linker if available

---

cmake/FindLibGc.cmake

Earlier versions of libgc did not have the full version specified
in a comment.

fix version detection for libgc on Ubuntu 14.04

---

frontends/p4/sideEffects.cpp
midend/actionSynthesis.cpp
testdata/p4_14_samples_outputs/action_inline2-frontend.p4
testdata/p4_14_samples_outputs/flowlet_switching-frontend.p4
testdata/p4_14_samples_outputs/flowlet_switching-midend.p4
testdata/p4_14_samples_outputs/issue894-frontend.p4
testdata/p4_14_samples_outputs/issue894-midend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_16_samples_outputs/flowlet_switching-bmv2-frontend.p4
testdata/p4_16_samples_outputs/flowlet_switching-bmv2-midend.p4
testdata/p4_16_samples_outputs/hash-bmv2-frontend.p4
testdata/p4_16_samples_outputs/hash-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue447-4-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue447-4-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue447-5-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue447-5-bmv2-midend.p4
testdata/p4_16_samples_outputs/side_effects-frontend.p4
testdata/p4_16_samples_outputs/side_effects-midend.p4
testdata/p4_16_samples_outputs/uninit-frontend.p4
testdata/p4_16_samples_outputs/uninit-midend.p4
testdata/p4_16_samples_outputs/uninit.p4-stderr

This PR contains a subset of the changes from the reverted PR (which changed v1model).
This PR only contains the improved alias analysis, which is useful in itself.
The main effect is to create fewer unneeded temporaries in the side-effect pass.

Better alias analysis in side-effects pass

---

midend/copyStructures.cpp
midend/copyStructures.h

In our back-end users have some leeway with writing their own functions/externs that get linked in later. Since they can choose to write a function that returns a struct I'd prefer not to reject the design outright. So I just put a conditional around the error call in this case.

allow CopyStructures pass to ignore methods

---

cmake/UnifiedBuild.cmake

This is just a trivial fix to `UnifiedBuild.cmake` to make the file reusable in other projects.

Make unified build paths relative to PROJECT_SOURCE_DIR

---

control-plane/p4RuntimeSerializer.cpp

Looks like some new unused parameter warnings have crept in recently.

Fix clang warnings in p4RuntimeSerializer.cpp

---

backends/bmv2/CMakeLists.txt
backends/bmv2/bmv2.cpp
backends/bmv2/midend.cpp
control-plane/p4RuntimeSerializer.cpp
control-plane/p4RuntimeSerializer.h
frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
ir/CMakeLists.txt
ir/indexed_vector.h
ir/json_generator.h
ir/json_loader.h
ir/node.h
ir/pass_manager.cpp
ir/pass_manager.h
ir/v1.def
ir/vector.h
ir/visitor.cpp
ir/visitor.h
lib/CMakeLists.txt
lib/safe_vector.h
midend/CMakeLists.txt
midend/synthesizeValidField.cpp
midend/synthesizeValidField.h
test/CMakeLists.txt
test/gtest/bmv2_isvalid.cpp
test/gtest/p4runtime.cpp

We're at the point now where we're ready to make P4Runtime generation backend independent. This PR eliminates all remaining dependencies on post-frontend passes. This is accomplished by moving the passes that *are* required inside `generateP4Runtime()`. This is a funny definition of "eliminate", I'll grant you. =) The point is that the users of the API don't need to know about these dependencies anymore, though. I've triaged them all; now that we have the full list, we can start gradually whittling it down until there's nothing left.
To make this work, we do have to move the `BMV2::SynthesizeValidField` pass into the midend code, because we need this available on all backends. Everyone, including me, has concerns about that pass, so I can understand some discomfort at making this move, …

Make P4Runtime generation backend independent

---

frontends/p4/fromv1.0/programStructure.cpp
frontends/parsers/v1/v1lexer.ll
frontends/parsers/v1/v1parser.ypp
ir/dbprint-p4.cpp
ir/v1.def
p4include/v1model.p4
testdata/p4_14_samples/issue946.p4
testdata/p4_14_samples_outputs/issue946-first.p4
testdata/p4_14_samples_outputs/issue946-frontend.p4
testdata/p4_14_samples_outputs/issue946-midend.p4
testdata/p4_14_samples_outputs/issue946.p4
testdata/p4_14_samples_outputs/issue946.p4-stderr

This PR implements the frontend support for parser_value_set. 
The backend support for bmv2 is TBD. There is a placeholder for it.
I also corrected the section number in v1parser.ypp to correspond to the P14 v1.0.4 spec.
Related to #946

Frontend support for parser_value_set

---

README.md

Fixes the CMake warning: "Boost graph headers not found, will not build 'graphs' backend" and thus builds the graphs backend.

Added libboost-graph-dev to Ubuntu dependencies

---

backends/bmv2/bmv2.cpp
backends/p4test/p4test.cpp
control-plane/p4RuntimeSerializer.cpp
control-plane/p4RuntimeSerializer.h

A wrapper around generateP4Runtime, which can be used by all backends
which want to output the serialized control-plane API structures to
files.

Add serializeP4RuntimeIfRequired convenience wrapper

---

Dockerfile

Since it is not guaranteed that the processor type in a docker VM is the same as the one that's actually running the container, we should not optimize for the native architecture. Several Travis builds are failing with illegal instruction.

remove -march=native for Travis optimized builds

---

backends/bmv2/parser.cpp
testdata/p4_16_samples/issue995-bmv2.p4
testdata/p4_16_samples/issue995-bmv2.stf
testdata/p4_16_samples_outputs/issue995-bmv2-first.p4
testdata/p4_16_samples_outputs/issue995-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue995-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue995-bmv2.p4

Correct the masks generated in bmv2 backend for select expressions
with multiple fields.

Proposed fix for issue #995

---

backends/graphs/graphs.cpp
backends/graphs/graphs.h
backends/graphs/parser.cpp

The GraphAttributeSetter is used also in both controls.cpp and parser.cpp and thus it needs to be fully defined -- the forward declaration in graphs.h is not sufficient.
Also, the typeMap and referenceMap headers need to be explicitly included.

fixes includes and class definitions for non-unified build

---

backends/bmv2/backend.cpp
backends/bmv2/control.cpp
backends/bmv2/expression.cpp
backends/bmv2/expression.h
backends/bmv2/header.cpp
backends/bmv2/midend.cpp
backends/ebpf/midend.cpp
backends/p4test/midend.cpp
midend/simplifyKey.cpp
midend/simplifyKey.h
midend/synthesizeValidField.cpp
midend/synthesizeValidField.h
test/gtest/bmv2_isvalid.cpp
testdata/p4_16_samples/issue841.p4
testdata/p4_16_samples/issue955.p4
testdata/p4_16_samples_outputs/issue841-first.p4
testdata/p4_16_samples_outputs/issue841-frontend.p4
testdata/p4_16_samples_outputs/issue841-midend.p4
testdata/p4_16_samples_outputs/issue841.p4
testdata/p4_16_samples_outputs/issue841.p4-stderr
testdata/p4_16_samples_outputs/issue955-first.p4
testdata/p4_16_samples_outputs/issue955-frontend.p4
testdata/p4_16_samples_outputs/issue955-midend.p4
testdata/p4_16_samples_outputs/issue955.p4

This PR fixes these two issues by removing the SynthesizeValidBits pass from the normal compiler flow.
That pass breaks invariants about the semantics of the IR, and does not seem to be necessary anymore.
I have also changed the policies used when to simplify table keys: they were using double negation, now they are easier to read and to combine.

Fix for issue #841 and #955

---

backends/bmv2/CMakeLists.txt
testdata/p4_14_samples/gateway1.p4
testdata/p4_14_samples/gateway2.p4
testdata/p4_14_samples/gateway3.p4
testdata/p4_14_samples/gateway4.p4
testdata/p4_14_samples_outputs/gateway1-first.p4
testdata/p4_14_samples_outputs/gateway1-frontend.p4
testdata/p4_14_samples_outputs/gateway1-midend.p4
testdata/p4_14_samples_outputs/gateway1.p4
testdata/p4_14_samples_outputs/gateway2-first.p4
testdata/p4_14_samples_outputs/gateway2-frontend.p4
testdata/p4_14_samples_outputs/gateway2-midend.p4
testdata/p4_14_samples_outputs/gateway2.p4
testdata/p4_14_samples_outputs/gateway3-first.p4
testdata/p4_14_samples_outputs/gateway3-frontend.p4
testdata/p4_14_samples_outputs/gateway3-midend.p4
testdata/p4_14_samples_outputs/gateway3.p4
testdata/p4_14_samples_outputs/gateway4-first.p4
testdata/p4_14_samples_outputs/gateway4-frontend.p4
testdata/p4_14_samples_outputs/gateway4-midend.p4
testdata/p4_14_samples_outputs/gateway4.p4

These failures all are due to bmv2 sending packets out of port 0 for a
P4_14 program that never assigns a value to the egress_spec intrinsic
metadata field.
Chris Dodd suggested changing the programs so that if they do not
explicitly assign a value to egress_spec, then they drop the packet.
This makes the existing STF tests for these programs pass, so these
tests appear to have been written with this behavior in mind.

Fix some of the failing STF tests described in #961

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h
ir/expression.def
ir/pass_manager.cpp

This adds some hooks so that convertExternInstance can add additional declarations to the scope of the control in which is being converted and/or get at other previously converted objects in the scope (registers is the particular need).

P4_14->16 conversion hooks for register/stateful conversion

---

lib/source_file.cpp

Let's get rid of this assertion. It can be frustrating because it's easy to hit while writing source-to-source translations based on the `p4c` compiler infrastructure.

Don't assert if a source line is missing

---

backends/bmv2/CMakeLists.txt
backends/bmv2/bmv2stf.py
testdata/p4_14_samples/07-MultiProtocol.p4
testdata/p4_14_samples/07-MultiProtocol.stf
testdata/p4_14_samples_outputs/07-MultiProtocol-first.p4
testdata/p4_14_samples_outputs/07-MultiProtocol-frontend.p4
testdata/p4_14_samples_outputs/07-MultiProtocol-midend.p4
testdata/p4_14_samples_outputs/07-MultiProtocol.p4

This fixes the old stf file parser to ignore the key handle part of a command.
This makes the tests pass again, but the stf support in the old parser is still incomplete.

Fix for issue #961

---

ir/v1.cpp

This is undoubtfully a hack, but we already have hacks in this file to support type inference on `execute_stateful_` primitives.

support another blackbox primitive  in p4-14 type inference

---

backends/p4test/run-p4-sample.py

I cannot conceive how simple character classes like `\w` don't work correctly on the `sed` that ships with macOS, but somehow it's true. =\ This patch makes `P4TEST_REPLACE` strip paths correctly on both macOS and Linux.

Make P4TEST_REPLACE strip paths correctly on macOS

---

frontends/common/options.cpp
lib/options.cpp
lib/options.h
test/gtest/diagnostics.cpp

As @mbudiu-vmw pointed out in #1074, when you forget the argument to an option, the error message that the compiler reports isn't very helpful. The ambiguity is unfortunately impossible to resolve in general, I think, but this specific case is fairly easy: in analogy with GCC, users expect that `--Werror` without an argument will be accepted and will make the compiler treat all warnings as errors, and we should make that work.
To that end, this PR adds a flag to `Util::Options::registerOption()` that lets you specify that an option's argument may be omitted. To avoid ambiguity, for such options we don't allow `--foo bar`; only `--foo=bar` is accepted. That means that you must use `--Werror=foo` and not `--Werror foo`. `--foo bar` still works for options with non-optional arguments, of …

Allow options to have optional arguments

---

tools/driver/CMakeLists.txt
tools/driver/p4c_src/config.py
tools/driver/p4c_src/driver.py
tools/driver/p4c_src/main.py
tools/driver/p4c_src/p4c.bmv2.cfg
tools/driver/p4c_src/p4c.ebpf.cfg
tools/driver/p4c_src/util.py

Refactors the p4c driver code to allow more flexibility for backends.
Different backends may carry special configurations, flags, and
intermediate passes that were not captured in the current design.
To that end, we define a Driver class that each backend instantiates
and configures its commands, setup and cleanup steps, as well as the
options to pass to commands.
Since different backends may want to add options that are proprietary
we refactor the option processing such that they can add these options
as part of different argument groups.
Also, segregated the processing of generic options from the options that
require the source file to be present. The source dependent options are
typically backend dependent, so it is expected that backends will set them
in the subclass, just before the …

p4c driver refactoring

---

tools/driver/p4c_src/main.py

Printing the message through parser.exit puts it to stderr, and thus
version and targets are not available in scripts without redirection.

print the output directly to stdout rather than using parser.exit

---

Dockerfile

The behavioral-model image now has pi as a base image, not the other way around.

Change base Docker image to behavioral-model

---

README.md

Because that is the version all our CI testing is done with and that is
the version required for P4 Runtime.

Recommend installing version 3.2.0 of protobuf

---

ir/visitor.h
midend/local_copyprop.cpp
midend/local_copyprop.h

- allows backends fine-grained control over what values should be
copy-propagated and which should not

Add 'policy' argument for local_copyprop

---

frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/v1model.h
p4include/v1model.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4

- bmv2 allows any type up to the bmv2 word size
- makes it easier to convert/deal with programs that use random numbers
of sizes other than 32 bits.

Make v1model 'random' extern type generic

---

frontends/parsers/p4/p4lexer.ll
frontends/parsers/v1/v1lexer.ll

Makes frontends/parsers/*/*.ll consistent with
tools/ir-generator/ir-generator-lex.l

Add #ifdef __clang__ around diagnostic pragma

---

CMakeLists.txt

These unit tests are built even when I am not interested in running
them (e.g. when building a docker image for the compiler), which can
take quite some time.
The tests are enabled by default.

Add CMake flag to disable building GTests

---

frontends/common/constantFolding.cpp
frontends/p4/toP4/toP4.cpp
frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeUnification.cpp
testdata/p4_16_samples/issue1107.p4
testdata/p4_16_samples_outputs/issue1107-first.p4
testdata/p4_16_samples_outputs/issue1107-frontend.p4
testdata/p4_16_samples_outputs/issue1107-midend.p4
testdata/p4_16_samples_outputs/issue1107.p4

There were two subtle bugs in constant folding
- the constant declaration value was substituted, but the type in the constant declaration was ignored.
- cloning an Type_InfInt does not produce a new Type_InfInt, just another copy of the same type. Here we really wanted a new type, which can be bound to a different value when performing unification.

Fix for issue #1107

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h

This is a fix for #718 and #1036.
The fix is to remove the fields in v1model.p4 standard_metadata_t that are marked with `@alias`, which is only supposed to be used in P4-16 programs. If a P4-16 program is generated from a P4-14 program, these annotated fields should be removed, so they don't show up in the JSON file.

remove alias fields from standard_metadata when translating p4-14

---

backends/p4test/run-p4-sample.py
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h
frontends/p4/typeChecking/typeChecker.cpp
frontends/parsers/v1/v1parser.ypp
ir/v1.def

- for now when converting to P4_16 we just use the first algorithm, as
P4_16 architectures are not set up to handle more than one.

Add P4_14 frontend support for mulitple algorithms in a field list

---

midend/copyStructures.cpp
testdata/p4_16_samples/inline-stack-bmv2.p4
testdata/p4_16_samples_outputs/inline-stack-bmv2-midend.p4

As @jafingerhut pointed out, the removed code was incorrect, since it was assuming that copying all elements of an array is the same as copying the array. This would actually be correct within a control block only, where the .next and .last fields are not accessible. But that code was not really necessary for removing nested structures, which is the point of copyStructures. I don't think this is enough to solve issue #1128.

Remove incorrect expansion of array copy

---

tools/driver/CMakeLists.txt

The driver installed all the configurations available, even when
the target was not enabled, resulting in an error with a missing backend.
This patch installs only the targets that are enabled.

driver installs only the targets that were configured

---

midend/convertEnums.cpp

1U << 32 is 0, we should use 1LL << 32.
Also, the BUG_CHECK condition is reversed, we were lucky to not hit on that check.

Use 1LL << 32, instead of 1U << 32

---

lib/bitvec.h
lib/ltbitmatrix.h
lib/symbitmatrix.h

This implementation is slower, but has larger valid range and fixed the #1150 .

fix for #1150: implement |= in a naive way

---

midend/CMakeLists.txt
midend/local_copyprop.cpp
midend/simplifyBitwise.cpp
midend/simplifyBitwise.h

In the p4-14 to p4-16 translation, the following instruction:
modify_field(field, param, mask)
becomes:
field = field & ~mask | param & mask
which is correct, but could be simplified for a backend as a vector of assignments of slices, as long as the masks don't have any collisions.
This also required a change to the equivalency check of Constants in local_copyprop.

Added Midend Pass to Optimize Complex Bitwise Operations

---

ir/expression.cpp
ir/expression.def
ir/pattern.h
midend/simplifyBitwise.cpp
midend/simplifyBitwise.h

It seems so much simpler to do this with a basic pattern matcher that I couldn't resist refactoring it to use one...

Simplify SimplifyBitwise by using a general pattern matcher for expressions

---

control-plane/p4RuntimeSerializer.cpp

the control plane API apparently does not support boolean type action arguments, @antoninbas can you please confirm if that is intended? If not, this PR fixes the issue to support boolean as well.

handle boolean type action parameter in p4Runtime

---

CMakeLists.txt

Updating the version should be done at "release" time, however, we
can automatically add the sha to the version number so people can
identify which release of the compiler are using.
Fixes #1173

add sha to the p4c version

---

frontends/parsers/v1/v1parser.ypp

bison C++ parser can't recover properly (automatically) from errors on eof, due to the explicit END token required.  Need to explicitly match END where it can occur in error recovery to avoid hang.
Fixes issue #1093

Match explicit END tokens after error in bison parser

---

frontends/p4/inlining.cpp
frontends/p4/typeChecking/typeChecker.cpp
test/gtest/arch_test.cpp
testdata/p4_16_errors/spec-issue563.p4
testdata/p4_16_errors_outputs/spec-issue563.p4
testdata/p4_16_errors_outputs/spec-issue563.p4-stderr
testdata/p4_16_samples/control-as-param.p4
testdata/p4_16_samples/issue496.p4
testdata/p4_16_samples_outputs/control-as-param-first.p4
testdata/p4_16_samples_outputs/control-as-param-frontend.p4
testdata/p4_16_samples_outputs/control-as-param-midend.p4
testdata/p4_16_samples_outputs/control-as-param.p4
testdata/p4_16_samples_outputs/issue496-first.p4
testdata/p4_16_samples_outputs/issue496.p4

With this commit we distinguish a control from the type of the control. So you cannot use a control as the type of a parameter.

Fix for spec issue 563

---

backends/bmv2/backend.cpp
p4include/v1model.p4

Just like for learn lists, field list ids (which are used for resubmit)
need to be non-zero, since the id is actually used as a flag to indicate
whether or not resubmit was invoked.
Given that the "resubmit_flag" v1model metadata field is supposed to
hold a field list id, its bitwidth was increased from 1 to 32.

Fix resubmit in bmv2 backend

---

p4include/v1model.p4
testdata/p4_16_errors_outputs/issue584.p4-stderr
testdata/p4_16_samples_outputs/drop-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue841.p4-stderr

This is to enable the implementation of INT with v1model. This metadata
field does exist in PSA, but until PSA becomes mainstream, it is nice to
have access to the same metadata in v1model.
The egress timestamp is the "time at which the packet began processing
in the egress parser".

Add egress timestamp to v1model's metadata fields

---

backends/bmv2/parser.cpp
control-plane/p4RuntimeSerializer.cpp
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/hierarchicalNames.cpp
frontends/p4/uniqueNames.cpp
test/gtest/p4runtime.cpp
testdata/p4_14_samples_outputs/issue946-first.p4
testdata/p4_14_samples_outputs/issue946-frontend.p4
testdata/p4_14_samples_outputs/issue946-midend.p4
testdata/p4_14_samples_outputs/issue946.p4
testdata/p4_14_samples_outputs/parser_value_set0-first.p4
testdata/p4_14_samples_outputs/parser_value_set0-frontend.p4
testdata/p4_14_samples_outputs/parser_value_set0-midend.p4
testdata/p4_14_samples_outputs/parser_value_set0.p4
testdata/p4_14_samples_outputs/parser_value_set1-first.p4
testdata/p4_14_samples_outputs/parser_value_set1-frontend.p4
testdata/p4_14_samples_outputs/parser_value_set1-midend.p4
testdata/p4_14_samples_outputs/parser_value_set1.p4
testdata/p4_14_samples_outputs/parser_value_set2-first.p4
testdata/p4_14_samples_outputs/parser_value_set2-frontend.p4
testdata/p4_14_samples_outputs/parser_value_set2-midend.p4
testdata/p4_14_samples_outputs/parser_value_set2.p4
testdata/p4_16_samples_outputs/pvs-frontend.p4
testdata/p4_16_samples_outputs/pvs-midend.p4

The P4 syntax may not be set in stone, but people are starting to use parser value sets and require support from the compiler to include the correct information in the P4Info message.

Support value_set in P4Info generation

---

cmake/P4CUtils.cmake

Instead of passing all args as a string. This is useful for more complex
invocations of the test script which involve "args with spaces".

When calling cmake's add_test pass args as array

---

tools/ir-generator/ir-generator.ypp

- parse errors in the ir generator were causing a BUG_CHECK crash (and
not reporting the actual error) due the lack of a BaseCompileContext
for error reporing.

Fix parse error reporting in the ir generator

---

frontends/p4/evaluator/evaluator.h
frontends/p4/fromv1.0/programStructure.h

Make the .h parameter names match the corresponding .cpp implementation per ClangTidy output.

Fix ClangTidy complaints about parameter name differences

---

lib/json.cpp
lib/json.h
test/gtest/json_test.cpp

On some 64-bit sytems, int64 is a typedef to "long long" and not
"long". On those systems, trying to construct a JsonValue object from a
int64 or uint64 triggers a compiler error. In this commit, we add
support for constructing JsonValue objects from "long long" and
"unsigned long long" values. Note that the constructor for GMP's
mpz_class does not support "long long" values so we have to use a
workaround. This commit also makes handling of integral types in
lib/json more generic.
Note that this commit should also help for compiling on 32-bit systems,
where int64 is probably always a typedef to "long long".

Handle "long long" primitive types in lib/json

---

frontends/CMakeLists.txt

Adds the .ll file as an input dependency to the custom flex rule.
Fixes #1224

fix missing dependency on .ll files

---

p4include/psa.p4
testdata/p4_16_samples/issue1208-1.p4

We already have a proposal with named argument to make the PacketReplicationEngine and BufferingQueueingEngine arguments optional. 
I would like to remove the PSA_SWITCH macro in psa.p4 to avoid creating more test cases that use a macro which is going to be retired later. 
Another reason to remove the macro is it does not play well with the gtest infrastructure, because gtest includes a raw string as test program which assumes the preprocessing is done, but there is no preprocessing support in the frontend, so all gtest cases that include psa.p4 is going to give a syntax error for the macro.

remove macro for PSA_SWITCH in psa.p4, update test case

---

backends/bmv2/JsonObjects.cpp
backends/bmv2/expression.cpp
backends/bmv2/expression.h
frontends/p4/typeChecking/typeChecker.h
frontends/parsers/p4/p4lexer.ll
frontends/parsers/p4/p4parser.ypp
ir/dbprint-expression.cpp
ir/dbprint.h
ir/expression.def
testdata/p4_16_samples/saturated-bmv2.p4
testdata/p4_16_samples/saturated-bmv2.stf
testdata/p4_16_samples_outputs/saturated-bmv2-first.p4
testdata/p4_16_samples_outputs/saturated-bmv2-frontend.p4
testdata/p4_16_samples_outputs/saturated-bmv2-midend.p4
testdata/p4_16_samples_outputs/saturated-bmv2.p4

We add support for |+| and |-| in the frontend of the compiler, as
well as bmv2 backend support. This includes defining two binary
operation IR nodes for saturating addition and subtraction, and
generating the json for bmv2 as defined in
https://github.com/p4lang/behavioral-model/pull/590. For that, we
update the json version to 2.18.
We also added a test that ensures that saturating arithmetic properly
bounds the min and max values for signed and unsigned integer
operations.
Still to do:
- translate P4_14 saturating operations to the new IR expression nodes.
Fixes #1229

adds support for saturating arithmetic in P4_16

---

control-plane/CMakeLists.txt
control-plane/p4RuntimeSerializer.cpp
test/gtest/p4runtime.cpp

The different values for the ID prefix (first byte of every ID) are now defined in p4info.proto. In this commit, we switch to using these values when generating the P4Info message. One notable difference is that the direct & indirect versions of counters / meters now use a different prefix value for their ids.
Fixes #1214

Use correct ID prefixes in P4Runtime serializer

---

backends/bmv2/bmv2.cpp
backends/p4test/p4test.cpp

For bmv2 and p4test backends. It is important to run the serializer
before some of the midend passes that could have an impact on the
contents of the P4Info message - such as the EliminateTuples pass.
Currently, the serializer seems to have a dependency on a few passes
usually run in the midend, which is why it has its own pass manager.
Note that if a given backend later runs some transformation pass like
EliminateTuples, it is the responsibility of this backend to provide the
P4Runtime server implementation with the necessary information to do
data transformation.

Move p4RuntimeSerializer invocation to right after frontend

---

frontends/p4/typeChecking/typeChecker.cpp

- abstract methods may not all be required for every instantiation of an
extern with abstract methods.
- avoid losing annotations on methods when canonicalizing them

experimental: Allow @optional on abstract methods

---

control-plane/p4RuntimeSerializer.cpp
control-plane/typeSpecConverter.cpp
test/gtest/p4runtime.cpp

Use declaration instance type instead of evaluated block instance
type. The evaluated block instance type gives us a
Type_SpecializedCanonical node which doesn't use Type_Name and therefore
violates pre-condition for typeSpecConverter.

Fix generation of P4Info for v1model registers

---

midend/simplifyBitwise.cpp
test/CMakeLists.txt
test/gtest/complex_bitwise.cpp

IR::Slices were made in reverse and the assignment statement that was being adapted was never assigned, resulting in a SEGFAULT.

Fixed some small bugs in simplifyBitwise.

---

frontends/p4/simplifyParsers.cpp
frontends/p4/unusedDeclarations.cpp
testdata/p4_14_samples/parser_pragma.p4
testdata/p4_14_samples_outputs/parser_pragma-first.p4
testdata/p4_14_samples_outputs/parser_pragma-frontend.p4
testdata/p4_14_samples_outputs/parser_pragma-midend.p4
testdata/p4_14_samples_outputs/parser_pragma.p4

Annotations on parser state may be useful for certain midend and backend. Do not eliminate the parser state that has an annotation other than `name`(because it is always added), but not invoked by any other parser state.

Do not eliminate annotated states.

---

tools/driver/p4c_src/driver.py

In debug mode, propagate the -g only to the known commands, rather
than all commands. Different backends may chose to add -g to these
commands on a case-by-case basis.

propagate -g only to "known" tools

---

ir/pattern.h
midend/simplifyBitwise.cpp

I think this little bit of syntactic sugar makes the patterns being matched against a bit clearer.

Alternate cleaner way of specifying pattern matches.

---

ir/expression.def
ir/namemap.h
ir/node.h
ir/nodemap.h
ir/vector.h
midend/local_copyprop.cpp
midend/local_copyprop.h
test/CMakeLists.txt
test/gtest/equiv_test.cpp
tools/ir-generator/irclass.h
tools/ir-generator/methods.cpp

I talked about this awhile back -- this has the ir-generator generate a deep-compare method `equiv` for all IR classes.  It recursively compares all pointed at IR classes, so it is potentially expensive, but when it's needed, it's needed.

Generate a deep-compare "equiv" function for IR nodes

---

control-plane/p4RuntimeSerializer.cpp

nullptr could occur if package argument is optional.

check for nullptr when generating control plane API

---

control-plane/CMakeLists.txt
control-plane/p4RuntimeArchHandler.cpp
control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp
control-plane/p4RuntimeSerializer.h

More architectures are being developped and there is a desire to be able
to use P4Runtime with them. P4Runtime supports standard architectures
(v1model & PSA) natively and support architecture-specific extensions
(table properties & externs). In order to enable using P4Runtime with
vendor-specific architectures, we define a framework that can be used to
implement P4Info generation for these architectures more easily. v1model
& PSA also use this framework, but support for these standard
architectures is supported natively by p4c, while vendor-specific
architectures must be supported in the vendor's backend.
The goal of the framework is to reduce code redundancy. A
P4RuntimeArchHandlerIface implementation can be registered for each
architecture. The P4RuntimeSerializer singleton object …

A framework for P4Info generation for arbitrary architectures

---

backends/bmv2/CMakeLists.txt
backends/bmv2/run-bmv2-test.py

restore original p4c-bm2-ss name.

fix bmv2 backend names

---

control-plane/typeSpecConverter.cpp
test/gtest/p4runtime.cpp

Typedef's are eliminated in the midend, not the frontend, but the P4Info
generation happens after the frontend, so we have to support the case
where a type name can be a typdef.

Support typedef in P4Info TypeSpecConverter pass

---

frontends/p4/fromv1.0/programStructure.cpp

The issue seems to occur when compiling a P4_14 program which has a
direct meter with a pre_color property. It seems to be fixed by only
invoking the ExpressionConverter on pre_color if the field is not null.

Fix segfault when compiling with O3

---

ir/json_generator.h
ir/json_loader.h

A JSON loader/JSON generator template class was required for std::set, std::map, and ordered_set in order to include it as part of the IR.

std::set, std::map, ordered_set now allowed in IR

---

tools/driver/p4c_src/driver.py

Long running subprocesses with buffered output create the illusion
that nothing works. With this change, subprocesses of the driver will
inherit the stdout and stderr from the parent and display the output
of the child process unbuffered.

use parent stdout and stderr rather than pipe for subprocesses

---

frontends/p4/fromv1.0/programStructure.cpp

During the P4-14 to 16 translation, when a table has an attached direct_counter
or direct meter, the translation inserts a counter.count() or meter.execute()
method call to each of the action in the table.
As a result, if an action is used in the default_action property of the table,
the default_action has changed from the original unmodified action to the
updated action with counter.count() or meter.execute().
The current P4-14 to 16 translation has a bug which does not update the
default_action property in the table, and the wrong default_action is used when
a direct_counter or meter present.

bugfix: default_action translation to p4-16

---

frontends/parsers/p4/p4parser.ypp

dotPrefix non-terminal was not used for expressions starting with dot prefixes, which meant they were parsed in the local context instead of being parsed at the toplevel context (and this can lead to local types interfering with toplevel nonTypeName s).

 Use dotPrefix non-terminal for expressions having a dot prefix

---

backends/bmv2/CMakeLists.txt
backends/bmv2/bmv2stf.py
backends/bmv2/common/action.cpp
backends/bmv2/common/extern.cpp
backends/bmv2/common/extern.h
backends/bmv2/run-bmv2-test.py
backends/bmv2/simple_switch/simpleSwitch.cpp
testdata/extern_modules/extern-funcs-bmv2.cpp
testdata/p4_16_bmv_errors/no-externs-bmv2.p4
testdata/p4_16_samples/extern-funcs-bmv2.p4
testdata/p4_16_samples/extern-funcs-bmv2.stf

This change builds on top of pull request #1217 to also support emitting
extern functions (in addition to objects and methods).
It assumes extern functions have the __extern_ prefix, to avoid name
collision.

Emit extern functions with --emit-externs

---

frontends/parsers/p4/p4parser.ypp

In the spec, it is written that each architecture may have its own table properties, like, for example, an `implementation` table property.
But table property names, in the current grammar, cannot be type names.
So imagine that a programmer accidentally defines a type that has the same name as a table property for the architecture he is targeting (or includes another P4 program that does). He could no longer use the table property in tables, as it would be seen as a syntax error.
This pr allows table properties to be type names, preventing this problem.

Minor extension: prevent defined types from disabling table properties

---

control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeArchStandard.h
control-plane/p4RuntimeSerializer.cpp
test/gtest/helpers.cpp
test/gtest/p4runtime.cpp

Because PSA and v1model share many similarities (not to mention that
they are both considered standard architectures in the context of
P4Runtime), we tried to unify the code for the two architectures as much
as possible using meta-programming. We define a "traits" class for each
extern type to handle the difference in naming (table property names,
extern type names, extern method parameter names). One major difference
between the two architectures is digest: v1model uses an extern method
while PSA defines an extern type.
We added a new gtest unit test for the PSA code, very similar to the
ones we already have for v1model. Unfortunately PSA requires a lot of
boiler-plate code so the test is pretty verbose. We may want to find a
better solution in the future. The unit test covers digest, …

Add support for PSA in p4RuntimeSerializer

---

tools/driver/p4c_src/p4c.bmv2.cfg

The --p4runtime-file option provided by the user was ignored by the
driver (for bmv2), which was adding its own --p4runtime-file option when
invoking the compiler. For some reason, the bnv2 backend was the only
one to work this way. With this commit, the driver no longer generates
its own option by default and instead honors the one provided by the
user.
Fixes #1221

Fix handling of p4runtime options in p4c driver

---

backends/ebpf/ebpftargets.py

This hotfix provides the makefile with the location of the compiler. It allows non-global generation of p4 programs.
In general the structure of the makefiles needs to be rethought, this is a future ToDo.

Fix ebpf testing when make install has not been called.

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/programStructure.h
frontends/p4/simplifyParsers.cpp
frontends/p4/unusedDeclarations.cpp
testdata/p4_14_samples/parser_pragma2.p4
testdata/p4_14_samples_outputs/parser_pragma-first.p4
testdata/p4_14_samples_outputs/parser_pragma-frontend.p4
testdata/p4_14_samples_outputs/parser_pragma-midend.p4
testdata/p4_14_samples_outputs/parser_pragma.p4
testdata/p4_14_samples_outputs/parser_pragma2-first.p4
testdata/p4_14_samples_outputs/parser_pragma2-frontend.p4
testdata/p4_14_samples_outputs/parser_pragma2-midend.p4
testdata/p4_14_samples_outputs/parser_pragma2.p4
testdata/p4_14_samples_outputs/parser_pragma2.p4-stderr

This PR extends the P4-14 to P4-16 converter to support multiple entry points to parser. This feature does not comply with the P4-14 specification, as the P4-14 spec only allow one entry point to the parser, however, it is a useful feature for certain targets. 
Previously, the frontend had a hack in unusedDeclaration.cpp and simplifyParser.cpp to prevent any state with `packet_entry` pragma from being eliminated. However, this hack does not work on a state that is used and only used by the the additional entry point states. As a result, the frontend gives a 'Cannot find declaration' error when a state used by the additional entry point is eliminated. This PR fixes this bug.
The added `start` state needs to be removed by the backend. However, backend does not have to support this feature, …

Extend P4-14 frontend to support multiple entry points to parser

---

frontends/p4/commonInlining.h

The build with -DENABLE_UNIFIED_COMPILATION=OFF is currently broken. It fails with the error
```
In file included from p4c/frontends/p4/actionsInlining.cpp:17:
In file included from p4c/frontends/p4/actionsInlining.h:23:
p4c/frontends/p4/commonInlining.h:77:13: error: no member named 'CallGraph' in namespace 'P4'
P4::CallGraph<const Callable*> cg("Call-graph");
~~~~^
```
This change adds `#include` with the missing dependency.

Include missing header file

---

CMakeLists.txt
tools/ir-generator/CMakeLists.txt

This fix makes the build system work with the Xcode generator,
which otherwise fails to produce the correct dependencies for
the custom command that builds IR generated sources.

Fix irgenerator dependecy in cmake files

---

control-plane/p4RuntimeSerializer.cpp

Targets/backends can define additional match types, so there should be some way of telling this code what to do with them.  For now though, its better to just ignore them so at least the compiler can get to the backend...

Ignore unknown match types (with warning) rather than crashing out.

---

backends/p4test/CMakeLists.txt
backends/p4test/run-p4-sample.py
cmake/P4CUtils.cmake
control-plane/p4RuntimeArchStandard.cpp

* Fix P4Info register serialization for PSA
The PSA register has 2 type parameters (while the v1model register has a
single one), so the BUG_CHECK didn't make sense.
* Generate P4Info as part of p4test backend tests
In order to improve test coverage of P4Info generation, we are now
generating it by default in p4test backend tests.
Tests can be explicitly added to P4RUNTIME_EXCLUDE if P4Info cannot be
generated even though they are valid v1model / PSA programs.
A new cmake macro was introduced to register tests which include P4Info
generation: p4c_add_tests_w_p4runtime. I didn't want to modify
p4c_add_tests to avoid breaking backends that may be using this macro to
register their own tests.

Generate P4info in p4test backend tests

---

midend/simplifyKey.h

Actually change is between line 43 and 58.
I also ran clang-format on this file.

bugfix: reset bool 'simple' to true when apply to a new IR node

---

backends/p4test/CMakeLists.txt
control-plane/p4RuntimeSerializer.cpp

The elementType is in this case a type name, but you want the actual type represented by it.
This is obtained by looking it up in the typeMap.

Fix for issue #1401

---

ir/visitor.cpp

When a Transform is trying memoize modified/generated nodes to avoid
making duplicates in a postorder function, we don't want to undo that
memoization with the fixup for a noop postorder.
A trivial fix for a very obscure, hard to track down corner case...

Fix corner case bug in Transfor::apply_visitor

---

ir/pass_manager.cpp

When a backtrack trigger of type `t` is thrown from a nested pass manager and when it is meant to be
caught in the top-level pass manager, the trigger type currently does not recognize type `t`. This
PR ensures that the trigger type is not lost when a backtrack exception is rethrown by the nested
pass manager.

Fix a bug with the backtracking framework

---

cmake/FindLibGc.cmake

I noticed this while debugging a problem I was having finding libgc. The cause turned out to be unrelated i.e. FindLibGc worked as it is. Nevertheless the apparently mis-typed package name is confusing for a human.

Fix bdw-gc package name in FindLibGc.make

---

lib/error_reporter.h

I would like to write some GTests in which I change the output stream to
be a stringstream so that the unit test can verify that the error
message is the expected one. Adding the getOutputStream method enables
me to "save" the existing output stream then "restore" it when I am
done.

Add getOutputStream method to ErrorReporter

---

lib/bitvec.h
test/gtest/bitvec_test.cpp

Here are a couple of gtest additions for bitvecs -- even revealed an unnoticed typo in the previous checkin.

gtest additions for bitvec

---

frontends/p4/inlining.cpp
frontends/p4/localizeActions.cpp
frontends/p4/symbol_table.cpp

- error messages should use the original name from the source

Try to preserve IR::ID::originalName when renaming things

---

lib/n4.h

This PR ensures that p4c works in a 32-bit environment.
There are a number of assumptions in the code that unsigned long is 8 bytes. Therefore, unsigned long and uintptr_t data types are converted to uint64_t and appropriate constants.
There is still a potential issue with the asLong constant which also returns a long. However, the gmp library casts those values to long itself, and thus the 32-bit version of the library is consistent. Even though, the entire suite of tests passes, I'm not 100% sure that this does not break any other assumptions in the compiler.

32-bit support

---

backends/bmv2/common/header.cpp
backends/bmv2/simple_switch/simpleSwitch.cpp
p4include/v1model.p4
testdata/p4_14_samples_outputs/issue-1426-midend.p4
testdata/p4_16_errors_outputs/issue584.p4-stderr
testdata/p4_16_samples/issue1325-bmv2.p4
testdata/p4_16_samples_outputs/drop-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1325-bmv2-first.p4
testdata/p4_16_samples_outputs/issue1325-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1325-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1325-bmv2.p4
testdata/p4_16_samples_outputs/issue1409-bmv2-first.p4
testdata/p4_16_samples_outputs/issue1409-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1409-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1409-bmv2.p4
testdata/p4_16_samples_outputs/issue1409-bmv2.p4-stderr
testdata/p4_16_samples_outputs/issue841.p4-stderr

@antoninbas : I don't know if this is sufficient to fix #808, but it can't harm.
@hanw: the error code generation was done too early, so the errors[] array was always empty.
We should write some real tests for handling parser errors, but this fix should address #1325.

Fix for issue #1325, hopefully for #808 too

---

ir/expression.def
test/CMakeLists.txt
test/gtest/constant_expr_test.cpp
testdata/p4_16_errors_outputs/width_e.p4-stderr

Casting to long on 32-bit machines does not achieve the expected
result that the value is 64-bit. This PR adds support for uint64_t in
IR::Constant, by expanding the set of constructors with the
almost all used integer data types (exception is unsigned long because the
ir parser generator does not handle types that have two qualifiers).
TODO: deprecate the use of asLong throughout the code base. Right now,
it is used only in v1parser.ypp, and as far as I can tell, only for
sizes that should be well within 32-bits (ids, bit-widths, etc.). I do
recommend a review of the code, and replacement with asUnsigned().
Added a gtest to check different values for all the types -- which is really
what forced me to the solution adding all constructors!

add support for uint64_t constants in IR::Constant (for 32-bit)

---

lib/cstring.h
lib/enumerator.h
lib/json.h
lib/path.h
lib/sourceCodeBuilder.h
lib/stringify.cpp

Fixed operator std::string += cstring in cstring library. Implementation do nothing now, modifies copy of string and returns copy of modified copy.
Fixed memory leak in stringify utility. cstring makes copy of string internally in strings table,
memory will never be released without GC
LUTSENKO DANIL
SOFTWARE DEVELOPER
www.jabil.com

Utilities minor fixes

---

ir/dump.cpp
ir/type.cpp

- return a nullptr when trying to infer a tuple type from a list if an
element can't be inferred properly.  Allows the calling code to give a
reasonable error message.

Avoid 'Null e' CompilerBug

---

README.md
backends/ebpf/CMakeLists.txt
backends/ebpf/README.md
backends/ebpf/run-ebpf-test.py
backends/ebpf/targets/kernel_target.py
tools/testutils.py

This should fix issue #1459.
To run the tests that require root one should do `sudo make check-ebpf-kernel`.

Skip tests that require root rather than failing them

---

frontends/common/parseInput.cpp
ir/pass_manager.cpp
test/gtest/arch_test.cpp
test/gtest/midend_test.cpp
test/gtest/p4runtime.cpp

- after an error, arbitrarily returning nullptr from a PassManager can
result in a crash or error cascade -- we instead return the tree from
before the error.
- stop_on_error should only abort after a NEW error, to allow some
continued error checking after an error.

Avoid crashing after errors

---

backends/ebpf/targets/ebpfenv.py
backends/ebpf/targets/kernel_target.py
cmake/P4CUtils.cmake
tools/testutils.py

This requests modifies `p4c_add_test_list` to add the absolute path to file inputs. This is necessary for xfail tests in extensions such as p4c-xdp, which did not properly matched and were ignored.
Another addition is a check for Travis builds in the ebpf-kernel tests. It seems that due to privilege issues Travis does not support netem or ip netns commands:
`mount --make-shared /var/run/netns failed: Operation not permitted`
The check is to ensure that run does not get executed. Ideally, we still want to check that loading is possible, but this requires creating a new type of virtual environment.

Sanitize file path input in cmake, add travis check to skip tests

---

ir/json_generator.h

Refactored `generate()` for pairs to introduce `toJSON()`, for cases where we just want to generate the body of a JSON object.

Refactored generate() for pairs.

---

backends/bmv2/simple_switch/midend.cpp
ir/indexed_vector.h
midend/CMakeLists.txt
midend/actionSynthesis.h
midend/checkSize.h
testdata/p4_16_samples/issue1478-bmv2.p4
testdata/p4_16_samples_outputs/issue1478-bmv2-first.p4
testdata/p4_16_samples_outputs/issue1478-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1478-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1478-bmv2.p4

Unfortunately the stderr is produced by p4test, and not by p4c-bm2-ss.
But when running p4c-bm2-ss on the sample it will produce two warnings:
```
issue1478-bmv2.p4(25): warning: 3: Size specified for table without keys
size = 3;
^
issue1478-bmv2.p4(35): warning: 10: Size specified for table with constant entries
size = 10;
^^
```

Fix for issue #1478

---

frontends/p4/typeChecking/bindVariables.cpp
lib/exceptions.h

The specific case that comes up is passing a list of values to validateChecksum -- if one value is an untyped constant, then the error message was just giving the line info about the validateChecksum declaration (in the header file) and not providing any clarity as to the actual problem.  Several people have run into this problem and been unable to figure out what was going wrong from the error message.
I'm not a big fan of elaborating special cases in error messages like this, so it would be better to come up with a more general scheme; perhaps saving the expressions that are used to infer types in type inferencing.

 Improve error message for a specific type inferencing failure that seems to come up frequently.

---

cmake/FindLibGmp.cmake
tools/ir-generator/CMakeLists.txt

While statically linking the order of libraries matters. Note that we
don't do that by default, we just allow the tools to be built when
requested to link against static libraries for gmp and boost.

support for static linking

---

backends/bmv2/psa_switch/psaSwitch.cpp
backends/bmv2/simple_switch/simpleSwitch.cpp
backends/ebpf/ebpfProgram.cpp

This should improve the error message when someone uses the wrong architecture file.
Unfortunately it's not easy to add tests due to the way our testing infrastructure is setup. These would have to be negative tests, and the negative tests would only fail with some compilers, not with p4test.

Fix for issue #1508

---

frontends/p4/fromv1.0/programStructure.cpp
frontends/parsers/v1/v1lexer.ll
frontends/parsers/v1/v1parser.ypp
ir/v1.def
testdata/p4_14_samples/const_default_action.p4
testdata/p4_14_samples_outputs/const_default_action-first.p4
testdata/p4_14_samples_outputs/const_default_action-frontend.p4
testdata/p4_14_samples_outputs/const_default_action-midend.p4
testdata/p4_14_samples_outputs/const_default_action.p4

This PR implements an experimental feature in P4-14 to support const default_action by introducing a new table property keyword 'const_default_action'.

support const default_action in p4-14

---

frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/programStructure.h

- P4_14 allows multiple things with the same name in the global scope
and requires the compiler to figure out which is which based on
context.  In P4_14 typechecking we don't have detailed knowledge of
what primitive arguments should be, so we assume they are externs or
other objects (target dependent), which can turn out to be wrong in
the case of field_list_calculations.

P4_14->16 conversion of field_list_calculation with same name as other object

---

CMakeLists.txt
README.md

I believe we've had more than 3 people cut and paste optional arguments to cmake, so here is for their benefit!

make optional arguments to cmake explicit

---

backends/ebpf/run-ebpf-test.py
backends/ebpf/targets/bcc_target.py
backends/ebpf/targets/ebpfenv.py
backends/ebpf/targets/kernel_target.py
backends/ebpf/targets/target.py
backends/ebpf/targets/test_target.py

- Move IPv6 options out of the critical path
- Move qdisc operations into the kernel target, it is the only target that needs them.
- Improve the test parsing, it is now easier to modify or add options.
- Rename create_filter to compile_dataplane to clarify the purpose of the function

Optimizations on the testing backend

---

.travis.yml
backends/p4test/run-p4-sample.py
ir/indexed_vector.h
ir/ir.def
tools/install_os_deps.sh

Adds OSX in Travis. While we don't do as extensive testing as in docker since we do not install bmv2, we do compile and run the p4 tests, which will at least ensure that OSX builds are clean.

add support for OSX in Travis

---

tools/install_os_deps.sh

The command
```
brew link --force bison
```
returns an error on recent versions of Homebrew/OS X:
```
Warning: Refusing to link macOS-provided software: bison
...
```
This PR implements the suggestion from Homebrew. Note: it assumes that Homebrew binaries are installed in the standard location (`/usr/local/opt`).

Fix OS X dependency script

---

frontends/p4/fromv1.0/programStructure.cpp
ir/type.cpp
ir/type.def
testdata/p4_14_samples/saturated-bmv2.p4
testdata/p4_14_samples/saturated-bmv2.stf
testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4

Implements saturated arithmetic in P4-14. Since the fields are tagged
with the saturated annotation, we add isSaturated to the Type_Bits.
This also requires refactoring the map caching the bit
types. Previously, we were storing signed and unsigned in separate
maps. Adding more maps to accomodate the saturated types is
impractical, so we unified the maps and added a key consisting of
(width, sign, saturation).
Since P4-16 supports only operations as saturated, the conversion
routines for the supported primitives, add, subtract, add_to_field,
subtract_from_field, change the operation to saturated if any of its
arguments are saturated.

add saturated arithmetic support to p4-14

---

ir/visitor.cpp

A couple of people have tried to call `prune()` in a Transform::preorder function before calling visit on some child, which doesn't work (as visiting the child will reset the prune flag.)  This avoids that problem by making the recursive visit call preserve the flag, so things will work as expected regardless of when prune() is called.

Save/restore prune_flag in Transform::apply_visitor

---

control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp

* modify postCollect method to accept a pointer to symbol table instead
of a const reference, in case the architecture-specific code needs to
add some new symbols to the table
* add postAdd method so that some architecture-specific post-processing
can be performed on the P4Info message after all objects have been
added

Extend arch-handler interface in P4Runtime serializer code

---

frontends/p4/defaultArguments.h

This fixes the build when `ENABLE_UNIFIED_COMPILATION` cmake option is set to OFF.  Without this header `TypeChecking` class is undefined.

Include missing header

---

backends/ebpf/CMakeLists.txt
backends/ebpf/run-ebpf-test.py
backends/ebpf/targets/target.py

Currently to run ebpf tests the compiler must be built in `build/` subdirectory of the repository clone.  It is hard-coded.  This patch fixes that and allows the compiler to be built anywhere, including outside the source directory.

Allow ebpf tests to work in any build location

---

.gitmodules
control-plane/CMakeLists.txt
control-plane/google/rpc/status.proto
control-plane/p4RuntimeArchStandard.cpp

The P4Runtime specification (including the Protobuf definition files) is
no longer hosted on p4lang/PI but on p4lang/p4runtime, so we updated the
submodule to refelect that.
We need a third-party Protobuf file to compile P4Runtime
(google/rpc/status.proto). Rather than pull-in the entire googleapis
repository (100+MB) where this file is hosted, we add a copy of the file
here.

Remove PI submodule and use p4runtime instead

---

control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp
testdata/p4_16_samples_outputs/issue430-1-bmv2.p4-stderr

* Fix typo that was causing all indirect meters to be omitted from
P4Info.
* Collect extern functions (e.g. digest) invoked directly from a
control. It may not have been necessary in the past when the
serializer was run after the synthetization of actions by the
compiler, but it is necessary now.

Fix 2 bugs in P4Info generation code

---

control-plane/p4RuntimeSerializer.cpp

- static entries for a table with a selector (or other) key component
that is not relevant for the entry need a placeholder default for that
key component, which should just be ignored.

Supress error in P4RuntimeSerializer for default entry of unknown type

---

lib/bitvec.h

Bitvec operators that have arguments uintptr_t end up converting
other integer types to uintptr_t. On 32-bit systems, the conversion
from uint64_t to uintptr_t is wrong. For that we add new template
methods that do the proper conversion.
Interestingly enough, only the OR methods had the uintptr_t parameters.
Why?

add specialized methods for other integer types

---

CMakeLists.txt
backends/bmv2/CMakeLists.txt
backends/bmv2/psa_switch/main.cpp
backends/bmv2/psa_switch/version.h.cmake
backends/bmv2/simple_switch/main.cpp
backends/bmv2/simple_switch/version.h.cmake
backends/ebpf/CMakeLists.txt
backends/ebpf/p4c-ebpf.cpp
backends/ebpf/version.h.cmake
backends/graphs/CMakeLists.txt
backends/graphs/p4c-graphs.cpp
backends/graphs/version.h.cmake
backends/p4test/CMakeLists.txt
backends/p4test/p4test.cpp
backends/p4test/version.h.cmake

We add support for versioning different p4c backends independently of
each other. Currently we specify a global version in the root
CMakeLists.txt file, which will be reported by the p4c driver.
Individual backends get a configurable version string that is set at
configuration time based on macros derived from the global
version. However, each backend can customize the format of the
version, and see the example in the psa backend that hardcodes the
version to 0.0.1 and uses only the git SHA.
In honor of the language spec 1.1 release, I set the default version to 1.1.0-rc1.
Alternative solution to #1491.

add support for versioning p4c backends

---

backends/bmv2/bmv2stf.py
backends/bmv2/simple_switch/midend.cpp
frontends/p4/fromv1.0/programStructure.cpp
test/gtest/p4runtime.cpp
testdata/p4_14_samples_outputs/exact_match_mask1-first.p4
testdata/p4_14_samples_outputs/exact_match_mask1-frontend.p4
testdata/p4_14_samples_outputs/exact_match_mask1-midend.p4
testdata/p4_14_samples_outputs/exact_match_mask1.p4
testdata/p4_14_samples_outputs/issue1237-first.p4
testdata/p4_14_samples_outputs/issue1237-frontend.p4
testdata/p4_14_samples_outputs/issue1237-midend.p4
testdata/p4_14_samples_outputs/issue1237.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160226/switch.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch.p4
testdata/p4_16_samples/issue1560-bmv2.p4
testdata/p4_16_samples/key-bmv2.stf
testdata/p4_16_samples_outputs/issue1560-bmv2-first.p4
testdata/p4_16_samples_outputs/issue1560-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1560-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1560-bmv2.p4

Interestingly, this also fixes a long-standing bug in the stf testing infrastructure.
When converting P4-14 programs with table keys (reads) that have masks we have to generate the correct key names.

Fix for issue #1560

---

frontends/p4/typeChecking/typeSubstitution.cpp
testdata/p4_14_samples_outputs/saturated-bmv2-first.p4
testdata/p4_14_samples_outputs/saturated-bmv2-frontend.p4
testdata/p4_14_samples_outputs/saturated-bmv2-midend.p4
testdata/p4_14_samples_outputs/saturated-bmv2.p4
testdata/p4_16_samples/issue1540.p4
testdata/p4_16_samples/issue1566.p4
testdata/p4_16_samples/issue1586.p4
testdata/p4_16_samples_outputs/issue1540-first.p4
testdata/p4_16_samples_outputs/issue1540-frontend.p4
testdata/p4_16_samples_outputs/issue1540-midend.p4
testdata/p4_16_samples_outputs/issue1540.p4
testdata/p4_16_samples_outputs/issue1566-first.p4
testdata/p4_16_samples_outputs/issue1566-frontend.p4
testdata/p4_16_samples_outputs/issue1566-midend.p4
testdata/p4_16_samples_outputs/issue1566.p4
testdata/p4_16_samples_outputs/issue1586-first.p4
testdata/p4_16_samples_outputs/issue1586.p4
testdata/p4_16_samples_outputs/issue1586.p4-stderr

I think this is a bug in the design of C++.
If you get such an iterator: ` for (auto bound : binding)` over a map, the first and second fields should be const.

Fix for issue #1586; added more test cases

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h

Added a hook in P4-14 to P4-16 translation to allow customizing ExpressionConverter visitor function. Currently, it is only used to overload IR::FieldList visitor function.

add hook to support custom expression converter visitor function

---

tools/driver/p4c_src/main.py

The driver now checks the existence of the input file and bail out
early with an error message.
Fixes #1609

fail early when the input file does not exist

---

backends/bmv2/simple_switch/midend.cpp
ir/ir.def
midend/CMakeLists.txt
midend/flattenInterfaceStructs.cpp
midend/flattenInterfaceStructs.h
midend/nestedStructs.cpp
midend/nestedStructs.h
testdata/p4_16_samples/issue562-bmv2.p4
testdata/p4_16_samples_outputs/issue562-bmv2-first.p4
testdata/p4_16_samples_outputs/issue562-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue562-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue562-bmv2.p4

I am not 100% that this fix is foolproof - but it may be better than nothing for now.
I will have to think whether it can be tripped up by some crafty programs that use the nested structs for other purposes. However, the only bad thing that can happen is that we trigger more BUGs because we rewrite the programs incorrectly. But such programs weren't supported on bmv2 anyway, so the situation won't be any worse than it is now.

Fix for issue #562

---

control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp

New symbols cannot be added to the symbol table in the postCollect pass
because the table has already been created by then and cannot really be
mutated. A new virtual method (collectExtra) is added to let
architectures add symbols while the table can still be mutated.

Small refactor of ArchHandlerIface in P4Runtime serializer

---

frontends/parsers/p4/p4parser.ypp

This fixes the broken build when ENABLE_UNIFIED_COMPILATION=OFF
The error is the following
```
In file included from ../frontends/parsers/p4/p4AnnotationLexer.cpp:1:
In file included from ../frontends/parsers/p4/p4AnnotationLexer.hpp:4:
In file included from ../frontends/parsers/p4/abstractP4Lexer.hpp:4:
parsers/p4/p4parser.ypp:57:8: error: use of undeclared identifier 'std'
inline std::ostream& operator<<(std::ostream& out, const P4::OptionalConst& oc) {
```

Move #include directives to fix broken dependencies

---

backends/bmv2/common/annotations.h
control-plane/p4RuntimeSerializer.cpp
frontends/CMakeLists.txt
frontends/p4/frontend.cpp
frontends/p4/frontend.h
frontends/p4/parseAnnotations.cpp
frontends/p4/parseAnnotations.h
frontends/parsers/p4/p4AnnotationLexer.cpp
frontends/parsers/p4/p4AnnotationLexer.hpp
frontends/parsers/p4/p4parser.ypp
frontends/parsers/parserDriver.cpp
frontends/parsers/parserDriver.h
ir/base.def
test/gtest/helpers.cpp
test/gtest/helpers.h
test/gtest/p4runtime.cpp
testdata/p4_16_errors/annotation.p4
testdata/p4_16_errors_outputs/annotation.p4-stderr

* Improved the reporting of annotation-parsing errors:
* We now report source-line information when the annotation parser runs off the end of the annotation.
* Introduced a new `END_ANNOTATION` symbol for a better error message when the parser runs off the end of the annotation.
* Added a negative test case for annotation parsing.
* Fixed & improved handling of unparsed annotations, and added the ability to warn about unknown annotations.
* We now explicitly track whether an annotation needs parsing.
* Added a few more productions for parsing annotations with pairs or triples of expressions, string literals, and integer constants.
* Added ability to skip parsing of annotations. This is useful for avoiding warnings about annotations that are explicitly ignored.
* Renamed `PARSE_NO_BODY` to …

Fixes & improvements to annotation parsing

---

ir/json_parser.h

Some compiler issue the following warning
```
p4c/ir/json_parser.h:46:24: warning: all paths through this function will call itself [-Winfinite-recursion]
operator cstring() { return cstring(*this); }
```
This is because they interpret the expression in return statement
as cast and not as an invocation of cstring constructor.
To disambiguate, use the C string pointer embedded in the object
to invoke a different cstring constructor.

Fix possible infinite recursion in cast operator

---

frontends/p4/frontend.cpp
frontends/p4/localizeActions.cpp
frontends/p4/typeChecking/bindVariables.cpp
frontends/p4/typeChecking/bindVariables.h
frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_errors/issue1638-e.p4
testdata/p4_16_errors_outputs/issue1638-e.p4
testdata/p4_16_errors_outputs/issue1638-e.p4-stderr
testdata/p4_16_samples/default-package-argument.p4
testdata/p4_16_samples/issue1638.p4
testdata/p4_16_samples_outputs/default-package-argument-first.p4
testdata/p4_16_samples_outputs/default-package-argument-frontend.p4
testdata/p4_16_samples_outputs/default-package-argument-midend.p4
testdata/p4_16_samples_outputs/default-package-argument.p4
testdata/p4_16_samples_outputs/issue1333-first.p4
testdata/p4_16_samples_outputs/issue1333-frontend.p4
testdata/p4_16_samples_outputs/issue1333-midend.p4
testdata/p4_16_samples_outputs/issue1638-first.p4
testdata/p4_16_samples_outputs/issue1638-frontend.p4
testdata/p4_16_samples_outputs/issue1638-midend.p4
testdata/p4_16_samples_outputs/issue1638.p4

This also fixes a couple of bugs which were losing default parameter values, found by @hanw.

 Reorganize passes to handle default values; fixes #1638 and #1639 

---

backends/bmv2/README.md
frontends/p4/fromv1.0/converters.cpp
testdata/p4_14_samples/issue576.p4
testdata/p4_14_samples_outputs/09-IPv4OptionsUnparsed-first.p4
testdata/p4_14_samples_outputs/09-IPv4OptionsUnparsed-frontend.p4
testdata/p4_14_samples_outputs/09-IPv4OptionsUnparsed-midend.p4
testdata/p4_14_samples_outputs/09-IPv4OptionsUnparsed.p4
testdata/p4_14_samples_outputs/TLV_parsing-first.p4
testdata/p4_14_samples_outputs/TLV_parsing-frontend.p4
testdata/p4_14_samples_outputs/TLV_parsing-midend.p4
testdata/p4_14_samples_outputs/TLV_parsing.p4
testdata/p4_14_samples_outputs/issue576-first.p4
testdata/p4_14_samples_outputs/issue576-frontend.p4
testdata/p4_14_samples_outputs/issue576-midend.p4
testdata/p4_14_samples_outputs/issue576.p4
testdata/p4_14_samples_outputs/issue576.p4-stderr
testdata/p4_14_samples_outputs/issue781-first.p4
testdata/p4_14_samples_outputs/issue781-frontend.p4
testdata/p4_14_samples_outputs/issue781-midend.p4
testdata/p4_14_samples_outputs/issue781.p4

This is about translating P4-14 header stacks into P4-16. The translation was incorrect for stacks with varbits. We now handle correctly headers that contain one varbit field. 
Instead of splitting a header into multiple headers, we read the fixed-sized part of a header using lookahead, and use it to compute the length, which is then used to read the whole header using an extract. The previous translation was not handling correctly the next/last stack fields.
Fixes #576.
(This also generates better code.)

Improved translation of P4-14 header stacks with varbits (fixes #576)

---

control-plane/p4RuntimeArchHandler.cpp
control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp
test/gtest/p4runtime.cpp
testdata/p4_16_samples_outputs/bitwise-and.p4-stderr
testdata/p4_16_samples_outputs/issue1524.p4-stderr
testdata/p4_16_samples_outputs/issue407-2.p4-stderr
testdata/p4_16_samples_outputs/issue407-3.p4-stderr

The documentation information comes from the '@brief' and '@description'
annotations. The PkgInfo message is populated based on the annotations
on the P4 package declaration.
To reduce code duplication, a new setPreamble helper function is added,
which can be used to set all the fields (including documentation and
generic annotations) in the preamble for all P4Info entities.
Fixes #1170

Populate Documentation fields and PkgInfo in P4Info

---

frontends/common/options.cpp
frontends/p4/commonInlining.h
frontends/p4/inlining.cpp
frontends/p4/inlining.h
frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeChecker.h
ir/pass_manager.h
lib/log.cpp
testdata/p4_14_samples_outputs/issue-1426-frontend.p4
testdata/p4_14_samples_outputs/issue-1426-midend.p4
testdata/p4_16_samples_outputs/inline-stack-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1466-frontend.p4
testdata/p4_16_samples_outputs/issue1466-midend.p4
testdata/p4_16_samples_outputs/issue1566-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1566-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1566-frontend.p4
testdata/p4_16_samples_outputs/issue1566-midend.p4
testdata/p4_16_samples_outputs/pipe-frontend.p4
testdata/p4_16_samples_outputs/pipe-midend.p4

When inlining controls, we check for aliasing and avoid creating copies of arguments if there is no possibility of aliasing, but currently that is restricted to a single call site.  This change extends that to multiple call sites if all the call sites use the same arguments.  If the arguments are different, we would need copies in at least some cases (to get them into the same place), but if all call sites are the same, copies are not needed.
Currently this only avoids the copies if the call sites are completely the same -- if the call sites had the same arguments for some parameters and not others, copies would be needed only for the parameters that were different between calls sites, but that would be a bit more work.
There's also a bunch of cleanups that crept into this branch.

Avoid unneeded copies when inlining controls

---

frontends/p4/typeChecking/typeChecker.h

Otherwise, when method in derived class calls setTypeType, the setTypeType
method will create an instance of the base class TypeInference and apply it.

change setTypeType to virtual to allow override.

---

ir/base.def
tools/ir-generator/methods.cpp

- add Declarator::equiv and Type_Declarator::equiv that ignores declid,
so repeated specializations with the same types will compare
equivalent.

Fix equiv generation to be easier to override properly

---

ir/ir-inline.h
ir/visitor.h

- using this as a way of getting a 'bottom' flow lattice element is
confusing and error prone, and not really necessary; not having it
only makes a couple of visit_children routines slightly more complex.  That additional complexity also has the added bonus of being more efficient.

Get rid of Visitor::flow_dead

---

frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeChecker.h
ir/visitor.cpp
ir/visitor.h

A class that introducing new IR class needs to subclass TypeInference and overriding the clone() method.

move clone() method from ControlFlowVisitor to Visitor

---

backends/bmv2/common/backend.h
backends/p4test/midend.cpp
midend/actionSynthesis.cpp
midend/actionSynthesis.h

- add a query to specify when statements should be combined into a
single action, or made into separate actions.

extend ActionSynthesisPolicy

---

testdata/p4_16_samples/v1model-special-ops-bmv2.p4
testdata/p4_16_samples_outputs/v1model-special-ops-bmv2-first.p4
testdata/p4_16_samples_outputs/v1model-special-ops-bmv2-frontend.p4
testdata/p4_16_samples_outputs/v1model-special-ops-bmv2-midend.p4
testdata/p4_16_samples_outputs/v1model-special-ops-bmv2.p4

It seems unlikely that standard or intrinsic metadata should be
allowed to be explicitly preserved in this way, since the architecture
defines how these should be filled in at the beginning of an ingress
and/or egress pipeline.

Remove standard_metadata from preserved metadata in test program

---

backends/p4test/CMakeLists.txt
control-plane/CMakeLists.txt
control-plane/flattenHeader.cpp
control-plane/flattenHeader.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp
control-plane/typeSpecConverter.cpp
control-plane/typeSpecConverter.h
test/gtest/p4runtime.cpp
testdata/p4_16_samples_outputs/issue1670-bmv2.p4.p4info.txt
testdata/p4_16_samples_outputs/p4rt_digest_complex.p4.p4info.txt

The P4Info generation code now handles complex headers by flattening
them. This is independent from the FlattenHeaders pass, which is a
midend pass. This code is much simpler and has no dependency on non
frontend pass. It simply performs a "local" flattening of a given
Type_Header, without updating any program references. It also preserves
the fully-qualified name using a @name annotation (unlike the
FlattenHeaders pass), along with annotations of the nested
fields. Because of the local nature of this flattening, it seemed silly
to write an actual pass (I tried and it was clumsy, with a call to
visitAgain).
The flattening is performed wherever the p4RuntimeSerializer has to deal
with header types, so only 2 places: for controller headers and in the
typeSpecConverter.

Handle complex headers (with nested structs) in P4Info generation

---

backends/bmv2/bmv2stf.py

When there are multiple expected output packets, this can help in more
quickly determining why the STF test is failing.

Show both expected and received packet when STF test fails

---

backends/bmv2/CMakeLists.txt
testdata/p4_14_samples/p414-special-ops-2-bmv2.p4
testdata/p4_14_samples/p414-special-ops-2-bmv2.stf
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2-first.p4
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2-frontend.p4
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2-midend.p4
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2.p4

It is nearly identical to the test program p414-special-ops.p4
proposed to be added in the PR #1704, except that program explicitly
lists individual fields to be preserved during resubmit
etc. operations, whereas this one gives the name of an entire metadata
'header' to be preserved.
For p414-special-ops-2-bmv2.p4, p4c as of this writing introduces
temporary metadata variables and preserves those instead of the ones
named in the source file, and since the STF packet tests cases rely
for their correct operation on the metadata fields being preserved,
they fail.

Add XFAIL P4_14 test program that fails because of issue #1669

---

backends/bmv2/CMakeLists.txt
testdata/p4_14_samples/p414-special-ops-3-bmv2.p4
testdata/p4_14_samples/p414-special-ops-3-bmv2.stf
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2-first.p4
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2-frontend.p4
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2-midend.p4
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2.p4

It is nearly identical to the test program p414-special-ops.p4
proposed to be added in the PR #1704, except this program explicitly
modifies metadata fields after a resubmit, recirculate, or clone
operation is performed, and the STF tests will only pass if the
behavior of the packet processing is that the metadata fields are
preserved at the _end_ of ingress/egress processing, _not_ the values
that the metadata fields have at the time of the
recirculate/resubmit/clone primitive operation call.
This is consistent with the P4_14 language specification, at least as
of the clarifications made in v1.0.5 of the specification.

Add XFAIL P4_14 test program that fails because of issue #1694

---

control-plane/p4RuntimeSerializer.cpp
frontends/common/options.cpp
frontends/common/options.h
tools/driver/p4c_src/main.py

Fixes #1705.
I haven't deleted the old options. Together they are a bit redundant, but I don't want to break any scripts.

Support multiple p4runtime files

---

frontends/common/constantFolding.h
frontends/p4/simplify.h
frontends/p4/strengthReduction.h
midend/actionSynthesis.h
midend/complexComparison.h
midend/convertEnums.h
midend/copyStructures.h
midend/eliminateNewtype.h
midend/eliminateSerEnums.h
midend/eliminateTuples.h
midend/expandEmit.h
midend/expandLookahead.h
midend/local_copyprop.h
midend/nestedStructs.h
midend/orderArguments.h
midend/removeExits.h
midend/removeParameters.cpp
midend/removeParameters.h
midend/removeSelectBooleans.h
midend/simplifyKey.h
midend/simplifySelectCases.h
midend/simplifySelectList.h
midend/tableHit.h

To allow some target to experiment with new IR types and reuse existing midend passes.

allow customizing typeChecker in some midend passes

---

backends/bmv2/common/deparser.cpp
backends/bmv2/common/deparser.h
backends/bmv2/common/parser.cpp
backends/bmv2/common/parser.h
backends/bmv2/psa_switch/psaSwitch.cpp
backends/bmv2/psa_switch/psaSwitch.h

This is useful for PSA, for which there are 2 parsers and 2
deparsers.
The bmv2 PSA backend now uses the following names:
* ingress_parser
* egress_parser
* ingress_deparser
* egress_deparser

Add support for multiple parsers / deparsers in bmv2 backend

---

frontends/common/resolveReferences/resolveReferences.cpp
midend/actionSynthesis.cpp

- propagate source info from statements to newly created actions and
tables; allows later passes to generate errors/warnings referring to
the code that the tables were created from rather than just a
meaningless name like tbl_act_14

actionSynthesis propagate source info

---

testdata/p4_16_errors/typedef-and-type-definitions.p4
testdata/p4_16_errors_outputs/typedef-and-type-definitions.p4
testdata/p4_16_errors_outputs/typedef-and-type-definitions.p4-stderr

This is the test program I wrote while determining which types were
supported for typedef and type while creating this proposed table to
add to the P4_16 language spec:
https://github.com/p4lang/p4-spec/pull/731

Add program that tests p4c's error-detection capability for bad type's

---

control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp
ir/ir.def

Making control plane name generation generic to an `IR::Block`. This allows overriding the function to have a different implementation if desired.

Generic control plane name generation from IR::Block

---

midend/flattenHeaders.cpp
midend/flattenHeaders.h

This change will keep the annot on struct with the fields that the struct is flattened to.
```
@my_annot
struct st {
bit<8> f0; 
}
header hd{
st s;
}
```
```
header hd {
@my_annot _s_f0;
}
```

move annotations on header to fields

---

backends/bmv2/psa_switch/psaSwitch.cpp
backends/bmv2/psa_switch/psaSwitch.h

Changelog:
Add psa specific metadata to the psa_switch backend in accordance with https://github.com/jafingerhut/p4-guide/blob/master/psa-examples/README-psa-implementation.md.
Test:
All tests passed in travis on fork

Add psa specific metadata to bmv2 psa_switch backend

---

control-plane/p4RuntimeSerializer.cpp
ir/expression.def
lib/stringify.cpp
lib/stringify.h
test/gtest/p4runtime.cpp
testdata/p4_14_samples_outputs/issue583.p4-stderr
testdata/p4_16_errors_outputs/issue413.p4-stderr
testdata/p4_16_errors_outputs/issue584.p4-stderr
testdata/p4_16_errors_outputs/width1_e.p4-stderr
testdata/p4_16_samples_outputs/const.p4-stderr
testdata/p4_16_samples_outputs/large.p4-stderr
testdata/p4_16_samples_outputs/spec-ex04.p4-stderr
testdata/p4_16_samples_outputs/strength.p4-stderr
testdata/p4_16_samples_outputs/table-entries-exact-ternary-bmv2.p4-stderr
testdata/p4_16_samples_outputs/table-entries-exact-ternary-bmv2.p4.entries.txt
testdata/p4_16_samples_outputs/table-entries-lpm-bmv2.p4-stderr
testdata/p4_16_samples_outputs/table-entries-lpm-bmv2.p4.entries.txt
testdata/p4_16_samples_outputs/table-entries-priority-bmv2.p4-stderr
testdata/p4_16_samples_outputs/table-entries-priority-bmv2.p4.entries.txt
testdata/p4_16_samples_outputs/table-entries-range-bmv2.p4.entries.txt
testdata/p4_16_samples_outputs/table-entries-ternary-bmv2.p4-stderr
testdata/p4_16_samples_outputs/table-entries-ternary-bmv2.p4.entries.txt

See #1805
* omit don't care matches
* toggle off value bits which are masked off for ternary and LPM
* emit a warning for ignored @priority annotation, and generate correct
priority values
* I couldn't move to the canonical binary string representation for
bit<W> values because it is not currently supported by p4lang/PI

Make --p4runtime-entries outputs more conformant to P4Runtime spec

---

backends/bmv2/common/expression.cpp
backends/bmv2/psa_switch/psaSwitch.cpp
backends/bmv2/psa_switch/psaSwitch.h

Changelog:
Added referencing the metadata so ExpressionConverter::postorder actually uses the new ones. Small refactor of convertParam in psaSwitch.h and added a lot of logs so in the future I don't have to rewrite them (labeled with cornell: will remove once psa development is done). I can remove the logs if we'd like but they're helpful for development in the time being. 
Actually compiles https://github.com/jafingerhut/p4-guide/blob/master/psa-examples/psa-unicast-or-drop.p4 and https://github.com/jafingerhut/p4-guide/blob/master/psa-examples/psa-simple-reflector.p4 now.
Test:
All tests pass in travis in peteli3/p4c fork

Fix issue with bmv2 psa_switch backend not able to reference the new metadata

---

backends/p4test/CMakeLists.txt
frontends/common/options.cpp
lib/CMakeLists.txt
lib/error.h
lib/error_helper.h
lib/error_reporter.h
lib/exceptions.h

The compiler error reporting is based on the principle that printing
as many errors as possible will allow users to fix multiple of them in
a single compilation pass. However large number of errors is usually
too hard to handle, and people will incrementally fix errors as they
go. What is that magic number? Clang uses 20, which seems quite
reasonable, so we use that as a base.
We also provide the `ErrorReporter::setMaxErrorCount` function, so
that different backends can chose their own threshold matching their
user's expectations.
And finally, a bit more cleanup to remove redundancies in the error
reporting code. The main reason for splitting error_helper and
bug_helper functions into a separate header is to avoid circular
include dependencies:
error.h -> error_reporter.h -> exceptions.h …

add a bound to the number of errors that are printed before exiting

---

backends/bmv2/CMakeLists.txt
frontends/p4/inlining.cpp
frontends/p4/inlining.h
testdata/p4_16_samples_outputs/functors2-frontend.p4
testdata/p4_16_samples_outputs/functors3-frontend.p4
testdata/p4_16_samples_outputs/functors4-frontend.p4
testdata/p4_16_samples_outputs/functors5-frontend.p4
testdata/p4_16_samples_outputs/issue1470-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1470-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue281-frontend.p4
testdata/p4_16_samples_outputs/issue281-midend.p4
testdata/p4_16_samples_outputs/issue561-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue561-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue823-frontend.p4
testdata/p4_16_samples_outputs/issue823-midend.p4
testdata/p4_16_samples_outputs/issue982-frontend.p4
testdata/p4_16_samples_outputs/issue982-midend.p4
testdata/p4_16_samples_outputs/named-arg1-frontend.p4
testdata/p4_16_samples_outputs/psa-fwd-bmv2-frontend.p4
testdata/p4_16_samples_outputs/psa-fwd-bmv2-midend.p4
testdata/p4_16_samples_outputs/subparser-with-header-stack-bmv2-frontend.p4
testdata/p4_16_samples_outputs/subparser-with-header-stack-bmv2-midend.p4

- template combining P4Control and P4Parser inlining
- extend avoidance of unnecessary copying to parser inlining
This would be much simpler if P4Control and P4Parser had a common base class, but using a template allows the two cases to share common code.

Refactor GeneralInliner common code

---

control-plane/p4RuntimeArchHandler.cpp
control-plane/p4RuntimeArchHandler.h
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeSerializer.cpp
testdata/p4_16_samples/action_profile_max_group_size_annotation.p4
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation-first.p4
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation-frontend.p4
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation-midend.p4
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation.p4
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation.p4-stderr
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation.p4.p4info.txt

This annotation is standardized by the P4Runtime specification and
enables the P4 programmer to specify the maximum group size (sum of
weights across all members in a group) for a given v1model / PSA
action selector.

Handle @max_group_size annotation when generating P4Info

---

backends/bmv2/common/expression.cpp
testdata/p4_16_samples/issue1824-bmv2.p4
testdata/p4_16_samples/issue1824-bmv2.stf
testdata/p4_16_samples_outputs/issue1824-bmv2-first.p4
testdata/p4_16_samples_outputs/issue1824-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue1824-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1824-bmv2.p4
testdata/p4_16_samples_outputs/issue1824-bmv2.p4.p4info.txt

Changed the way error code value is generated in bmv2 backend.
Instead of decimal value, it is generated as hex value into json file
(issue #1824)
Signed-off-by: Enisa Hadzic <enisa.hadzic@rt-rk.com>

Fix for the issue when number of error values is more than 9 (#1824)

---

backends/bmv2/common/header.cpp
backends/bmv2/common/header.h
backends/bmv2/common/options.h
backends/bmv2/psa_switch/main.cpp
backends/bmv2/psa_switch/midend.cpp
backends/bmv2/psa_switch/midend.h
backends/bmv2/simple_switch/main.cpp
backends/bmv2/simple_switch/midend.cpp
backends/bmv2/simple_switch/midend.h
backends/bmv2/simple_switch/simpleSwitch.cpp
backends/bmv2/simple_switch/simpleSwitch.h
backends/ebpf/ebpfOptions.h
backends/ebpf/midend.cpp
backends/ebpf/p4c-ebpf.cpp
backends/graphs/p4c-graphs.cpp
backends/p4test/p4test.cpp
ir/json_loader.h
ir/json_parser.cpp
ir/json_parser.h
ir/node.cpp
ir/pass_manager.h
lib/source_file.h
tools/driver/p4c_src/driver.py
tools/driver/p4c_src/main.py

* Added --fromJSON flag, as registerOption for all backends.
* Construction : "--fromJSON" "file", where file represents
IR representation json instead of p4 file.
* Modified all backends to skip parsing stage and FrontEnd pass.
* ConvertEnums is skipped in MidEnd pass(when --fromJson flag is used)
since it was already processed during initial IR generation
(checksum already been computed).
* ParseAnnotation is skipped in backend(while using --fromJSON flag),
because InputSources are empty
* Extended class JsonObject with fields and methods
for making JsonObject object, when program is reading from jsonFile
dumped after midEnd previously
* Extended class SourceInfo,
to make object SourceInfo from parameters read from the jsonFile
* Modified function IR::Node::sourceInfoJsonObj() to …

Added support for --fromJSON flag (#1280)

---

backends/ebpf/targets/xdp_target.py
ir/type.def

also delete spurious sym-link that somehow got checked in.

Fix Type_InfInt::equiv (all InfInt types are the same)

---

lib/stringref.h
midend/flattenHeaders.cpp

fixed two issues:
- stringref could run into infinite loop.
- flattening should keep the original annotation on the header instead of discard them.

A couple bugfixes

---

control-plane/p4RuntimeSerializer.cpp
testdata/p4_16_errors_outputs/issue1803_same_table_name.p4-stderr
testdata/p4_16_samples/same_name_for_table_and_action.p4
testdata/p4_16_samples_outputs/same_name_for_table_and_action-first.p4
testdata/p4_16_samples_outputs/same_name_for_table_and_action-frontend.p4
testdata/p4_16_samples_outputs/same_name_for_table_and_action-midend.p4
testdata/p4_16_samples_outputs/same_name_for_table_and_action.p4
testdata/p4_16_samples_outputs/same_name_for_table_and_action.p4.p4info.txt

It seems that some people use P4Runtime with P4_14 programs. In P4_14 it
is valid (and quite common) when defining a keyless table with a const
default action to use the same same for both the table and the default
action. When the compiler translates the program to P4_16, it ensures
that the names are different but preserves the original names with a
@name annotation. The @name annotation is used when generating the
P4Info message. In order to avoid breaking backward-compatibility for
these P4_14 programs, it seems that we need to restrict the duplicate
name check to objects of the same type. This is a weaker guarantee than
what is required by both the P4_16 and the P4Runtime spec but in my
experience consumers of P4Info are capable of handling non-unique names,
as longs as names are …

Restrict duplicate name check for P4Info to objects of the same "type"

---

backends/p4test/CMakeLists.txt
frontends/p4/validateParsedProgram.cpp
testdata/p4_16_errors_outputs/accept_e.p4-stderr
testdata/p4_16_errors_outputs/constructor_e.p4-stderr
testdata/p4_16_errors_outputs/control-inline.p4-stderr
testdata/p4_16_errors_outputs/dup-param.p4-stderr
testdata/p4_16_errors_outputs/dup-param1.p4-stderr
testdata/p4_16_errors_outputs/dup-param2.p4-stderr
testdata/p4_16_errors_outputs/dup-param3.p4-stderr
testdata/p4_16_errors_outputs/dupConst.p4-stderr
testdata/p4_16_errors_outputs/issue435.p4-stderr
testdata/p4_16_errors_outputs/local_instance.p4-stderr
testdata/p4_16_errors_outputs/missing_actions.p4-stderr
testdata/p4_16_errors_outputs/package.p4-stderr
testdata/p4_16_errors_outputs/table-entries-non-const.p4-stderr
testdata/p4_16_errors_outputs/typedef-and-type-definitions.p4-stderr
testdata/p4_16_samples_outputs/default-switch.p4-stderr

I have also create a new class of tests in the CMakeFile, called "err". This includes all tests from testdata/p4_16_errors. Now you can say 'make check-err'.
I am not 100% happy about the way error messages are printed now. E.g. the following is a bit clumsy:
```
missing_actions.p4(19): [--Werror=expected] error: t: Expected Table t does not have an `actions' property
```
@cc10512 : maybe you have a suggestion on how to improve this.

Convert some error messages to the new format

---

backends/bmv2/CMakeLists.txt
testdata/p4_16_samples/psa-unicast-or-drop-bmv2.stf

Two of them are passing now, and should be removed from the XFAIL list.
One of them was written in a way that it was passing, but it should
not have been.  Updated the STF test so it fails.  A separate PR on
behavioral-model code is required to make that test pass.

Make changes to 3 PSA tests that are causing the build to fail

---

backends/bmv2/CMakeLists.txt
testdata/p4_16_samples/psa-drop-all-bmv2.stf
testdata/p4_16_samples/psa-unicast-or-drop-bmv2.stf

given recent changes in p4lang/behavioral-model code for PSA
implementation.

Remove XFAIL for two PSA test programs that should now pass

---

testdata/p4_16_samples/bvec-hdr-bmv2.stf
testdata/p4_16_samples/table-entries-exact-ternary-bmv2.stf
testdata/p4_16_samples/table-entries-priority-bmv2.p4
testdata/p4_16_samples/table-entries-priority-bmv2.stf
testdata/p4_16_samples_outputs/table-entries-priority-bmv2.p4-stderr

They had odd numbers of hex digits in some expected packets, which
isn't really very well defined in its behavior.

Clean up a few more STF files

---

backends/bmv2/psa_switch/midend.cpp
backends/bmv2/simple_switch/midend.cpp
midend/CMakeLists.txt
midend/convertEnums.cpp
midend/fillEnumMap.cpp
midend/fillEnumMap.h
test/CMakeLists.txt
test/gtest/load_ir_from_json.cpp
test/test_fromJSON.p4

*Modifed convertEnums to save user defined enums in program
instead of removing them.
*Added pass fillEnumMap, which is called in reduced midEnd branch,
that fills enumMap
Signed-off-by: Jelena Vidakovic <jelena.vidakovic@rt-rk.com>

Load support for ir enum map when --fromJSON is used (#1784)

---

backends/bmv2/simple_switch/simpleSwitch.cpp
backends/bmv2/simple_switch/simpleSwitch.h
testdata/p4_16_samples/issue1876.p4
testdata/p4_16_samples_outputs/issue1876-first.p4
testdata/p4_16_samples_outputs/issue1876-frontend.p4
testdata/p4_16_samples_outputs/issue1876-midend.p4
testdata/p4_16_samples_outputs/issue1876.p4
testdata/p4_16_samples_outputs/issue1876.p4.p4info.txt

@hanw @jnfoster The bug was caused by assuming that each control block is unique, and using the control blocks as keys in a hashmap. In this program the same control block is used for multiple purposes. Fortunately the hashmap wasn't really necessary. 
The PSA back-end may have the same bug, though.

Delete useless PassManagers; fixes #1876

---

backends/bmv2/common/header.cpp
testdata/p4_16_samples/issue1897-bmv2.p4
testdata/p4_16_samples_outputs/issue1897-bmv2.p4.p4info.txt

Fix #1897 by explicitly converting HeaderUnions to JSON

BMV2: handle local variables that are a header_union; fixes #1897

---

lib/log.h
lib/ordered_set.h

- allows sets of ordered_sets or ordered_sets as map keys in a sensible way.
Compares the underlying sets independent of the order, so that it is
possible to have ordered_sets where !(a < b) && !(b < a) && !(a == b).
Such sets contain the same elements but in a different order.

ordered_set::operator<

---

frontends/p4/parseAnnotations.h
tools/driver/p4c_src/main.py

Printing help is a backend specific option. It requires a bit more
flexible parsing of annotations (i.e., registering handlers outside
the constructor) and a bit of driver tweaking.

add support for printing help for pragmas

---

ir/node.cpp
testdata/p4_16_samples/match-on-exprs-bmv2.p4
testdata/p4_16_samples/match-on-exprs-bmv2.stf
testdata/p4_16_samples_outputs/match-on-exprs-bmv2-first.p4
testdata/p4_16_samples_outputs/match-on-exprs-bmv2-frontend.p4
testdata/p4_16_samples_outputs/match-on-exprs-bmv2-midend.p4
testdata/p4_16_samples_outputs/match-on-exprs-bmv2.p4
testdata/p4_16_samples_outputs/match-on-exprs-bmv2.p4.p4info.txt

Without this change, it is possible for a BMv2 JSON file with
incorrect JSON syntax to be generated, if there are @name annotations,
or any others that contain strings, close to the beginning of a table
definition.

Process source_info strings via JSON escaping in one missing case

---

.gdbinit
midend/actionSynthesis.cpp
midend/actionSynthesis.h

When a target supports an exit primitive to jump unconditionally out of the MAU pipeline, it is desirable to NOT call the midend RemoveExits pass that changes exit calls into flag settings and extra tests on subsequent tables.  Its also desirable to move exit statements that appear directly in controls into actions so that they can work properly.
In the normal case (bmv2, ebpf) where RemoveExits is used, this additional code will have no effect as there will no longer be any ExitStatements in the code.

Move exit; statement to actions in actionSynthesis

---

frontends/p4/fromv1.0/programStructure.cpp
ir/indexed_vector.h

Check pointers before operating on them. Bug occurs only on Ubuntu 18.04.
Fixes #1924.

defensive programming

---

Dockerfile

Instead install pip with get-pip.py
(https://pip.pypa.io/en/stable/installing/).
python-pip seems to be broken on Ubuntu 16.04. The installation of pip
itself is failing (it seems that it fails to reach PyPI, which may be
specific to the Travis environment, which causes a backtrace).
We also remove Tenjin from the python dependencies, since it is not used
by p4lang/p4c.

Fix Travis CI by removing python-pip from Dockerfile deps

---

ir/visitor.h

- add support for tracking named 'global' flow paths between different
parts of the IR, useful for tracking data flow over things like
exit/return or calls or state transitions.

Framework for non-local branches in ControlFlowVisitor

---

tools/driver/p4c_src/driver.py

Need to get a proper exit code rather than a None!

p4c_driver: add missing return in case of success

---

backends/ebpf/CMakeLists.txt

This pull request is intended to introduce a workaround for #1376.
Instead of using CMAKE's `find_package` we manually check the LLVM version and compare. This prevents crashes with specific versions of LLVM and Ubuntu. 
The downside of this method is that it does not catch versions of LLVM that were installed (via ` apt install llvm-3.8` for example) and disables the eBPF backend despite an LLVM version that exists. 
However, because the eBPF framework uses `llc` anyway instead of, say, `llc-3.8` it is probably for the better that this discrepancy is caught.
Let me know what you think.

Make eBPF CMAKE robust against llvm check failures

---

lib/match.cpp
lib/match.h

As per out discussion in https://github.com/p4lang/p4c/issues/1953, it seems more correct to print the default value of `match_t` (which means "no match") as `*`.
The other idea is to print it as `-`.

fix stream output for default value of match_t

---

backends/ebpf/runtime/ebpf_kernel.h

Change to use PIN_OBJECT_NS(1) instead of PIN_GLOBAL_NS(2).
So when unloading the ebpf program, the map will be clean up.
Reported-at: https://github.com/vmware/p4c-xdp/issues/105

ebpf: avoid global ebpf map pinning

---

backends/bmv2/common/extern.cpp
backends/bmv2/common/extern.h
backends/bmv2/common/parser.cpp
backends/bmv2/psa_switch/midend.cpp
backends/bmv2/simple_switch/midend.cpp
backends/p4test/midend.cpp
frontends/common/options.cpp
frontends/common/options.h
frontends/p4/reservedWords.cpp
midend/CMakeLists.txt
midend/removeAssertAssume.cpp
midend/removeAssertAssume.h
p4include/psa.p4
p4include/v1model.p4
tools/driver/p4c_src/driver.py
tools/driver/p4c_src/main.py

* Added removeAssertAssume pass in midend which will remove
all assert and assume statements from program when --ndebug = true
* Not supported in ebpf backend yet
Signed-off-by: Enisa Hadzic <enisa.hadzic@rt-rk.com>

Added support for assert and assume statement in bmv2 backend (#1548)

---

tools/ir-generator/ir-generator.ypp
tools/ir-generator/type.cpp
tools/ir-generator/type.h

This adds support for template arguments of the form `T(T1, ..., Tn)`.

Support function-type arguments in IR generator

---

control-plane/p4RuntimeSerializer.cpp

Extending #1789 which adds generic control plane name generation for `const entries`.

Extend generic control plane name generation for const entries

---

lib/bitrange.h
lib/bitvec.h
test/gtest/bitvec_test.cpp
tools/cpplint.py

- obscure corner case -- when a ctor is called with an rvalue ref to a
temp, the lifetime of that temp is only until the end of the ctor --
we need to have it persist until the dtor is called.

Fix construction of bitref or bitranges object with a temp bitvec to not dangle

---

testdata/p4_16_samples/ipv6-switch-ml-bmv2.p4
testdata/p4_16_samples/ipv6-switch-ml-bmv2.stf
testdata/p4_16_samples/ml-headers.p4
testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2-first.p4
testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2-frontend.p4
testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2-midend.p4
testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2.p4
testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2.p4.p4info.txt

See https://datatracker.ietf.org/doc/draft-hsingh-ipv6-coin-ml/
This test adds sending an IPv6 link-local packet to a multicast destination.  The multicast packet is replicated to few ports.   It would be good to add this test to p4c for folks in the switch ML community to leverage.

Add IPv6 switch ml test

---

lib/gc.cpp
lib/log.cpp
lib/log.h

This was broken awhile back when logging was reorganized -- the caching routines can't be called from the gc_callback, so the LOG macros can't be used there -- and was never fixed properly.

Fix gc.cpp tracing

---

backends/bmv2/common/JsonObjects.cpp
backends/bmv2/common/JsonObjects.h
backends/bmv2/simple_switch/simpleSwitch.cpp
backends/ebpf/targets/xdp_target.py

As discussed in the last LDWG, the bmv2 back-end currently does not implement correctly recirculate, resubmit and clone3. So we give a warning to the users. This would be ideally a temporary solution until we provide a working implementation of these primitives. A solution, proposed in #1698, has not been adopted yet, and no one has proposed an implementation for an alternative solution.

Warn on unsupported use of recirculate/resubmit/clone

---

frontends/p4/fromv1.0/programStructure.cpp

Added an annotation to indicate use of csum16_udp in p4-14  to activate zeros_as_ones feature.

Support for zeros_as_ones

---

control-plane/p4RuntimeSerializer.cpp
frontends/p4/typeChecking/typeUnification.cpp
testdata/p4_16_samples/table-entries-ser-enum-bmv2.p4
testdata/p4_16_samples/table-entries-ser-enum-bmv2.stf
testdata/p4_16_samples_outputs/table-entries-ser-enum-bmv2-first.p4
testdata/p4_16_samples_outputs/table-entries-ser-enum-bmv2-frontend.p4
testdata/p4_16_samples_outputs/table-entries-ser-enum-bmv2-midend.p4
testdata/p4_16_samples_outputs/table-entries-ser-enum-bmv2.p4
testdata/p4_16_samples_outputs/table-entries-ser-enum-bmv2.p4.entries.txt
testdata/p4_16_samples_outputs/table-entries-ser-enum-bmv2.p4.p4info.txt

Most of the changes are in the p4RuntimeSerializer. One change was
required in type unification to support:
`((bit<16>)MyEnum2B.MBR2) &&& 0xff00`
`MyEnum2B.MBR2 &&& 0xff00` gives a compiler error, but AFAIK that 
behavior conforms to the P4_16 spec.

Support serializable enums in const table entries

---

backends/bmv2/CMakeLists.txt
backends/bmv2/common/header.cpp
backends/bmv2/psa_switch/main.cpp
backends/bmv2/psa_switch/midend.cpp
backends/bmv2/psa_switch/midend.h
backends/bmv2/psa_switch/options.h
backends/bmv2/simple_switch/main.cpp
backends/bmv2/simple_switch/midend.cpp
backends/bmv2/simple_switch/midend.h
backends/bmv2/simple_switch/options.h
backends/bmv2/simple_switch/simpleSwitch.cpp
backends/ebpf/CMakeLists.txt
backends/ebpf/ebpfOptions.cpp
backends/ebpf/ebpfOptions.h
backends/ebpf/midend.cpp
backends/ebpf/midend.h
frontends/common/options.cpp
frontends/common/options.h
frontends/p4/frontend.cpp
frontends/p4/frontend.h
ir/pass_manager.cpp
ir/pass_manager.h

Added four new compiler options :
--listFrontendPasses, prints names of all frontend passes
--listMidendPasses, prints names of all midend passes
--excludeFrontendPasses,  exclude one or more frontend passes,
which names are passed as arguments, from further processing
--excludeMidendPasses, exclude one or more midend passes,
which names are passed as arguments, from further processing
*Developers should be aware of possibility that skipping some passes may trigger bugs
in other parts of compiler

Abillity to disable passes in the frontend and midend (#830)

---

frontends/p4/parseAnnotations.cpp
frontends/p4/parseAnnotations.h
frontends/parsers/p4/p4AnnotationLexer.hpp
frontends/parsers/p4/p4parser.ypp
frontends/parsers/parserDriver.cpp
frontends/parsers/parserDriver.h

Add support for annotations whose bodies can be an integer constant or a string literal, an integer list, a string list, and a list of (integer constant or string literal).

Add support for more kinds of annotation bodies

---

backends/graphs/parsers.h
ir/v1.def

A bunch of classes in `v1.def` weren't implementing `IAnnotated` when they really should have.
Also fixed a missing `#include`.

Implement IAnnotated where possible

---

ir/pattern.h

- because of the operator T * converter operations between a Match and
an int that could be pointer arithmetic or comparisons generate an
ambiguous overload message.  Avoid that by explicitly supplying these
operator overloads that avoid user-defined conversions.

Avoid ambiguous overload when doing operations on a Match

---

frontends/common/options.cpp
frontends/common/options.h
frontends/parsers/p4/p4parser.ypp
frontends/parsers/parserDriver.cpp
tools/driver/p4c_src/driver.py
tools/driver/p4c_src/main.py

Add the --disable-annotations option to disable annotations by name.
It accepts a comma separated list of annotations that will not be
added in the IR tree. A warning will be printed that the annotation
was explicitly disabled. We do print the warning for every instance of
the annotation, which may be an overkill, however, it is intentional,
so that users can make sure that a particular annotation was not taken
into account.
The option only disable annotations present in the source
file. Compiler passes may continue to add annotations and process them
as before. Note that users may be able to disable annotations that may
cripple the code generation -- backend or control-plane. That's
another reason why it is important to print those warnings!

add a compiler option to disable specific annotations/pragmas

---

backends/ebpf/CMakeLists.txt
backends/ebpf/targets/kernel_target.py

I don't know how to fix the building of the ebpf kernel-based tests so that they work on any kernel/distribution combination, so I am disabling them for now. @fruffy has actually created these tests. If anyone has time to work on them we can re-enable them.
We are still testing the p4c-ebpf compiler, but just with portable user-level tests.

Disable kernel ebpf tests

---

backends/ebpf/targets/target.py

Somehow this statement:
```
from scapy.layers.all import RawPcapWriter
```
does not raise an exception for older versions of Scapy like 2.2.0 and
2.3.2, even though the class RawPcapWriter is defined in the file for
scapy.utils.  With newer versions of Spapy like 2.4.2 and 2.4.3, this
import statement fails.
By importing it from the correct package scapy.utils, it works on all
versions of Scapy mentioned above.

Correct import statement in ebpf target.py test running file

---

.travis.yml

- avoid Travis 50 minute timeout
There's probably a more efficient way to do this?

Do unified and non-unified builds in separate Travis instances

---

CMakeLists.txt
lib/log.h

This limits the logging level compiled into the program -- when combined with -O it should also completely dead-code eliminate the unwanted logging code, making the binary smaller.

Compile-time MAX_LOGGING_LEVEL

---

frontends/p4-14/typecheck.cpp

manually tested on one of our internal test case

fix type inference for IR::Neg and IR::Cmpl

---

cmake/FindPythonModule.cmake

Not sure what the purpose of all the find_python_module directives is,
since we only check for presence of standard library stuff. We also
use find_python_module to "find" the "re" module, and the
find_python_module implementation itself imports "re" :)
Fixes #2095

Fix FindPythonModule to avoid warnings

---

backends/ebpf/targets/target.py
tools/testutils.py

Maybe this fixes the byte casting issues with scapy. `received` is a scapy raw object and `bytes(received)` converts the object to its byte representation.

Quick scapy fix.

---

README.md

Without something like this, `cd p4c/build ; make check` fails on a
freshly installed Ubuntu Linux machine.

Add instructions to install Python 3 version of Scapy as dependency

---

frontends/p4/typeChecking/typeUnification.cpp
testdata/p4_16_samples/select-struct.p4
testdata/p4_16_samples_outputs/select-struct-first.p4
testdata/p4_16_samples_outputs/select-struct-frontend.p4
testdata/p4_16_samples_outputs/select-struct-midend.p4
testdata/p4_16_samples_outputs/select-struct.p4

Fixing order of arguments allows removing of unnecessary
destination and source argument swapping if dst is base list
type and src is struct like type.
Select-struct.p4 test is changed to be in conformance with
specification.

Order of src and dst template function arguments fix

---

lib/error_reporter.h
testdata/p4_16_errors_outputs/nostart.p4-stderr

This avoids burying errors in a pile of warnings by ignoring all warnings after the first error.

Ignore warnings if we've already emitted errors

---

frontends/p4/parseAnnotations.cpp
ir/base.def
ir/type.cpp
midend/has_side_effects.h
midend/local_copyprop.cpp
midend/local_copyprop.h

- allows transformations/optimizations to have more knowledge of
architecture-specific externs so as to better optimize things.

Allow extern methods to be marked @noSideEffects

---

frontends/p4/simplifyDefUse.cpp

- fixes issue seen in #2026.  Allows table.hit/miss tests to remain in if conditions, where they need to be.

Fix simplifyDefUse to deal with side effect in if condition

---

README.md

Without this, following the existing README instructions leads to an
installation that fails all ebpf tests run by 'cd p4c/build ; make
check'.  With this addition, I believe all tests pass.

Add Python 3 ply to install steps in README

---

frontends/p4/createBuiltins.cpp
frontends/p4/createBuiltins.h
frontends/parsers/p4/p4parser.ypp
testdata/p4_16_samples/table-entries-no-arg-actions.p4
testdata/p4_16_samples_outputs/table-entries-no-arg-actions-first.p4
testdata/p4_16_samples_outputs/table-entries-no-arg-actions-frontend.p4
testdata/p4_16_samples_outputs/table-entries-no-arg-actions-midend.p4
testdata/p4_16_samples_outputs/table-entries-no-arg-actions.p4

This pull request fixes a discrepancy between the language specification and `p4c` with respect to the syntax for action references in `const` table entries.
The grammar in the language specification allows action references to be written with or without parentheses:
```
entry
: keysetExpression ':' actionRef optAnnotations ';'
;
actionRef
: optAnnotations prefixedNonTypeName
| optAnnotations prefixedNonTypeName '(' argumentList ')'
;
```
However, the grammar in the `p4c` parser requires all action references to be given with parentheses, even for actions that do not take arguments:
```
entry
: keysetExpression ":" actionBinding optAnnotations ";"
{ ... }
;
actionBinding
: lvalue "(" argumentList ")"
{ ... }
| lvalue "<" typeArgumentList ">" "(" argumentList ")"
{ ... }
;
```
This pull …

Correctly parse action references in const table entries

---

CMakeLists.txt

Backends install their own headers, however, when a backend is
disabled, we might still want to run p4test to validate the p4.
Therefore we copy the headers in the build directory.
Fixes #2130

fix missing header when backends are disabled

---

testdata/p4_16_errors/table-entries-lpm-2.p4
testdata/p4_16_errors_outputs/table-entries-lpm-2-first.p4
testdata/p4_16_errors_outputs/table-entries-lpm-2-frontend.p4
testdata/p4_16_errors_outputs/table-entries-lpm-2-midend.p4
testdata/p4_16_errors_outputs/table-entries-lpm-2.p4
testdata/p4_16_errors_outputs/table-entries-lpm-2.p4-stderr
testdata/p4_16_errors_outputs/table-entries-lpm-2.p4.entries.txt
testdata/p4_16_errors_outputs/table-entries-lpm-2.p4.p4info.txt

From looking at the C++ code, I thought there might be some cases that
were not caught, but it seems that all of them get at least a warning,
if not an error, in some cases in the target-independent code, others
in the P4Runtime back end.

Add test program that tests catching of incorrect lpm const entries

---

frontends/p4/simplify.cpp
frontends/p4/simplify.h
frontends/p4/strengthReduction.cpp
ir/ir.def
testdata/p4_16_samples/issue2148.p4
testdata/p4_16_samples_outputs/issue2148-first.p4
testdata/p4_16_samples_outputs/issue2148-frontend.p4
testdata/p4_16_samples_outputs/issue2148-midend.p4
testdata/p4_16_samples_outputs/issue2148.p4
testdata/p4_16_samples_outputs/issue2148.p4-stderr
testdata/p4_16_samples_outputs/issue2148.p4.p4info.txt

This was happening because an EmptyStatement is replaced with nullptr in a block, but the same EmptyStatement was a child of an IfStatement. The solution is `visitDagOnce = false` for this pass.

visitDagOnce = false for control flow simplifications; fixes #2148

---

frontends/parsers/p4/p4lexer.ll
frontends/parsers/p4/p4parser.ypp
frontends/parsers/parserDriver.cpp
frontends/parsers/parserDriver.h
testdata/p4_16_errors_outputs/shift_e.p4-stderr
testdata/p4_16_samples/shift_precendence.p4
testdata/p4_16_samples_outputs/shift_precendence-first.p4
testdata/p4_16_samples_outputs/shift_precendence-frontend.p4
testdata/p4_16_samples_outputs/shift_precendence-midend.p4
testdata/p4_16_samples_outputs/shift_precendence.p4

Use a lookahead to identify > characters directly followed by another > as a separate token from other > characters -- either may be used to close angle brackets, but only the appropriate one as party of a right shift or a greater-than

Fix right-shift operator precedence

---

control-plane/p4RuntimeSerializer.cpp
testdata/p4_16_samples/runtime-index-2-bmv2.p4
testdata/p4_16_samples/runtime-index-2-bmv2.stf
testdata/p4_16_samples_outputs/runtime-index-2-bmv2-first.p4
testdata/p4_16_samples_outputs/runtime-index-2-bmv2-frontend.p4
testdata/p4_16_samples_outputs/runtime-index-2-bmv2-midend.p4
testdata/p4_16_samples_outputs/runtime-index-2-bmv2.p4

After checkin of https://github.com/p4lang/p4c/commit/b281cddc79de75f048a2f3c663ebce5b732d2c63, this PR enables Slice and runtime index test line of code.
This PR has also changed p4RuntimeSerializer.cpp to use ErrorType so that when the error occurs, the line number of P4 code causing the error is also printed. 
I will file a separate issue against p4RuntimeSerializer.cpp because many of its errors do not print the line of P4 code where the error occurs.  The code should change.

Enable Slice test with runtime index

---

ir/visitor.cpp

Found a corner case where the Transform infrastructure could undo what the Transform was trying to do.

Allow for a Transform that combines identical nodes

---

tools/driver/p4c_src/main.py

A script will be executed using the interpreter specified on the first line.

tools-driver: Move shebang on first line

---

backends/bmv2/CMakeLists.txt

See https://github.com/p4lang/behavioral-model/issues/862.
This way p4c Travis tests will pass and gives time to behavioral model to fix its code.

Quarantine four tests broken by behavioral model

---

backends/bmv2/common/lower.cpp
frontends/p4/sideEffects.cpp
frontends/p4/typeMap.cpp
frontends/p4/typeMap.h

Production quality software does not duplicate code.  This PR defines a new function for use by two passes to set left value.

Add function to set left value

---

frontends/p4/strengthReduction.cpp
testdata/p4_14_samples_outputs/09-IPv4OptionsUnparsed-midend.p4
testdata/p4_14_samples_outputs/issue576-midend.p4
testdata/p4_14_samples_outputs/issue781-midend.p4
testdata/p4_16_samples/strength5.p4
testdata/p4_16_samples_outputs/precedence-first.p4
testdata/p4_16_samples_outputs/strength5-first.p4
testdata/p4_16_samples_outputs/strength5.p4
testdata/p4_16_samples_outputs/strength5.p4-stderr

This is inspired by the recent bug of shr.
Perhaps we should do this only if both shift amounts are constants?

One more strength reduction

---

backends/bmv2/common/control.cpp
backends/bmv2/common/helpers.cpp
backends/bmv2/common/helpers.h
control-plane/p4RuntimeSerializer.cpp
frontends/p4/fromv1.0/v1model.h
p4include/v1model.p4
testdata/p4_16_errors/table-entries-optional-2-bmv2.p4
testdata/p4_16_errors_outputs/issue1541.p4-stderr
testdata/p4_16_errors_outputs/issue1557-bmv2.p4-stderr
testdata/p4_16_errors_outputs/issue513.p4-stderr
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2-first.p4
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2-frontend.p4
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2-midend.p4
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2.p4
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2.p4-stderr
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2.p4.entries.txt
testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2.p4.p4info.txt
testdata/p4_16_samples/table-entries-optional-bmv2.p4
testdata/p4_16_samples/table-entries-optional-bmv2.stf
testdata/p4_16_samples_outputs/issue841.p4-stderr
testdata/p4_16_samples_outputs/table-entries-optional-bmv2-first.p4
testdata/p4_16_samples_outputs/table-entries-optional-bmv2-frontend.p4
testdata/p4_16_samples_outputs/table-entries-optional-bmv2-midend.p4
testdata/p4_16_samples_outputs/table-entries-optional-bmv2.p4
testdata/p4_16_samples_outputs/table-entries-optional-bmv2.p4.entries.txt
testdata/p4_16_samples_outputs/table-entries-optional-bmv2.p4.p4info.txt

In consultation with Antonin Bas on how best to implement this in
behavioral-model code, we decided to implement optional in table keys
in the P4_16 source code, by representing them exactly the same in the
BMv2 JSON file as ternary keys are.
The P4Info file generated does use the new OPTIONAL key type, as it
should, so that software using that file knows the difference between
ternary and optional keys in the source code.

Add match_kind optional to v1model.p4 and bmv2 back end

---

backends/bmv2/common/JsonObjects.h

A very minor change but I noticed while reviewing code that there was a
declaration for a function that was neither defined nor called.

Remove unused function declaration in bmv2 backend

---

backends/bmv2/common/JsonObjects.cpp
backends/bmv2/common/JsonObjects.h
backends/bmv2/common/parser.cpp
ir/ir.def

Please see this issue against behavioral model where is it asked that p4c support pvs size in bvm2 JSON.
https://github.com/p4lang/behavioral-model/issues/856

Add pvs size to bmv2 JSON

---

lib/ordered_set.h

The `contains` and `intersects` predicates for `ordered_set` can take `const` parameters.

Constified some function parameters.

---

backends/bmv2/CMakeLists.txt
backends/ebpf/CMakeLists.txt
backends/graphs/CMakeLists.txt
backends/p4test/CMakeLists.txt

Using absolute paths for symlinks interacts badly with trying to use docker containers that want to mount things with different paths.  Relative symlinks work better.

Use relative paths for symlinks

---

backends/bmv2/common/parser.cpp
backends/bmv2/common/parser.h
testdata/p4_16_samples_outputs/select-struct-frontend.p4
testdata/p4_16_samples_outputs/select-struct-midend.p4

bmv2 only supports exact matches, and a warning is better than silently
ignoring the @match annotation.

Warn in bmv2 backend about unsupported match types in value_sets

---

frontends/p4/fromv1.0/programStructure.cpp
testdata/p4_14_errors/issue2188.p4
testdata/p4_14_errors_outputs/issue2188.p4-stderr

This addresses #2188 somewhat: it will reject such programs instead of converting them silently into something incorrect. But #2188 also asks whether we want to support this idiom.

Reject value sets with masks

---

backends/bmv2/run-bmv2-test.py

Added options.compilerSrcDir to a few paths so that `run-bmv2-test.py` can be run outside of the build directory.
Plus a few autoformatting adjustments.

Some small changes to run-bmv2-test.py

---

backends/ubpf/tests/environment/setup-pktgen.sh
backends/ubpf/tests/environment/setup-switch.sh

Once uBPF back-end is merged into master, the links in the installation scripts should be updated to point to the proper repo.

p4c-ubpf: Update links in installation scripts

---

backends/ubpf/CMakeLists.txt

Hi,
My ninja build stopped working with:
ninja: error: build.ninja:1517: bad $-escape (literal $ must be written as 19185)
The fix was to add the second '$' in the CMakeList.txt file.

fix ninja builds

---

frontends/p4/def_use.cpp
frontends/p4/def_use.h
frontends/p4/simplifyDefUse.cpp
testdata/p4_16_samples/issue2273-1.p4
testdata/p4_16_samples/issue2273.p4
testdata/p4_16_samples/two-functions.p4
testdata/p4_16_samples_outputs/issue2104-1-first.p4
testdata/p4_16_samples_outputs/issue2104-1-frontend.p4
testdata/p4_16_samples_outputs/issue2104-1-midend.p4
testdata/p4_16_samples_outputs/issue2104-1.p4
testdata/p4_16_samples_outputs/issue2273-1-first.p4
testdata/p4_16_samples_outputs/issue2273-1-frontend.p4
testdata/p4_16_samples_outputs/issue2273-1-midend.p4
testdata/p4_16_samples_outputs/issue2273-1.p4
testdata/p4_16_samples_outputs/issue2273-first.p4
testdata/p4_16_samples_outputs/issue2273-frontend.p4
testdata/p4_16_samples_outputs/issue2273-midend.p4
testdata/p4_16_samples_outputs/issue2273.p4
testdata/p4_16_samples_outputs/virtual3.p4-stderr

The bug that is being fixed was using the same representation for a program point before and after the execution of a function. Now we have two distinct program points.
Most of the changes in this PR are about making debugging easier and checking that the live definitions are not overwritten accidentally. This PR should make PR #2272 unnecessary.

Cleanup def-use analysis; fixes #2273

---

control-plane/p4RuntimeSerializer.cpp
test/gtest/p4runtime.cpp

@id annotation support for match fields, action parameters and
controller metadata fields, as per the current P4Runtime specification
(dev version of P4Runtime 1.2.0).
Fixes #2242

Implement @id annotation support for non top-level objects

---

control-plane/p4RuntimeArchHandler.cpp
control-plane/p4RuntimeArchHandler.h
ir/base.def
ir/expression.def
test/gtest/p4runtime.cpp
testdata/p4_16_samples/structured_annotations.p4
testdata/p4_16_samples_outputs/structured_annotations-first.p4
testdata/p4_16_samples_outputs/structured_annotations-frontend.p4
testdata/p4_16_samples_outputs/structured_annotations-midend.p4
testdata/p4_16_samples_outputs/structured_annotations.p4
testdata/p4_16_samples_outputs/structured_annotations.p4.p4info.txt

The addAnnotations function is modified to handle both unstructured and
structured annotations. This was the least disruptive choice:
architecture-dependent P4Info serialization code in proprietary
compilers will not need to be updated.
Fixes #2128

Support structured annotations in P4Info serializer

---

backends/ebpf/targets/ebpfenv.py
cmake/P4CUtils.cmake

Like most of the shebangs in the rest of the repo, /usr/bin/env to pick
bash from `$PATH`, instead of invoking it from /bin/bash.
This fixes execution on systems that don't have bash in /bin/bash, or
have explicitly configured another one to be used.

use /usr/bin/env bash instead of /bin/bash

---

control-plane/p4RuntimeSerializer.cpp
test/gtest/p4runtime.cpp

The P4Info generation code was incorrectly treating programmer-provided
ids as signed integers instead of unsigned. Thanks @jafingerhut for
reporting this issue to me.

Support arbitrary unsigned integer ids

---

README.md

From travis-ci.org to travis-ci.com.
Travis is in the process of transitioning all repos to travis-ci.com
(used to be for paid accounts only). I just did the transition for
p4lang/p4c in order to fix some build issues (status not reported in a
timely fashion for PRs), which means that the status badge link needs to
be updated.

Update Travis CI status badge

---

backends/bmv2/psa_switch/midend.cpp
backends/bmv2/simple_switch/midend.cpp
backends/p4test/midend.cpp
midend/predication.cpp
midend/predication.h
testdata/p4_16_samples/issue2248.p4
testdata/p4_16_samples_outputs/issue2248-first.p4
testdata/p4_16_samples_outputs/issue2248-frontend.p4
testdata/p4_16_samples_outputs/issue2248-midend.p4
testdata/p4_16_samples_outputs/issue2248.p4
testdata/p4_16_samples_outputs/issue2248.p4.p4info.txt
testdata/p4_16_samples_outputs/issue512-midend.p4

This PR is follow-up of the #2231 
expr_name refactored to lvalue_name because it's used only for lvalue in every assignemnt.
visitThen and visitElse  merged to visitBranch with extra bool parameter.
Comments for functions fixed, unnecessary name generator removed.

Predication fixes and cleanup

---

frontends/p4/frontend.cpp
frontends/p4/moveDeclarations.cpp
frontends/p4/moveDeclarations.h
testdata/p4_16_samples/issue2314.p4
testdata/p4_16_samples_outputs/default-frontend.p4
testdata/p4_16_samples_outputs/fabric_20190420/fabric-frontend.p4
testdata/p4_16_samples_outputs/initializers-frontend.p4
testdata/p4_16_samples_outputs/issue1538-frontend.p4
testdata/p4_16_samples_outputs/issue2314-first.p4
testdata/p4_16_samples_outputs/issue2314-frontend.p4
testdata/p4_16_samples_outputs/issue2314-midend.p4
testdata/p4_16_samples_outputs/issue2314.p4
testdata/p4_16_samples_outputs/issue2314.p4-stderr
testdata/p4_16_samples_outputs/issue2314.p4.p4info.txt
testdata/p4_16_samples_outputs/issue281-frontend.p4
testdata/p4_16_samples_outputs/issue281-midend.p4
testdata/p4_16_samples_outputs/issue361-bmv2-frontend.p4
testdata/p4_16_samples_outputs/parser-conditional-frontend.p4
testdata/p4_16_samples_outputs/parser-conditional-midend.p4

Create a new state for initializations

---

tools/stf/stf_parser.py

There was a problem trying to parse files with the stf parser. The filename class was not imported. Opening directly as file should fix the issue.

Simple stf parser fix.

---

backends/p4test/CMakeLists.txt
frontends/p4/symbol_table.cpp
frontends/p4/symbol_table.h
frontends/parsers/p4/p4lexer.ll
frontends/parsers/p4/p4parser.ypp
frontends/parsers/parserDriver.h
testdata/p4_16_errors_outputs/dup-param1.p4-stderr
testdata/p4_16_errors_outputs/dup-param3.p4-stderr
testdata/p4_16_errors_outputs/issue1932.p4-stderr
testdata/p4_16_samples_outputs/cast-call-first.p4
testdata/p4_16_samples_outputs/cast-call.p4
testdata/p4_16_samples_outputs/cast-call.p4-stderr
testdata/p4_16_samples_outputs/precedence-lt-first.p4
testdata/p4_16_samples_outputs/precedence-lt-frontend.p4
testdata/p4_16_samples_outputs/precedence-lt.p4
testdata/p4_16_samples_outputs/precedence-lt.p4-stderr

- if the symbol before it is something that expects template args, we
use a higher precedence (same as postfix operators) rather than
normal less-than precedence.
Fixes issue #13

Change precedence of '<' based on symbol immediately before it

---

frontends/common/resolveReferences/resolveReferences.cpp
ir/base.def
ir/ir.cpp
ir/ir.def
ir/node.h
ir/type.def
testdata/p4_16_samples/shadow-after-use.p4
testdata/p4_16_samples_outputs/shadow-after-use-first.p4
testdata/p4_16_samples_outputs/shadow-after-use-frontend.p4
testdata/p4_16_samples_outputs/shadow-after-use-midend.p4
testdata/p4_16_samples_outputs/shadow-after-use.p4
testdata/p4_16_samples_outputs/shadow-after-use.p4-stderr

- when multiple namespaces exist in a single IR::Node, and symbols in
those namespaces may shadow each other, lookup depends on the location
of the name.
This is a subtle corner case that is a consequence of the decision to prohibit uses before definitions in P4_16 -- it also means that symbols in inner scopes only partly shadow symbols in enclosing scopes (only in the part of the scope after they are defined.)  Which means that in objects embodying multiple scopes, we must keep those scopes separate for symbol lookup.

Fix P4_16 name resolution

---

frontends/common/constantFolding.cpp
frontends/parsers/p4/p4parser.ypp
p4include/ebpf_model.p4
p4include/ubpf_model.p4
p4include/v1model.p4
p4include/xdp_model.p4
testdata/p4_16_errors/const.p4
testdata/p4_16_errors/issue2332-1.p4
testdata/p4_16_errors/issue2332.p4
testdata/p4_16_errors_outputs/const.p4
testdata/p4_16_errors_outputs/const.p4-stderr
testdata/p4_16_errors_outputs/issue1541.p4-stderr
testdata/p4_16_errors_outputs/issue1557-bmv2.p4-stderr
testdata/p4_16_errors_outputs/issue2332-1.p4
testdata/p4_16_errors_outputs/issue2332-1.p4-stderr
testdata/p4_16_errors_outputs/issue2332.p4
testdata/p4_16_errors_outputs/issue2332.p4-stderr
testdata/p4_16_errors_outputs/issue513.p4-stderr
testdata/p4_16_errors_outputs/issue67.p4-stderr
testdata/p4_16_samples_outputs/issue2248-first.p4
testdata/p4_16_samples_outputs/issue2248.p4
testdata/p4_16_samples_outputs/issue841.p4-stderr

Pay more attention to types during constant folding

---

backends/bmv2/common/JsonObjects.cpp
backends/bmv2/common/parser.cpp

The bmv2 backend was still using a very old format (from 2016), and
while it is still supported by bmv2 for backwards-compatibility reasons,
it is confusing to people who compare the generated JSON files to the
bmv2 JSON format spec.
We also update JSON_MINOR_VERSION to the latest version.
Fixes #2311

Fix bmv2 default parser transitions

---

test/gtest/load_ir_from_json.cpp

checks the return values during unit testing rather than ignoring them.

Remove compilation warning

---

frontends/common/options.cpp
tools/driver/p4c.in

- toP4 compares paths to decide when to output #include directives,
which sometime fails when symlinks are involved, as there can be
mulitple different but equivalent paths.

Get rid of symlinks in include paths to avoid mismatches

---

backends/p4test/midend.cpp
midend/interpreter.cpp
midend/parserUnroll.cpp
midend/parserUnroll.h

Fixes #289.
The loop unrolling pass is still not used anywhere - as implemented it may generate lots of parser states (millions) in some circumstances. But this PR fixes a the bug reported in issue 289 that throws an exception when this pass is called. The pass could still be useful in some backends... although there are currently no tests that exercise it.

Fix incorrect invocation of pass; unrolling still disabled

---

frontends/p4/frontend.cpp
frontends/parsers/p4/p4parser.ypp
testdata/p4_16_samples/parser-if.p4
testdata/p4_16_samples_outputs/parser-if-first.p4
testdata/p4_16_samples_outputs/parser-if-frontend.p4
testdata/p4_16_samples_outputs/parser-if-midend.p4
testdata/p4_16_samples_outputs/parser-if.p4
testdata/p4_16_samples_outputs/parser-if.p4.p4info.txt

@vgurevich : this is actually a two-line change to the compiler.
We should add this to the spec as well; right now it's labeled as experimental.

Support if statements in parsers

---

frontends/p4/typeChecking/bindVariables.cpp
frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeUnification.cpp
frontends/parsers/p4/p4lexer.ll
ir/type.def
testdata/p4_16_errors/issue2354-1.p4
testdata/p4_16_errors/issue2354.p4
testdata/p4_16_errors_outputs/factory-err2.p4-stderr
testdata/p4_16_errors_outputs/issue2354-1.p4
testdata/p4_16_errors_outputs/issue2354-1.p4-stderr
testdata/p4_16_errors_outputs/issue2354.p4
testdata/p4_16_errors_outputs/issue2354.p4-stderr
testdata/p4_16_errors_outputs/issue584.p4-stderr
testdata/p4_16_errors_outputs/issue764.p4-stderr
testdata/p4_16_errors_outputs/issue819-1.p4-stderr
testdata/p4_16_errors_outputs/push_nonconstant.p4-stderr

int parameters must be directionless

---

p4include/v1model.p4

When you try to compile using `p4c-bm2-ss --p4v 16 "foo.p4" -o "bar.json"`, 
where `foo.p4` includes `v1model.p4`, it throws this error - 
```
/usr/local/share/p4c/p4include/v1model.p4(72): [--Werror=duplicate] error: __v1model_version duplicates __v1model_version.
const bit<32> __v1model_version = 20180101;
^^^^^^^^^^^^^^^^^
/usr/local/share/p4c/p4include/v1model.p4(66)
const bit<32> __v1model_version = 20180101;
^^^^^^^^^^^^^^^^^
```
This because __v1model_version is declared twice. This PR fixes that by, well, removing a line. Felt it would be better to just create a PR than creating an issue. This fixes issue #2399

Fix #2399 - duplication error with __v1model_version in v1model

---

backends/bmv2/bmv2stf.py
backends/bmv2/common/action.cpp
backends/bmv2/psa_switch/midend.cpp
backends/bmv2/psa_switch/psaSwitch.cpp
midend/local_copyprop.h
testdata/p4_16_samples/psa-register-read-write-bmv2.p4
testdata/p4_16_samples/psa-register-read-write-bmv2.stf

Adding register support for PSA:
1. register_write().
2. register_read(). Syntax exposed to programmer is `dst = register_read(index)`. Internally, the compiler backend generate .json for `register_read(dst, index)`. This way, the generated .json shares the same .json format as v1model and is compatible with existing bmv2 backend.
3. Add register control plane commands support to STF: register_read, register_write, register_reset.  
Testing filename: testdata/p4_16_samples/psa-register-read-write-bmv2.p4 (.stf)

Adding register support to PSA

---

backends/p4test/run-p4-sample.py
backends/ubpf/p4c-ubpf.cpp
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeArchStandard.h
control-plane/p4RuntimeSerializer.cpp
testdata/p4_16_samples_outputs/action_call_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/action_fwd_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/csum_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/hash_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/ipv4-actions_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/ipv6-actions_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/metadata_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/simple-actions_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/simple-firewall_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/tunneling_ubpf.p4.p4info.txt
testdata/p4_16_samples_outputs/ubpf_checksum_extern.p4.p4info.txt
testdata/p4_16_samples_outputs/ubpf_hash_extern.p4.p4info.txt

The current version of uBPF backend does not allow to generate P4Info file. This PR enables generation of P4Info file by using `p4runtime-files` argument. 
I just have doubts if it is correct to re-use PSA as did for `P4RuntimeArchHandlerUBPF`.

Enable generation of P4Info file for uBPF backend

---

lib/gmputil.h

A `big_int` with -ve value passed to `ffs()` will result in `boost::multiprecision` error,
```
Testing individual bits in negative values is not supported - results are undefined.
```
Adding a check

Fix gmputil - ffs() to handle -ve big_int values

---

control-plane/p4RuntimeSerializer.cpp
control-plane/typeSpecConverter.h
testdata/p4_16_samples_outputs/issue2283_1-bmv2.p4.p4info.txt
testdata/p4_16_samples_outputs/v1model-const-entries-bmv2-first.p4
testdata/p4_16_samples_outputs/v1model-const-entries-bmv2-frontend.p4
testdata/p4_16_samples_outputs/v1model-const-entries-bmv2-midend.p4
testdata/p4_16_samples_outputs/v1model-const-entries-bmv2.p4

When a user-defined type is translated to a string controller type, the
bitwidth fields for match fields, action params and controller metadata
fields with this type must be unset in the P4Info message.
See https://github.com/p4lang/p4runtime/pull/294

Unset bitwidth for string controller types in P4Info

---

backends/bmv2/CMakeLists.txt
backends/bmv2/psa_switch/psaSwitch.cpp
backends/bmv2/psa_switch/psaSwitch.h
testdata/p4_16_samples/psa-example-register2-bmv2.p4
testdata/p4_16_samples/psa-example-register2-bmv2.stf
testdata/p4_16_samples/psa-register-complex-bmv2.p4
testdata/p4_16_samples/psa-register-complex-bmv2.stf
testdata/p4_16_samples_outputs/psa-example-register2-bmv2-first.p4
testdata/p4_16_samples_outputs/psa-example-register2-bmv2-frontend.p4
testdata/p4_16_samples_outputs/psa-example-register2-bmv2-midend.p4
testdata/p4_16_samples_outputs/psa-example-register2-bmv2.p4

Adding scalar type support in PSA:
When source code contains a more complex expression, for example:
`T a = register.read(x) + register.read(y);` (assume T has a width of 48 bits.)
p4c will transform the source code into:
```c
bit<48> tmp_0;
bit<48> tmp_1; 
tmp_0 = register.read(x);
tmp_1 = register.read(y);
a = tmp_0 + tmp_1;
```
In v1model, `bit<x> tmp;` is supported by:  
(1) create a `scalars` object in the headers section of the generated json file.    
(2) create a `scalars_t` object in the header_types section of the generated json file.   
(3) For each `bit<x> varName;` add a field to header_type `scalars_t`.  
This is not implemented for PSA yet and more complex expressions like the one mentioned above fails to run on bmv2. This PR implements the three points listed above for PSA …

Supporting scalar type in PSA

---

backends/ubpf/p4include/ubpf_model.p4
backends/ubpf/runtime/ebpf_runtime_ubpf.h
backends/ubpf/runtime/ubpf_test.h
backends/ubpf/target.cpp
backends/ubpf/ubpfControl.cpp
backends/ubpf/ubpfDeparser.cpp
backends/ubpf/ubpfModel.h
backends/ubpf/ubpfProgram.cpp
backends/ubpf/ubpfProgram.h
testdata/p4_16_samples/truncate_ubpf.p4
testdata/p4_16_samples/truncate_ubpf.stf

I've implemented support for `truncate()` extern in the uBPF backend. This allows cut off some last bytes from a packet, but dataplane must support that.
I think that @osinstom should be assigned.

Packet truncation support for uBPF backend

---

tools/travis-build

Build script for docker images cleans up packages including python3, but python3 is required for p4c to run. 
Installing python3 in docker image fixes the bug. Travis build works as packages don't get removed from that. 
Suggest listing python3 as a separate dependency in the build script, so it doesn't get removed on docker build

python3 missing from p4lang/p4c docker image

---

frontends/common/options.cpp
lib/CMakeLists.txt
lib/crash.cpp
lib/exename.cpp
lib/exename.h
lib/gc.cpp

- fix OOM to throw std::bad_alloc properly
- emergency pool of a little extra memory for use after throwing a
bad_alloc (to allow generating reasonable error messgages and a
stack trace before exiting)
- fix stack trace code to avoid some low-memory problems.

out-of-memory fixes/improvements

---

lib/source_file.cpp
lib/source_file.h

We build strings one token at a time in InputSources, which is extremely inefficient with cstring, as it involves copying and reallocating the string for each added token.  Using std::string instead is significantly better for building strings incrementally.
The java equivalence is
- cstring <-> java.lang.String
- std::string <-> java.lang.StringBuilder

Use std::string instead of cstring in InputSources

---

ir/ir.def
testdata/p4_16_errors/switch_expression.p4
testdata/p4_16_errors_outputs/switch_expression.p4-stderr

Hi,
This is a tweak to the way an error is reported from:
```
In file: /home/rlytton/repos/p4c/ir/ir.def:479
Compiler Bug: ../testdata/p4_16_errors/switch_expression.p4(3): 85: Unexpected expression for switch case
const bit<8> NumConstant = 0x55;
^^^^
```
to:
```
switch_expression.p4(3): [--Werror=expr] error: 0x55: Unexpected expression for switch case
const bit<8> NumConstant = 0x55;
^^^^
```

Illegal P4 to report error rather than  compiler-error

---

backends/ubpf/ubpfParser.cpp
testdata/p4_16_samples/advance_ubpf.p4
testdata/p4_16_samples/advance_ubpf.stf

I've implemented `advance()` in the uBPF parser. This allows to skip some bits without need to define headers.
In this implementation parser advances the packet cursor. When the packet is too short, it goes to reject state.
I think that @osinstom should be assigned.

Implementation of advance() for parser in uBPF backend

---

backends/bmv2/bmv2stf.py
backends/bmv2/common/action.cpp
backends/bmv2/psa_switch/midend.cpp
backends/bmv2/psa_switch/psaSwitch.cpp
testdata/p4_16_samples/psa-meter7-bmv2.p4
testdata/p4_16_samples/psa-meter7-bmv2.stf

Supporting meter extern on PSA:
meter.execute(): Syntax exposed to programmer is `ret = meter.execute(index)`. Internally, the compiler backend generate .json for `meter.execute(dst, ret)`, where `ret` is a parameter of `execute()` in the .json file.
`meter` is generated in `extern_instances` section of the .json file instead of the `meter_arrays` section.
Testing filename: `testdata/p4_16_samples/psa-meter7-bmv2.p4 (.stf)`
* A PR has been submitted to bmv2 end to support `psa-meter` as well.

[PSA] Supporting Indexed Meter as a Extern

---

frontends/common/options.cpp

Currently it is not possible to perform more complex queries for toP4 compiler pass dumps. We can only check for substrings. This pull request enables matches using regular expressions. Functionality should remain the same, but now it is possible to use commands like `p4c/build/p4test --dump dmp prog.p4 --top4 "FrontEnd.*PassRepeated"` which only dumps PassRepeated in the FrontEnd. Or `p4c/build/p4test --dump dmp prog.p4 --top4 ".*"` which dumps all compiler passes. 
Afaik C++ regex matching is supported after `gcc4.9`, which is the minimum version `p4c` requires.

Support regex matching for toP4 dumps.

---

lib/gmputil.h
midend/replaceSelectRange.cpp
testdata/p4_16_samples/issue2485.p4
testdata/p4_16_samples_outputs/issue2485-first.p4
testdata/p4_16_samples_outputs/issue2485-frontend.p4
testdata/p4_16_samples_outputs/issue2485-midend.p4
testdata/p4_16_samples_outputs/issue2485.p4

See https://github.com/p4lang/p4c/issues/2485 and this error from it:
`Can not shift by a negative value.`
This issue is caused by using ffs() from gmputil.h which returns `-1` when v is 0.

Fix Range error found with Issue 2485

---

.travis.yml
tools/travis-build

This pull request add translation validation to the CI workflow of p4c. Translation validation certifies that a particular compiler pass has correctly transformed a given input program without changing its semantics. To perform translation validation for p4c, we use a symbolic interpreter ([Gauntlet](https://github.com/p4gauntlet/p4_tv)) to transform P4 programs into [Z3](https://github.com/Z3Prover/z3) formulas. The Gauntlet workflow requires two external dependencies, which are described in this [source organization](https://github.com/p4gauntlet). You can also find a detailed description of the tool and basic usage instructions there. I currently maintain this organization.
To validate a P4 program, the symbolic interpreter converts the program into a Z3 formula capturing its …

[Testing] Add Travis Validation Tests for P4C.

---

frontends/p4/typeChecking/typeChecker.cpp
frontends/p4/typeChecking/typeSubstitution.cpp
testdata/p4_16_samples/issue2492.p4
testdata/p4_16_samples_outputs/issue2492-first.p4
testdata/p4_16_samples_outputs/issue2492-frontend.p4
testdata/p4_16_samples_outputs/issue2492-midend.p4
testdata/p4_16_samples_outputs/issue2492.p4

This fixes the immediate problem in issue #2492 -- at least with respect to package instantiations.  Its possible something additional is needed for extern instantiations and/or other method calls.

Infer don't care for type args used only by @optional args

---

.travis.yml
tools/travis-build

`python-xdist` recently upgraded to 2.0.0, which seems to cause some issues with older Python or Ubuntu versions. This pull request fixes the dependency to 1.34.0 for the time being.

Use an older version of python-xdist

---

backends/bmv2/CMakeLists.txt
backends/p4test/CMakeLists.txt

Remove mention of a test program psa-ingress-input-meta-bmv2.p4, which
as far as I can tell was never added to the p4c repository.
Update some comments in backends/p4test/CMakeLists.txt to reflect the
reason why some tests are excluded.

Small updates to CMakeLists.txt for PSA test programs

---

backends/bmv2/psa_switch/midend.cpp
backends/bmv2/simple_switch/midend.cpp
backends/p4test/midend.cpp
frontends/p4/strengthReduction.cpp
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2-midend.p4
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2-midend.p4
testdata/p4_14_samples_outputs/p414-special-ops-midend.p4
testdata/p4_16_samples_outputs/complex10-midend.p4
testdata/p4_16_samples_outputs/complex9-midend.p4
testdata/p4_16_samples_outputs/issue2495-bmv2-first.p4
testdata/p4_16_samples_outputs/issue2495-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue2495-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue2495-bmv2.p4
testdata/p4_16_samples_outputs/issue2495-bmv2.p4.p4info.txt
testdata/p4_16_samples_outputs/issue561-midend.p4
testdata/p4_16_samples_outputs/issue983-bmv2-midend.p4
testdata/p4_16_samples_outputs/struct_init-1-midend.p4

Fixes #2495.
The reason this works is that our code generator only handles very limited expressions in `if` statements that contain a table apply `if (table.apply()...)`.  LocalCopyProp would create an expression `if (!!table.apply().hit)`. The expressions in `if` statements are simplified very early in the compilation, and there isn't a pass in the back-end that would handle more complex expressions - under the assumption that no other pass could make the expression more complex.
We can probably simplify this even further to an unconditional table application.

Strength-reduce !!

---

testdata/p4_16_samples/psa-recirculate-no-meta-bmv2.p4
testdata/p4_16_samples/psa-recirculate-no-meta-bmv2.stf
testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2-first.p4
testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2-frontend.p4
testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2-midend.p4
testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2.p4
testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2.p4.p4info.txt

It still does not exercise recirculation of packets with preserved
user-defined metadata, since that is not yet implemented in p4c for
PSA, but it does copy the value received for ingress_port by the
ingress control into the output packet, so the STF test can check
whether it has the expected value.

Make PSA packet recirculation test more strict

---

frontends/p4/frontend.cpp
midend/copyStructures.cpp
testdata/p4_16_samples_outputs/issue2261-midend.p4
testdata/p4_16_samples_outputs/issue2289-frontend.p4
testdata/p4_16_samples_outputs/issue2289-midend.p4
testdata/p4_16_samples_outputs/issue2383-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue396-frontend.p4
testdata/p4_16_samples_outputs/issue396-midend.p4
testdata/p4_16_samples_outputs/issue841-midend.p4
testdata/p4_16_samples_outputs/issue982-midend.p4
testdata/p4_16_samples_outputs/struct_init-1-frontend.p4
testdata/p4_16_samples_outputs/struct_init-1-midend.p4

Frontend pass setHeaders shifted after InlineFunctions pass, so that return values of functions could be processed as right operands of assignment statements, where left operand is header type or a header field. The idea was to remove the redundant setValid() calls in some outputs. The solution was tested on code given in issue 2383, and tests that had a duplicated setValid() call.
With this change, there is no need for checking for header types when handling structures or lists in copyStructures pass in midend, because setValid() call is handled in frontend. There are no changes at the end of midend in test #2383 after implementing these changes, and tests with redundant setValid() calls have different outputs. For an example, in test issue2261.p4, there is no redundant setValid() call …

Enhancement: Issue #2396 duplicated setValid() call removal

---

frontends/p4/def_use.cpp
frontends/p4/def_use.h
frontends/p4/frontend.cpp
frontends/p4/structInitializers.cpp
testdata/p4_16_samples/issue2487.p4
testdata/p4_16_samples_outputs/issue2487-first.p4
testdata/p4_16_samples_outputs/issue2487-frontend.p4
testdata/p4_16_samples_outputs/issue2487-midend.p4
testdata/p4_16_samples_outputs/issue2487.p4

There was actually also a second bug in the def_use analysis in the handling of list expressions.
Fixes #2487.
The fix is essentially to push the type of the result down in both branches of a Mux if it is useful.

Handle Mux when generating struct initializers

---

tools/driver/p4c_src/p4c.bmv2.cfg

pragmas are specific to each backend, bmv2 backend currently does not provide help message for pragmas.
Fix #2521

error and exit if --help-pragmas used for bmv2

---

lib/log.h

This PR prefixes the `ERROR` and `WARNING` macro with `P4C_` to prevent collisions with other libraries (`windows.h`, glog).
After inspecting the code, I went for a minimal change here. There are no other uses of these inside p4c.
Alternatives:
If the code were better structured (i.e. would not include internal headers in public headers), this rename would not be necessary. This would require a larger restructure, though.
There is also this piece of code, which might cause surpises: https://github.com/p4lang/p4c/blob/5e05765e0c0d8d69e0ffe4ed4392e0e976203937/lib/log.h#L150-L166
I'm not sure if publicly overloading `ostream` for STL types is good practice.
Closes #2523

Rename ERROR and WARNING macros

---

testdata/p4_16_errors/action-named-default-bmv2.p4
testdata/p4_16_errors_outputs/action-named-default-bmv2.p4-stderr

It gives compile-time syntax error, which seems better than allowing
such a confusing name, given the special meaning of 'default' in
switch statements.

Add test case attempting to name an action 'default'

---

midend/has_side_effects.h
testdata/p4_16_samples/issue1985.p4
testdata/p4_16_samples_outputs/issue1025-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue1985-first.p4
testdata/p4_16_samples_outputs/issue1985-frontend.p4
testdata/p4_16_samples_outputs/issue1985-midend.p4
testdata/p4_16_samples_outputs/issue1985.p4
testdata/p4_16_samples_outputs/issue396-midend.p4
testdata/p4_16_samples_outputs/issue561-midend.p4

Change made in makeSideEffectStatement where the case which processed binary operator was missing.
After that a new bug appeared because isValid has not yet been processed in convertActionBody.
Change made:
In makeSideEffectStatement:
-Processing of unary operation was replaced with processing of unary and binary
-The given example illustrates the situation where the change needs to be applied
~~~ P4
control c3(inout headers hdr,inout metadata meta,inout standard_metadata_t std_meta) {
action a(in bool b) {
hdr.h.x = 8w0;
}
table t {
key = { }
actions = {
a(hdr.h.isValid() || (bool) 1w1);
}
}
apply {
t.apply();
}
}
~~~
or more complicated:
~~~ P4
control c3(inout headers hdr,inout metadata meta,inout standard_metadata_t std_meta) {
action a(in bool b) {
hdr.h.x = 8w0;
}
table t {
key = { …

Fix compiler Bug in local copy propagation #1985

---

ir/base.def
ir/ir.cpp

The removed code checked if two CompileTimeValues were equal by checking pointer equality.
This can cause errors such as the following:
In file: third_party/p4lang_p4c/ir/ir.cpp:210
Compiler Bug: <redacted>: hdr.ipv4_base.isValid(); already set in <ControlBlock>(2443131) ingress(); instance type=control ingress<>(inout parsed_packet_t hdr, inout local_metadata_t local_metadata, inout standard_metadata_t standard_metadata); to hdr.ipv4_base.isValid();, not hdr.ipv4_base.isValid();
if (hdr.ipv4_base.isValid()) {
Unfortunately I cannot provide a small example provoking the error at this time.

Fix compiler bug confusing physical equality with semantic equality.

---

bazel/p4_library.bzl

Sorry for the noise, I missed this in #2539.

Fix: don't supply arguments twice in p4_library.

---

backends/ubpf/target.cpp
backends/ubpf/target.h
backends/ubpf/ubpfProgram.cpp
backends/ubpf/ubpfRegister.cpp
backends/ubpf/ubpfRegister.h
backends/ubpf/ubpfTable.cpp
backends/ubpf/ubpfTable.h
backends/ubpf/ubpfType.cpp
backends/ubpf/ubpfType.h
testdata/p4_16_samples/lpm_ubpf.p4
testdata/p4_16_samples_outputs/lpm_ubpf-first.p4
testdata/p4_16_samples_outputs/lpm_ubpf-frontend.p4
testdata/p4_16_samples_outputs/lpm_ubpf-midend.p4
testdata/p4_16_samples_outputs/lpm_ubpf.p4
testdata/p4_16_samples_outputs/lpm_ubpf.p4.p4info.txt

Similarily to the eBPF backend, this PR introduces support for Longest-Prefix Match for the uBPF target.
Obviously, a uBPF target must implement `UBPF_MAP_TYPE_LPM_TRIE` type of the BPF map. In the upcoming commits, I'm going to prepare a specification of functionalities/APIs that a switch should support to work properly with `p4c-ubpf`.

uBPF target: add support for LPM match

---

frontends/p4/parameterSubstitution.h
ir/ir.cpp
lib/enumerator.h

Static analysis identified locations where we immediately dereference a returned `Util::Enumerator *` that might be null.  Add an `EmptyEnumerator` to avoid the undefined behavior.

EmptyEnumerator instread of nullptr

---

CMakeLists.txt
tools/driver/CMakeLists.txt

This introduces a `P4C_DRIVER_NAME` CMake parameter for customization of the name of the driver script that is produced.

Allow customization of driver-script name.

---

lib/error.h

This adds back the legacy version of `::warning`, which was removed in #2531. Like the legacy version of `::error`, the legacy `::warning` is guarded by the `LEGACY` cpp symbol.

Re-introduce legacy version of `::warning`.

---

CMakeLists.txt

OPTION only supports boolean values, which means the default p4c driver
name is currently 'OFF'...
Fixes #2557

Fix default p4c driver name

---

ir/pass_manager.cpp
lib/n4.h
tools/ir-generator/irclass.cpp
tools/ir-generator/irclass.h
tools/ir-generator/methods.cpp

- use qualified name for classes when the unqualified would be
ambiguous/incorrect (multiple classes with the same name in different
namespaces)
- Fix gc memory reporting in pass manager (pre C++20 undefined order of eval)

ir generator fixes

---

.travis.yml

I wanted to add this in a more substantial pull request but considering there are new features being developed it makes sense to add this now. With this Gauntlet no longer should report an error if there is a language construct that is not implemented. I will have to fix those at my end later.

Ignore crashes in Gauntlet validation

---

.travis.yml
Dockerfile
tools/travis-build

When the toz3 extension does not build only the validation test should fail. Now the question is what to do when the build for Gauntlet fails. Just ignore or try to issue some sort of warning? 
There is also the possibility of using [allow_failures](https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail) in Travis but I am not exactly sure if that has the intended effect.

Separate Gauntlet from the normal P4C tests

---

backends/bmv2/CMakeLists.txt
backends/ebpf/CMakeLists.txt
backends/graphs/CMakeLists.txt
backends/p4test/CMakeLists.txt

`realpath` is not present by default on macOS, and `realpath` provided from coreutils does support `--relative-to`.
Instead use the equivalent functionality provided by the cmake's `file` command.
Fixes: #2573

Do not assume the presence of realpath

---

.github/workflows/ci-test.yml
.github/workflows/ci-validation.yml

There was a regression where validation tests could not handle a failing build. By setting Github environment variables we should be able to circumvent this issue. Also moved the validation build to its own workflow file.

Fix validation tests.

---

ir/node.h

Added a convenience method `INode::checkedTo` for checked casts. The effect of `n->checkedTo<N>()` is similar to `&n->as<N>()`, except the former produces an error message that is easier to debug. The former also has clearer intent: the latter could be easily mistaken as being equivalent to `n->to<N>()`.

Add INode::checkedTo for checked casts.

---

frontends/p4/def_use.cpp
frontends/p4/def_use.h
frontends/p4/simplifyDefUse.cpp
testdata/p4_16_samples/issue2583_simplify_slice.p4
testdata/p4_16_samples/issue2583_simplify_slice2.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice-first.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice-frontend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice-midend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice2-first.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice2-frontend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice2-midend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice2.p4

* Overwritten slice statements skipped
* Improved logging in FindUninitialized
When FU is registering uses in a lhs slice of an assignment statement, it skips those
which the given slice can overwrite.
To make these changes more comprehensible, I'll start by explaining my view of the problem.
How removing redundant assignment statements works (no-slice lhs assignments):
The issue starts by pointing out that the following
```
h.data = 8;
h.data = 8;
```
gets reduced to
```
h.data = 8;
```
But these snippets are misleading - in reality, the above holds true only when
```
h.data = 8;
h.data = 8;
// a third, certain kind of statement (not necessarily right after the one above) 
```
Why is this third statement required? Because the second `h.data = 8;` would disappear just as well as the …

Remove redundant slice statements during SimplifyDefUse (#2583)

---

lib/bitops.h
lib/gmputil.h

The implementation in bitops.h only supports 32bit unsigned int.

remove duplicated library function in favor of big_int version

---

midend/predication.cpp
testdata/p4_16_samples/predication_issue.p4
testdata/p4_16_samples_outputs/predication_issue-first.p4
testdata/p4_16_samples_outputs/predication_issue-frontend.p4
testdata/p4_16_samples_outputs/predication_issue-midend.p4
testdata/p4_16_samples_outputs/predication_issue.p4

The removal of the condition on the line 192 leads to the correct predication output. The mentioned condition was not correct, it only tests if the travesalPath is false, which is true when there is any else branch in a p4 test. The assignment in 'then' should be erased only when there is a statement with the same statementName in the else branch inside a p4 test.
Then-else handling is correctly managed in if block on line 201 (new line 196), so no other test outputs are changed by this commit.

Fixes #2613 predication issue

---

lib/bitops.h
lib/gmputil.h

Revert previous commit to keep the original library function as they are used by other part of the compiler. Only adds ceil_log2 to gmputil.h.

add ceil_log2 to gmputil.h

---

frontends/p4/simplifyDefUse.h
testdata/p4_14_samples_outputs/modify_conditionally-frontend.p4
testdata/p4_16_samples_outputs/enumCast-frontend.p4
testdata/p4_16_samples_outputs/generic-struct-frontend.p4
testdata/p4_16_samples_outputs/generic-struct-midend.p4
testdata/p4_16_samples_outputs/issue2105-frontend.p4
testdata/p4_16_samples_outputs/issue2221-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue2287-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue2356-frontend.p4
testdata/p4_16_samples_outputs/issue2488-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue2543-1-frontend.p4
testdata/p4_16_samples_outputs/issue2543-1-midend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice-frontend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice-midend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice2-frontend.p4
testdata/p4_16_samples_outputs/issue2583_simplify_slice2-midend.p4
testdata/p4_16_samples_outputs/issue561-frontend.p4
testdata/p4_16_samples_outputs/issue561-midend.p4
testdata/p4_16_samples_outputs/pred2-frontend.p4
testdata/p4_16_samples_outputs/pred2-midend.p4
testdata/p4_16_samples_outputs/side_effects-frontend.p4
testdata/p4_16_samples_outputs/side_effects-midend.p4
testdata/p4_16_samples_outputs/simplify_slice-frontend.p4
testdata/p4_16_samples_outputs/stack-frontend.p4
testdata/p4_16_samples_outputs/stack-midend.p4
testdata/p4_16_samples_outputs/tuple-frontend.p4
testdata/p4_16_samples_outputs/tuple-midend.p4
testdata/p4_16_samples_outputs/uninit-frontend.p4

This (second) PR is a continuation of the discussion in https://github.com/p4lang/p4c/pull/2610.
Originally suggested as part of the solution, it was decided to become a separate concern.
As a result, the SimplifyDefUse pass runs until convergence, instead of only once.

Convert SimplifyDefUse to a PassRepeated (#2610)

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_samples/issue2492.p4
testdata/p4_16_samples/issue2630.p4
testdata/p4_16_samples_outputs/issue2492.p4
testdata/p4_16_samples_outputs/issue2630-first.p4
testdata/p4_16_samples_outputs/issue2630-frontend.p4
testdata/p4_16_samples_outputs/issue2630-midend.p4
testdata/p4_16_samples_outputs/issue2630.p4

This update was lost when the statement to save the values of the type variables was moved in #2603.
Fixes #2630

Add don't cares to the list of type variable bindings

---

backends/bmv2/common/options.h
backends/ebpf/ebpfOptions.cpp
backends/ebpf/ebpfOptions.h
backends/p4test/p4test.cpp
frontends/common/options.cpp
frontends/common/options.h
lib/options.cpp
lib/options.h

p4c backends in bmv2, ebpf, and ubpf support the `-o` option.  It's only the p4test backend that does not.  P4 modularity is one example of an app which would use the `-o` option to dump the merged P4 program.   This PR moves the option to `frontend/common/options.h[.cpp]`.

Add -o option to p4test backend

---

frontends/p4/typeChecking/typeConstraints.h

* Unitialized variable added to constructor (introduced by 6b9da239267529aeea6946cb0aa984c4487b07d9)

Fixed unitialized variable in frontend typeChecking

---

backends/bmv2/common/options.h
backends/ebpf/ebpfOptions.cpp
backends/ebpf/ebpfOptions.h
backends/p4test/p4test.cpp
frontends/common/options.cpp
frontends/common/options.h
lib/options.cpp
lib/options.h

This reverts commit ecba24ad591e719268860f66202530830d2a914e.
Not all targets outputs to a single file, moving '-o' to top level creates unnecessary work.

Revert "Add -o option to p4test backend (#2634)"

---

.github/workflows/ci-bazel.yml
bazel/p4c_deps.bzl

GitHub's caching mechanism never overwrites cache entries for existing keys. Since we were using a static key, this caused our cache to never be refreshed. 
With this PR, a new cache entry is generated at the end of every CI run; at the beginning of every CI run, the freshest cache entry is restored.

Improve Bazel CI build times through smarter caching

---

frontends/common/constantFolding.cpp
frontends/common/constantParsing.cpp
frontends/common/options.cpp
frontends/common/options.h
ir/configuration.h
ir/type.cpp
lib/compile_context.h

This turns the `P4CConfiguration` into an abstract class to allow overriding of compiler configuration parameters. The active configuration can be obtained from `P4CContext`.

Add more flexibility to compiler configuration.

---

testdata/p4_16_errors/stack-const-index-out-of-bounds-bmv2.p4
testdata/p4_16_errors_outputs/stack-const-index-out-of-bounds-bmv2.p4
testdata/p4_16_errors_outputs/stack-const-index-out-of-bounds-bmv2.p4-stderr

p4c already gives an error message if a header stack index is a
compile-time known value that is out of range, so there is no bug
here.  This is simply a test program that verifies that p4c does give
an error message for P4 programs that do this.

Added test case with out-of-bounds index to header stack

---

lib/ordered_set.h

The emplace_back function is missing a return statement. Add the missing return statement.
Fixes #2672

add return statement to ordered_set::emplace_back

---

testdata/p4_16_samples_outputs/gauntlet_function_if_hdr_return-bmv2-frontend.p4
testdata/p4_16_samples_outputs/gauntlet_function_if_hdr_return-bmv2-midend.p4
testdata/p4_16_samples_outputs/gauntlet_hdr_in_value-bmv2-frontend.p4
testdata/p4_16_samples_outputs/gauntlet_nested_ifs_in_function-bmv2-frontend.p4
testdata/p4_16_samples_outputs/gauntlet_nested_table_calls-bmv2-frontend.p4
testdata/p4_16_samples_outputs/gauntlet_nested_table_calls-bmv2-midend.p4

@fruffy : our improved dead code detection has now removed some functions that have no side-effects.
So these four gauntlet tests fail. For now I have updated the reference outputs, but you may want to fix the tests so that the code is not actually dead. If the code is dead it also means that your stf files are not checking anything really.

Reference outputs changed

---

frontends/p4/frontend.cpp
frontends/p4/moveDeclarations.h
frontends/p4/parserControlFlow.h
test/gtest/load_ir_from_json.cpp
testdata/p4_16_samples/issue2409.p4
testdata/p4_16_samples_outputs/issue2409-first.p4
testdata/p4_16_samples_outputs/issue2409-frontend.p4
testdata/p4_16_samples_outputs/issue2409-midend.p4
testdata/p4_16_samples_outputs/issue2409.p4
testdata/p4_16_samples_outputs/issue2409.p4-stderr
testdata/p4_16_samples_outputs/predication_issue.p4.p4info.txt

Make declarations global in parser before converting ifs to states

---

frontends/p4/typeChecking/typeChecker.cpp
ir/type.def
testdata/p4_16_samples_outputs/gauntlet_bounded_loop-first.p4
testdata/p4_16_samples_outputs/issue2617.p4-stderr

This only has cosmetic changes, but the tests fail because some reference outputs have changed.

Merging PRs broke master; fix it

---

bazel/p4_library.bzl

In upcoming versions of Bazel, cc toolchains will be resolved via toolchain resolution, which requires the `toolchains` argument to the `rule` function.
The `incompatible_use_toolchain_transition` flag is set due to a migration, we will remove this when it is no longer needed (on the order of a half year, I suspect).

Add correct Bazel cc toolchain dependency

---

tools/travis-build

With the changes to the base image, this package was missing for the Gauntlet installation. This just installs 'software-properties-common'. Once we switch to Ubuntu 20.04 all of this will not be necessary anymore.

Fix Gauntlet install.

---

frontends/CMakeLists.txt
frontends/common/options.cpp
frontends/common/options.h
frontends/common/parseInput.h
frontends/common/parser_options.cpp
frontends/common/parser_options.h

Implements issue #2679. The CompilerOptions class now inherits from a new class called ParserOptions that is defined in the parser_options file, which sits between Util::Options and CompilerOptions. This change should be invisible to other users, and all changes are local to the frontends folder. Note we also changed the signature of the parseP4File function in parseInput which will now take in a ParserOptions object instead of a CompilerOptions object as an argument. 
This would allow for an added level of granularity for extensions like ours in regards to the number of options that we have at hand, which would tidy up our usage message. 
@fruffy

Seperate parser options from frontend options

---

backends/bmv2/common/helpers.h
backends/ebpf/ebpfModel.h
backends/ubpf/ubpfModel.h
control-plane/p4RuntimeArchStandard.cpp
frontends/common/model.h
frontends/p4/coreLibrary.h
frontends/p4/evaluator/evaluator.cpp
frontends/p4/fromv1.0/programStructure.cpp
frontends/p4/fromv1.0/v1model.h
frontends/p4/modelInstances.cpp
frontends/p4/simplifyDefUse.cpp
frontends/p4/toP4/toP4.cpp
frontends/p4/toP4/toP4.h
frontends/p4/uniqueNames.h
frontends/p4/unusedDeclarations.cpp
ir/dump.cpp
midend/interpreter.cpp
test/gtest/helpers.cpp

In particular, v1model::instance::version was a global static variable. That's bad.
The weird thing is that some of the classes I have introduced to represent the two versions of v1model are currently not used.
@antoninbas some of these are in the control-plane API generation code.
In particular, V1MODEL2020 is never used, but all tests pass.

Make v1model immutable

---

frontends/p4/specializeGenericTypes.cpp
frontends/p4/specializeGenericTypes.h
frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_samples/generic-struct-tuple.p4
testdata/p4_16_samples/generic-struct.p4
testdata/p4_16_samples/issue2627.p4
testdata/p4_16_samples_outputs/generic-struct-first.p4
testdata/p4_16_samples_outputs/generic-struct-frontend.p4
testdata/p4_16_samples_outputs/generic-struct-midend.p4
testdata/p4_16_samples_outputs/generic-struct-tuple-first.p4
testdata/p4_16_samples_outputs/generic-struct-tuple-frontend.p4
testdata/p4_16_samples_outputs/generic-struct-tuple.p4
testdata/p4_16_samples_outputs/generic-struct-tuple.p4-stderr
testdata/p4_16_samples_outputs/generic-struct.p4
testdata/p4_16_samples_outputs/issue2627-first.p4
testdata/p4_16_samples_outputs/issue2627-frontend.p4
testdata/p4_16_samples_outputs/issue2627.p4
testdata/p4_16_samples_outputs/issue2627.p4-stderr

This fixes a bug found as a result of reviewing this design in the language design working group.
After specializing generic structs the original type definitions are removed from the program so not further passes have to worry about them. Without these passes the tuple elimination pass generates incorrect code.

Remove generic types after specialization

---

ir/type.def

Looks like the lastest merge broke the build for MacOs. I hope that this commit fixes it.

Missing override keyword

---

backends/dpdk/DpdkXfail.cmake
backends/dpdk/dpdkArch.cpp
backends/dpdk/dpdkArch.h
testdata/p4_16_samples_outputs/psa-action-selector1.p4.spec
testdata/p4_16_samples_outputs/psa-action-selector2.p4.spec
testdata/p4_16_samples_outputs/psa-action-selector3.p4.spec
testdata/p4_16_samples_outputs/psa-register2.p4.spec
testdata/p4_16_samples_outputs/psa-register3.p4.spec

This commit fixes the "declaration not found" error with p4c-dpdk. 
- Added a new preorder function which works on the Pathexpressions for replacing the header and metadata variable references.
- With this change, some of the tests in XFAIL list of dpdk backend are compiling fine. Updated the XFAIL list for the same.

Fix dpdk regression failure: declaration not found

---

frontends/p4/def_use.cpp
frontends/p4/def_use.h
testdata/p4_16_samples/issue2393.p4
testdata/p4_16_samples_outputs/issue2393-first.p4
testdata/p4_16_samples_outputs/issue2393-frontend.p4
testdata/p4_16_samples_outputs/issue2393-midend.p4
testdata/p4_16_samples_outputs/issue2393.p4
testdata/p4_16_samples_outputs/issue2393.p4-stderr

Fixes #2393 
Most of the changes are just improved debugging output.
There were two typos in def_use.cpp, as one can notice by comparing with similar code nearby.

Fix typo in def-use analysis

---

test/CMakeLists.txt
test/gtest/env.h.in
test/gtest/parser_unroll.cpp

These changes allow running gtestp4c from different folders.

Changing relative paths for parsers Unroll gtests

---

backends/dpdk/DpdkXfail.cmake
backends/dpdk/dpdkArch.cpp
backends/dpdk/dpdkArch.h
testdata/p4_16_samples_outputs/psa-action-profile1.p4.spec
testdata/p4_16_samples_outputs/psa-action-profile3.p4.spec
testdata/p4_16_samples_outputs/psa-action-profile4.p4.spec
testdata/p4_16_samples_outputs/psa-counter1.p4.spec
testdata/p4_16_samples_outputs/psa-counter2.p4.spec
testdata/p4_16_samples_outputs/psa-counter3.p4.spec
testdata/p4_16_samples_outputs/psa-counter4.p4.spec
testdata/p4_16_samples_outputs/psa-custom-type-counter-index.p4.spec
testdata/p4_16_samples_outputs/psa-header-stack.p4.spec
testdata/p4_16_samples_outputs/psa-idle-timeout.p4.spec
testdata/p4_16_samples_outputs/psa-meter1.p4.spec
testdata/p4_16_samples_outputs/psa-meter4.p4.spec
testdata/p4_16_samples_outputs/psa-meter5.p4.spec
testdata/p4_16_samples_outputs/psa-register1.p4.spec

This commit fixes the "Duplicates declaration" error with p4c-dpdk.
Added new preorder functions for Type_Control and Type_Parser. These functions updates the names of header and metadata parameters to "h" and "m" respectively.
With this change, some of the tests in XFAIL list of dpdk backend are compiling fine. Updated the XFAIL list and sample outputs for the same.

Fix dpdk regression failure: Duplicates declaration

---

test/gtest/parser_unroll.cpp

P4C_16_INCLUDE_PATH is now reset to any previous value (or unset if it wasn't set previously). This is so that any gtests run after parser_unroll have the default environment (not the one changed by parser_unroll).

Parser unroll gtest now does not modify environment

---

.github/.travis.yml.disabled
.github/workflows/ci-bazel.yml
.github/workflows/ci-test.yml
.github/workflows/ci-validation.yml
README.md
bazel/p4c_deps.bzl
docs/README.md
docs/doxygen/doxygen.cfg
p4include/psa.p4
p4include/v1model.p4
testdata/p4_16_samples/v1model-special-ops-bmv2.p4

This is in preparation for renaming p4c's primary branch. 
In particular, update references to "master" in the CI scripts. Also update references to main branch in behavioral-model.
This PR should be merged at the same time as we (manually) rename the branch on GitHub's website.

Replace "master" with "main" 

---

README.md
bazel/p4c_deps.bzl

The primary purpose of this commit is to check Travis CI scripts on the recently renamed `main` branch for p4c.
It also updates the list of backends for the open-source compiler.

Test `main` branch

---

backends/dpdk/dpdk.def
backends/dpdk/dpdkHelpers.cpp
backends/dpdk/spec.cpp
testdata/p4_16_samples_outputs/psa-example-incremental-checksum.p4.spec

checksum clear() method is implemented by initializing the internal state to 0.

dpdk: implement checksum clear method

---

ir/ir.def

The `ifTrue` branch doesn't have a `NullOK` annotation, so the IR
generator already adds the same check:
```
void IR::IfStatement::validate() const {
CHECK_NULL(condition);
CHECK_NULL(ifTrue);
{ CHECK_NULL(ifTrue); } }
```

Eliminate redundant validation code.

---

frontends/p4/cloner.h
frontends/p4/methodInstance.cpp
frontends/p4/methodInstance.h
frontends/p4/uniqueNames.cpp
ir/visitor.h

Once type inferencing is finished, the typemap is no longer needed to resolve method calls, so this allows not providing one.  This change allows calling MethodInstance::resolve with a nullptr for the typeMap, so it can be used when a type map is not available.
Also clean up some redundant clones that were making things harder to debug (and just wasting space/time), and better allow ControlFlowVisitor to be extended to allow more general stuff.

Cleanups to help with resolving methodcalls without a typeMap

---

frontends/parsers/p4/p4parser.ypp

Removed "experimental" comments from parser features that are slated for inclusion in P4 version 1.2.2.

Features no longer marked as experimental

---

tools/ci-build.sh

I recently switched to a C++-based interpreter for validation. The functionality should stay the same, but it is easier to maintain and much faster. However, there are some additional dependencies required when building with Ubuntu 16.04. I hope I can sort them out over time. For now they have to  be added to get the tests to run again.

Add some more required dependencies for the validation tests.

---

frontends/p4/typeChecking/typeConstraints.h
lib/CMakeLists.txt
lib/compile_context.h
lib/error_helper.h
lib/error_message.cpp
lib/error_message.h
lib/error_reporter.h

Motivation behind this PR is to be able to use custom sinks for logging errors and to have maximum flexibility when formatting these messages.
Originally, all error/warning messages were send to `error_helper` functions which used template metaprogramming to serialize arguments into `boost::format` object and to add diagnostic information to the message. It used four string values to hold intermediate results and returned one formatted string at the end.
This PR uses dedicated struct for holding those intermediate values, most notably storing vector of `SourceInfo`s instead of serializing it into strings. This struct (`ErrorMessage`) contains `toString`` method which yields the same formatted strings as before, but `ErrorReporter::emit_message` function has been modified to accept this …

Refactor error logging

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_errors/issue122.p4
testdata/p4_16_errors_outputs/issue122.p4
testdata/p4_16_errors_outputs/issue122.p4-stderr

I think that this is the right approach; otherwise it's very complicated to explain when the possible side-effects of the function call may take place. But the working group has to validate this restriction.
Fixes #122

Do not allow function calls in select labels 

---

.github/workflows/ci-test.yml

I don't really understand github actions, but I copied some code I found on the net.
When we have multiple push requests to the same PR or branch we run needless workflows.
I hope that this cancels all runs of the same branch.

Cancel active workflows on new push

---

backends/ebpf/ebpfControl.cpp
backends/ebpf/ebpfType.cpp
backends/ebpf/ebpfType.h
backends/ubpf/ubpfControl.cpp
backends/ubpf/ubpfType.cpp
backends/ubpf/ubpfType.h

Fixes https://github.com/p4lang/p4c/issues/2822
In current p4c ebpf and ubpf backend code, callers that call declare do not know what type the variable is to declare.  All types implement declare.  So a new declareInit() method is added to code for all types.  The scope of changes is narrow.  Only for the Scalartype, declareInit() is supported - this is my need.  All other declareInit() just default to declare().  In each of ebpfControl.cpp and ubpfControl.cpp, emitDeclaration() is changed to use declareInit().  I have unit tested the changes with my p4tovpp backend.

Add C variable initialization

---

backends/bmv2/CMakeLists.txt
backends/bmv2/run-bmv2-test.py
backends/ebpf/run-ebpf-test.py
backends/ubpf/run-ubpf-test.py
tools/testutils.py

Update the file to use proper arguments etc instead of custom parsing. Makes extending the script much easier.
Also add a new option `--testfile`, which allows for specifying your own path for test files.

Modernize run-bmv2-test a little

---

p4include/bmv2/psa.p4
p4include/dpdk/psa.p4

There is no reason for the psa.p4 include file to include core.p4,
given that it is recommended practice that every P4_16 PSA program
first include core.p4, then psa.p4.
Move const declarations in bmv2/psa.p4 later, after the types they use
have been declared.
Correct a URL in comments in bmv2/psa.p4
bmv2/psa.p4 should declare match_kind optional.  It was already part
of the former p4include/psa.p4, but was not copied over into
p4include/bmv2/psa.p4
Remove comments from bmv2/psa.p4 that are either obsolete, or specific
to the BMV2 target.

Minor updates to BMv2 and DPDK psa.p4 include files

---

lib/error_catalog.cpp
testdata/p4_16_samples_outputs/action_profile_max_group_size_annotation.p4-stderr
tools/driver/p4c_src/driver.py
tools/driver/p4c_src/main.py

Backends might want to implement custom --help-* options and in that
case they need a way to signal the driver that this option does not
require input source file to be set.
Since some sanity checks rely on the fact input has been provided,
we set the input to dummy.p4 so those checks still work.

Allow backend to skip input file check

---

BUILD.bazel
bazel/example/p4/BUILD.bazel
bazel/p4_library.bzl

This PR adds
- a target (`:p4c_graphs`) to build the compiler binary with the graphs
backend, and
- a build rule `p4_graphs` to invoke this backend and merge the graph
files
so that the graphs backend can be used in other projects using Bazel.
We need a new build rule (rather than specifying a different binary for
`_p4c` in the `p4_library` rule) because the graphs backend does
not use the normal output file arguments and uses a separate argument to
specify the output *directory* to write the graphs in. The names of the
output files depend on the content of the input p4 file, and blaze
outputs cannot be directories (they can be file groups but we do not
know the exact file names without effectively running the p4 compiler).
So, we cannot directly use the output files in a blaze target. …

Bazel rules for the graphs backend.

---

README.md

Fix Ubuntu dependencies installation script.
Without these `\` we can't just copy a script

Fix install dependencies `bash` script

---

README.md

Addition to https://github.com/p4lang/p4c/pull/2853
We should remove `$` symbol because it's not a part of a script, hence we cannot use the copy button.

Fix install Ubuntu dependencies script.

---

frontends/common/constantFolding.h
frontends/p4/parseAnnotations.cpp
frontends/p4/reassociation.h
frontends/p4/strengthReduction.h

This is a very trivial addition to allow disabling strength reduction in pieces of the code that is not really relevant to to language at all (its an annotation that does not affect program semantics at all), but I'm of mixed mind because it is probably not useful for programmers in any meaningful way.
The impetus for this actually comes from some hardware people who are trying to test corner cases in our hardware and are having difficulties because the compiler keeps modifying/eliminating their code, so the program ends up bypassing what they are trying to test.  This particular case happpens very early on in the frontend where we can't really avoid it in our custom midend/backend code.  I'm open to discussions of better ways similar things might be done -- perhaps some kind of …

annotation to disable strength reduction in a block

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_samples/methodArgDontcare.p4
testdata/p4_16_samples_outputs/methodArgDontcare-first.p4
testdata/p4_16_samples_outputs/methodArgDontcare-frontend.p4
testdata/p4_16_samples_outputs/methodArgDontcare-midend.p4
testdata/p4_16_samples_outputs/methodArgDontcare.p4

Since ee77e40f0864c1157eb858bb14d6ea94f9837721 frontend (correctly)
inserts type casts of method call arguments if necessary.
However, if a method accepts "dontcare" input parameter and the method
is called with a InfInt value, a cast between these types is also
inserted. But the cast is later rejected during typechecking as
invalid. This commit prevents any cast to Dontcare type to be
inserted.

Fix "dontcare" type method argument

---

backends/dpdk/dpdkAsmOpt.cpp
backends/dpdk/dpdkAsmOpt.h
backends/dpdk/dpdkHelpers.cpp
backends/p4test/CMakeLists.txt
testdata/p4_16_samples/psa-example-dpdk-counter.p4
testdata/p4_16_samples/psa-example-dpdk-externs.p4
testdata/p4_16_samples_outputs/psa-conditional_operator.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-counter-first.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-counter-frontend.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-counter-midend.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-counter.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-counter.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-externs-first.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-externs-frontend.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-externs-midend.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-externs.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-externs.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-meter.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-meter1.p4.spec
testdata/p4_16_samples_outputs/psa-table-hit-miss.p4.spec

This PR includes the following changes
1) Fixing the increment value for packet and byte counters. The count method should increment the counter by packet length for byte counter and by 1 for packet counter.
2) Added parameter checks for the counters.
3) Modified tests related to counters as per the above change
4) In some cases, two labels are generated back to back. Extended the Asm optimization passes for removing redundant labels and jumps in action body also.
5) Added a test for label optimization in action body.
6) Updated p4test XFAIL list as p4test does not support conditional execution in action body
7) Updated reference outputs

DPDK backend: Fixing couple of issues in counter implementation and extend jump and label optimizations in action body

---

backends/dpdk/dpdkHelpers.cpp
backends/dpdk/dpdkHelpers.h
testdata/p4_16_samples/psa-dpdk-table-key-isValid1.p4
testdata/p4_16_samples/psa-dpdk-table-key-isValid2.p4
testdata/p4_16_samples/psa-dpdk-table-key-isValid3.p4
testdata/p4_16_samples/psa-dpdk-table-key-isValid4.p4
testdata/p4_16_samples/psa-dpdk-table-key-isValid5.p4
testdata/p4_16_samples/psa-dpdk-table-key-isValid6.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid1.p4.spec
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid2.p4.spec
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid3.p4.spec
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid4.p4.spec
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid5.p4.spec
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid6.p4.spec

This PR includes changes for
- Adding support for using isValid as table key. 
- Handling logical operations as RHS of assignment
The table key having _isValid_ method call is first assigned to a temporary and then the temporary variable is used a table key.
This temporary variable is moved to metadata as DPDK requires all temporary variables to be moved to metadata.
```
table tbl {
key = {
hdr.ethernet.isValid() : exact @name ("hdrValid");
hdr.ethernet.srcAddr : exact ;
}
}
```
gets translated to 
```
struct metadata {
....
bit<8> key;
}
..
table tbl {
key = {
key : exact @name ("hdrValid");
hdr.ethernet.srcAddr : exact ;
}
}
apply {
key = hdr.ethernet.isValid();
tbl.apply();
}
```

DPDK backend: Add support for using isValid as table key

---

backends/ebpf/codeGen.cpp
backends/ebpf/ebpfParser.cpp
backends/ebpf/ebpfType.cpp
backends/ebpf/midend.cpp
backends/ubpf/midend.cpp
backends/ubpf/ubpfParser.cpp
frontends/p4/commonInlining.h
frontends/p4/inlining.h
midend/singleArgumentSelect.cpp
midend/singleArgumentSelect.h
testdata/p4_16_samples/issue2816-1_ebpf.p4
testdata/p4_16_samples/issue2816_ebpf.p4
testdata/p4_16_samples_outputs/issue2816-1_ebpf-first.p4
testdata/p4_16_samples_outputs/issue2816-1_ebpf-frontend.p4
testdata/p4_16_samples_outputs/issue2816-1_ebpf-midend.p4
testdata/p4_16_samples_outputs/issue2816-1_ebpf.p4
testdata/p4_16_samples_outputs/issue2816_ebpf-first.p4
testdata/p4_16_samples_outputs/issue2816_ebpf-frontend.p4
testdata/p4_16_samples_outputs/issue2816_ebpf-midend.p4
testdata/p4_16_samples_outputs/issue2816_ebpf.p4

Fixes #2816 
@osinstom : you may want to consider applying similar fixes to the ubpf back-end.
In fact, this scheme is better than it used to be, but it is still not general enough: it won't handle select expressions where the expression has more than 64 bits combined.

Allow masks in select expressions

---

backends/dpdk/midend.cpp
midend/convertEnums.cpp
midend/convertEnums.h
testdata/p4_16_samples_outputs/psa-example-dpdk-externs.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-meter.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-meter1.p4.spec

This PR is to fix the issue mentioned in https://github.com/p4lang/p4c/issues/2874
The changes include
1) Improving the convertEnums midend pass to allow custom encoding of the enum constants by the backends. 
2) Customizing the enum values in the DPDK backend to emit DPDK compatible meter color values
PSA Meter color values are `RED = 0, GREEN = 1, YELLOW = 2 `and DPDK target implementation has the 
following meter color enum values `GREEN = 0, YELLOW = 1,  RED = 2`
3) Reference outputs updated

DPDK backend: Handle custom values for PSA_Meter_t enum

---

backends/dpdk/dpdkProgram.cpp
testdata/p4_16_samples/psa-dpdk-table-key-consolidation-mixed-keys-4.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-4.p4.spec

This commit appends tables and actions from the egress pipeline to be included in the output spec file.
Fixes: #2893

dpdk: export egress tables and actions

---

tools/driver/p4c_src/main.py

Spaces were missing in driver's help of command line option --parser-inline-opt, which caused that some words were concatenated together. This fixes it.

Add missing spaces to help of driver command line option

---

lib/exceptions.h
test/gtest/exception_test.cpp

This change makes sure that no escape characters for terminal colorizations are present in error logs when standard error output is redirected to a file.

Remove colors from error messages when redirected to a file

---

backends/dpdk/dpdkArch.h
backends/dpdk/dpdkHelpers.cpp
testdata/p4_16_samples/psa-example-dpdk-meter.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-meter-first.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-meter-frontend.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-meter-midend.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-meter.p4
testdata/p4_16_samples_outputs/psa-example-dpdk-meter.p4.spec

DPDK backend does not have instructions corresponding to conditional jump on GEQ(>=) and LEQ(<=) comparisons.
Hence, for these cases we negate the condition and jump on false block label.
```
if (a <= b)                                                     if (a > b)
<true block>                       =>                          <false block>
else                                                            else
<false block>                                                  <true block>
```
This PR fixes the existing support for these conditional jump instructions.
Also, corrected one of the example testcase for dpdk meter.

DPDK Backend: Fix conditional jumps when condition is LEQ or GEQ

---

midend/local_copyprop.cpp
midend/local_copyprop.h
testdata/p4_16_samples/struct_assignment_optimization.p4
testdata/p4_16_samples_outputs/issue2147-1-midend.p4
testdata/p4_16_samples_outputs/struct_assignment_optimization-first.p4
testdata/p4_16_samples_outputs/struct_assignment_optimization-frontend.p4
testdata/p4_16_samples_outputs/struct_assignment_optimization-midend.p4
testdata/p4_16_samples_outputs/struct_assignment_optimization.p4

Fix #2249 
This optimizes _LocalCopyPropagation Pass_ in case there is an assignment in the body of the action, where the left side and the right side of that assignment are equivalent, by not updating the writes set of that action.
As a consequence of this change, the test _issue-2147-1.p4_ failed, so I updated it as well.

Missed optimization: Struct-assignment in action prevents ConstantFolding (#2249)

---

frontends/common/resolveReferences/referenceMap.h
frontends/p4/typeChecking/typeSubstitution.h
frontends/p4/typeMap.h

Replace std::set and std::map with ordered_set and ordered_map to
provide consistent ordering in logs when running with -T typeChecker:3
Addresses issue: #2928

dbg: replace unordered collections with ordered

---

backends/dpdk/dpdkContext.cpp

Minor fix to use the getSizeProperty() method instead of getProperty for retrieving the table size.

DPDK Backend: Fix context Json generation when table size is explicitly specified

---

backends/dpdk/control-plane/bfruntime_arch_handler.h
ir/ir.def

With clang 13, there is this representative warning
ir/ir.def:90:28: warning: 'getAnnotations' overrides a member function
but is not marked 'override' [-Winconsistent-missing-override]
So add some override's.

Cleanup override warnings

---

midend/interpreter.cpp

These small changes allow to pass assignments of error type through parserUnroll. These changes allow to pass issue510-bmv2 example through parserUnroll without error : "Assign to void".

Support errors for parserUnroll

---

README.md

This pull request updates the installation instructions for packaged versions of p4c built in the [Open Build Service](https://build.opensuse.org/package/show/home:p4lang/p4lang-p4c).

readme: Update installation instructions

---

backends/ebpf/runtime/ebpf_kernel.h
backends/ebpf/runtime/kernel.mk
backends/ebpf/targets/kernel_target.py

On fedora rawhide with clang 13, there are multiple false positve
test failures similar to
p4c/backends/ebpf/runtime/ebpf_kernel.h:28:10: fatal error:
'bpf_endian.h' file not found
The libbfp-devel package installs bpf_endian.h to /usr/include/bpf/
The ./build_libbpf script installs it to
${CMAKE_CURRENT_SOURCE_DIR}/runtime/usr/include/bpf/
So the include should have a bpf/ prefix.
And since it is a system header the ""'s changed to <>'s

improve include path to bpf_endian.h

---

midend/global_copyprop.cpp

The code was calling a method on a NULL pointer.
While this will work most of the time with most compilers, this is still
undefined behavior. As a result, when compiling with O3 the compiler may
assume that the method is never called with a NULL pointer to optimize
code.
In our case the compiler can assume that to<T> is not called on a NULL
pointer and therefore that dynamic_cast is not called with a NULL
pointer. This can lead to the NULL pointer check in dynamic_cast
([example](https://github.com/gcc-mirror/gcc/blob/29a1af24eface3620e348be9429e7c2e872accbc/libstdc%2B%2B-v3/libsupc%2B%2B/dyncast.cc#L50-L51))
being eliminated and we end up with a runtime crash.
Fixes #2944

Fix undefined behavior in GlobalCopyPropagation pass

---

frontends/p4/fromv1.0/converters.h
ir/ir.def
midend/global_copyprop.cpp
testdata/p4_14_samples_outputs/parser_pragma-first.p4
testdata/p4_14_samples_outputs/parser_pragma-frontend.p4
testdata/p4_14_samples_outputs/parser_pragma-midend.p4
testdata/p4_14_samples_outputs/parser_pragma.p4
testdata/p4_14_samples_outputs/parser_pragma2-first.p4
testdata/p4_14_samples_outputs/parser_pragma2-frontend.p4
testdata/p4_14_samples_outputs/parser_pragma2-midend.p4
testdata/p4_14_samples_outputs/parser_pragma2.p4

A rarely used code path inside the p4-14 to p4-16 conversion was inserting parser states in the local variables instead of the states array. This is the real fix to the problem reported in #2942.

Pragma fix

---

backends/dpdk/dpdkArch.cpp
testdata/p4_16_samples/psa-dpdk-table-key-isValid7.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7-first.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7-frontend.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7-midend.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7.p4
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7.p4-error
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7.p4.bfrt.json
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7.p4.p4info.txt
testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7.p4.spec

DPDK assembly does not have a syntax for having isValid() as a table key. This expression should be moved to metadata and the metadata should be used as table key.
This PR fixes a case where all the table keys are isValid() method calls and the isValid() expression is not moved to metadata.
- Added a new test and reference outputs for this case.

DPDK Backend: Fix a corner case in handling isValid() as table key

---

backends/dpdk/CMakeLists.txt
backends/dpdk/backend.cpp
backends/dpdk/dpdkArch.cpp
backends/dpdk/dpdkArch.h
backends/dpdk/dpdkCheckExternInvocation.h
backends/dpdk/dpdkHelpers.cpp
backends/dpdk/dpdkHelpers.h
backends/dpdk/dpdkProgram.cpp
midend/CMakeLists.txt
midend/checkExternInvocationCommon.h
testdata/p4_16_samples_outputs/pna-add-on-miss.p4.spec
testdata/p4_16_samples_outputs/pna-example-template.p4.spec

send_to_port() extern for PNA architecture has been added recently, but instructions were not generated properly.
This commit fixes the generated instructions.
Metadata field used as operand for 'tx' instruction is added to the main metadata structure.
The name of the field set when send_to_port extern is used is unified with the name of the field used as operand for 'tx' instruction.

dpdk: support of PNA extern send_to_port

---

midend/parserUnroll.h
testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test1-midend.p4
testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test2-midend.p4
testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test3-midend.p4

Example test: all of parserUnroll tests or issue692-bmv2.p4.
Solves problems related to incorrect generation of verify functions and creation of OutOfBound state

Fix problems with OutOfBound state creation

---

midend/interpreter.cpp
midend/interpreter.h
test/gtest/parser_unroll.cpp

Solving "Null element" errors  which are related with HeaderUnion type.
Tests for example : issue561-7-bmv2.p4 , issue561-4-bmv2.p4,  issue561-5-bmv2.p4,  issue561-6-bmv2.p4.
Use `--loopsUnroll` argument for programs starting

"Null element" errors which are related with HeaderUnion type

---

README.md

The official designation seems to be `SWX`: https://doc.dpdk.org/guides/prog_guide/packet_framework.html#the-software-switch-swx-pipeline

Fix DPDK SWX typo in README

---

backends/dpdk/dpdkArch.cpp
backends/dpdk/dpdkArch.h
frontends/p4/sideEffects.cpp
frontends/p4/sideEffects.h
testdata/p4_16_samples/issue2900.p4
testdata/p4_16_samples_outputs/issue2900-first.p4
testdata/p4_16_samples_outputs/issue2900-frontend.p4
testdata/p4_16_samples_outputs/issue2900-midend.p4
testdata/p4_16_samples_outputs/issue2900.p4

Fixes #2900 
Bug in file def_use in method setDefinitionsAt class AllDefinitions
In that method definition in map atPoint is overridden
This happens beacuse there is more than one AsssignStatement with the same id
Pass KeySideEffect is creating those AssignStatements (in method KeySideEffect::doStatement)
This method creates a BlockStatement and inserts AssignStatements from TableInsertions variable and then inserts that block before tbl.apply()
Bug is removed by cloning an AssignStatement before inserting it in a BlockStatement
Backend pass CopyMatchKeysToSingleStruct inherits KeySideEffect
Backend uses this pass to transform tables such that all the Match keys are part of the same header/metadata struct
With cloning two test fail (psa-dpdk-table-key-consolidation-if*) in spec file
This …

Compiler Bug : overwriting definitions in defuse (#2900)

---

frontends/p4/simplifyDefUse.cpp
testdata/p4_16_samples/issue2958.p4
testdata/p4_16_samples_outputs/issue2958-first.p4
testdata/p4_16_samples_outputs/issue2958-frontend.p4
testdata/p4_16_samples_outputs/issue2958-midend.p4
testdata/p4_16_samples_outputs/issue2958.p4

Add temporary IR nodes to typeMap

---

midend/global_copyprop.cpp
midend/global_copyprop.h
testdata/p4_16_samples/issue2956.p4
testdata/p4_16_samples_outputs/issue2956-first.p4
testdata/p4_16_samples_outputs/issue2956-frontend.p4
testdata/p4_16_samples_outputs/issue2956-midend.p4
testdata/p4_16_samples_outputs/issue2956.p4

Fixes issue #2956 
* Added preorder of switch statement for FindVariableValue pass
* There is no need for these in DoGlobalCopyPropagation because this pass operates on action bodies only and  switch statements aren't allowed within an action

GlobalCopyPropagation is too agressive in switch statements (#2956)

---

ir/visitor.cpp
ir/visitor.h

- add a way of registering backtrack exceptions to ensure that they are
scanned as gc roots

Backtrack::trigger::register_for_gc

---

midend/flattenHeaders.cpp
midend/flattenHeaders.h
midend/flattenInterfaceStructs.cpp
midend/flattenInterfaceStructs.h
testdata/p4_16_samples/issue2982.p4
testdata/p4_16_samples_outputs/issue2982-first.p4
testdata/p4_16_samples_outputs/issue2982-frontend.p4
testdata/p4_16_samples_outputs/issue2982-midend.p4
testdata/p4_16_samples_outputs/issue2982.p4
testdata/p4_16_samples_outputs/issue383-bmv2-first.p4
testdata/p4_16_samples_outputs/issue383-bmv2-frontend.p4
testdata/p4_16_samples_outputs/issue383-bmv2-midend.p4
testdata/p4_16_samples_outputs/issue383-bmv2.p4

Fixes #2982
There were essentially 2 copies of the class StructTypeReplacement with minor variations, used by two separate passes: flattenInterfaceStructs, and flattenHeaders. These two classes have been unified into a templated class that is reused by both passes.

Handle nested headers correctly when flattening

---

frontends/p4/simplifyDefUse.cpp
testdata/p4_16_samples/wrong-warning.p4
testdata/p4_16_samples_outputs/invalid-hdr-warnings5.p4-stderr
testdata/p4_16_samples_outputs/invalid-hdr-warnings6.p4-stderr
testdata/p4_16_samples_outputs/wrong-warning-first.p4
testdata/p4_16_samples_outputs/wrong-warning-frontend.p4
testdata/p4_16_samples_outputs/wrong-warning-midend.p4
testdata/p4_16_samples_outputs/wrong-warning.p4
testdata/p4_16_samples_outputs/wrong-warning.p4-stderr
testdata/p4_16_samples_outputs/wrong-warning.p4.p4info.txt

Fixed wrong warning for header unions and header union stacks. (#2229)
There was a warning that a header union is not initialized if only one member of the union is initialized.
Unlike other StructLike types header unions are initialized when only one member of the union is initialized, so the warning was not correct.
Initialization checking in method FindUninitialized::registerUses() was looking at all members at the same time, and if one of them was uninitialized, it returned the warning. This is now modified so that if a header union is detected, it checks all members separately, and if at least one of them is initialized it doesn't return the warning. If it is a header union stack it does the same as above, but for each element of the stack.

Fixed wrong warning for header union and header union stack

---

backends/bmv2/psa_switch/psaSwitch.h

This patch adds a missing new line between two error messages.
Before:
```
error: Package package PSA_Switch has no parameter named 'ingress'Are you using an up-to-date 'psa.p4'?
```
After:
```
error: Package package PSA_Switch has no parameter named 'ingress'
Are you using an up-to-date 'psa.p4'?
```

psa: Add missing new line in error message

---

backends/bmv2/common/lower.cpp
testdata/p4_16_samples_outputs/psa-basic-counter-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-e2e-cloning-basic-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-i2e-cloning-basic-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-multicast-basic-2-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-multicast-basic-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-multicast-basic-corrected-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-register-complex-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-register-read-write-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-resubmit-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-unicast-or-drop-bmv2.p4.spec
testdata/p4_16_samples_outputs/psa-unicast-or-drop-corrected-bmv2.p4.spec

* dpdk: explictly discard upper bits when downcasting
Explicitly discard extra bits by creating a temporary
and masking with correct bit width

dpdk: explictly discard upper bits when downcasting

---

frontends/p4/simplifyDefUse.cpp
testdata/p4_16_samples/issue2957.p4
testdata/p4_16_samples_outputs/invalid-hdr-warnings4-frontend.p4
testdata/p4_16_samples_outputs/invalid-hdr-warnings4-midend.p4
testdata/p4_16_samples_outputs/issue2957-first.p4
testdata/p4_16_samples_outputs/issue2957-frontend.p4
testdata/p4_16_samples_outputs/issue2957-midend.p4
testdata/p4_16_samples_outputs/issue2957.p4
testdata/p4_16_samples_outputs/issue2957.p4-stderr

Bug #2957  
Discussion in PR #3004 
- For member expression added write for next/last as a read/write to the whole stack
- Added test for example issue2957.p4
- Changed test output for invalid-hdr-warnings4.p4
Besides writing pkt.extract(hdr.k1.next) is also reading a whole stack, so assignments hdr.h1[0].data = 32w1; hdr.h1[1].data = 32w1; (preceding) are saved.
They won't be deleted because they are preserved by pkt.extract(hdr.k1.next) and this ProgramPoint is always saved in hasUses, because it has a side effect.

 SimplifyDefUse does not respect method calls in stack indices in parsers #2957 

---

lib/alloc.h

This changes `Alloc{1,2}Dbase` to be a non-owning view into one- or two-dimensional array, and `AllocXD` to hold the actual data inline instead of owning it through `AllocXDbase` class (which stores elements in manually managed heap-allocated memory).
The change improves mainly performance of the class, it also simplifies the class a bit as a bonus.

Inline Alloc{1,2}D storage

---

backends/dpdk/DpdkXfail.cmake
backends/dpdk/dpdkArch.cpp
backends/dpdk/dpdkArch.h
testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4-error
testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4.bfrt.json
testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4.spec

When the condition in if statement is a logical operation with complex common subexpression, the expression is evaluated only once and it results in incorrect intermediate program.
For example:
`if (((bit<8>)(hdr.ethernet.dstAddr >> 8) >> 1) && ((bit<8>)(hdr.ethernet.dstAddr >> 8) <= 3))`
In this, the logical expression unroller, generates
```
tmp = h.ethernet.dstAddr >> 8;
tmp_0 = (bit<8>)tmp;
if (tmp_0 >= 8w1 && tmp_0 >= 8w1 <= 8w3)
```
This PR attempts to fix this issue by evaluating the complex expression for its every occurrence.

DPDK Backend: Fixing a regression failure 'not defined on bool and bit<'

---

frontends/p4/strengthReduction.h

For StrengthReduction, do not type check if no type map is provided. This is similar to how [constantFolding](https://github.com/p4lang/p4c/blob/main/frontends/common/constantFolding.h#L161) works. This allows the use of StrenghtReduction on fully-typed IR expressions without needing to initialize a dummy type and ref map beforehand. This can be useful when one wants to optimize automatically generated IR expressions.

Allow nullptr refmap and typemap in StrenghtReduction.

---

control-plane/p4RuntimeArchHandler.h
frontends/p4/evaluator/evaluator.cpp
testdata/p4_16_samples/issue2844-enum.p4
testdata/p4_16_samples_outputs/issue2844-enum-first.p4
testdata/p4_16_samples_outputs/issue2844-enum-frontend.p4
testdata/p4_16_samples_outputs/issue2844-enum-midend.p4
testdata/p4_16_samples_outputs/issue2844-enum.p4
testdata/p4_16_samples_outputs/issue2844-enum.p4.p4info.txt

Adds evaluation for Serializable Enums as compile-time known values. Fixes case 1 of issue #2844.
> Using a serializable enum for an extern parameter during invocation,
> ```
> enum bit<32> sizes {
>      COUNTER_SIZE = 1024
> }
> 
> control C1(inout bit<16> x) {
>      counter(sizes.COUNTER_SIZE, CounterType.packets) stats;
> }
> ```
> In above, counter extern parameter size needs to be a constant which should be the case for a serializable enum.
After fixing this, there was a new issue with generating p4info files. This was fixed by adding SerEnum support for Counters in p4runtime.

Added evaluation for SerEnums. Added p4runtime info SerEnum support for counters.

---

backends/dpdk/README.md
backends/dpdk/backend.cpp
backends/dpdk/dpdkHelpers.cpp
backends/dpdk/dpdkHelpers.h
backends/dpdk/dpdkProgram.cpp
testdata/p4_16_samples_outputs/pna-example-dpdk-varbit.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-varbit-bmv2.p4.spec

DPDK target expects the size of varbit field for extract instruction
in bytes, but compiler was using the same value as in the P4 source
code which is a size in bits.
This commit adds the instructions to make a computation of the size
in bytes instead of bits.

dpdk: use varbit field size for extract in bytes instead of bits

---

backends/dpdk/DpdkXfail.cmake
backends/dpdk/dpdkProgram.cpp

IR::ID has 2 names, current name (class member 'name') and original
name which should refer to the name originally used in the P4 source
code (class member 'originalName').
Different ways of getting textual representation of the name as
cstring leads to different results.
Some ways return the current name while other ways return the original
name.
Mixing these can lead to problems as it happened also in this case.
This commit makes the use of the names consistent in the method
where the bug occurred.

dpdk: fix unsupported parser loop bug

---

.github/workflows/ci-container-image.yml

Other p4lang Docker images are now updated periodically. We do the same
thing for p4c to pick up updates to the base images even when the p4c
repo itself is not updated.
We update the image every 4 hours. To avoid using using too much compute
in Github actions, we update the workflow definition to 1) use native
Docker actions and 2) leverage the Github actions cache. When the base
image (p4lang/behavioral-model) has not been updated and there are no
changes to the p4c code, the workflow will complete in less than a
minute.

Update the p4c Docker image periodically

---

frontends/common/copySrcInfo.h
midend/local_copyprop.cpp
midend/local_copyprop.h
testdata/p4_16_samples_outputs/gauntlet_side_effects_in_mux-bmv2-midend.p4
testdata/p4_16_samples_outputs/psa-switch-expression-without-default.p4-error
testdata/p4_16_samples_outputs/psa-switch-expression-without-default.p4-stderr

Fixes #2678 
This has been cherry-picked from https://github.com/mbudiu-vmw/p4c-clone/commit/d22c2a2
This should only influence error messages give to users.

When doing copyprop use original source position

---

docs/README.md

This pull request adds an example of how to run a single test case in `docs/README.md`.

docs: add example for running a single test case

---

frontends/p4/typeChecking/typeChecker.cpp

During TypeInference some constants can be folded, but in some cases the new expressions (representing the new folded constant) did not have their type set in the TypeMap - this fixes that.

Fixed missing types for folded constants

---

midend/interpreter.cpp

This PR is a much simpler version of https://github.com/p4lang/p4c/pull/2915/files.
@vladyslav-dubina : if there is a test case where the compiler crashes with these changes please post it as a comment.

Proper constant folding in the abstract interpreter

---

backends/dpdk/control-plane/bfruntime_arch_handler.h
backends/dpdk/dpdkContext.h
backends/dpdk/main.cpp
control-plane/p4RuntimeArchStandard.cpp
control-plane/p4RuntimeArchStandard.h
control-plane/p4RuntimeSerializer.cpp

This PR adds support for generating runtime files (P4info, bfRT json and context json ) for PNA architecture.
Since PNA derives from most of the externs from PSA, currently the PSA arch handler is used for PNA as well.

DPDK Backend: Add initial support for generating runtime files for PNA architecture

---

backends/dpdk/dpdkHelpers.cpp
testdata/p4_16_samples/psa-dpdk-errorcode-2.p4
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2-first.p4
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2-frontend.p4
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2-midend.p4
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4-error
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4-stderr
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4.bfrt.json
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4.p4info.txt
testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4.spec

This PR fixes an issue with the order in which the labels and jumps were generated for GEQ and LEQ operations. 
Since dpdk does have a conditional jump for GEQ and LEQ, we negate the condition. However, the true and false blocks were not swapped which was leading to unreachable code.

DPDK Backend: Fix a bug in handling GEQ and LEQ operations

---

tools/driver/p4c_src/driver.py

The compiler now creates empty output folder (foo.tofino), when run with -E (preprocessor only) option.
This makes sure no output folder is created in such a case.

Don't create output folder when -E is used.

---

frontends/parsers/p4/p4parser.ypp
frontends/parsers/v1/v1parser.ypp
tools/ir-generator/ir-generator.ypp

This pull request fixes the following warnings:
```
ir-generator.ypp:95.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
95 | %error-verbose
| ^~~~~~~~~~~~~~
| %define parse.error verbose
```
```
parsers/p4/p4parser.ypp:24.1-36: warning: deprecated directive: ‘%define parser_class_name {P4Parser}’, use ‘%define api.parser.class {P4Parser}’ [-Wdeprecated]
24 | %define parser_class_name {P4Parser}
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| %define api.parser.class {P4Parser}
```
```
parsers/v1/v1parser.ypp:24.1-36: warning: deprecated directive: ‘%define parser_class_name {V1Parser}’, use ‘%define api.parser.class {V1Parser}’ [-Wdeprecated]
24 | %define parser_class_name {V1Parser}
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| %define …
```

ir: fix deprecated directive warnings

---

lib/ordered_set.h

Accept const qualified ref for 2nd argument in ordered_set
* In ordered_set operator overloads like |=, &=, -= should accept
2nd argument as const ref, it would then accept lvalue as well as rvalue as a argument.

Fixes #3071

---

CMakeLists.txt
tools/ci-build.sh
tools/install_mac_deps.sh

* use same Scapy version as PTF (2.4.5)
* set Boost_USE_STATIC_RUNTIME when looking for Boost libraries with cmake

Build improvements

---

.github/workflows/ci-validation.yml
tools/ci-build.sh

This pull request migrates the P4C validation tests that use Gauntlet away from pytest to CMake. This change also removes a couple unnecessary dependencies and simplifies the build process. Gauntlet is now a simple P4C back end and does not require any additional dependencies other than `boost-filesystem`.

Migrate validation tests to CMake

---

frontends/p4/unusedDeclarations.cpp

Solves `verify: declaration not found` error when p4include  within the path
This pull request addresses the problem when the path is not at the beginning.
For example launch `parser-unroll-test2.p4` test  with `-I ./p4include` argument

Solution when p4include may be within the path

---

.github/workflows/ci-test.yml
README.md
tools/install_fedora_deps.sh

As a follow up on the discussion in https://github.com/p4lang/p4c/pull/3076, this pull request extends the CI to run P4C tests with Fedora in addition to Ubuntu.

Run CI tests with Fedora

---

frontends/p4/fromv1.0/converters.cpp
frontends/p4/fromv1.0/converters.h

This exposes the visitor so it can be used elsewhere.

Moved FindRecirculated from .cpp to .h

---

backends/dpdk/DpdkXfail.cmake
backends/dpdk/backend.cpp
backends/dpdk/dpdkArch.cpp
backends/dpdk/dpdkArch.h
testdata/p4_16_samples/pna-dpdk-parser-state-err.p4
testdata/p4_16_samples/pna-mux-dismantle.p4
testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err-first.p4
testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err-frontend.p4
testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err-midend.p4
testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4
testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4-stderr
testdata/p4_16_samples_outputs/pna-mux-dismantle-first.p4
testdata/p4_16_samples_outputs/pna-mux-dismantle-frontend.p4
testdata/p4_16_samples_outputs/pna-mux-dismantle-midend.p4
testdata/p4_16_samples_outputs/pna-mux-dismantle.p4
testdata/p4_16_samples_outputs/pna-mux-dismantle.p4-error
testdata/p4_16_samples_outputs/pna-mux-dismantle.p4-stderr
testdata/p4_16_samples_outputs/pna-mux-dismantle.p4.spec

LowerExpressions pass which introduces ternary operator (?:) which is not supported in DPDK. 
This PR dismantle ternary operator to if else chain.

Dismantle Mux expression / Ternary operator in dpdk

---

frontends/common/constantFolding.cpp

Constant folding was missing some type information for bool literals, which are added with this pull request. Please let me know if I am missing some more. 
I am aware that there is no guarantee for these passes to preserve type information. However, ConstantFolding and StrengthReduction are also useful in isolation. This is because they can be applied to any well-typed IR::Expression construct to simplify it.

Preserve type information in constant folding

---

frontends/common/constantFolding.cpp
frontends/p4/typeChecking/typeChecker.cpp
frontends/parsers/p4/p4parser.ypp
testdata/p4_16_samples/issue3091-1.p4
testdata/p4_16_samples/issue3091.p4
testdata/p4_16_samples_outputs/issue3091-1-first.p4
testdata/p4_16_samples_outputs/issue3091-1-frontend.p4
testdata/p4_16_samples_outputs/issue3091-1.p4
testdata/p4_16_samples_outputs/issue3091-1.p4-stderr
testdata/p4_16_samples_outputs/issue3091-first.p4
testdata/p4_16_samples_outputs/issue3091-frontend.p4
testdata/p4_16_samples_outputs/issue3091-midend.p4
testdata/p4_16_samples_outputs/issue3091.p4
testdata/p4_16_samples_outputs/issue3091.p4.p4info.txt

Treat match_kind as a regular type

---

testdata/p4_16_errors/structure-valued-expr-errs-1.p4
testdata/p4_16_errors/structure-valued-expr-errs-2.p4
testdata/p4_16_errors_outputs/structure-valued-expr-errs-1.p4
testdata/p4_16_errors_outputs/structure-valued-expr-errs-1.p4-stderr
testdata/p4_16_errors_outputs/structure-valued-expr-errs-2.p4-stderr
testdata/p4_16_samples/structure-valued-expr-ok-1-bmv2.p4
testdata/p4_16_samples_outputs/structure-valued-expr-ok-1-bmv2-first.p4
testdata/p4_16_samples_outputs/structure-valued-expr-ok-1-bmv2-frontend.p4
testdata/p4_16_samples_outputs/structure-valued-expr-ok-1-bmv2-midend.p4
testdata/p4_16_samples_outputs/structure-valued-expr-ok-1-bmv2.p4
testdata/p4_16_samples_outputs/structure-valued-expr-ok-1-bmv2.p4.p4info.txt

I did not find any behavior that I would consider a bug in writing these tests, but I also did not see any existing tests that exercise some of these compile-time error catching cases in the p4_16_errors_outputs directory, so it seems they are not exercised by any existing test cases before these.

Add correct and error test cases for structure-values expressions

---

backends/ebpf/ebpfBackend.cpp
backends/ebpf/ebpfControl.cpp
backends/ebpf/ebpfOptions.cpp
backends/ebpf/ebpfOptions.h
backends/ebpf/ebpfParser.cpp
backends/ebpf/ebpfProgram.cpp
backends/ebpf/ebpfTable.cpp
backends/ebpf/target.cpp
backends/ebpf/target.h

This PR adds `--trace` flag to the p4c-ebpf compiler. With the option enabled, p4c-ebpf compiler will generate additional debug logs that will be printed by eBPF program during packet processing. These logs might be helpful when debugging compiler, P4 programs or some tools. This option should only be used for troubleshooting as it decreases performance.
With this option disabled (which is by default) performance should not be affected because debug messages are not emitted into C code.
To see debug messages from program read from /sys/kernel/debug/tracing/trace_pipe file or use `bpftool prog tracelog`.

Add debug messages for generated eBPF programs

---

backends/dpdk/DpdkXfail.cmake
control-plane/bfruntime.cpp

Fix regression failure like "Error when generating BF-RT info for 'Digest' .*: packed type is too complex"
for types like 
type PortIdUint_t PortId_t;

Handle bfrt Info for new type

---

ir/ir-inline.h
ir/node.h
ir/visitor.cpp
ir/visitor.h

- by default will BUG("IR loop detected") (the old behavior), but allows
writing visitor passes that can override and deal with it.
This is an experimental infrastructure extension that is most useful with the ResolutionContext/apply with context param stuff added awhile back -- using that code, a visitor can look up symbols and recursively visit the definition of the symbol, but doing so may lead to loops in the traversal.  This change allows dealing with those resulting loops rather than just exiting with a BUG (though that is still the default behavior) by overriding the loop_revisit method in the Visitor subclass.

loop_revisit method for dealing with recursive loops in the IR

---

ir/visitor.cpp
ir/visitor.h

Minor cleanup making SetupJoinPoints a protected class that can be subclassed by a subclass of ControlFlowVisitor, and make the join point filtering cleaner/faster by using revisit method instead of the preorder.

Refactor SetupJoinPoints to make it more extensible

---

ir/node.h

This way one can immediately see the actual type of the node.

Print the current node type name when checkedTo fails

---

frontends/p4/fromv1.0/programStructure.cpp
testdata/p4_14_samples/register_signed.p4
testdata/p4_14_samples_outputs/register_signed-first.p4
testdata/p4_14_samples_outputs/register_signed-frontend.p4
testdata/p4_14_samples_outputs/register_signed-midend.p4
testdata/p4_14_samples_outputs/register_signed.p4

Signed p4_14 Register is currently incorrectly translated into unsigned p4_16 Register due to missing signedness handling.

from1.0: fix signed register type

---

backends/ebpf/ebpfProgram.cpp
backends/ebpf/runtime/ebpf_kernel.h
backends/ebpf/runtime/kernel.mk
backends/ebpf/target.cpp
backends/ebpf/target.h
backends/ubpf/target.cpp
backends/ubpf/target.h

This PR extends the eBPF kernel target with:
- support for defining other BPF map types
- support for BPF map-in-maps
- support for BPF maps using BPF spinlocks
- method to generate packet descriptor type (e.g. `__sk_buff`) depending on the eBPF hook type. It's required to support mixed deployments leveraging both TC and XDP programs.
- method to generate packet buffer's size adjustment
- BTF annotation of BPF maps, so that BPF types can be read at runtime
This PR is one from the series of PRs bringing the support for the PSA model to eBPF backend. The goal is to shrink the "main PR" with the full implementation of PSA for eBPF to facilitate review.

Extend eBPF kernel target with support for additional BPF helpers and more types of BPF maps

---

backends/ebpf/ebpfControl.cpp
backends/ebpf/ebpfTable.cpp
backends/ebpf/ebpfTable.h
backends/ebpf/targets/ebpfstf.py

This PR changes the way of handling `NoAction` in eBPF tables. With this change, `NoAction` will always be allocated with actionID = 0 regardless of its position in the action list. User-defined actions are enumerated starting from index=1. 
Additionally, this PR introduces modifications to the format of the ActionIDs list. We get rid of `enum` to store action IDs and implement new naming format: `<TABLE_NAME>_ACT_<ACTION_NAME>`. 
Also, this PR refactors eBPF table implementation, so that it's easier to inherit from the base eBPF table. 
This PR is one from the series of PRs bringing the support for the PSA model to eBPF backend. The goal is to shrink the "main PR" with the full implementation of PSA for eBPF to facilitate review.
Co-authored-by: Mateusz Kossakowski …

Use 0 as action ID for NoAction and refactor eBPF table implementation

---

backends/dpdk/DpdkXfail.cmake
midend/interpreter.cpp
testdata/p4_16_samples/verify_disjunction.p4
testdata/p4_16_samples_outputs/verify_disjunction-first.p4
testdata/p4_16_samples_outputs/verify_disjunction-frontend.p4
testdata/p4_16_samples_outputs/verify_disjunction-midend.p4
testdata/p4_16_samples_outputs/verify_disjunction.p4
testdata/p4_16_samples_outputs/verify_disjunction.p4.p4info.txt

Added a simple test verify_disjunction.p4 to show the need for this change, we can run this test with `--loopsUnroll` argument
Changes solve the `Non Type_Bits type bool for expression` error.
Since there are cases when the `expression ` in the `setNonConstant ` function is of type `Type_Boolean`. This is mainly possible with multiple `or` in the condition.

Solution for "Non Type_Bits type bool for expression" error

---

backends/ebpf/codeGen.cpp
backends/ebpf/codeGen.h
backends/ebpf/ebpfControl.cpp

This PR enables emitting eBPF fields as pointer variables by eBPF `CodeGenInspector`. So far,  `CodeGenInspector` assumes that eBPF fields (e.g. `Headers`) are on-stack variables. With this change, we can decide whether to access fields' member via `.` or `->`. 
A use case for this change is PSA implementation for eBPF backend. PSA-eBPF uses BPF array map to store the `Headers` structure, instead of an on-stack variable, to avoid BPF stack size limit, see the discussion here https://github.com/vmware/p4c-xdp/issues/43. Using BPF array map to store large piece of data (parsed headers) is a common approach used also by Cilium/Calico eBPF datapaths. We've observed almost no impact on performance when using BPF array map.
Note that `ebpf_model.p4` is not affected by this change, because …

Enable generation of pointer variables by eBPF CodeGenInspector

---

midend/interpreter.cpp

This is the correct fix of the problem described in #3127. There isn't an attached test, but the problem fixed can be reproduced by invoking `./p4test --loopsUnroll ../testdata/p4_16_samples/default.p4`, which causes the compiler to crash.

Type of a unary expression is not always the same as the input type

---

lib/stringref.h

We encountered a c++ compilation issue when using p4c together with inja (https://github.com/pantor/inja) in one project. Inja headers define:
```
template <class CharT, class Traits nssv_MSVC_ORDER(1)>
nssv_constexpr bool operator==(basic_string_view<CharT, Traits> lhs,
nssv_BASIC_STRING_VIEW_I(CharT, Traits) rhs) nssv_noexcept {
```
which is supposed to be called when `basic_string_view<>` is compared to `const char*`. But if p4c sources are also included, such call is ambiguous, because `operator==(T, StringRef)` also participates in overload resolution:
```
inja/include/inja/parser.hpp:207:31: error: ambiguous overload for ‘operator==’ (operand types are ‘nonstd::sv_lite::string_view {aka nonstd::sv_lite::basic_string_view<char>}’ and ‘const char [3]’)
} else if (tok.text == "in") { …
```

sfinae-protect operator== StringRef overload

---

backends/ebpf/CMakeLists.txt
backends/ebpf/ebpfControl.h
backends/ebpf/ebpfDeparser.cpp
backends/ebpf/ebpfDeparser.h

This PR introduces a common, re-usable implementation of EBPF Deparser that can be used by different architecture models. The implementation is based on https://github.com/vmware/p4c-xdp. 
Since `ebpf_model.p4` doesn't define a deparser block, this PR doesn't affect its code. The main use case is PSA implementation for eBPF backend. It would be good to leverage the common deparser implementation in p4c-xdp at some point.
This PR is one from the series of PRs bringing the support for the PSA model to eBPF backend. The goal is to shrink the "main PR" with the full implementation of PSA for eBPF to facilitate review.
CC: @kmateuszssak @tatry

Implement EBPF deparser

---

bazel/p4_library.bzl

There's no reason I'm aware of to compile the compilers for the target architecture.
As a side benefit, this may improve the build system's cache hit rate slightly because these tools don't need to be recompiled for Tsan/Asan/Msan/etc let alone x86 vs. ARM vs. etc.
Signed-off-by: Chris Dolan <chrisdolan@google.com>

Compile the P4 compiler tools in host configuration

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_errors_outputs/issue561-1.p4-stderr

Same error message was used for all struct-like types:
* IR::Type_UnknownStruct
* IR::Type_Struct
* IR::Type_Header
* IR::Type_HeaderUnion
In case of a header or header_union it could result in a message
like this:
"""
Field my_field is not a member of structure header my_header_h
"""
which might have been confusing for a user (why is error message
mentioning structure and header at one place?).
The word "structure" is now omitted in case of IR::Type_Header
and IR::Type_HeaderUnion.
String representation of IR::Type_Header and IR::Type_HeaderUnion
nodes used in this error message already contains also header or
header_union keyword.

typeChecker: make error message less confusing

---

backends/dpdk/dpdkHelpers.cpp
testdata/p4_16_samples_outputs/pna-add-on-miss.p4.spec
testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4.spec
testdata/p4_16_samples_outputs/pna-mux-dismantle.p4.spec

This is a simple fix to move constant arguments for learn instruction to metadata. This is because DPDK target expects the operand to be in metadata.

DPDK Backend: Move learn instructions constant argument to metadata

---

backends/ebpf/ebpfDeparser.cpp
backends/ebpf/ebpfParser.h

The PR fixes the format of trace messages in EBPF deparser. The header name in the trace message was not substituted to the right value, if eBPF code uses pointer to access headers. Also, adds missing semicolon in EBPF Parser

Fix format of trace messages in EBPF deparser

---

backends/ebpf/codeGen.cpp
midend/interpreter.cpp

Fixes errors that appear in p4c-xdp tests.

Handle struct expression in ebfp backend

---

backends/ebpf/CMakeLists.txt
backends/ebpf/psa/ebpfPsaControl.cpp
backends/ebpf/psa/ebpfPsaControl.h
backends/ebpf/psa/ebpfPsaGen.cpp
backends/ebpf/psa/ebpfPsaGen.h
backends/ebpf/psa/ebpfPsaTable.cpp
backends/ebpf/psa/ebpfPsaTable.h
backends/ebpf/psa/externs/ebpfPsaCounter.cpp
backends/ebpf/psa/externs/ebpfPsaCounter.h
backends/ebpf/runtime/kernel.mk
backends/ebpf/target.cpp
backends/ebpf/tests/p4testdata/counters.p4
backends/ebpf/tests/ptf/common.py
backends/ebpf/tests/ptf/test.py

This PR adds the support for indirect Counter extern to PSA/eBPF backend.
We currently implement Counter as a BPF array map, so the index width must be less or equal to `bit<32>`. We're planning to use BPF hash maps for Counters with wider index type.
Similarly to `ebpf_model`, the PSA Counter implementation uses `__sync_fetch_and_add` to provide atomicity.
Co-authored-by: Mateusz Kossakowski <mateusz.kossakowski@orange.com>

Add support for Counter extern to PSA/eBPF backend

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_errors/issue3170.p4
testdata/p4_16_errors_outputs/issue3170.p4
testdata/p4_16_errors_outputs/issue3170.p4-stderr

typedef with generic types requires type arguments

---

backends/ebpf/CMakeLists.txt
backends/ebpf/ebpfObject.h
backends/ebpf/psa/ebpfPsaDeparser.cpp
backends/ebpf/psa/ebpfPsaDeparser.h
backends/ebpf/psa/ebpfPsaGen.cpp
backends/ebpf/psa/ebpfPsaParser.cpp
backends/ebpf/psa/ebpfPsaParser.h
backends/ebpf/psa/externs/ebpfPsaChecksum.cpp
backends/ebpf/psa/externs/ebpfPsaChecksum.h
backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.h
backends/ebpf/tests/p4testdata/checksum-updates-crc16.p4
backends/ebpf/tests/p4testdata/checksum-updates-crc32.p4
backends/ebpf/tests/ptf/checksum.py

This PR adds Checksum extern and adds support for CRC16 and CRC32 algorithms.

Add support for Checksum extern and CRC16/32 algorithms to eBPF backend

---

frontends/common/constantFolding.cpp
frontends/p4/commonInlining.h
frontends/p4/enumInstance.cpp
testdata/p4_14_samples_outputs/copy_to_cpu-first.p4
testdata/p4_14_samples_outputs/copy_to_cpu-frontend.p4
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2-first.p4
testdata/p4_14_samples_outputs/p414-special-ops-2-bmv2-frontend.p4
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2-first.p4
testdata/p4_14_samples_outputs/p414-special-ops-3-bmv2-frontend.p4
testdata/p4_14_samples_outputs/p414-special-ops-first.p4
testdata/p4_14_samples_outputs/p414-special-ops-frontend.p4
testdata/p4_14_samples_outputs/packet_redirect-first.p4
testdata/p4_14_samples_outputs/packet_redirect-frontend.p4
testdata/p4_14_samples_outputs/resubmit-first.p4
testdata/p4_14_samples_outputs/resubmit-frontend.p4
testdata/p4_14_samples_outputs/simple_nat-first.p4
testdata/p4_14_samples_outputs/simple_nat-frontend.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4
testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4
testdata/p4_16_samples/issue3178.p4
testdata/p4_16_samples_outputs/enumCast-first.p4
testdata/p4_16_samples_outputs/issue3178-first.p4
testdata/p4_16_samples_outputs/issue3178.p4
testdata/p4_16_samples_outputs/issue3178.p4-stderr

Constant fold casts of serializble enums

---

tools/install_fedora_deps.sh

The simple_switch_grpc target has been integrated with the main `autogen.sh` and `configure.ac` files.
https://github.com/p4lang/behavioral-model/pull/1105
Fixes #3189

test: Update install_fedora_deps.sh

---

backends/ebpf/ebpfOptions.cpp
backends/ebpf/ebpfOptions.h
backends/ebpf/p4c-ebpf.cpp
backends/ebpf/psa/README.md
backends/ebpf/psa/ebpfPipeline.cpp
backends/ebpf/psa/ebpfPsaGen.cpp
backends/ebpf/psa/xdpHelpProgram.h
backends/ebpf/tests/ptf/checksum.py
backends/ebpf/tests/ptf/common.py
backends/ebpf/tests/test.sh

This PR makes the XDP2TC mode configurable. The XDP2TC mode determines how the metadata (containing original EtherType) is passed from XDP up to TC. This is needed because we discovered that the default `meta` mode using `bpf_xdp_adjust_meta()` is not supported by some NIC drivers. In such a case, the entire PSA implementation for eBPF does not work. This PR adds two alternative modes: `head` and `cpumap` that can be used to work around the NIC limitations.

Add --xdp2tc compiler flag for eBPF backend

---

BUILD.bazel
backends/dpdk/backend.cpp
backends/dpdk/dbprint-dpdk.cpp
backends/dpdk/dpdk.def
backends/dpdk/dpdkArch.h
backends/dpdk/dpdkAsmOpt.cpp
backends/dpdk/dpdkAsmOpt.h
backends/dpdk/dpdkProgram.cpp
backends/dpdk/dpdkProgram.h
backends/dpdk/run-dpdk-test.py
backends/dpdk/spec.cpp
testdata/p4_16_samples/psa-dpdk-token-too-big.p4
testdata/p4_16_samples_outputs/pna-example-dpdk-varbit.p4.spec
testdata/p4_16_samples_outputs/pna-example-tunnel.p4.spec
testdata/p4_16_samples_outputs/pna-lookahead-structure-bit-field.p4.spec
testdata/p4_16_samples_outputs/pna-lookahead-structure.p4.spec
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big-first.p4
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big-frontend.p4
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big-midend.p4
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big.p4
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big.p4.bfrt.json
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big.p4.p4info.txt
testdata/p4_16_samples_outputs/psa-dpdk-token-too-big.p4.spec
testdata/p4_16_samples_outputs/psa-example-dpdk-varbit-bmv2.p4.spec

to be less than 64 because dpdk does not allow Identifer longer than 63 chars

Shorten the Identifer name, including dots(.) in Member expression

---

backends/ebpf/ebpfDeparser.cpp
backends/ebpf/ebpfObject.h
backends/ebpf/psa/ebpfPsaDeparser.cpp
backends/ebpf/psa/ebpfPsaParser.cpp
backends/ebpf/psa/externs/ebpfPsaChecksum.cpp
backends/ebpf/psa/externs/ebpfPsaChecksum.h
backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.h
backends/ebpf/tests/p4testdata/common_headers.p4
backends/ebpf/tests/p4testdata/internet-checksum.p4
backends/ebpf/tests/ptf/checksum.py

This PR adds InternetChecksum extern.

Add support for InternetChecksum extern to eBPF backend

---

backends/ebpf/ebpfTable.cpp
backends/ebpf/ebpfTable.h
backends/ebpf/psa/ebpfPsaControl.h
backends/ebpf/psa/ebpfPsaGen.cpp
backends/ebpf/psa/ebpfPsaTable.cpp
backends/ebpf/psa/ebpfPsaTable.h
backends/ebpf/psa/externs/ebpfPsaCounter.cpp
backends/ebpf/psa/externs/ebpfPsaCounter.h
backends/ebpf/tests/p4testdata/direct-counters.p4
backends/ebpf/tests/ptf/test.py

This PR adds the support for DirectCounter extern to PSA/eBPF backend.
Co-authored-by: Mateusz Kossakowski <mateusz.kossakowski@orange.com>

Add support for DirectCounter extern to PSA/eBPF backend

---

backends/dpdk/DPDK_context_schema.json
backends/dpdk/dpdkContext.cpp

This PR is to add a new field to context json. This field holds the unique internal name of the actions .This name should be same as the action name in output spec file.
Context json would now contain two fields for the action name, one name is the externalName and should be same as in bfrt json file and another name "target_action_name" should be same as the name in the spec file.
NoAction is handled in special manner to always use the externalName().
Note: Context json files are not part of the repo, hence attaching the patch to show the change. Also attaching bfrt.json and spec file for reference.
[pna-example-tunnel.p4.bfrt.json.txt](https://github.com/p4lang/p4c/files/8478943/pna-example-tunnel.p4.bfrt.json.txt)
[pna-example-tunnel.p4.spec.txt](https://github.com/p4lang/p4c/files/8478 …

DPDK Backend: Minor fix to emit target_action_name in context json

---

frontends/p4/typeChecking/typeChecker.cpp
testdata/p4_16_samples/issue3219.p4
testdata/p4_16_samples_outputs/issue3219-first.p4
testdata/p4_16_samples_outputs/issue3219-frontend.p4
testdata/p4_16_samples_outputs/issue3219-midend.p4
testdata/p4_16_samples_outputs/issue3219.p4
testdata/p4_16_samples_outputs/issue3219.p4-stderr

Allow casts int to int
