p4lang/p4c

backends/bmv2/jsonconverter.cpp
nameFromAnnotation seems to mostly just be a more verbose, less readable way of calling externalName, so this change just makes everything use externalName (including a couple of places it wasn't looking at the @name annotation and should be).
=> use "externalName()" consistently to get the names of things in the json

frontends/p4-14/p4-14-parse.ypp
also allow redundant masking of valid
=> Allow header.valid as alias for valid(header)

testdata/p4_14_samples/switch_20160226/acl.p4, testdata/p4_14_samples/switch_20160226/port.p4, testdata/p4_14_samples/switch_20160512/acl.p4, testdata/p4_14_samples/switch_20160512/port.p4, testdata/p4_14_samples_outputs/switch_20160226/switch-first.p4, testdata/p4_14_samples_outputs/switch_20160226/switch-frontend.p4, testdata/p4_14_samples_outputs/switch_20160226/switch-midend.p4, testdata/p4_14_samples_outputs/switch_20160226/switch.p4, testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4, testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4, testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4, testdata/p4_14_samples_outputs/switch_20160512/switch.p4
This is just a change of the switch profiles.
Evan
=> Changed switch profiles in testdata with temporary name change

.travis.yml, frontends/p4-14/typecheck.cpp, frontends/p4/fromv1.0/programStructure.h, ir/ir.cpp, ir/visitor.h
I went ahead and fixed cpplint's current complaints so we can enable it on Travis.
=> Enable cpplint on Travis

backends/ebpf/ebpfControl.cpp, backends/ebpf/ebpfControl.h, backends/ebpf/ebpfParser.cpp, backends/ebpf/ebpfProgram.cpp, backends/ebpf/target.h, backends/p4test/Makefile.am, frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue242.p4, testdata/p4_16_samples_outputs/issue242-first.p4, testdata/p4_16_samples_outputs/issue242-frontend.p4, testdata/p4_16_samples_outputs/issue242-midend.p4, testdata/p4_16_samples_outputs/issue242.p4
The bulk of the change is EBPF-related.
One class has been made public by moving the declaration to a header; the diff looks much larger than it should.
There is also a reproduction which XFAILs for issue #242.
=> Several improvements

backends/p4test/p4test.cpp, frontends/common/parseInput.cpp, frontends/p4-14/p4-14-parse.ypp, frontends/p4/fromv1.0/converters.cpp, ir/pass_manager.cpp, ir/pass_manager.h, lib/symbitmatrix.h
Trivial change (essentially a typo)
=> fix parsing of default action to allow empty argmuents

frontends/p4/fromv1.0/converters.cpp, frontends/p4/fromv1.0/programStructure.cpp, ir/v1.def, lib/cstring.h
One bug fix and one warning fix
=> Fixes for problems identified by google (issues 34773327, 34872853)

backends/bmv2/bmv2stf.py, testdata/p4_14_samples/counter1.stf, testdata/p4_14_samples/counter2.stf, testdata/p4_14_samples/counter3.stf, testdata/p4_14_samples/counter4.stf
- need these to flag errors for packets showing up where not expected.
=> Add explicit expects for output ports that might be used in stf files

Makefile.am
Turns out I broke make recheck by not understanding how to add extra depedencies properly to automake targets...
=> Fix make recheck

bootstrap.sh
Add libtoolize in bootstrap to get more coverage for aclocal m4 macro search path
=> Fix for issue #262

testdata/p4_16_samples/issue134-bmv2.p4, testdata/p4_16_samples_outputs/issue134-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue134-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue134-bmv2.p4
The #271 pull request has also fixed issue #134; this is a test case to illustrate it.
=> Test for issue #134

control-plane/p4RuntimeSerializer.cpp
=> Fix incorrect error message in p4RuntimeSerializer

control-plane/p4RuntimeSerializer.cpp
This patch adds support for ArrayIndex expressions (i.e., expressions that index into header stacks) in table match keys. This fixes #291.
=> Support header stacks in match keys

control-plane/p4RuntimeSerializer.cpp
This PR adds support for action profiles to the P4Runtime serialization code.
Should be pretty straightforward.
=> Support action profiles in P4RuntimeSerializer

frontends/common/options.cpp
Minor aesthetic clean up for help message.
=> remove redudant -h flag

backends/ebpf/ebpfControl.cpp, frontends/common/options.cpp, lib/error.h, testdata/p4_14_samples_outputs/hash_action_two_same-frontend.p4, testdata/p4_14_samples_outputs/hash_action_two_same-midend.p4, testdata/p4_14_samples_outputs/hash_action_two_same.p4
Unfortunately this uses two minus signs, so it is unlike gcc, but this was simplest to do by treating this as a long option.
=> Added --Werror flag

backends/bmv2/jsonconverter.h, frontends/p4/substitution.cpp, frontends/p4/substitution.h, frontends/p4/typeChecking/bindVariables.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeConstraints.cpp, testdata/p4_16_errors/issue344.p4, testdata/p4_16_errors/issue345.p4, testdata/p4_16_errors_outputs/issue344.p4, testdata/p4_16_errors_outputs/issue344.p4-stderr, testdata/p4_16_errors_outputs/issue345.p4, testdata/p4_16_errors_outputs/issue345.p4-stderr
The PR again contains two unsquashed commits. I wish I knew how to check beforehand which commits will show up...
Anyway, the actual changes are just from two real commits, one for each issue.
The issue code has been very much simplified.
=> Fixes for issues #344 and #345

backends/bmv2/run-bmv2-test.py, backends/ebpf/run-ebpf-sample.py, backends/p4test/run-p4-sample.py
Minor fix, but necessary for unit test to run correctly.
=> fix return code on run-*.py scripts

control-plane/p4RuntimeSerializer.cpp
This PR continues the process of moving p4c to the new P4Info API, which won't include header fields and header field lists.
There's no new functionality here. This PR just deletes code that's related to those concepts. A few new comments are introduced because the subject those comments discuss was originally documented in code that's being deleted.
Lots of code removed. Whew. There's more code that will become removable once we have a better approach to handling match key names, which is in the pipeline.
=> Remove header field and header field list support from p4RuntimeSerializer

backends/bmv2/bmv2stf.py
tail end of the fix. I missed several conversions, and it turns out that tests were succeeding when they shouldn't because the keys in the self.expected were ints, while the search key was string.
=> fixes missing conversions from/to int/str for interfaces

ir/dbprint-stmt.cpp, ir/ir.def, midend/local_copyprop.cpp
A one-line fix and several dozen lines of logging additions needed to find it...
=> fix local_copyprop flow_merge (need_key_rewrite flag)

frontends/p4-14/p4-14-lex.l
This is to allow parsing some P4_14 programs that use `@pragma command_line`
=> Turn random text on @pragma line into STRING_LITERALs

Makefile.am, control-plane/p4RuntimeSerializer.cpp, docs/doxygen/doxygen.cfg
and fixes a few other minor issues
- add license file
- disable PDF/Latex in the config
- add dependencies to build ir/ir-generated.h
=> add control-plane sources and module

tools/ir-generator/ir-generator.ypp, tools/ir-generator/irclass.cpp, tools/ir-generator/irclass.h
- output comment blocks for IR classes inside the namespace IR { ... }
=> fix comment block handling in ir generator

README.md
`README.md` needed some updating; it contained out-of-date information about compiler and platform support. While I was at it, I tried to clean it up and make it a bit easier to follow for new users.
=> Update and clean up README.md

control-plane/p4RuntimeSerializer.cpp
Direct/indirect counters/meters have been factored out into separate
entities.
Needs to be merged at the same time as https://github.com/p4lang/PI/pull/131
=> Update P4Runtime serializer after p4info changes

backends/bmv2/midend.cpp, backends/p4test/midend.cpp, testdata/p4_16_samples/issue512.p4, testdata/p4_16_samples_outputs/issue512-frontend.p4, testdata/p4_16_samples_outputs/issue512-midend.p4, testdata/p4_16_samples_outputs/issue512.p4
Predication creates new local variables, which have to be pushed to the top for the next pass to work correctly.
=> Fix for issue #512

frontends/p4/strengthReduction.cpp, frontends/p4/strengthReduction.h
This commit reviews and adds Doxygen comments for strength reduction.
=> Strength reduction polishing.

frontends/p4/frontend.cpp
This commit reviews and adds Doxygen comments for the (trivial) front-end-last pass.
=> Polish front end last pass.

control-plane/p4RuntimeSerializer.cpp
The code was failing for this P4 program: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/action_selector_shared-bmv2.p4
with the following bug:
```
terminate called after throwing an instance of 'Util::CompilerBug'
what():  COMPILER BUG: ../control-plane/p4RuntimeSerializer.cpp:611
Looking up symbol 'as' without adding it to the table
```
We have to handle these 2 cases:
- when the action profile is directly instantiated in the table declaration (and cannot be shared): we use the name of the implementation property as the action profile control plane name
- when the action profile is instantiated outside and referenced in the table declaration (and can be shared): we use the name of the instantiation and we _ignore_ the name of the implementation property in the table(s) …
=> Fix p4Runtime serializer for shared action profs

frontends/p4/sideEffects.cpp, frontends/p4/sideEffects.h
@mbudiu-vmw: I added several TODO comments with questions that you may know the answer to.  If you think they are useful pointers to things we should address in the future, we can leave them in---if not, I'm happy to remove them.
=> Add/convert Doxygen comments for SideEffects and DoSimplifyExpressions visitors.

frontends/p4-14/p4-14-lex.l, frontends/p4-14/p4-14-parse.ypp
Trivial addition that was missing in the P4_14 frontend.
=> Support for 'bool' type in P4_14

midend/local_copyprop.h
This is a continuation of the fix for #512.
=> Documentation improvements

control-plane/p4RuntimeSerializer.cpp
We generate the names differently based on whether the input is P4_14 or
P4_16. This allows us to:
* be consistent with existing old tools in the P4_14 code
* be more consistent for control plane name generation in P4_16. The
existing behavior was suprising and did not match the language
specification IMO.
=> Generate header field names differently in p4runtime

frontends/p4/simplify.cpp, frontends/p4/simplify.h
There are also a couple minor TODOs that should be addressed.  I'm happy to update this PR with code fixes if the TODO comments make sense.
=> Add Doxygen-style documentation for the SimplifyControlFlow pass.

frontends/p4-14/typecheck.cpp, frontends/p4/fromv1.0/programStructure.cpp, frontends/p4/fromv1.0/programStructure.h, testdata/p4_14_errors/issue583.p4, testdata/p4_14_samples/issue583.p4, testdata/p4_14_samples_outputs/issue583-first.p4, testdata/p4_14_samples_outputs/issue583-frontend.p4, testdata/p4_14_samples_outputs/issue583-midend.p4, testdata/p4_14_samples_outputs/issue583.p4, testdata/p4_14_samples_outputs/issue583.p4-stderr
This pull request has already been reviewed, but I deleted the branch by mistake. There are no code changes with respect to the previous review.
=> For for issue #583

frontends/p4/simplifyDefUse.cpp, testdata/p4_16_samples/issue648.p4, testdata/p4_16_samples/uninit.p4, testdata/p4_16_samples_outputs/issue561.p4-stderr, testdata/p4_16_samples_outputs/issue648-first.p4, testdata/p4_16_samples_outputs/issue648-frontend.p4, testdata/p4_16_samples_outputs/issue648-midend.p4, testdata/p4_16_samples_outputs/issue648.p4, testdata/p4_16_samples_outputs/uninit.p4-stderr
Every method is now just a preorder, makes the code easier to read.
=> Fix for issue #648

ir/v1.def, tools/ir-generator/ir-generator.ypp, tools/ir-generator/irclass.cpp, tools/ir-generator/irclass.h, tools/ir-generator/methods.cpp, tools/ir-generator/type.cpp, tools/ir-generator/type.h
- support for autogenerating methods in nested classes
- support for friend functions
- misc bug fixes
=> IRGen fixes

frontends/parsers/p4/p4parser.ypp, testdata/p4_16_samples/parser-locals2.p4, testdata/p4_16_samples_outputs/parser-locals2-first.p4, testdata/p4_16_samples_outputs/parser-locals2-frontend.p4, testdata/p4_16_samples_outputs/parser-locals2-midend.p4, testdata/p4_16_samples_outputs/parser-locals2.p4
=> Correctly manage symbol table in parser for P4 parse states.

testdata/p4_16_samples/spec-ex19.p4, testdata/p4_16_samples_outputs/spec-ex19-first.p4, testdata/p4_16_samples_outputs/spec-ex19.p4
See this issue for why this is a correction: https://github.com/p4lang/p4-spec/issues/276
Anyone that knows: After updating a testdata example program, what command can I use to update the expected output files associated with it?
=> Correct example program extracting header with varbit field

tools/driver/p4c_src/main.py
Looks like the previous two commits for the same thing interact badly...
=> Fix p4c driver stdout/stderr handling

README.md
=> link to unsupported features

backends/bmv2/README.md
Suggest to change structure name s1_t -> s0_t
=> Wrong Structure Name?

control-plane/p4RuntimeSerializer.cpp
This is a new P4Info / P4Runtime feature that enablese passing metadata
between the controller and the switch for Packet IO. The metadata format
is defined by P4 header objects which are tagged with a
@controller_metadata annotation.
=> Add support for P4Runtime ControllerPacketMetadata

backends/bmv2/bmv2stf.py
The previous code had a simple 2 second timeout which was an issue in
some cases (very slow system, "warm-up" time for libtool wrapper script
if a non-installed simple_switch is used, ...). The new timeout is much
larger but we also periodically check whether the bmv2 process is still
running to ensure we are not waiting for nothing.
=> Better STF check to test if simple_switch is ready

frontends/p4/fromv1.0/converters.cpp, testdata/p4_14_samples_outputs/issue604.p4-stderr
The automerge from github missed the final change of the warning messages...
=> Fix incorrect github automerge

tools/driver/CMakeLists.txt
=> support for Ubuntu 14.04 cmake 3.2.2

frontends/common/options.cpp
This is required if we want to match on srcInfo to figure out whether a declaration comes from architecture or user program.
=> convert path passed by -I to absolute path

frontends/common/options.cpp
This reverts commit b4db551d5cb1106daf085baf547720f60905f7a4.
=> Revert "convert path passed by -I to absolute path internally (#770)"

backends/bmv2/backend.cpp
This is an attempt to fix issue #801
=> Start numbering learn_lists at 1

frontends/CMakeLists.txt, frontends/parsers/v1/v1parser.ypp
- allow single statements without braces in if/else or apply cases
- allow redundant {} in control blocks
=> P4_14 brace generalization

frontends/p4/fromv1.0/programStructure.cpp, frontends/p4/fromv1.0/programStructure.h, ir/expression.def, ir/ir.def, testdata/p4_14_errors/issue747.p4
Avoid including the same support file multiple times when converting P4_14->16
=> Sugar for making constructing calls easier.

backends/ebpf/ebpfControl.cpp, backends/ebpf/ebpfTable.cpp, backends/ebpf/ebpfTable.h, testdata/p4_16_samples/valid_ebpf.p4, testdata/p4_16_samples_outputs/valid_ebpf-first.p4, testdata/p4_16_samples_outputs/valid_ebpf-frontend.p4, testdata/p4_16_samples_outputs/valid_ebpf-midend.p4, testdata/p4_16_samples_outputs/valid_ebpf.p4
The changes look bigger than they actually are: most code changed because it is now guarded by if statements.
=> Bug-fixes for ebpf code generation

testdata/p4_14_samples/counter1.stf, testdata/p4_14_samples/counter2.stf, testdata/p4_14_samples/counter3.stf, testdata/p4_14_samples/counter4.stf
Adding fully qualified names for the few tests that have used abbreviations.
=> add fully qualified names to STF counter tests

tools/ir-generator/ir-generator.ypp
=> Remove shift-reduce conflicts in IR Generator grammar

.travis.yml
Travis seems determined to not cache anything. Let's try specifying the cache directory manually.
=> Try to convince Travis to actually cache the ccache db

Dockerfile
This PR is just an experiment for now.
=> Build with optimizations enabled on Travis

frontends/p4-14/typecheck.cpp
=> Fix P4_14 binop typechecking fix to not error on `int`

lib/ordered_map.h
=> fix ordered_map bug for clang 9.0 on osx

lib/ordered_map.h, lib/ordered_set.h
@hanw: does this help with your xcode issues?
=> rebind allocators in ordered_map/set to make newer compilers happy

CMakeLists.txt, tools/driver/p4c.in, tools/driver/p4c_src/main.py
Add a -g flag that is passed down to components and ability to set the version at build time.
=> add -g flag to driver and versioning info

midend/local_copyprop.cpp, testdata/p4_16_samples/issue949.p4, testdata/p4_16_samples_outputs/array_field-midend.p4, testdata/p4_16_samples_outputs/array_field1-midend.p4, testdata/p4_16_samples_outputs/generic1-midend.p4, testdata/p4_16_samples_outputs/issue561-midend.p4, testdata/p4_16_samples_outputs/issue949-first.p4, testdata/p4_16_samples_outputs/issue949-frontend.p4, testdata/p4_16_samples_outputs/issue949-midend.p4, testdata/p4_16_samples_outputs/issue949.p4, testdata/p4_16_samples_outputs/side_effects-midend.p4
=> When eliminating an assignment, preserve side effects in the rhs.

backends/bmv2/header.h, frontends/p4/deprecated.h
Affects backends/bmv2 and frontends/p4.
=> Add missing include dependencies:

CMakeLists.txt
=> fixes the path and the install command for documentation.

ir/visitor.cpp, ir/visitor.h
It always takes me a bit to remember how this works.  This time I took notes.
=> Add comments for some ControlFlowVisitor methods.

testdata/p4_14_samples/issue767.p4, testdata/p4_14_samples/simple_router.p4, testdata/p4_14_samples_outputs/issue767-first.p4, testdata/p4_14_samples_outputs/issue767-frontend.p4, testdata/p4_14_samples_outputs/issue767-midend.p4, testdata/p4_14_samples_outputs/issue767.p4, testdata/p4_14_samples_outputs/simple_router-first.p4, testdata/p4_14_samples_outputs/simple_router-frontend.p4, testdata/p4_14_samples_outputs/simple_router-midend.p4, testdata/p4_14_samples_outputs/simple_router.p4
original test program does not conform to the p4-14 spec.
=> update simple_router.p4 test case to set egress_spec, not egress_port

frontends/common/constantFolding.cpp, frontends/common/constantFolding.h, testdata/p4_14_samples_outputs/basic_conditionals-first.p4, testdata/p4_14_samples_outputs/basic_conditionals-frontend.p4, testdata/p4_14_samples_outputs/basic_conditionals-midend.p4, testdata/p4_16_samples_outputs/constants-first.p4, testdata/p4_16_samples_outputs/enum-bmv2-midend.p4, testdata/p4_16_samples_outputs/exit2-midend.p4, testdata/p4_16_samples_outputs/exit3-midend.p4, testdata/p4_16_samples_outputs/synth-action-midend.p4
I'm surprised this was missing...
=> constant folding if statements with constant conditions

testdata/p4_16_samples/issue461-bmv2.p4, testdata/p4_16_samples_outputs/issue461-bmv2-first.p4, testdata/p4_16_samples_outputs/issue461-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue461-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue461-bmv2.p4
@jafingerhut : can we close #461?
=> Test case to validate that #461 is fixed

testdata/p4_16_samples/issue737-bmv2.p4, testdata/p4_16_samples_outputs/issue737-bmv2-first.p4, testdata/p4_16_samples_outputs/issue737-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue737-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue737-bmv2.p4
Test case adapted from https://github.com/p4lang/behavioral-model/issues/399
=> Test case for issue #737, which seems to be fixed

backends/p4test/p4test.cpp
@jafingerhut : if this is good enough maybe we can close this issue.
=> Fix for issue #530

backends/bmv2/expression.cpp, backends/bmv2/expression.h, testdata/p4_16_samples/issue1049-bmv2.p4, testdata/p4_16_samples/issue1049-bmv2.stf, testdata/p4_16_samples_outputs/issue1049-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1049-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1049-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1049-bmv2.p4
=> Fix for issue #1049

backends/bmv2/CMakeLists.txt, backends/bmv2/control.cpp, frontends/p4/evaluator/evaluator.cpp, frontends/parsers/p4/p4parser.ypp, ir/expression.def, testdata/p4_16_samples/issue1062-1-bmv2.p4, testdata/p4_16_samples/issue1062-bmv2.p4, testdata/p4_16_samples_outputs/issue1062-1-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1062-1-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1062-1-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1062-1-bmv2.p4, testdata/p4_16_samples_outputs/issue1062-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1062-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1062-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1062-bmv2.p4
A CompileTimeValue is not necessarily  an Expression.
So IR::ListCompileTimeValue cannot inherit from ListExpression.
This PR also adds some checks to the bmv2 back-end that the key field type is a bitstring or a boolean.
=> Fix for issue #1062

backends/bmv2/CMakeLists.txt
This is @mbudiu-vmw's PR from #1066, but rebased. It was already approved. I'm trying to fast track this because all Travis jobs in this repo are failing right now due to this issue and Travis dropped the ball on the job for Mihai's PR.
=> Mark tests as xfailed due issue #486 - to be fixed

backends/bmv2/simpleSwitch.cpp, testdata/p4_16_samples/issue1079-bmv2.p4, testdata/p4_16_samples_outputs/issue1079-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1079-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1079-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1079-bmv2.p4
Bug report and solution contributed by @ygottlieb-vencorelabs-com
=> Fix for issue #1079

cmake/config.h.cmake
This needs to be present to config properly...
=> Add HAVE_CXXABI_H to config.h.cmake so it gets added properly to config.h

backends/bmv2/analyzer.cpp, backends/bmv2/analyzer.h, testdata/p4_16_samples/issue1127-bmv2.p4, testdata/p4_16_samples_outputs/issue1127-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1127-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1127-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1127-bmv2.p4
I will lose all my self-respect one of these days.
How could I mess up so badly such a simple piece of code? I could not even read what I had written...
Hopefully it's much simpler now.
=> Fix for issue #1127

backends/bmv2/backend.cpp, testdata/p4_16_samples/named_meter_1-bmv2.p4, testdata/p4_16_samples_outputs/named_meter_1-bmv2-first.p4, testdata/p4_16_samples_outputs/named_meter_1-bmv2-frontend.p4, testdata/p4_16_samples_outputs/named_meter_1-bmv2-midend.p4, testdata/p4_16_samples_outputs/named_meter_1-bmv2.p4
The diagnosis of @DGeorgeNetro was very good; I just had to swap two lines, processing globals at the end.
=> Fix for issue #1137

backends/graphs/parsers.cpp, backends/graphs/parsers.h, test/gtest/diagnostics.cpp
A few minor fixes for when ENABLE_UNIFIED_COMPILATION is OFF.
=> fixes for non-unified-build

ir/indexed_vector.h, ir/vector.h
A couple of people ran into this problem recently; this comment is an attempt to better address the issue.
=> Better comment about IR::Vector override problems.

backends/bmv2/CMakeLists.txt, backends/bmv2/globals.h, backends/bmv2/simpleSwitch.cpp, backends/p4test/CMakeLists.txt, testdata/p4_16_samples/issue1193-bmv2.p4, testdata/p4_16_samples_outputs/issue1193-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1193-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1193-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1193-bmv2.p4
@jnfoster is right, we should at least print an error.
Fixes #1193
=> add error check for unsupported externs

frontends/parsers/p4/p4parser.ypp, testdata/p4_16_errors/issue1202.p4, testdata/p4_16_errors_outputs/issue1202.p4-stderr, testdata/p4_16_errors_outputs/type-params_e.p4, testdata/p4_16_samples_outputs/extern2-first.p4, testdata/p4_16_samples_outputs/extern2-frontend.p4, testdata/p4_16_samples_outputs/extern2.p4, testdata/p4_16_samples_outputs/extern2.p4-stderr, testdata/p4_16_samples_outputs/factory2-first.p4, testdata/p4_16_samples_outputs/factory2-frontend.p4, testdata/p4_16_samples_outputs/factory2-midend.p4, testdata/p4_16_samples_outputs/factory2.p4, testdata/p4_16_samples_outputs/header-stack-ops-bmv2-first.p4, testdata/p4_16_samples_outputs/header-stack-ops-bmv2-frontend.p4, testdata/p4_16_samples_outputs/header-stack-ops-bmv2-midend.p4, testdata/p4_16_samples_outputs/header-stack-ops-bmv2.p4
Instead of checking the error message I have tightened the grammar.
We should also fix the spec if we approve this.
=> Fix for issue #1202; missing reference outputs

frontends/p4-14/typecheck.cpp, frontends/p4/fromv1.0/converters.cpp, ir/v1.cpp
the condition argument to modify_field_conditionally wasn't being properly inferred in p4_14->16 conversion
=> Infer bool type for modify_field_conditionally condition

midend/complexComparison.cpp
=> Fix uninitialized variable bug in ComplexComparison

midend/simplifyKey.cpp, midend/simplifyKey.h
Prevent potentially full tables to run SimplifyKey if a target wished to do so.
=> Added Another Policy to SimplifyKey

frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeChecker.h, testdata/p4_16_samples/pvs-nested-struct.p4, testdata/p4_16_samples/pvs-struct.p4, testdata/p4_16_samples_outputs/pvs-nested-struct-first.p4, testdata/p4_16_samples_outputs/pvs-nested-struct-frontend.p4, testdata/p4_16_samples_outputs/pvs-nested-struct-midend.p4, testdata/p4_16_samples_outputs/pvs-nested-struct.p4, testdata/p4_16_samples_outputs/pvs-struct-first.p4, testdata/p4_16_samples_outputs/pvs-struct-frontend.p4, testdata/p4_16_samples_outputs/pvs-struct-midend.p4, testdata/p4_16_samples_outputs/pvs-struct.p4
as mentioned in https://github.com/p4lang/p4-spec/pull/602
=> Support struct as type parameter in value_set<T>

frontends/p4/fromv1.0/programStructure.cpp, testdata/p4_14_samples_outputs/switch_20160512/switch-first.p4, testdata/p4_14_samples_outputs/switch_20160512/switch-frontend.p4, testdata/p4_14_samples_outputs/switch_20160512/switch-midend.p4, testdata/p4_14_samples_outputs/switch_20160512/switch.p4
Some annotations on Counters were not saved on DirectCounters
=> DirectCounter min_width

backends/p4test/p4test.cpp, ir/json_parser.cpp
- fix json reading of strings with escaped quotes
for #1273
=> add --fromJSON option to p4test to load previously dumped json

frontends/p4/toP4/toP4.cpp, frontends/parsers/p4/p4parser.ypp, ir/base.def, midend/actionSynthesis.cpp, testdata/p4_16_errors/default-param.p4, testdata/p4_16_samples/kvanno.p4, testdata/p4_16_samples_outputs/kvanno-first.p4, testdata/p4_16_samples_outputs/kvanno.p4, testdata/p4_16_samples_outputs/kvanno.p4-stderr
This may soon be in the spec: https://github.com/p4lang/p4-spec/pull/625
=> support key=value annotations

frontends/p4/fromv1.0/programStructure.cpp
Missing pre_color for DirectMeters.
=> Added an annotation for meter pre_color

control-plane/p4RuntimeSerializer.cpp, test/gtest/p4runtime.cpp
The SynthesizeValidField pass used to take care of this but it was
removed with #1317.
=> Handle boolean literals in static table entries in P4Runtime serializer

frontends/parsers/p4/p4parser.ypp
=> Fix for issue 1336

backends/bmv2/psa_switch/midend.cpp
Converted PSA_PacketPath_t to bit<32>.
=> fixes for #1329

control-plane/CMakeLists.txt, control-plane/p4RuntimeArchHandler.cpp, control-plane/p4RuntimeArchHandler.h, control-plane/p4RuntimeArchStandard.cpp, control-plane/p4RuntimeArchStandard.h, control-plane/p4RuntimeSerializer.cpp, control-plane/typeSpecConverter.cpp, control-plane/typeSpecConverter.h, frontends/p4/externInstance.cpp, frontends/p4/externInstance.h
Integrated review feedback from @mbudiu-vmw (PR #1314).
Also seized the opportunity to update the PI submodule ref point.
This in preparation of me adding support for PSA.
=> Clean-up P4Runtime serializer code

frontends/p4/externInstance.h
causing compilation error on some backend.
=> missing include file

midend/convertEnums.cpp
=> fix nullptr bug

frontends/p4/externInstance.cpp, frontends/p4/inlining.cpp, frontends/p4/methodInstance.cpp, frontends/p4/methodInstance.h, frontends/p4/parameterSubstitution.h, frontends/p4/specialize.cpp, frontends/p4/specialize.h, ir/base.cpp, midend/orderArguments.cpp, testdata/p4_16_errors/issue1331.p4, testdata/p4_16_errors_outputs/issue1331-first.p4, testdata/p4_16_errors_outputs/issue1331.p4, testdata/p4_16_errors_outputs/issue1331.p4-stderr, testdata/p4_16_samples_outputs/action_call_table_ebpf-first.p4, testdata/p4_16_samples_outputs/action_call_table_ebpf-frontend.p4, testdata/p4_16_samples_outputs/action_call_table_ebpf-midend.p4, testdata/p4_16_samples_outputs/action_call_table_ebpf.p4, testdata/p4_16_samples_outputs/extern-funcs-bmv2-first.p4, testdata/p4_16_samples_outputs/extern-funcs-bmv2-frontend.p4, testdata/p4_16_samples_outputs/extern-funcs-bmv2-midend.p4, testdata/p4_16_samples_outputs/extern-funcs-bmv2.p4, testdata/p4_16_samples_outputs/inline-control-frontend.p4, testdata/p4_16_samples_outputs/inline-control-midend.p4, testdata/p4_16_samples_outputs/inline-control1-frontend.p4, testdata/p4_16_samples_outputs/inline-control1-midend.p4
This also improves error messages and removes the ConstructorCallDescription by folding its functionality in other classes.
=> Fix for issue #1331

tools/driver/p4c_src/driver.py
=> add `-undef` and `-nostdinc` to preprocessor cmd line

frontends/p4/toP4/toP4.cpp, frontends/p4/toP4/toP4.h
- check that the stacks are consistent with what they were in
init_apply, not that they are empty
=> Fix stack checks in toP4::end_apply

ir/node.h, ir/pass_manager.h
A couple of minor changes to make some things easier to debug.
=> Debugging improvements

backends/graphs/parsers.cpp, backends/graphs/parsers.h
Collect states/transitions for each parser, and save those in a map.
=> modified graphs::ParserGraphs for reuse

frontends/common/options.cpp, testdata/p4_14_samples/issue1428.p4, testdata/p4_14_samples_outputs/issue1428-first.p4, testdata/p4_14_samples_outputs/issue1428-frontend.p4, testdata/p4_14_samples_outputs/issue1428-midend.p4, testdata/p4_14_samples_outputs/issue1428.p4, tools/driver/p4c_src/driver.py, tools/driver/p4c_src/p4c.bmv2.cfg, tools/driver/p4c_src/p4c.ebpf.cfg
=> change the language used by the preprocessor

backends/bmv2/CMakeLists.txt, midend/local_copyprop.cpp, midend/local_copyprop.h, testdata/p4_14_samples/issue-1426.p4, testdata/p4_14_samples_outputs/issue-1426-first.p4, testdata/p4_14_samples_outputs/issue-1426-frontend.p4, testdata/p4_14_samples_outputs/issue-1426-midend.p4, testdata/p4_14_samples_outputs/issue-1426.p4, testdata/p4_16_samples_outputs/pipe-midend.p4
- deal with members and array elements properly when propagating into
the key of a table.
=> local_copyprop table key fix (#issue 1426)

lib/bitvec.h
This uses some template/enable_if magic to only do the overload if there exists a type larger than uintptr_t -- if uintptr_t and uintmax_t are the same, then a simple overload would fail, and just defining for uintmax_t would have trouble with shifts being out of range.
=> Construct bitvec from integer types larger than uintptr_t

lib/CMakeLists.txt, lib/cstring.cpp, lib/cstring.h, lib/hash.cpp, lib/hash.h, lib/stringify.cpp
Added hash utility with implemented FNV-1A hash
Do not make copy of string in cstring if possible
Minor cstring cleanup
LUTSENKO DANIL
SOFTWARE DEVELOPER
www.jabil.com
=> cstring optimization

backends/ebpf/codeGen.cpp, backends/ebpf/ebpfTable.cpp, frontends/CMakeLists.txt, frontends/p4/def_use.cpp, frontends/p4/defaultArguments.cpp, frontends/p4/defaultArguments.h, frontends/p4/deprecated.h, frontends/p4/dontcareArgs.cpp, frontends/p4/frontend.cpp, frontends/p4/inlining.cpp, frontends/p4/methodInstance.cpp, frontends/p4/methodInstance.h, frontends/p4/sideEffects.cpp, frontends/p4/simplifyDefUse.cpp, frontends/p4/toP4/toP4.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeUnification.cpp, frontends/p4/typeMap.cpp, midend/interpreter.cpp, midend/orderArguments.cpp, testdata/p4_16_errors/default-param.p4, testdata/p4_16_errors_outputs/default-param.p4, testdata/p4_16_errors_outputs/default-param.p4-stderr, testdata/p4_16_samples/issue1333.p4, testdata/p4_16_samples_outputs/issue1333-first.p4, testdata/p4_16_samples_outputs/issue1333-frontend.p4, testdata/p4_16_samples_outputs/issue1333-midend.p4, testdata/p4_16_samples_outputs/issue1333.p4
This completes the implementation of handling named arguments.
=>  Fixes for issues #1333 and #1381 

frontends/p4-14/typecheck.cpp
- P4_14 allows mulitple symbols of the same name -- which is referred to
depends on context
=> v1 ambiguous symbol referencing fix

p4include/v1model.p4
This i a recent update to simple_switch behavior.
=> Update comment on v1model.p4 checksum_error field to match simple_switch

tools/driver/p4c_src/driver.py, tools/driver/p4c_src/main.py
=> return from failure rather than exit

ir/dump.cpp, lib/map.h
- Keys and ValuesForKey helpers for (multi)map iteration
- dump child index/name in Visitor::Context dump routine
=> support routine additions

frontends/p4/def_use.cpp, frontends/p4/def_use.h, frontends/p4/simplifyDefUse.cpp, testdata/p4_16_samples/issue1595-1.p4, testdata/p4_16_samples/issue1595.p4, testdata/p4_16_samples_outputs/issue1595-1-first.p4, testdata/p4_16_samples_outputs/issue1595-1-frontend.p4, testdata/p4_16_samples_outputs/issue1595-1-midend.p4, testdata/p4_16_samples_outputs/issue1595-1.p4, testdata/p4_16_samples_outputs/issue1595-first.p4, testdata/p4_16_samples_outputs/issue1595-frontend.p4, testdata/p4_16_samples_outputs/issue1595-midend.p4, testdata/p4_16_samples_outputs/issue1595.p4
The fix is a one-liner (line 238 in simplifyDefUse), but I renamed a bunch of functions because TAGS were not useful to navigate the code at all.
=> Fix for issue #1595

lib/crash.cpp, lib/log.cpp, lib/log.h
- fix indentation control and locking for multithreaded (if its turned
on -- off by default)
- support for per file output control to different log files.
=> Logging fixes/improvements

backends/ebpf/ebpfParser.cpp, backends/ebpf/ebpfParser.h, backends/ebpf/ebpfProgram.cpp, backends/ebpf/midend.cpp, midend/CMakeLists.txt, midend/singleArgumentSelect.cpp, midend/singleArgumentSelect.h, testdata/p4_16_samples/calc-ebpf.p4, testdata/p4_16_samples_outputs/calc-ebpf-first.p4, testdata/p4_16_samples_outputs/calc-ebpf-frontend.p4, testdata/p4_16_samples_outputs/calc-ebpf-midend.p4, testdata/p4_16_samples_outputs/calc-ebpf.p4
There is also a new midend pass which may prove useful in other places.
=> Support lookahead in ebpf backend

lib/match.h
@liujed , I found your comment for `match_t` quite useful, and moved it here.
Also added `!=` operator.
=> documentation for match_t

backends/bmv2/CMakeLists.txt, backends/ebpf/CMakeLists.txt, backends/graphs/CMakeLists.txt, backends/p4test/CMakeLists.txt
=> Added missing build dependencies

backends/bmv2/simple_switch/simpleSwitch.cpp, p4include/v1model.p4, testdata/p4_16_bmv_errors/issue1672-bmv2.p4, testdata/p4_16_samples/issue1520-bmv2.p4, testdata/p4_16_samples_outputs/issue1520-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1520-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1520-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1520-bmv2.p4
=> Validate headers type for v1model

lib/bitvec.cpp
Better for building for sub libraries.
=> Move a message to assert

frontends/p4/fromv1.0/programStructure.cpp, testdata/p4_14_samples/issue1696-1.p4, testdata/p4_14_samples/issue1696.p4, testdata/p4_14_samples_outputs/06-SimpleVlanStack.p4-stderr, testdata/p4_14_samples_outputs/07-SimpleVlanStackIP.p4-stderr, testdata/p4_14_samples_outputs/08-SimpleVlanStackIPSplitFlags.p4-stderr, testdata/p4_14_samples_outputs/09-IPv4OptionsUnparsed.p4-stderr, testdata/p4_14_samples_outputs/action_chain1.p4-stderr, testdata/p4_14_samples_outputs/header-stack-ops-bmv2.p4-stderr, testdata/p4_14_samples_outputs/instruct5.p4-stderr, testdata/p4_14_samples_outputs/issue1696-first.p4, testdata/p4_14_samples_outputs/issue1696-frontend.p4, testdata/p4_14_samples_outputs/issue1696-midend.p4, testdata/p4_14_samples_outputs/issue1696.p4, testdata/p4_14_samples_outputs/issue576.p4-stderr, testdata/p4_14_samples_outputs/issue583.p4-stderr, testdata/p4_14_samples_outputs/switch_20160226/switch.p4-stderr, testdata/p4_14_samples_outputs/switch_20160512/switch.p4-stderr, testdata/p4_14_samples_outputs/validate_outer_ethernet.p4-stderr
=> Remove spurious warning caused by stack[next] self-loops

backends/bmv2/common/lower.cpp, testdata/p4_16_samples/issue1713-bmv2.p4, testdata/p4_16_samples_outputs/issue1713-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1713-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1713-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1713-bmv2.p4, testdata/p4_16_samples_outputs/issue1713-bmv2.p4.p4info.txt
=> Fix bug in bmv2 backend regarding slices of signed values

frontends/common/options.cpp, frontends/common/options.h, frontends/p4/typeChecking/typeChecker.cpp, lib/error_catalog.h, lib/error_reporter.h, testdata/p4_16_errors/issue1724.p4, testdata/p4_16_errors_outputs/issue1724.p4, testdata/p4_16_errors_outputs/issue1724.p4-stderr, testdata/p4_16_errors_outputs/stack_e.p4-stderr, tools/ir-generator/ir-generator.ypp
Also extend the --Wdisable, --Wwarn, --Werror to the error catalog, as it was used only for pragmas.
=>  add expressions to several type checking warnings

frontends/common/constantParsing.cpp, frontends/parsers/v1/v1lexer.ll, frontends/parsers/v1/v1parser.ypp
A couple of cases of things that are accepted by the old hlir P4_14 frontend which are not clearly illegal per the old standard.
=> V1 hlir compat

p4include/psa.p4
See https://github.com/p4lang/p4-spec/issues/730 for the rationale.
The corresponding changes have been made in the PSA specification
recently, reviewed by Antonin Bas and Calin Cascaval.
=> Add p4runtime_translation for all seven `type`s in psa.p4

frontends/p4/fromv1.0/converters.cpp, testdata/p4_14_errors/issue1745.p4, testdata/p4_14_errors_outputs/issue1745.p4-stderr
=> Reject varbit fields that do not come last in header in P4-14

frontends/p4/frontend.cpp, frontends/p4/parseAnnotations.h
=> Clear the type map after parsing annotations

frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeSubstitution.cpp, frontends/p4/typeMap.cpp, frontends/p4/typeMap.h, ir/type.cpp, ir/type.def, testdata/p4_16_errors_outputs/issue345.p4-stderr, testdata/p4_16_errors_outputs/issue67.p4-stderr, testdata/p4_16_samples/issue1717.p4, testdata/p4_16_samples_outputs/issue1717-first.p4, testdata/p4_16_samples_outputs/issue1717-frontend.p4, testdata/p4_16_samples_outputs/issue1717.p4, testdata/p4_16_samples_outputs/issue1717.p4-stderr
=> Implement sizeInBits

midend/flattenInterfaceStructs.cpp, midend/flattenInterfaceStructs.h, testdata/p4_16_errors/issue1777-bmv2.p4, testdata/p4_16_errors_outputs/issue1777-bmv2-first.p4, testdata/p4_16_errors_outputs/issue1777-bmv2-frontend.p4, testdata/p4_16_errors_outputs/issue1777-bmv2.p4, testdata/p4_16_errors_outputs/issue1777-bmv2.p4-stderr
=>  Error for struct arguments in out argument positions

control-plane/p4RuntimeSerializer.cpp, testdata/p4_16_samples/action-two-params.p4, testdata/p4_16_samples_outputs/action-two-params-first.p4, testdata/p4_16_samples_outputs/action-two-params-frontend.p4, testdata/p4_16_samples_outputs/action-two-params-midend.p4, testdata/p4_16_samples_outputs/action-two-params.p4, testdata/p4_16_samples_outputs/action-two-params.p4.p4info.txt
The parameterIndex has to be incremented.
=> Fix to issue 1788

backends/p4test/run-p4-sample.py, testdata/p4_16_samples_outputs/action-two-params.p4.entries.txt, testdata/p4_16_samples_outputs/bvec-hdr-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/crc32-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/issue1107.p4.entries.txt, testdata/p4_16_samples_outputs/issue1478-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/saturated-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-exact-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-exact-ternary-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-lpm-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-priority-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-range-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-ternary-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/table-entries-valid-bmv2.p4.entries.txt
Most of the checked in files are empty because very few programs have
static table entries.
Fixes #1800
=> Run p4test tests with --p4runtime-entries-files

frontends/common/options.cpp, frontends/p4/toP4/toP4.cpp
- only output full struct decl with declaration -- uses just use name
- squash symlinks when looking for #include possibilities
=> Fix P4 code output

backends/p4test/CMakeLists.txt, control-plane/p4RuntimeSerializer.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeMap.cpp, testdata/p4_16_samples/issue1806.p4, testdata/p4_16_samples_outputs/issue1806-first.p4, testdata/p4_16_samples_outputs/issue1806-frontend.p4, testdata/p4_16_samples_outputs/issue1806-midend.p4, testdata/p4_16_samples_outputs/issue1806.p4, testdata/p4_16_samples_outputs/issue1806.p4.p4info.txt
I don't know why this didn't cause any problems so far.
=> Add canonical base types to typemap; fixes #1806

control-plane/CMakeLists.txt
=> add p4parser.hpp to controlplane dependency

testdata/p4_16_bmv_errors/issue1167-bmv2.p4
The test was submitted by @jafingerhut , but I don't think it is part of the repository yet.
=> Test for issue #1167

backends/bmv2/CMakeLists.txt, backends/bmv2/common/JsonObjects.cpp, backends/bmv2/common/JsonObjects.h, backends/bmv2/common/extern.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeMap.cpp, testdata/p4_16_samples/empty-bmv2.p4, testdata/p4_16_samples/issue1882-1-bmv2.p4, testdata/p4_16_samples/issue1882-bmv2.p4, testdata/p4_16_samples_outputs/empty-bmv2-first.p4, testdata/p4_16_samples_outputs/empty-bmv2-frontend.p4, testdata/p4_16_samples_outputs/empty-bmv2-midend.p4, testdata/p4_16_samples_outputs/empty-bmv2.p4, testdata/p4_16_samples_outputs/empty-bmv2.p4.p4info.txt, testdata/p4_16_samples_outputs/issue1882-1-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1882-1-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1882-1-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1882-1-bmv2.p4, testdata/p4_16_samples_outputs/issue1882-1-bmv2.p4.p4info.txt, testdata/p4_16_samples_outputs/issue1882-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1882-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1882-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1882-bmv2.p4, testdata/p4_16_samples_outputs/issue1882-bmv2.p4.p4info.txt
I don't know if this fixes #1882, since I don't know exactly how an extern instance should be represented in the json. But perhaps this is good enough.
I have also added an empty-bmv2.p4 test, which was used to create issue1882-bmv2.p4.
=> Emit instances for unknown externs

testdata/p4_16_samples/issue1834-bmv2.p4, testdata/p4_16_samples_outputs/issue1834-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1834-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1834-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue1834-bmv2.p4, testdata/p4_16_samples_outputs/issue1834-bmv2.p4.entries.txt, testdata/p4_16_samples_outputs/issue1834-bmv2.p4.p4info.txt
Issue 1834 was fixed by recently committed PR 1792.
=> Add test program from issue 1834, which now passes

backends/bmv2/common/lower.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeUnification.cpp, testdata/p4_16_samples/constsigned.p4, testdata/p4_16_samples/strength4.p4, testdata/p4_16_samples_outputs/constsigned.p4, testdata/p4_16_samples_outputs/issue1713-bmv2-first.p4, testdata/p4_16_samples_outputs/issue1713-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue1713-bmv2-midend.p4, testdata/p4_16_samples_outputs/strength4-first.p4, testdata/p4_16_samples_outputs/strength4-frontend.p4, testdata/p4_16_samples_outputs/strength4-midend.p4, testdata/p4_16_samples_outputs/strength4.p4
=> Made all slices unsigned

testdata/p4_16_samples/psa-resubmit-bmv2.p4, testdata/p4_16_samples/psa-resubmit-bmv2.stf, testdata/p4_16_samples_outputs/psa-resubmit-bmv2-first.p4, testdata/p4_16_samples_outputs/psa-resubmit-bmv2-frontend.p4, testdata/p4_16_samples_outputs/psa-resubmit-bmv2-midend.p4, testdata/p4_16_samples_outputs/psa-resubmit-bmv2.p4, testdata/p4_16_samples_outputs/psa-resubmit-bmv2.p4.p4info.txt
@jafingerhut 
this tests checks that:
1) packet is actually resubmitted
2) the packet that was resubmitted == the original, but with `packet_path` metadata set to resubmit
redo of #1904
=> add resubmit test for psa

README.md
The sample commands given used to create a P4Info file, but now
additional command line options are needed for that to happen.
=> Small updates to the sample command lines in README

backends/bmv2/psa_switch/psaSwitch.cpp, backends/bmv2/psa_switch/psaSwitch.h, testdata/p4_16_samples/psa-top-level-assignments-bmv2.p4, testdata/p4_16_samples/psa-top-level-assignments-bmv2.stf, testdata/p4_16_samples_outputs/psa-top-level-assignments-bmv2-first.p4, testdata/p4_16_samples_outputs/psa-top-level-assignments-bmv2-frontend.p4, testdata/p4_16_samples_outputs/psa-top-level-assignments-bmv2-midend.p4, testdata/p4_16_samples_outputs/psa-top-level-assignments-bmv2.p4, testdata/p4_16_samples_outputs/psa-top-level-assignments-bmv2.p4.p4info.txt
This is exactly the same code changes to PSA back end that @hanw wrote in this PR: https://github.com/p4lang/p4c/pull/1964
The only difference is that the test program added in this PR is a different one.  It passes with these changes, and fails without them.
=> Fix for issue 1923

frontends/p4/fromv1.0/programStructure.cpp
missed one line in the latest refactoring.
=> one more fix to p4-14 translation

testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2-frontend.p4, testdata/p4_16_samples_outputs/ipv6-switch-ml-bmv2-midend.p4
Change the reference output of a test.
=> Fix broken build

frontends/common/constantFolding.cpp, testdata/p4_16_errors/signed.p4, testdata/p4_16_errors_outputs/signed.p4, testdata/p4_16_errors_outputs/signed.p4-stderr, testdata/p4_16_samples/issue1997.p4, testdata/p4_16_samples_outputs/issue1997-first.p4, testdata/p4_16_samples_outputs/issue1997-frontend.p4, testdata/p4_16_samples_outputs/issue1997.p4, testdata/p4_16_samples_outputs/issue1997.p4-stderr
I also added a test requested by @jafingerhut for the signed bit slices.
=> Constant fold values with type int; fixes #1997

backends/bmv2/CMakeLists.txt, backends/ebpf/CMakeLists.txt, frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue2033.p4, testdata/p4_16_errors_outputs/issue2033.p4, testdata/p4_16_errors_outputs/issue2033.p4-stderr
=> Require  list to come first; fix unified build

backends/bmv2/CMakeLists.txt, backends/ebpf/CMakeLists.txt, frontends/common/constantFolding.cpp, frontends/common/constantFolding.h, testdata/p4_16_errors/issue2021.p4, testdata/p4_16_errors_outputs/issue2021.p4, testdata/p4_16_errors_outputs/issue2021.p4-stderr
=> Do not constant fold on the lhs of =

backends/ebpf/CMakeLists.txt, tools/driver/p4c_src/main.py
For people like me who forget whether the option is singular or plural.
=> dyslexic help

.travis.yml, Dockerfile, backends/bmv2/common/deparser.cpp, tools/travis-build
This should catch any compilation issues when unified compilation is disabled.
Opening a PR to see if this works.
=> WIP: Add non-unified builds to Travis

control-plane/CMakeLists.txt, control-plane/bytestrings.cpp, control-plane/bytestrings.h, control-plane/p4RuntimeSerializer.cpp, control-plane/typeSpecConverter.cpp, test/gtest/p4runtime.cpp, testdata/p4_16_samples/register-serenum.p4, testdata/p4_16_samples_outputs/logging.p4.p4info.txt, testdata/p4_16_samples_outputs/register-serenum-first.p4, testdata/p4_16_samples_outputs/register-serenum-frontend.p4, testdata/p4_16_samples_outputs/register-serenum-midend.p4, testdata/p4_16_samples_outputs/register-serenum.p4, testdata/p4_16_samples_outputs/register-serenum.p4.p4info.txt, testdata/p4_16_samples_outputs/v1model-digest-containing-ser-enum.p4.p4info.txt
The value should be a P4Runtime "bytestring" and not a human-readable
hexadecimal string.
Thanks to @mbudiu-vmw for his help making the SerEnum Google Test work.
=> Fix SerEnum member values in generated P4Info

backends/bmv2/psa_switch/main.cpp, backends/bmv2/simple_switch/main.cpp, backends/ebpf/p4c-ebpf.cpp, backends/graphs/p4c-graphs.cpp, backends/p4test/p4test.cpp, lib/CMakeLists.txt, lib/backtrace.cpp, lib/backtrace.h, lib/crash.h, lib/ordered_map.h
- print the backtrace when unexpected exceptions are caught at the top
level
=> Stack backtrace in exceptions

frontends/parsers/v1/v1parser.ypp, testdata/p4_14_samples_outputs/name_collision-first.p4, testdata/p4_14_samples_outputs/name_collision-frontend.p4, testdata/p4_14_samples_outputs/name_collision-midend.p4, testdata/p4_14_samples_outputs/name_collision.p4, testdata/p4_14_samples_outputs/simple_router-first.p4, testdata/p4_14_samples_outputs/simple_router-frontend.p4, testdata/p4_14_samples_outputs/simple_router-midend.p4, testdata/p4_14_samples_outputs/simple_router.p4
- match obscure behavior of old p4-hlir code
=> Treat P4_14 default_action with () args as const

lib/gc.cpp
- glibstdc++ uses malloc to allocate exceptions being thrown, which
could result in them not being scanned by the garbage collector,
leading to memory corruption.
=> Use libgc for all malloc calls, so they are scanned properly.

README.md, backends/bmv2/common/JsonObjects.cpp, ir/README.md
Fixes:
https://github.com/p4lang/p4c/issues/2135
https://github.com/p4lang/p4c/issues/2117
and a minor spelling mistake.
=> Misc minor fixes

backends/bmv2/common/lower.cpp
There is no test associated with this file, because the PR #2139 contains a test.
=> Update leftValues when lowering; fixed #2150

frontends/parsers/p4/p4parser.ypp, testdata/p4_16_samples/shift_precendence.p4, testdata/p4_16_samples_outputs/shift_precendence-first.p4, testdata/p4_16_samples_outputs/shift_precendence-frontend.p4, testdata/p4_16_samples_outputs/shift_precendence-midend.p4, testdata/p4_16_samples_outputs/shift_precendence.p4
=> Fix precedence of RSH rule

lib/ordered_set.h, test/gtest/ordered_set.cpp
- sorted_begin/end to iterate over elements in sorted order rather than
internal order
- insert method with position.
=> ordered_set sorted_iterator

backends/bmv2/common/parser.cpp
=> Use the type from the typeMap; fixes #2163

backends/bmv2/common/JsonObjects.cpp
=> Change JSON size to max_size

frontends/p4/toP4/toP4.cpp, testdata/p4_16_samples/issue2208.p4, testdata/p4_16_samples_outputs/issue2208-first.p4, testdata/p4_16_samples_outputs/issue2208-frontend.p4, testdata/p4_16_samples_outputs/issue2208-midend.p4, testdata/p4_16_samples_outputs/issue2208.p4, testdata/p4_16_samples_outputs/issue2208.p4-stderr, testdata/p4_16_samples_outputs/issue2208.p4.p4info.txt
=> Print correctly negative constants with InfInt types

backends/bmv2/common/expression.cpp, frontends/common/options.cpp, ir/type.def, lib/source_file.h
=> Fix gcc warnings

testdata/p4_14_samples/counter3.stf
Change the expected counter values in the test +4 bytes per packet
=> Update stf test

frontends/p4/structInitializers.cpp, testdata/p4_16_samples/issue2213-bmv2.p4, testdata/p4_16_samples/issue2213.p4, testdata/p4_16_samples_outputs/issue2213-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2213-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2213-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2213-bmv2.p4, testdata/p4_16_samples_outputs/issue2213-bmv2.p4.p4info.txt, testdata/p4_16_samples_outputs/issue2213-first.p4, testdata/p4_16_samples_outputs/issue2213-frontend.p4, testdata/p4_16_samples_outputs/issue2213-midend.p4, testdata/p4_16_samples_outputs/issue2213.p4
This is literally a (half) line fix.
=> Struct initializers should infer types for nested structs; fixes #2213

backends/ubpf/ubpfDeparser.cpp
=> Refactor ubpfDeparser to properly emit outgoing packet size calculation

control-plane/p4RuntimeSerializer.cpp, control-plane/typeSpecConverter.cpp, control-plane/typeSpecConverter.h, test/gtest/p4runtime.cpp, testdata/p4_16_samples/v1model-digest-custom-type.p4, testdata/p4_16_samples_outputs/v1model-digest-custom-type-first.p4, testdata/p4_16_samples_outputs/v1model-digest-custom-type-frontend.p4, testdata/p4_16_samples_outputs/v1model-digest-custom-type-midend.p4, testdata/p4_16_samples_outputs/v1model-digest-custom-type.p4, testdata/p4_16_samples_outputs/v1model-digest-custom-type.p4.p4info.txt
The previous code was making assumptions that did not make sense to
me. I rewrote it and added tests (Gtest unit tests + the P4 test program
attached by @jafingerhut when he submitted the issue).
Fixes #2234
=> Fix "new type" handling in P4Info serialization code

backends/bmv2/run-bmv2-test.py
This print snuck in and should not be there.
=> Remove a stray print

backends/ubpf/CMakeLists.txt
Restarting #2269 (could not work out how to get travis to retry)
Also didn't want to do pull request via fork.
Sorry for the repeat.
=> Replace $$() with ${} in CMakeList.tx

frontends/p4/functionsInlining.h, testdata/p4_16_samples/issue2291-bmv2.p4, testdata/p4_16_samples_outputs/issue2291-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2291-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2291-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2291-bmv2.p4, testdata/p4_16_samples_outputs/issue2291-bmv2.p4.p4info.txt
=> Run inliner until convergence

frontends/common/resolveReferences/resolveReferences.cpp, frontends/common/resolveReferences/resolveReferences.h, frontends/p4/parseAnnotations.cpp, ir/base.def, ir/type.cpp, p4include/psa.p4, p4include/v1model.p4, testdata/p4_16_errors_outputs/issue1541.p4-stderr, testdata/p4_16_errors_outputs/issue513.p4-stderr, testdata/p4_16_samples_outputs/issue841.p4-stderr, testdata/p4_16_samples_outputs/psa-example-parser-checksum-midend.p4
+ written by Chris Dodd with additional annotations, trimmed back by
Andy Fingerhut to only use pure and noSideEffects annotations
+ add annotations in appropriate places in v1model.p4 and psa.p4
+ fix resolveReferences to look at parameters
=> Add pure annotation

backends/bmv2/common/backend.h, control-plane/flattenHeader.cpp, frontends/p4/fromv1.0/programStructure.cpp, frontends/p4/inlining.cpp, ir/base.def
=> additional annotation cleanup

testdata/p4_16_errors_outputs/issue2290.p4, testdata/p4_16_samples_outputs/issue2289-first.p4, testdata/p4_16_samples_outputs/issue2289-frontend.p4, testdata/p4_16_samples_outputs/issue2289-midend.p4, testdata/p4_16_samples_outputs/issue2289.p4
New test collision in merges...
=> update reference outputs for new tests

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue2317.p4, testdata/p4_16_errors_outputs/issue2317.p4, testdata/p4_16_errors_outputs/issue2317.p4-stderr
=> Do not allow actions to be used in expressions

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue2267.p4, testdata/p4_16_errors_outputs/issue2267.p4, testdata/p4_16_errors_outputs/issue2267.p4-stderr
=> Check for circular dependences in tables

frontends/common/resolveReferences/referenceMap.h, frontends/common/resolveReferences/resolveReferences.h, frontends/p4/typeChecking/typeUnification.cpp, ir/ir.def, testdata/p4_16_samples/issue2265-1.p4, testdata/p4_16_samples/issue2265.p4, testdata/p4_16_samples_outputs/issue2265-1-first.p4, testdata/p4_16_samples_outputs/issue2265-1.p4, testdata/p4_16_samples_outputs/issue2265-1.p4-stderr, testdata/p4_16_samples_outputs/issue2265-first.p4, testdata/p4_16_samples_outputs/issue2265.p4, testdata/p4_16_samples_outputs/issue2265.p4-stderr
=> Fix two bugs related to generics

frontends/common/resolveReferences/referenceMap.h, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeConstraints.cpp, frontends/p4/typeChecking/typeSubstitution.cpp, frontends/parsers/p4/p4lexer.ll, ir/ir.def, ir/node.h, ir/type.def, testdata/p4_16_errors/issue2335.p4, testdata/p4_16_errors_outputs/issue2335.p4, testdata/p4_16_errors_outputs/issue2335.p4-stderr, testdata/p4_16_samples/issue2335-1.p4, testdata/p4_16_samples_outputs/issue2335-1-first.p4, testdata/p4_16_samples_outputs/issue2335-1-frontend.p4, testdata/p4_16_samples_outputs/issue2335-1-midend.p4, testdata/p4_16_samples_outputs/issue2335-1.p4
=> Stronger checks for int values

frontends/p4/strengthReduction.cpp, testdata/p4_16_samples/issue2356.p4, testdata/p4_16_samples_outputs/issue2343-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2343-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2356-first.p4, testdata/p4_16_samples_outputs/issue2356-frontend.p4, testdata/p4_16_samples_outputs/issue2356-midend.p4, testdata/p4_16_samples_outputs/issue2356.p4, testdata/p4_16_samples_outputs/issue2356.p4.p4info.txt
=> Do not generate negative indexes for slices

midend/removeParameters.cpp, testdata/p4_16_samples/issue2359.p4, testdata/p4_16_samples_outputs/issue2359-first.p4, testdata/p4_16_samples_outputs/issue2359-frontend.p4, testdata/p4_16_samples_outputs/issue2359-midend.p4, testdata/p4_16_samples_outputs/issue2359.p4, testdata/p4_16_samples_outputs/issue2359.p4.p4info.txt
=> Return a Block instead of a Vector

lib/crash.cpp
- run addr2line through a pipe so it does not need to reload.
=> Faster crash dumps

backends/bmv2/common/controlFlowGraph.cpp, frontends/p4/simplifyParsers.cpp, lib/error_catalog.cpp, lib/error_catalog.h, testdata/p4_16_errors/issue2373.p4, testdata/p4_16_errors_outputs/issue2373-first.p4, testdata/p4_16_errors_outputs/issue2373.p4, testdata/p4_16_errors_outputs/issue2373.p4-stderr
=> Error for parser infinite loops

testdata/p4_16_samples/psa-action-profile1.p4, testdata/p4_16_samples/psa-action-profile2.p4, testdata/p4_16_samples/psa-action-profile3.p4, testdata/p4_16_samples/psa-action-profile4.p4, testdata/p4_16_samples/psa-action-selector2.p4, testdata/p4_16_samples/psa-action-selector3.p4, testdata/p4_16_samples_outputs/psa-action-profile1-first.p4, testdata/p4_16_samples_outputs/psa-action-profile1-frontend.p4, testdata/p4_16_samples_outputs/psa-action-profile1-midend.p4, testdata/p4_16_samples_outputs/psa-action-profile1.p4, testdata/p4_16_samples_outputs/psa-action-profile2-first.p4, testdata/p4_16_samples_outputs/psa-action-profile2-frontend.p4, testdata/p4_16_samples_outputs/psa-action-profile2-midend.p4, testdata/p4_16_samples_outputs/psa-action-profile2.p4, testdata/p4_16_samples_outputs/psa-action-profile3-first.p4, testdata/p4_16_samples_outputs/psa-action-profile3-frontend.p4, testdata/p4_16_samples_outputs/psa-action-profile3-midend.p4, testdata/p4_16_samples_outputs/psa-action-profile3.p4, testdata/p4_16_samples_outputs/psa-action-profile4-first.p4, testdata/p4_16_samples_outputs/psa-action-profile4-frontend.p4, testdata/p4_16_samples_outputs/psa-action-profile4-midend.p4, testdata/p4_16_samples_outputs/psa-action-profile4.p4, testdata/p4_16_samples_outputs/psa-action-selector2-first.p4, testdata/p4_16_samples_outputs/psa-action-selector2-frontend.p4, testdata/p4_16_samples_outputs/psa-action-selector2-midend.p4, testdata/p4_16_samples_outputs/psa-action-selector2.p4, testdata/p4_16_samples_outputs/psa-action-selector3-first.p4, testdata/p4_16_samples_outputs/psa-action-selector3-frontend.p4, testdata/p4_16_samples_outputs/psa-action-selector3-midend.p4, testdata/p4_16_samples_outputs/psa-action-selector3.p4
missed one from previous commit ...
=> update psa action selector/profile tests to include action data

control-plane/p4RuntimeSerializer.cpp
sets
Currently we support only `Type_Bit` and `structs` for parser value sets. This PR extends support for `serializabe enums`.
=> Add serializable enum support for p4runtime generation of parser value

backends/ebpf/build_libbpf, backends/ebpf/runtime/ebpf_common.h, backends/ebpf/runtime/ebpf_kernel.h, backends/ebpf/runtime/ebpf_test.h, testdata/extern_modules/extern-checksum-ebpf.c
=> Move byte order into targets.

backends/ebpf/README.md
Add instructions to the readme to avoid confusion about libbpf.
=> Add libbpf description to eBPF readme

frontends/p4/actionsInlining.cpp, ir/ir.def, testdata/p4_16_errors/issue2413.p4, testdata/p4_16_errors_outputs/issue2413-first.p4, testdata/p4_16_errors_outputs/issue2413.p4, testdata/p4_16_errors_outputs/issue2413.p4-stderr, testdata/p4_16_errors_outputs/issue513.p4-stderr
=> Check if all parameters have arguments in action calls

midend/local_copyprop.cpp, midend/local_copyprop.h, testdata/p4_16_samples/global_action_after_exit.p4, testdata/p4_16_samples/key_after_exit.p4, testdata/p4_16_samples_outputs/global_action_after_exit-first.p4, testdata/p4_16_samples_outputs/global_action_after_exit-frontend.p4, testdata/p4_16_samples_outputs/global_action_after_exit-midend.p4, testdata/p4_16_samples_outputs/global_action_after_exit.p4, testdata/p4_16_samples_outputs/global_action_after_exit.p4.p4info.txt, testdata/p4_16_samples_outputs/key_after_exit-first.p4, testdata/p4_16_samples_outputs/key_after_exit-frontend.p4, testdata/p4_16_samples_outputs/key_after_exit-midend.p4, testdata/p4_16_samples_outputs/key_after_exit.p4, testdata/p4_16_samples_outputs/key_after_exit.p4-stderr, testdata/p4_16_samples_outputs/psa-register-read-write-bmv2-first.p4, testdata/p4_16_samples_outputs/psa-register-read-write-bmv2-frontend.p4, testdata/p4_16_samples_outputs/psa-register-read-write-bmv2-midend.p4, testdata/p4_16_samples_outputs/psa-register-read-write-bmv2.p4, testdata/p4_16_samples_outputs/psa-register-read-write-bmv2.p4.p4info.txt
- add a flag (defaults to false) that controls what to do about unused
tables and actions in a control.  If it is false, treat the
table/action as if it is used and don't eliminate control locals that
it uses.  If true, then eliminate the unused tables/actions (along
with unused control locals), so as to not leave undefined references.
=> LocalCopyProp enhancements for unused tables/actions

p4include/ubpf_model.p4, testdata/p4_16_samples/spec-ex25.p4, testdata/p4_16_samples_outputs/spec-ex25-first.p4, testdata/p4_16_samples_outputs/spec-ex25.p4
This also improves slightly an old test.
=> Remove incorrect ubpf_model.p4

frontends/p4/evaluator/evaluator.h, testdata/p4_16_samples/specIssue884.p4, testdata/p4_16_samples_outputs/checksum-l4-bmv2-midend.p4, testdata/p4_16_samples_outputs/specIssue884-first.p4, testdata/p4_16_samples_outputs/specIssue884-frontend.p4, testdata/p4_16_samples_outputs/specIssue884-midend.p4, testdata/p4_16_samples_outputs/specIssue884.p4, testdata/p4_16_samples_outputs/specIssue884.p4-stderr
=> String literals are constants

testdata/p4_16_samples/psa-register-read-write-2-bmv2.p4, testdata/p4_16_samples/psa-register-read-write-2-bmv2.stf, testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2-first.p4, testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2-frontend.p4, testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2-midend.p4, testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4, testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4-stderr, testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4.p4info.txt
This one explicitly checks that writes to indexes outside of the range
of the register array do not modify any element of the register array.
=> Add another PSA test of Register extern

frontends/p4/validateParsedProgram.cpp, testdata/p4_16_errors/issue2525.p4, testdata/p4_16_errors_outputs/issue2525.p4, testdata/p4_16_errors_outputs/issue2525.p4-stderr, testdata/p4_16_samples_outputs/default-switch.p4-stderr
=> Rejet switch statements with two default labels

BUILD.bazel, bazel/example/BUILD.bazel, bazel/p4c_deps.bzl
This PR makes no semantic changes.
It simplifies and improves the Bazel BUILD file following best practices.
=> Improved Bazel BUILD file

frontends/p4/toP4/toP4.cpp
This PR does not make semantic changes; it refactors code that caused nasty linking errors on some platforms.
Removing the relative indexing fixed the issue.
=> Avoid linking errors.

BUILD.bazel
Sorry for the noise @mbudiu-vmw.
=> Remove redundant license comment to avoid future inconsistencies.

bazel/p4_library.bzl
...making it work on platforms where cc may not be on the PATH.
=> Make p4_library Bazel rule more portable

frontends/parsers/p4/p4parser.ypp, testdata/p4_16_errors_outputs/table-entries-exact-ternary.p4, testdata/p4_16_errors_outputs/table-entries-exact-ternary.p4-stderr, testdata/p4_16_samples/issue2514.p4, testdata/p4_16_samples_outputs/issue2514-first.p4, testdata/p4_16_samples_outputs/issue2514-frontend.p4, testdata/p4_16_samples_outputs/issue2514-midend.p4, testdata/p4_16_samples_outputs/issue2514.p4
Fixed #2514 
This will require a spec change too.
=> Allow tuples with a single element in key expressions

frontends/common/constantFolding.cpp, ir/type.cpp, testdata/p4_16_errors/issue2496.p4, testdata/p4_16_errors_outputs/issue2496.p4, testdata/p4_16_errors_outputs/issue2496.p4-stderr
=> Check width limits in more places

testdata/p4_16_samples/psa-e2e-cloning-basic-bmv2.p4, testdata/p4_16_samples/psa-e2e-cloning-basic-bmv2.stf, testdata/p4_16_samples_outputs/psa-e2e-cloning-basic-bmv2-first.p4, testdata/p4_16_samples_outputs/psa-e2e-cloning-basic-bmv2-frontend.p4, testdata/p4_16_samples_outputs/psa-e2e-cloning-basic-bmv2-midend.p4, testdata/p4_16_samples_outputs/psa-e2e-cloning-basic-bmv2.p4, testdata/p4_16_samples_outputs/psa-e2e-cloning-basic-bmv2.p4.p4info.txt
This PR is comprised of psa-e2e-cloning-basic-bmv2.p4/stf and generated sample output files.
e2e cloning implementation:
https://github.com/p4lang/behavioral-model/pull/947
=> [psa] e2e cloning bmv2 stf tests

frontends/common/constantFolding.cpp, testdata/p4_16_samples/constStruct.p4, testdata/p4_16_samples_outputs/constStruct-first.p4, testdata/p4_16_samples_outputs/constStruct-frontend.p4, testdata/p4_16_samples_outputs/constStruct-midend.p4, testdata/p4_16_samples_outputs/constStruct.p4, testdata/p4_16_samples_outputs/constStruct.p4-stderr
The code contains an example of a bug that is being fixed.
=> Do not constant fold structs before typing

midend/nestedStructs.cpp, midend/nestedStructs.h, testdata/p4_16_errors/issue2545.p4, testdata/p4_16_errors_outputs/issue2545-first.p4, testdata/p4_16_errors_outputs/issue2545-frontend.p4, testdata/p4_16_errors_outputs/issue2545.p4, testdata/p4_16_errors_outputs/issue2545.p4-stderr
=> Give error message for unsupported construct

frontends/p4/inlining.cpp, frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_14_samples_outputs/issue1237.p4-stderr, testdata/p4_16_samples/issue1958.p4, testdata/p4_16_samples/issue2542.p4, testdata/p4_16_samples_outputs/issue1958-first.p4, testdata/p4_16_samples_outputs/issue1958-frontend.p4, testdata/p4_16_samples_outputs/issue1958-midend.p4, testdata/p4_16_samples_outputs/issue1958.p4, testdata/p4_16_samples_outputs/issue1958.p4.p4info.txt, testdata/p4_16_samples_outputs/issue2542-first.p4, testdata/p4_16_samples_outputs/issue2542-frontend.p4, testdata/p4_16_samples_outputs/issue2542-midend.p4, testdata/p4_16_samples_outputs/issue2542.p4, testdata/p4_16_samples_outputs/issue2542.p4-stderr, testdata/p4_16_samples_outputs/key_after_exit.p4-stderr, testdata/p4_16_samples_outputs/spec-ex25.p4-stderr
=> Substitute directionless parameters early in inlining

frontends/CMakeLists.txt, frontends/parsers/p4/p4parser.ypp, p4include/ubpf_model.p4
Fixes #2553 
I have also tweaked the makefile to fail compilation of the grammar has a conflict; this will prevent this kind of problem from happening in the future.
=> Eliminate grammar ambiguity

frontends/p4/sideEffects.cpp, frontends/p4/structInitializers.cpp, frontends/p4/structInitializers.h, ir/expression.def, ir/indexed_vector.h, ir/ir.def, testdata/p4_16_samples/issue2543-1.p4, testdata/p4_16_samples/issue2543-2.p4, testdata/p4_16_samples/parenthesis-test_ubpf.p4, testdata/p4_16_samples_outputs/issue2383-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2383-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2488-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2488-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2543-1-first.p4, testdata/p4_16_samples_outputs/issue2543-1-frontend.p4, testdata/p4_16_samples_outputs/issue2543-1-midend.p4, testdata/p4_16_samples_outputs/issue2543-1.p4, testdata/p4_16_samples_outputs/issue2543-2-first.p4, testdata/p4_16_samples_outputs/issue2543-2-frontend.p4, testdata/p4_16_samples_outputs/issue2543-2-midend.p4, testdata/p4_16_samples_outputs/issue2543-2.p4, testdata/p4_16_samples_outputs/parenthesis-test_ubpf-first.p4, testdata/p4_16_samples_outputs/parenthesis-test_ubpf-frontend.p4, testdata/p4_16_samples_outputs/parenthesis-test_ubpf-midend.p4, testdata/p4_16_samples_outputs/parenthesis-test_ubpf.p4, testdata/p4_16_samples_outputs/parenthesis-test_ubpf.p4.p4info.txt
IndexedVector had a validation function, but it was never called. If it was, it would have caught one of these two bugs.
Fixes #2543
=> Fix bugs related to StructureExpressions

frontends/CMakeLists.txt, frontends/p4/frontend.cpp, frontends/p4/reassociation.cpp, frontends/p4/reassociation.h, frontends/p4/strengthReduction.cpp, frontends/p4/strengthReduction.h, testdata/p4_16_samples/issue2585.p4, testdata/p4_16_samples_outputs/bool_ebpf-first.p4, testdata/p4_16_samples_outputs/bool_ebpf-frontend.p4, testdata/p4_16_samples_outputs/fabric_20190420/fabric-first.p4, testdata/p4_16_samples_outputs/fabric_20190420/fabric-frontend.p4, testdata/p4_16_samples_outputs/fabric_20190420/fabric-midend.p4, testdata/p4_16_samples_outputs/issue2488-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2543-2-midend.p4, testdata/p4_16_samples_outputs/issue2585-first.p4, testdata/p4_16_samples_outputs/issue2585-frontend.p4, testdata/p4_16_samples_outputs/issue2585-midend.p4, testdata/p4_16_samples_outputs/issue2585.p4, testdata/p4_16_samples_outputs/issue737-bmv2-first.p4, testdata/p4_16_samples_outputs/issue737-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue737-bmv2-midend.p4, testdata/p4_16_samples_outputs/ubpf_checksum_extern-first.p4, testdata/p4_16_samples_outputs/ubpf_checksum_extern-frontend.p4, testdata/p4_16_samples_outputs/ubpf_checksum_extern-midend.p4
=> Reassociation pass; two more strength-reduction optimizations

.github/workflows/ci-bazel.yml
This should speed up CI quite a bit, starting with the first run after this PR.
=> Update CI script to improve caching.

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue2597.p4, testdata/p4_16_errors_outputs/call-table.p4-stderr, testdata/p4_16_errors_outputs/issue2597.p4, testdata/p4_16_errors_outputs/issue2597.p4-stderr, testdata/p4_16_errors_outputs/issue816.p4-stderr
=> Do not allow apply calls in actions

frontends/p4/def_use.h, ir/node.h
Signed-off-by: Steve King <steven.r.king@intel.com>
=> Fixed warnings about deprecated default copy.

frontends/common/constantFolding.cpp, frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue2444-1.p4, testdata/p4_16_errors_outputs/issue2444-1.p4, testdata/p4_16_errors_outputs/issue2444-1.p4-stderr, testdata/p4_16_samples/issue2444.p4, testdata/p4_16_samples_outputs/issue2444-first.p4, testdata/p4_16_samples_outputs/issue2444.p4, testdata/p4_16_samples_outputs/issue2444.p4-stderr
=> Allow casts between int and bool

backends/dpdk/dbprint-dpdk.cpp, backends/dpdk/dpdk.def, backends/dpdk/dpdkHelpers.cpp, backends/dpdk/spec.cpp, testdata/p4_16_samples/psa-remove-header.p4
pretty straightforward translation.
`h.setValid() -> validate h`
`h.setInvalid() -> invalidate h`
=> DPDK: add support for h.setValid and h.setInvalid

control-plane/p4RuntimeArchStandard.cpp, frontends/CMakeLists.txt, frontends/common/constantFolding.cpp, frontends/p4/enumInstance.h, frontends/p4/frontend.cpp, frontends/p4/simplifySwitch.cpp, frontends/p4/simplifySwitch.h, ir/ir.def, testdata/p4_16_samples/issue2617.p4, testdata/p4_16_samples_outputs/issue2617-first.p4, testdata/p4_16_samples_outputs/issue2617-frontend.p4, testdata/p4_16_samples_outputs/issue2617-midend.p4, testdata/p4_16_samples_outputs/issue2617.p4, testdata/p4_16_samples_outputs/issue2617.p4-stderr
Also fix a bug related to constant-folding selects statements with enum values.
Fixes #2617
=> Constant-fold switch statements

backends/bmv2/simple_switch/simpleSwitch.cpp, control-plane/p4RuntimeArchStandard.cpp, frontends/p4/structInitializers.cpp, frontends/p4/typeChecking/typeConstraints.h, testdata/p4_16_samples/issue2648.p4, testdata/p4_16_samples_outputs/issue2648-first.p4, testdata/p4_16_samples_outputs/issue2648-frontend.p4, testdata/p4_16_samples_outputs/issue2648-midend.p4, testdata/p4_16_samples_outputs/issue2648.p4
=> Use the type for the original IR node

backends/ebpf/codeGen.cpp, backends/ebpf/lower.cpp, testdata/p4_16_samples/op_bin.p4, testdata/p4_16_samples_outputs/op_bin-first.p4, testdata/p4_16_samples_outputs/op_bin-frontend.p4, testdata/p4_16_samples_outputs/op_bin-midend.p4, testdata/p4_16_samples_outputs/op_bin.p4, testdata/p4_16_samples_outputs/predication_issue.p4.p4info.txt
Add parenthesis to Operation_Binary to fix gcc compile error reported in https://github.com/p4lang/p4c/issues/2670
`expressionPrecedence` doesn't work for Operation_Binary yet that would also fix the gcc compile error.  
Another fix is to print, e.g., `0xffff0000` instead of its decimal format.
=> Fix for p4c Issue 2670

backends/bmv2/CMakeLists.txt, backends/bmv2/common/expression.cpp, testdata/p4_16_samples/issue2664-bmv2.p4, testdata/p4_16_samples_outputs/issue2664-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2664-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2664-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2664-bmv2.p4, testdata/p4_16_samples_outputs/issue2664-bmv2.p4.p4info.txt
=> Do not crash when handling unknown externs

backends/dpdk/CMakeLists.txt, backends/dpdk/DpdkXfail.cmake, backends/dpdk/run-dpdk-test.py, cmake/P4CUtils.cmake
Reusing the p4test script with minor modification
=> Add regression script for dpdk backend

frontends/common/constantFolding.cpp
=> Missing null pointer check

CMakeLists.txt, backends/p4test/p4test.cpp
=> Do not dump json when program is null because of an error

backends/dpdk/DpdkXfail.cmake, backends/dpdk/dpdkHelpers.cpp
Fixes the bug described by #2682
=> Fix uninitialized variable

CMakeLists.txt, frontends/common/model.h, lib/algorithm.h, lib/alloc.h, lib/backtrace.h, lib/bitops.h, lib/bitvec.h, lib/compile_context.h, lib/cstring.h, lib/enumerator.h, lib/error.h, lib/error_catalog.h, lib/error_helper.h, lib/error_reporter.h, lib/exceptions.h, lib/hex.h, lib/indent.h, lib/log.h, lib/ltbitmatrix.h, lib/map.h, lib/nullstream.h, lib/ordered_set.h, lib/path.h, lib/safe_vector.h, lib/sourceCodeBuilder.h, lib/source_file.h, lib/stringify.h, lib/stringref.h, lib/symbitmatrix.h
- Improved CMakeLists.txt:
* Added support for creating a tarball with "make dist".
* Need to compile with -Wno-deprecated-declarations.
- Fixed define in includes to correspond to the actual include file name.
=> Some build fixes

frontends/common/options.cpp, frontends/common/options.h, frontends/common/parser_options.cpp, frontends/common/parser_options.h, lib/options.cpp
Clean up options some more. Push some more options down from the parser options and differentiate the additional usage section from the rest of the arguments.
=> More options cleanup

frontends/p4/fromv1.0/programStructure.cpp, frontends/p4/fromv1.0/v1model.h, frontends/p4/modelInstances.cpp, ir/type.cpp, ir/type.def
@ChrisDodd: this addresses the comment you made in an already merged PR.
=> Remove inlined constant from code

frontends/p4/inlining.cpp, frontends/p4/inlining.h, testdata/p4_16_samples/annotation-inline-propagate.p4, testdata/p4_16_samples_outputs/annotation-inline-propagate-first.p4, testdata/p4_16_samples_outputs/annotation-inline-propagate-frontend.p4, testdata/p4_16_samples_outputs/annotation-inline-propagate-midend.p4, testdata/p4_16_samples_outputs/annotation-inline-propagate.p4, testdata/p4_16_samples_outputs/annotation-inline-propagate.p4.p4info.txt
Copy annotations when inlining ControlBlock and ParserBlock objects.
Please let me know what you think of this approach to solve #2727 
There's also the open question of whether we should propagate all or a subset of annotations. Any opinions on how to proceed here?
=> propagate annotations when inlining blocks (#2727)

frontends/p4/typeChecking/bindVariables.cpp, testdata/p4_16_samples/issue2735-bmv2.p4, testdata/p4_16_samples/issue2735.p4, testdata/p4_16_samples_outputs/issue2735-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2735-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2735-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2735-bmv2.p4, testdata/p4_16_samples_outputs/issue2735-bmv2.p4.p4info.txt, testdata/p4_16_samples_outputs/issue2735-first.p4, testdata/p4_16_samples_outputs/issue2735-frontend.p4, testdata/p4_16_samples_outputs/issue2735.p4, testdata/p4_16_samples_outputs/issue2735.p4-stderr
=> Handle typedefs of generic types

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue2726-bmv2.p4, testdata/p4_16_samples_outputs/issue2726-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2726-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2726-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2726-bmv2.p4, testdata/p4_16_samples_outputs/issue2726-bmv2.p4.p4info.txt
=> Support serenum types for array indexes

backends/dpdk/run-dpdk-test.py
This pull request makes a few minor improvements to the `run-dpdk-test.py` script.
=> Minor run-dpdk-test improvements

backends/dpdk/dpdkArch.h, frontends/p4/def_use.h, test/gtest/parser_unroll.cpp, tools/install_mac_deps.sh
Instead of using brew to install the latest version of protobuf we compile explicitly the recommended version 3.6.1
=> Attempt to fix Mac build breakage

backends/bmv2/common/extern.cpp, testdata/p4_16_samples/issue2657-bmv2.p4, testdata/p4_16_samples_outputs/issue2657-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2657-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2657-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2657-bmv2.p4, testdata/p4_16_samples_outputs/issue2657-bmv2.p4.p4info.txt
Fixes #2657 
As the issue discusses, there are actually 2 bugs in that issue, but one of them is addressed already by #2637 which is waiting for review, so I won't replicate that code here. This fix is however enough to make this test pass.
=> Expand structs into lists for bmv2 backend computations

backends/ebpf/ebpfParser.cpp, backends/ubpf/ubpfParser.cpp, testdata/p4_16_samples/issue2797_ebpf.p4, testdata/p4_16_samples_outputs/issue2797_ebpf-first.p4, testdata/p4_16_samples_outputs/issue2797_ebpf-frontend.p4, testdata/p4_16_samples_outputs/issue2797_ebpf-midend.p4, testdata/p4_16_samples_outputs/issue2797_ebpf.p4
Fixes #2797 
The bug exists in the UBPF back-end too, so I fixed it there too.
@osinstom : can you please validate this fix?
=> Fix bug in ebpf C code generation for parsers

frontends/common/parser_options.cpp, frontends/common/parser_options.h
Add support for backend to specify more search paths for p4include directory.
=> support additional search path for p4include directory from backend

backends/bmv2/common/control.h
=> Set table size when entries are known

testdata/p4_16_samples/issue2321.p4, testdata/p4_16_samples_outputs/issue2321-first.p4, testdata/p4_16_samples_outputs/issue2321-frontend.p4, testdata/p4_16_samples_outputs/issue2321-midend.p4, testdata/p4_16_samples_outputs/issue2321.p4, testdata/p4_16_samples_outputs/issue2321.p4.p4info.txt
Fixes #2321 
The bug was in fact fixed by #2820
=> Test case for issue #2321

p4include/pna.p4, testdata/p4_16_samples/pna-example-template.p4, testdata/p4_16_samples_outputs/pna-example-template-first.p4, testdata/p4_16_samples_outputs/pna-example-template-frontend.p4, testdata/p4_16_samples_outputs/pna-example-template-midend.p4, testdata/p4_16_samples_outputs/pna-example-template.p4
I have added pna.p4 to p4include to get folks started on writing pna programs. So far, people only need p4test to work to write syntactically correct pna programs. 
Backend support is work-in-progress.
=> initial commit for pna.p4

backends/dpdk/dpdkArch.cpp, testdata/p4_16_samples/psa-dpdk-table-key-consolidation-mixed-keys-1.p4, testdata/p4_16_samples/psa-dpdk-table-key-consolidation-mixed-keys-2.p4, testdata/p4_16_samples/psa-dpdk-table-key-consolidation-mixed-keys-3.p4, testdata/p4_16_samples/psa-dpdk-table-key-consolidation-mixed-keys.p4, testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-1.p4.spec, testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-2.p4.spec, testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-3.p4.spec, testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys.p4.spec
This PR is for the same issue as in the 
https://github.com/p4lang/p4c/pull/2864
Resubmitting with a cleaner commit log
=> Fixing table key consolidation criteria

backends/bmv2/psa_switch/psaSwitch.cpp, backends/dpdk/control-plane/bfruntime_ext.cpp, backends/dpdk/control-plane/bfruntime_ext.h, backends/dpdk/midend.cpp, control-plane/bfruntime.cpp, control-plane/bfruntime.h, ir/base.cpp, midend/predication.cpp
=> Print unparsed annotations differently

backends/dpdk/DpdkXfail.cmake, backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkArch.h, testdata/p4_16_samples_outputs/psa-end-of-ingress-test-bmv2.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-end-of-ingress-test-bmv2.p4.spec, testdata/p4_16_samples_outputs/psa-example-dpdk-varbit.p4.spec, testdata/p4_16_samples_outputs/psa-example-register2-bmv2.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-example-register2-bmv2.p4.spec, testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-recirculate-no-meta-bmv2.p4.spec
The changes include the following:
1) Fix handling of Unary operations in ExpressionUnroll and LogicalExpressionUnroll passes.
2) Remove explicit preorder function for Cast. Cast expression should be checked for further  unrolling and hence the preorder function for Cast operation would exactly be the same as the one for Unary operations.
3) Update XFAIL list and reference outputs for the tests that started passing with these changes.
=> DPDK Backend: Fix minor issues in handling Unary operations

test/gtest/helpers.cpp, test/gtest/helpers.h
- allow loading custom headers in additional tests
=> Minor gtest helper refactor to make it easier to extend

frontends/p4/def_use.cpp, testdata/p4_16_samples/next-def-use.p4, testdata/p4_16_samples_outputs/next-def-use-first.p4, testdata/p4_16_samples_outputs/next-def-use-frontend.p4, testdata/p4_16_samples_outputs/next-def-use-midend.p4, testdata/p4_16_samples_outputs/next-def-use.p4, testdata/p4_16_samples_outputs/next-def-use.p4.p4info.txt
=> Def-use should not treat array.next as a structure field

.github/workflows/ci-container-image.yml
This pull request adds a GitHub action that would build a container image and push it to a container registry.
Closes #2965
=> ci: Auto-build container image

midend/hsIndexSimplify.cpp, midend/hsIndexSimplify.h
This changes contain some update according review of #2914
=> HS index unroller simple update

backends/bmv2/psa_switch/psaSwitch.cpp, backends/ebpf/targets/xdp_target.py, control-plane/p4RuntimeSerializer.cpp, frontends/p4/directCalls.cpp, frontends/p4/frontend.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeChecker.h, frontends/p4/typeMap.cpp, frontends/p4/typeMap.h, ir/base.def, ir/ir.cpp, ir/type.cpp, ir/type.def, midend/expandLookahead.cpp, testdata/p4_16_errors/minWidth.p4, testdata/p4_16_errors_outputs/minWidth.p4, testdata/p4_16_errors_outputs/minWidth.p4-stderr, testdata/p4_16_errors_outputs/stack_e.p4-stderr, testdata/p4_16_samples/issue1717.p4, testdata/p4_16_samples/minsize.p4, testdata/p4_16_samples_outputs/issue1717-first.p4, testdata/p4_16_samples_outputs/issue1717-frontend.p4, testdata/p4_16_samples_outputs/issue1717-midend.p4, testdata/p4_16_samples_outputs/issue1717.p4, testdata/p4_16_samples_outputs/issue1717.p4-stderr, testdata/p4_16_samples_outputs/minsize-first.p4, testdata/p4_16_samples_outputs/minsize-frontend.p4, testdata/p4_16_samples_outputs/minsize-midend.p4, testdata/p4_16_samples_outputs/minsize.p4
A proposal solution for https://github.com/p4lang/p4-spec/issues/937
=> Support minSizeInBits and minSizeInBytes for scalars and type names

frontends/p4/sideEffects.cpp, ir/visitor.cpp, testdata/p4_16_samples/issue3001-1.p4, testdata/p4_16_samples/issue3001.p4, testdata/p4_16_samples_outputs/issue3001-1-first.p4, testdata/p4_16_samples_outputs/issue3001-1-frontend.p4, testdata/p4_16_samples_outputs/issue3001-1-midend.p4, testdata/p4_16_samples_outputs/issue3001-1.p4, testdata/p4_16_samples_outputs/issue3001-1.p4-stderr, testdata/p4_16_samples_outputs/issue3001-1.p4.p4info.txt, testdata/p4_16_samples_outputs/issue3001-first.p4, testdata/p4_16_samples_outputs/issue3001-frontend.p4, testdata/p4_16_samples_outputs/issue3001-midend.p4, testdata/p4_16_samples_outputs/issue3001.p4, testdata/p4_16_samples_outputs/issue3001.p4-stderr
=> Remove BUG_CHECK which is too conservative

backends/dpdk/dpdkHelpers.cpp, testdata/p4_16_samples/pna-example-SelectByDirection.p4, testdata/p4_16_samples/pna-example-SelectByDirection1.p4, testdata/p4_16_samples/pna-example-SelectByDirection2.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection-first.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection-frontend.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection-midend.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection.p4.spec, testdata/p4_16_samples_outputs/pna-example-SelectByDirection1-first.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection1-frontend.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection1-midend.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection1.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection1.p4.spec, testdata/p4_16_samples_outputs/pna-example-SelectByDirection2-first.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection2-frontend.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection2-midend.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection2.p4, testdata/p4_16_samples_outputs/pna-example-SelectByDirection2.p4.spec
This PR adds support for SelectByDirection PNA extern.
SelectByDirection is implemented as if-else statement based on the direction.
`bit <T> var = SelectByDirection<T>(in PNA_Direction_t direction, in T n2h_value, in T h2n_value);`
is replaced by 
```
if (direction == PNA_Direction_t.NET_TO_HOST) {
var = n2h_value;
} else {
var = return h2n_value;
}
```
Some tests are added to cover statements where SelectByDirection can possibly be used.
1) as table key
2) as an operand of comparison
3) as action parameter
In all the cases, a temporary variable is inserted by midend passes and the call to SelectByDirection is assigned to this temporary. Backend needs to handle this Method call only as RHS of assignment.
=> DPDK Backend: Add support for SelectByDirection PNA extern

control-plane/p4RuntimeSerializer.cpp, testdata/p4_16_samples/issue2904.p4, testdata/p4_16_samples_outputs/issue2904-first.p4, testdata/p4_16_samples_outputs/issue2904-frontend.p4, testdata/p4_16_samples_outputs/issue2904-midend.p4, testdata/p4_16_samples_outputs/issue2904.p4, testdata/p4_16_samples_outputs/issue2904.p4-stderr, testdata/p4_16_samples_outputs/issue2904.p4.entries.txt, testdata/p4_16_samples_outputs/issue2904.p4.p4info.txt
=> Support p4runtime info for serenum action arguments

frontends/p4/sideEffects.h, testdata/p4_16_errors/issue2835-bmv2.p4, testdata/p4_16_errors_outputs/issue2835-bmv2-first.p4, testdata/p4_16_errors_outputs/issue2835-bmv2.p4, testdata/p4_16_errors_outputs/issue2835-bmv2.p4-stderr
=> Disallow programs that call tables in the 'actions' table property

frontends/p4/typeChecking/typeChecker.cpp, midend/simplifySelectCases.cpp, testdata/p4_14_samples_outputs/parser_pragma2.p4-stderr, testdata/p4_16_errors/pr2918.p4, testdata/p4_16_errors_outputs/pr2918.p4, testdata/p4_16_errors_outputs/pr2918.p4-stderr, testdata/p4_16_samples_outputs/default2.p4-stderr
Related to https://github.com/p4lang/p4-spec/pull/968
=> Check the types of sub-expressions involved in a select expression

frontends/parsers/p4/p4parser.ypp, testdata/p4_16_samples/issue2905-bmv2.p4, testdata/p4_16_samples/issue2905.p4, testdata/p4_16_samples_outputs/issue2905-bmv2-first.p4, testdata/p4_16_samples_outputs/issue2905-bmv2-frontend.p4, testdata/p4_16_samples_outputs/issue2905-bmv2-midend.p4, testdata/p4_16_samples_outputs/issue2905-bmv2.p4, testdata/p4_16_samples_outputs/issue2905-bmv2.p4.p4info.txt, testdata/p4_16_samples_outputs/issue2905-first.p4, testdata/p4_16_samples_outputs/issue2905-frontend.p4, testdata/p4_16_samples_outputs/issue2905.p4, testdata/p4_16_samples_outputs/issue2905.p4-stderr
=> Allow empty entries lists for tables

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue2810.p4, testdata/p4_16_samples_outputs/issue2810-first.p4, testdata/p4_16_samples_outputs/issue2810-frontend.p4, testdata/p4_16_samples_outputs/issue2810-midend.p4, testdata/p4_16_samples_outputs/issue2810.p4
=> Do not require explicit types for type variables of optional parameters

backends/ebpf/targets/xdp_target.py, frontends/p4/toP4/toP4.h, frontends/p4/typeChecking/typeChecker.h, frontends/p4/typeChecking/typeSubstitutionVisitor.cpp, frontends/p4/typeChecking/typeUnification.cpp, frontends/p4/typeMap.cpp, ir/base.def, ir/ir.def, ir/type.def, testdata/p4_16_errors/issue3045-1.p4, testdata/p4_16_errors/issue3045-2.p4, testdata/p4_16_errors/issue3045.p4, testdata/p4_16_errors_outputs/issue3045-1.p4, testdata/p4_16_errors_outputs/issue3045-1.p4-stderr, testdata/p4_16_errors_outputs/issue3045-2.p4, testdata/p4_16_errors_outputs/issue3045-2.p4-stderr, testdata/p4_16_errors_outputs/issue3045.p4, testdata/p4_16_errors_outputs/issue3045.p4-stderr
=> Unification for generic types must compare type arguments too

frontends/p4/inlining.cpp, frontends/p4/parameterSubstitution.cpp, testdata/p4_16_samples/issue3051.p4, testdata/p4_16_samples_outputs/issue3051-first.p4, testdata/p4_16_samples_outputs/issue3051-frontend.p4, testdata/p4_16_samples_outputs/issue3051-midend.p4, testdata/p4_16_samples_outputs/issue3051.p4
=> Optional parameters may not have initializers

backends/dpdk/dpdkProgram.cpp, backends/dpdk/spec.cpp, testdata/p4_16_samples_outputs/pna-add-on-miss.p4.spec
* Do not emit semicolon at end of learn statement
* Do not append _0 in learner table name
=> Fix issues in generated learner table and statement for dpdk

midend/interpreter.cpp, testdata/p4_16_samples/bool_to_bit_cast.p4, testdata/p4_16_samples_outputs/bool_to_bit_cast-first.p4, testdata/p4_16_samples_outputs/bool_to_bit_cast-frontend.p4, testdata/p4_16_samples_outputs/bool_to_bit_cast-midend.p4, testdata/p4_16_samples_outputs/bool_to_bit_cast.p4, testdata/p4_16_samples_outputs/bool_to_bit_cast.p4.p4info.txt
Solving problem with `Cast` when the expression is a `SymbolicValue` .
Test for example : bool_to_bit_cast.p4,
@mbudiu-vmw Changes in the past PR proved useless. We found out that `PassRepeated` pass which is set in your midend does similar calculations. We believe that it is necessary to add a note that for the correct operation of `ParserUnroll`, should use `PassRepeated` before `ParserUnroll`.
=> Solve some problems with cast

frontends/common/constantFolding.cpp, frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue3056.p4, testdata/p4_16_samples_outputs/issue3056-first.p4, testdata/p4_16_samples_outputs/issue3056.p4, testdata/p4_16_samples_outputs/issue3056.p4-stderr
=> Handle implicit serenum casts in more circumstances

.github/.travis.yml.disabled, .github/workflows/ci-static-build-test.yml, .github/workflows/ci-test.yml, .github/workflows/ci-validation.yml, CMakeLists.txt, Dockerfile, README.md, tools/ci-build.sh
Some changes are required for the Docker build now that the base
image is Ubuntu 20.04.
=> Updates for Ubuntu 20.04

backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkArch.h, backends/dpdk/dpdkProgramStructure.cpp, backends/dpdk/dpdkProgramStructure.h, testdata/p4_16_samples/pna-action-selector.p4, testdata/p4_16_samples_outputs/pna-action-selector-first.p4, testdata/p4_16_samples_outputs/pna-action-selector-frontend.p4, testdata/p4_16_samples_outputs/pna-action-selector-midend.p4, testdata/p4_16_samples_outputs/pna-action-selector.p4, testdata/p4_16_samples_outputs/pna-action-selector.p4-error, testdata/p4_16_samples_outputs/pna-action-selector.p4-stderr, testdata/p4_16_samples_outputs/pna-action-selector.p4.spec
This PR fixes action selector and action profile related table generation for DPDK backend.
Changes include:
- Fix to pick the table property based on architecture.
- New test and reference outputs for PNA program using action selector
=> DPDK Backend: Fix action selector and action profile support for PNA architecture

backends/ebpf/ebpfParser.cpp
Fixes https://github.com/p4lang/p4c/issues/3092
=> Emit semicolon after method call

backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkArch.h, testdata/p4_16_samples/psa-dpdk-flatten-local-struct.p4, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct-first.p4, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct-frontend.p4, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct-midend.p4, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct.p4, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct.p4-error, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct.p4-stderr, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct.p4.p4info.txt, testdata/p4_16_samples_outputs/psa-dpdk-flatten-local-struct.p4.spec
When a local variable of struct type is declared within control/action body, this PR flatten the declared struct.
=> Flatten local struct decl in dpdk

lib/source_file.cpp
=> Fix off-by-one bug in source file position calculation

frontends/p4/fromv1.0/converters.cpp, frontends/parsers/v1/v1parser.ypp, ir/v1.def, testdata/p4_14_errors/issue3140.p4, testdata/p4_14_errors_outputs/issue3140.p4, testdata/p4_14_errors_outputs/issue3140.p4-stderr, testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4-error, testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4.bfrt.json, testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4.spec
=> Keep track of source position for p4-14 switch statement labels

frontends/common/constantFolding.cpp, frontends/common/constantFolding.h, frontends/p4/strengthReduction.cpp, frontends/p4/strengthReduction.h, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeChecker.h, frontends/parsers/p4/p4parser.ypp, ir/README.md, ir/dbprint-expression.cpp, ir/expression.def, testdata/p4_16_errors/issue3153.p4, testdata/p4_16_errors_outputs/issue3153.p4, testdata/p4_16_errors_outputs/issue3153.p4-stderr, testdata/p4_16_samples_outputs/expression.p4
=> Represent unary plus in the IR

lib/symbitmatrix.h
=> Fixed underflow during row-access in the SymBitMatrix (#3143)

frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeChecker.h, testdata/p4_16_errors/issue3170-1.p4, testdata/p4_16_errors_outputs/header2_e.p4-stderr, testdata/p4_16_errors_outputs/header3.p4-stderr, testdata/p4_16_errors_outputs/issue2290.p4-stderr, testdata/p4_16_errors_outputs/issue2454.p4-stderr, testdata/p4_16_errors_outputs/issue3170-1.p4, testdata/p4_16_errors_outputs/issue3170-1.p4-stderr, testdata/p4_16_errors_outputs/issue407-1.p4-stderr, testdata/p4_16_errors_outputs/stack_e.p4-stderr, testdata/p4_16_errors_outputs/string-e1.p4-stderr, testdata/p4_16_errors_outputs/string-e2.p4-stderr
=> Improve error messages during type checking

frontends/p4/specializeGenericTypes.cpp, testdata/p4_16_samples/issue3203.p4, testdata/p4_16_samples/issue3204.p4, testdata/p4_16_samples_outputs/issue3203-first.p4, testdata/p4_16_samples_outputs/issue3203-frontend.p4, testdata/p4_16_samples_outputs/issue3203.p4, testdata/p4_16_samples_outputs/issue3203.p4-stderr, testdata/p4_16_samples_outputs/issue3204-first.p4, testdata/p4_16_samples_outputs/issue3204-frontend.p4, testdata/p4_16_samples_outputs/issue3204.p4, testdata/p4_16_samples_outputs/issue3204.p4-stderr
=> Insert type specializations before functions

backends/ebpf/ebpfControl.cpp, backends/ebpf/ebpfTable.cpp, backends/ebpf/ebpfTable.h, backends/ebpf/psa/README.md, backends/ebpf/psa/ebpfPsaGen.cpp, backends/ebpf/psa/ebpfPsaTable.cpp, backends/ebpf/psa/ebpfPsaTable.h, backends/ebpf/psa/externs/ebpfPsaTableImplementation.cpp, backends/ebpf/psa/externs/ebpfPsaTableImplementation.h, backends/ebpf/tests/p4testdata/action-selector-action-run.p4, backends/ebpf/tests/p4testdata/action-selector-hit.p4, backends/ebpf/tests/p4testdata/action-selector-lpm.p4, backends/ebpf/tests/p4testdata/action-selector1.p4, backends/ebpf/tests/p4testdata/action-selector2.p4, backends/ebpf/tests/p4testdata/action-selector3.p4, backends/ebpf/tests/p4testdata/action-selector4.p4, backends/ebpf/tests/p4testdata/action-selector5.p4, backends/ebpf/tests/ptf/common.py, backends/ebpf/tests/ptf/table_implementation.py
This PR adds the support for ActionSelector extern to PSA/eBPF backend.
Co-authored-by: Mateusz Kossakowski <mateusz.kossakowski@orange.com>
=> Add support for ActionSelector extern to PSA/eBPF backend

.github/workflows/ci-bazel.yml, .github/workflows/ci-container-image.yml, .github/workflows/ci-ptf.yml, .github/workflows/ci-release.yml, .github/workflows/ci-static-build-test.yml, .github/workflows/ci-test.yml, .github/workflows/ci-validation.yml
=> Try to cancel previous Jenkins runs

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3221.p4, testdata/p4_16_errors_outputs/issue3221.p4, testdata/p4_16_errors_outputs/issue3221.p4-stderr
=> Fix error message for cast to 'type'

backends/ebpf/CMakeLists.txt, backends/ebpf/targets/ebpfstf.py, testdata/p4_16_samples/lpm_ebpf.stf
=> Fix incorrect C code generation for ebpf control plane

backends/ebpf/CMakeLists.txt, backends/ubpf/CMakeLists.txt, backends/ubpf/codeGen.h, backends/ubpf/midend.h, backends/ubpf/target.h, backends/ubpf/ubpfBackend.h, backends/ubpf/ubpfControl.h, backends/ubpf/ubpfDeparser.h, backends/ubpf/ubpfModel.h, backends/ubpf/ubpfParser.h, backends/ubpf/ubpfProgram.h, backends/ubpf/ubpfRegister.h, backends/ubpf/ubpfType.h, cmake/P4CUtils.cmake
=> UBPF backend header files were not cpplinted

backends/ebpf/psa/examples/l2l3-acl.p4, backends/ebpf/tests/ptf/l2l3_acl.py
This PR adds L2L3-ACL, a more complex sample PSA program for eBPF backend. 
Co-authored-by: Mateusz Kossakowski <mateusz.kossakowski@orange.com>
=> Add L2L3-ACL sample program for PSA/eBPF backend

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3246.p4, testdata/p4_16_errors_outputs/issue3246.p4, testdata/p4_16_errors_outputs/issue3246.p4-stderr, testdata/p4_16_samples/issue3246-1.p4, testdata/p4_16_samples_outputs/issue3246-1-first.p4, testdata/p4_16_samples_outputs/issue3246-1-frontend.p4, testdata/p4_16_samples_outputs/issue3246-1.p4, testdata/p4_16_samples_outputs/issue3246-1.p4-stderr
=> Stricter type checking for built-in methods

frontends/common/resolveReferences/resolveReferences.cpp, ir/expression.def, testdata/p4_16_errors/issue3264.p4, testdata/p4_16_errors_outputs/issue3264.p4, testdata/p4_16_errors_outputs/issue3264.p4-stderr
=> Do not crash on illegal uses of 'this'

backends/dpdk/backend.cpp, backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkArch.h, testdata/p4_16_samples/pna-elim-hdr-copy-dpdk.p4, testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4.spec, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk-first.p4, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk-frontend.p4, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk-midend.p4, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk.p4, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk.p4.bfrt.json, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk.p4.spec, testdata/p4_16_samples_outputs/pna-mux-dismantle.p4.spec
Dpdk does not support direct header copy.
So, Eliminate temporary copies of header, which generally populated after inlining, if it;s not temporary copy then transform direct header copy to element wise copy.
=> [dpdk] Eliminate header copy

frontends/p4/typeChecking/typeChecker.cpp, frontends/parsers/p4/p4parser.ypp, testdata/p4_16_errors/issue3273.p4, testdata/p4_16_errors_outputs/issue2335.p4-stderr, testdata/p4_16_errors_outputs/issue2354-1.p4-stderr, testdata/p4_16_errors_outputs/issue2354.p4-stderr, testdata/p4_16_errors_outputs/issue3045-1.p4-stderr, testdata/p4_16_errors_outputs/issue3045.p4-stderr, testdata/p4_16_errors_outputs/issue3273.p4, testdata/p4_16_errors_outputs/issue3273.p4-stderr, testdata/p4_16_errors_outputs/issue67.p4-stderr, testdata/p4_16_errors_outputs/mux_e.p4-stderr, testdata/p4_16_errors_outputs/string-e.p4-stderr, testdata/p4_16_errors_outputs/string-e1.p4-stderr, testdata/p4_16_errors_outputs/virtual1.p4-stderr
=> Forbid methods to return int or string

frontends/p4/validateParsedProgram.cpp, testdata/p4_16_errors/issue3210.p4, testdata/p4_16_errors/issue3271-1.p4, testdata/p4_16_errors/issue3271.p4, testdata/p4_16_errors_outputs/issue3210.p4, testdata/p4_16_errors_outputs/issue3210.p4-stderr, testdata/p4_16_errors_outputs/issue3271-1.p4, testdata/p4_16_errors_outputs/issue3271-1.p4-stderr, testdata/p4_16_errors_outputs/issue3271.p4, testdata/p4_16_errors_outputs/issue3271.p4-stderr
=> Forbid instantiations in functions or methods

backends/ebpf/ebpfOptions.cpp, backends/ebpf/p4c-ebpf.cpp, backends/p4test/run-p4-sample.py, ir/type.def, lib/nullstream.cpp, midend/eliminateSwitch.cpp, testdata/p4_16_errors/issue3299.p4, testdata/p4_16_errors_outputs/issue3299-first.p4, testdata/p4_16_errors_outputs/issue3299-frontend.p4, testdata/p4_16_errors_outputs/issue3299.p4, testdata/p4_16_errors_outputs/issue3299.p4-stderr, testdata/p4_16_errors_outputs/issue3299.p4.p4info.txt
Fixes #3299
This also contains a few small code cleanups discovered during inspection.
=> p4test does not support switch statements in actions

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3304.p4, testdata/p4_16_errors_outputs/issue3304.p4, testdata/p4_16_errors_outputs/issue3304.p4-stderr
=> Do not allow structure have specialized parsers as type arguments

backends/dpdk/backend.cpp, backends/dpdk/dpdkMetadata.cpp, backends/dpdk/dpdkMetadata.h, testdata/p4_16_samples_outputs/pna-action-selector.p4.spec, testdata/p4_16_samples_outputs/pna-add-on-miss.p4.spec, testdata/p4_16_samples_outputs/pna-direction.p4.spec, testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4.spec, testdata/p4_16_samples_outputs/pna-dpdk-table-key-use-annon.p4.spec, testdata/p4_16_samples_outputs/pna-elim-hdr-copy-dpdk.p4.spec, testdata/p4_16_samples_outputs/pna-example-SelectByDirection.p4.spec, testdata/p4_16_samples_outputs/pna-example-SelectByDirection1.p4.spec, testdata/p4_16_samples_outputs/pna-example-SelectByDirection2.p4.spec, testdata/p4_16_samples_outputs/pna-example-dpdk-varbit.p4.spec, testdata/p4_16_samples_outputs/pna-example-mirror-packet.p4.spec, testdata/p4_16_samples_outputs/pna-example-pass-1.p4.spec, testdata/p4_16_samples_outputs/pna-example-pass-2.p4.spec, testdata/p4_16_samples_outputs/pna-example-pass-3.p4.spec, testdata/p4_16_samples_outputs/pna-example-pass-parser.p4.spec, testdata/p4_16_samples_outputs/pna-example-pass.p4.spec, testdata/p4_16_samples_outputs/pna-example-recirculate.p4.spec, testdata/p4_16_samples_outputs/pna-example-template.p4.spec, testdata/p4_16_samples_outputs/pna-example-tunnel.p4.spec, testdata/p4_16_samples_outputs/pna-extract-local-header.p4.spec, testdata/p4_16_samples_outputs/pna-issue3041.p4.spec, testdata/p4_16_samples_outputs/pna-lookahead-structure-bit-field.p4.spec, testdata/p4_16_samples_outputs/pna-lookahead-structure.p4.spec, testdata/p4_16_samples_outputs/pna-mux-dismantle.p4.spec, testdata/p4_16_samples_outputs/pna-subparser.p4.spec
Initialize direction only once
Increase regarray size to 256
=> [dpdk]  Fix calculation of direction from input port

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3316.p4, testdata/p4_16_errors_outputs/issue3316.p4, testdata/p4_16_errors_outputs/issue3316.p4-stderr
=> Check that parameter default values are compile-time known

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3335.p4, testdata/p4_16_errors_outputs/issue3335.p4, testdata/p4_16_errors_outputs/issue3335.p4-stderr, testdata/p4_16_errors_outputs/pr2918.p4-stderr, testdata/p4_16_errors_outputs/select-struct.p4-stderr, testdata/p4_16_errors_outputs/select-varbits.p4-stderr
=> Improve error message when validating select expressions

frontends/p4/typeMap.cpp, testdata/p4_16_samples/issue3292.p4, testdata/p4_16_samples_outputs/issue3292-first.p4, testdata/p4_16_samples_outputs/issue3292-frontend.p4, testdata/p4_16_samples_outputs/issue3292.p4, testdata/p4_16_samples_outputs/issue3292.p4-stderr
=> Unification of generic types can reduce to unification of Type_Name

frontends/common/constantFolding.cpp, testdata/p4_16_samples/issue3288.p4, testdata/p4_16_samples_outputs/issue3288-first.p4, testdata/p4_16_samples_outputs/issue3288.p4, testdata/p4_16_samples_outputs/issue3288.p4-stderr
=> Allow shifts with serenums on the RHS

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3345.p4, testdata/p4_16_errors_outputs/issue1986-1.p4-stderr, testdata/p4_16_errors_outputs/issue1986.p4-stderr, testdata/p4_16_errors_outputs/issue3345.p4, testdata/p4_16_errors_outputs/issue3345.p4-stderr
=> Improve error message when select types do not match

backends/ebpf/psa/ebpfPsaTable.cpp
=> Remove unused variables in psa/ebpf backend

backends/ebpf/tests/ptf/common.py, backends/ebpf/tests/ptf/l2l3_acl.py, backends/ebpf/tests/ptf/table_implementation.py, backends/ebpf/tests/ptf/test.py, tools/ci-build.sh
* Removed extern type from output JSON
* Changed semantic with action specification
* Changed in digest CLI
=> PSA-eBPF PTF tests: update psabpf to the latest version

backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkContext.cpp, backends/dpdk/dpdkContext.h, backends/dpdk/dpdkHelpers.cpp, backends/dpdk/dpdkProgramStructure.h, testdata/p4_16_samples/pna-add_on_miss_action_name.p4, testdata/p4_16_samples_outputs/pna-add_on_miss_action_name-first.p4, testdata/p4_16_samples_outputs/pna-add_on_miss_action_name-frontend.p4, testdata/p4_16_samples_outputs/pna-add_on_miss_action_name-midend.p4, testdata/p4_16_samples_outputs/pna-add_on_miss_action_name.p4, testdata/p4_16_samples_outputs/pna-add_on_miss_action_name.p4.bfrt.json, testdata/p4_16_samples_outputs/pna-add_on_miss_action_name.p4.spec
This PR fixes two issues:
1) Learn instruction corresponding to add_entry extern takes action name from user as input.
However, compiler modifies the action name for creating unique names. Since the names are different, dpdk pipeline fails to load.
Added a mapping between user visible name and compilers internal name used in spec file to emit the right compiler generated action name.
```
extern bool add_entry<T>(string action_name,
in T action_params,
in ExpireTimeProfileId_t expire_time_profile_id);
```
2) "name" field for actions in context json should match with action name in bfrt json. bfrt json uses controlPlaneName(). Updated the "name" field to use controlPlaneName.
=> DPDK Backend: Fix action name used in learn instruction, minor fix in context json

frontends/common/resolveReferences/resolveReferences.cpp, testdata/p4_16_samples/issue3379-1.p4, testdata/p4_16_samples/issue3379.p4, testdata/p4_16_samples_outputs/issue3379-1-first.p4, testdata/p4_16_samples_outputs/issue3379-1.p4, testdata/p4_16_samples_outputs/issue3379-1.p4-stderr, testdata/p4_16_samples_outputs/issue3379-first.p4, testdata/p4_16_samples_outputs/issue3379.p4, testdata/p4_16_samples_outputs/issue3379.p4-stderr
=> Fix incorrect overload resolution for specialized (package) types

frontends/CMakeLists.txt, frontends/p4/simplifyDefUse.cpp, frontends/p4/simplifyDefUse.h, frontends/p4/ternaryBool.cpp, testdata/p4_16_samples/issue3417.p4, testdata/p4_16_samples_outputs/issue3417-first.p4, testdata/p4_16_samples_outputs/issue3417-frontend.p4, testdata/p4_16_samples_outputs/issue3417-midend.p4, testdata/p4_16_samples_outputs/issue3417.p4, testdata/p4_16_samples_outputs/issue3417.p4-stderr
=> Fix def-use analysis bug when handling virtual methods

midend/parserUnroll.cpp
=> loop unrolling: Use type of original expression

frontends/common/constantFolding.cpp, frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue3283.p4, testdata/p4_16_samples_outputs/issue3283-first.p4, testdata/p4_16_samples_outputs/issue3283.p4, testdata/p4_16_samples_outputs/issue3283.p4-stderr
=> Handle constant folding for tuple/list constants

midend/parserUnroll.cpp
=> Remove spurious print from parserUnroll

backends/ebpf/lower.h, frontends/common/constantFolding.cpp, testdata/p4_16_errors/issue3430.p4, testdata/p4_16_errors_outputs/issue3430.p4, testdata/p4_16_errors_outputs/issue3430.p4-stderr
=> Prevent crash caused by incorrect error message

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue3394.p4, testdata/p4_16_samples_outputs/issue3394-first.p4, testdata/p4_16_samples_outputs/issue3394-frontend.p4, testdata/p4_16_samples_outputs/issue3394.p4
Similar to #3408, but for relations.
=> Values with type int are legal constants, part 2

backends/ebpf/tests/ptf/common.py, tools/ci-build.sh
=> pft-ebpf tests: update psabpf to fix tests

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3378.p4, testdata/p4_16_errors_outputs/issue3378.p4, testdata/p4_16_errors_outputs/issue3378.p4-stderr
=> Forbid packages, controls, etc as tuple fields

midend/replaceSelectRange.cpp, midend/replaceSelectRange.h, testdata/p4_16_errors_outputs/issue-2123_e.p4-stderr, testdata/p4_16_samples/inverted-range.p4, testdata/p4_16_samples_outputs/inverted-range-first.p4, testdata/p4_16_samples_outputs/inverted-range-frontend.p4, testdata/p4_16_samples_outputs/inverted-range-midend.p4, testdata/p4_16_samples_outputs/inverted-range.p4, testdata/p4_16_samples_outputs/inverted-range.p4-stderr
Related to https://github.com/p4lang/p4-spec/pull/1127
=> Support inverted ranges

frontends/common/constantFolding.cpp, testdata/p4_16_samples/issue3486.p4, testdata/p4_16_samples_outputs/issue3486-first.p4, testdata/p4_16_samples_outputs/issue3486-frontend.p4, testdata/p4_16_samples_outputs/issue3486.p4, testdata/p4_16_samples_outputs/issue3486.p4-stderr
=> Fix bug related to varbits width

backends/dpdk/dpdkArch.cpp
Addressing a [comment](https://github.com/p4lang/p4c/pull/3496#discussion_r957666796) in https://github.com/p4lang/p4c/pull/3496
=> Dpdk Backend : Add null check for default action property

backends/dpdk/DpdkXfail.cmake, backends/dpdk/constants.h, backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkProgram.cpp, backends/dpdk/dpdkProgram.h, testdata/p4_16_samples/psa-dpdk-large-struct-fields.p4, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields-first.p4, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields-frontend.p4, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields-midend.p4, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields.p4, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields.p4.p4info.txt, testdata/p4_16_samples_outputs/psa-dpdk-large-struct-fields.p4.spec, testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err3.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err3.p4.spec, testdata/p4_16_samples_outputs/psa-dpdk-struct-field.p4-error, testdata/p4_16_samples_outputs/psa-dpdk-struct-field.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-dpdk-struct-field.p4.spec
=> Since dpdk now Support large struct fields(more than 64 bits) as key

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_samples/issue3550.p4, testdata/p4_16_samples_outputs/issue3550-first.p4, testdata/p4_16_samples_outputs/issue3550-frontend.p4, testdata/p4_16_samples_outputs/issue3550-midend.p4, testdata/p4_16_samples_outputs/issue3550.p4, testdata/p4_16_samples_outputs/issue3550.p4-stderr, testdata/p4_16_samples_outputs/issue3550.p4.entries.txt, testdata/p4_16_samples_outputs/issue3550.p4.p4info.txt
=> Entries can be implicitly cast to the key type

frontends/parsers/p4/p4parser.ypp
This PR fixes #3552.
If this PR gets accepted, I'll keep the spec in sync accordingly.
=> Use prefixedNonTypeName to simplify the expression production in parser

.github/workflows/ci-p4tools.yml, backends/p4tools/CMakeLists.txt, backends/p4tools/cmake/common.cmake, backends/p4tools/common/core/z3_solver.cpp, backends/p4tools/scripts/tools/run-clang-format.sh, backends/p4tools/testgen/core/program_info.cpp, backends/p4tools/testgen/core/program_info.h, backends/p4tools/testgen/core/small_step/expr_stepper.h, backends/p4tools/testgen/test/lib/format_int.cpp, ir/visitor.h, tools/ci-build.sh
Includes some small fixes to the P4Tools back end that were not part of the larger PR. Also adds style checks back.
=> Several small compilation fixes for P4Tools.

backends/p4tools/.clang-tidy, backends/p4tools/scripts/tools/check-git-submodules.sh, backends/p4tools/testgen/targets/bmv2/backend/stf/stf.cpp, backends/p4tools/testgen/targets/bmv2/backend/stf/stf.h, backends/p4tools/testgen/targets/bmv2/test/BMV2PTFXfail.cmake, backends/p4tools/testgen/targets/bmv2/test/BMV2ProtobufXfail.cmake, backends/p4tools/testgen/targets/bmv2/test/BMV2Xfail.cmake, backends/p4tools/testgen/targets/bmv2/test/p4-programs/up4.p4
Several small fixes to the P4Tools repository.
Also transition the STF back end to INJA templates.
=> More fixes to the P4Tools repository.

backends/p4tools/common/lib/taint.cpp, backends/p4tools/testgen/test/lib/taint.cpp
Taint analysis was always tainting the remaining binary operands. This was too aggressive.
=> Fix taint analysis that was too conservative.

backends/p4tools/testgen/targets/bmv2/backend/protobuf/protobuf.cpp, backends/p4tools/testgen/targets/bmv2/table_stepper.cpp, backends/p4tools/testgen/targets/bmv2/table_stepper.h, control-plane/addMissingIds.cpp, control-plane/addMissingIds.h
Implements [one-shot action selector/profile](https://p4.org/p4-spec/p4runtime/v1.3.0/P4Runtime-Spec.html#sec-oneshot) programming for the v1model protobuf back end.
=> An action profile implementation for v1model protobuf.

frontends/common/constantFolding.cpp, testdata/p4_16_errors/issue3622.p4, testdata/p4_16_errors_outputs/issue3622.p4, testdata/p4_16_errors_outputs/issue3622.p4-stderr
=> Do not constant fold mux before it has been typechecked

.github/workflows/ci-ptf-kernels-weekly.yml
=> Fix PTF eBPF weekly CI job

frontends/p4/simplify.cpp, testdata/p4_16_samples/issue3619-1.p4, testdata/p4_16_samples/issue3619.p4, testdata/p4_16_samples_outputs/issue3619-1-first.p4, testdata/p4_16_samples_outputs/issue3619-1-frontend.p4, testdata/p4_16_samples_outputs/issue3619-1-midend.p4, testdata/p4_16_samples_outputs/issue3619-1.p4, testdata/p4_16_samples_outputs/issue3619-first.p4, testdata/p4_16_samples_outputs/issue3619.p4, testdata/p4_16_samples_outputs/issue3619.p4-stderr
=> Handle correctly general switch statements when simplifying

frontends/p4/createBuiltins.cpp, frontends/p4/createBuiltins.h, ir/ir.def, testdata/p4_16_errors/issue3644-1.p4, testdata/p4_16_errors/issue3644-2.p4, testdata/p4_16_errors/issue3644.p4, testdata/p4_16_errors/missing_match.p4, testdata/p4_16_errors_outputs/issue3644-1.p4, testdata/p4_16_errors_outputs/issue3644-1.p4-stderr, testdata/p4_16_errors_outputs/issue3644-2.p4, testdata/p4_16_errors_outputs/issue3644-2.p4-stderr, testdata/p4_16_errors_outputs/issue3644.p4, testdata/p4_16_errors_outputs/issue3644.p4-stderr, testdata/p4_16_errors_outputs/missing_match.p4, testdata/p4_16_errors_outputs/missing_match.p4-stderr
=> Tighten checks for NoAction

frontends/p4/typeChecking/typeChecker.cpp, frontends/parsers/p4/p4parser.ypp, testdata/p4_16_errors/issue3656.p4, testdata/p4_16_errors_outputs/issue3656.p4, testdata/p4_16_errors_outputs/issue3656.p4-stderr
Fixes #3656 
We also keep track of source position for Vectors, this gives better error messages.
=> Do not allow action invocations with type arguments

backends/dpdk/dpdkArch.h, backends/dpdk/dpdkHelpers.cpp, testdata/p4_16_samples_outputs/psa-example-parser-checksum.p4.spec
=> Dpdk backend: Use vector to populate checksum struct

frontends/p4/specializeGenericTypes.cpp, frontends/p4/toP4/toP4.cpp, frontends/p4/typeChecking/syntacticEquivalence.cpp, frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeChecker.h, frontends/p4/typeChecking/typeConstraints.h, testdata/p4_16_errors/issue3671-2.p4, testdata/p4_16_errors_outputs/issue1542.p4-stderr, testdata/p4_16_errors_outputs/issue2033.p4-stderr, testdata/p4_16_errors_outputs/issue3671-2.p4, testdata/p4_16_errors_outputs/issue3671-2.p4-stderr, testdata/p4_16_samples/issue3671-1.p4, testdata/p4_16_samples/issue3671.p4, testdata/p4_16_samples/issue3672.p4, testdata/p4_16_samples_outputs/issue3671-1-first.p4, testdata/p4_16_samples_outputs/issue3671-1-frontend.p4, testdata/p4_16_samples_outputs/issue3671-1.p4, testdata/p4_16_samples_outputs/issue3671-1.p4-stderr, testdata/p4_16_samples_outputs/issue3671-first.p4, testdata/p4_16_samples_outputs/issue3671-frontend.p4, testdata/p4_16_samples_outputs/issue3671.p4, testdata/p4_16_samples_outputs/issue3671.p4-stderr, testdata/p4_16_samples_outputs/issue3672-first.p4, testdata/p4_16_samples_outputs/issue3672-frontend.p4, testdata/p4_16_samples_outputs/issue3672.p4, testdata/p4_16_samples_outputs/issue3672.p4-stderr
=> Insert casts in action call arguments

backends/bmv2/CMakeLists.txt, backends/p4test/CMakeLists.txt, backends/p4tools/testgen/targets/bmv2/test/P4Tests.cmake, testdata/p4_16_samples/pins/README.md, testdata/p4_16_samples/pins/pins_fabric.p4, testdata/p4_16_samples/pins/pins_middleblock.p4, testdata/p4_16_samples/pins/pins_wbb.p4, testdata/p4_16_samples_outputs/pins/pins_fabric-first.p4, testdata/p4_16_samples_outputs/pins/pins_fabric-frontend.p4, testdata/p4_16_samples_outputs/pins/pins_fabric-midend.p4, testdata/p4_16_samples_outputs/pins/pins_fabric.p4, testdata/p4_16_samples_outputs/pins/pins_fabric.p4-stderr, testdata/p4_16_samples_outputs/pins/pins_fabric.p4.p4info.txt, testdata/p4_16_samples_outputs/pins/pins_middleblock-first.p4, testdata/p4_16_samples_outputs/pins/pins_middleblock-frontend.p4, testdata/p4_16_samples_outputs/pins/pins_middleblock-midend.p4, testdata/p4_16_samples_outputs/pins/pins_middleblock.p4, testdata/p4_16_samples_outputs/pins/pins_middleblock.p4-stderr, testdata/p4_16_samples_outputs/pins/pins_middleblock.p4.p4info.txt, testdata/p4_16_samples_outputs/pins/pins_wbb-first.p4, testdata/p4_16_samples_outputs/pins/pins_wbb-frontend.p4, testdata/p4_16_samples_outputs/pins/pins_wbb-midend.p4, testdata/p4_16_samples_outputs/pins/pins_wbb.p4, testdata/p4_16_samples_outputs/pins/pins_wbb.p4-stderr, testdata/p4_16_samples_outputs/pins/pins_wbb.p4.p4info.txt
These are some of the examples taken from https://github.com/sonic-net/sonic-pins/tree/main/sai_p4/instantiations/google. They are complex switch models written for v1model.p4. They can serve as good test examples for BMv2 and the simple-switch back end.
=> Add PINS examples to test suite.

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3727.p4, testdata/p4_16_errors_outputs/issue3727.p4, testdata/p4_16_errors_outputs/issue3727.p4-stderr
=> Method calls in the actions list must invoke actions

frontends/p4/typeChecking/typeChecker.cpp
=> Defensive programming suggested by static analysis - check iterator bound

backends/ebpf/ebpfParser.h, backends/ebpf/psa/ebpfPipeline.cpp, backends/ebpf/psa/ebpfPipeline.h, backends/ebpf/psa/ebpfPsaGen.cpp, backends/ebpf/psa/ebpfPsaParser.cpp, backends/ebpf/psa/ebpfPsaParser.h
=> eBPF/PSA: add support for parser input metadata

.github/workflows/ci-container-image.yml
Detect problems sooner than after commit.
=> Build (only) container images for new PRs

.github/workflows/ci-bazel.yml, .github/workflows/ci-container-image.yml, .github/workflows/ci-p4tools.yml, .github/workflows/ci-ptf-kernels-weekly.yml, .github/workflows/ci-ptf.yml, .github/workflows/ci-release.yml, .github/workflows/ci-static-build-test.yml, .github/workflows/ci-test.yml, .github/workflows/ci-validation.yml
This pull request updates the following GitHub actions in CI:
* [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) from v1 to v2
* [docker/build-push-action](https://github.com/docker/build-push-action) from v2 to v3
* [docker/login-action](https://github.com/docker/login-action) from v1 to v2
* [actions/checkout](https://github.com/actions/checkout) from v2 to v3
=> ci: update actions

frontends/p4/typeChecking/typeChecker.cpp, testdata/p4_16_errors/issue3787.p4, testdata/p4_16_errors_outputs/issue1296.p4-stderr, testdata/p4_16_errors_outputs/issue3787.p4, testdata/p4_16_errors_outputs/issue3787.p4-stderr, testdata/p4_16_samples/generic.p4, testdata/p4_16_samples_outputs/generic-first.p4, testdata/p4_16_samples_outputs/generic.p4
=> Forbid generic externs for in parameter values

backends/dpdk/backend.cpp, backends/dpdk/midend.cpp, testdata/p4_16_samples/pna-example-bAnd-in-tableKey.p4, testdata/p4_16_samples_outputs/pna-example-bAnd-in-tableKey-first.p4, testdata/p4_16_samples_outputs/pna-example-bAnd-in-tableKey-frontend.p4, testdata/p4_16_samples_outputs/pna-example-bAnd-in-tableKey-midend.p4, testdata/p4_16_samples_outputs/pna-example-bAnd-in-tableKey.p4, testdata/p4_16_samples_outputs/pna-example-bAnd-in-tableKey.p4.bfrt.json, testdata/p4_16_samples_outputs/pna-example-bAnd-in-tableKey.p4.spec
Ex: 
```
table ipv4_da_lpm {
key = {
hdr.ipv4.dstAddr & 0xf: exact;
}
```
=> Dpdk Backend : Do not treat BAnd expresion in table key as simple expression

.clang-format, .clang-tidy, backends/bmv2/common/helpers.h, backends/graphs/graphs.h, backends/p4tools/cmake/common.cmake, backends/p4tools/common/compiler/compiler_target.cpp, backends/p4tools/common/compiler/compiler_target.h, backends/p4tools/common/lib/util.cpp, backends/p4tools/common/lib/util.h, backends/p4tools/modules/.gitignore, backends/p4tools/modules/testgen/CMakeLists.txt, control-plane/p4RuntimeArchStandard.h, lib/nullstream.h, midend/parserUnroll.h
- Make the compiler implementation function virtual
- Contribute some utility function
-  Update tools standard to C++17
=> Utility edits for P4Tools.

frontends/p4/checkNamedArgs.cpp, frontends/p4/checkNamedArgs.h, testdata/p4_16_errors/issue3813.p4, testdata/p4_16_errors/issue3814.p4, testdata/p4_16_errors_outputs/issue3813.p4, testdata/p4_16_errors_outputs/issue3813.p4-stderr, testdata/p4_16_errors_outputs/issue3814.p4, testdata/p4_16_errors_outputs/issue3814.p4-stderr
=> Forbid @optional parameters in some places

backends/dpdk/DpdkXfail.cmake, backends/dpdk/backend.cpp, backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkArch.h, backends/dpdk/dpdkAsmOpt.cpp, backends/dpdk/dpdkAsmOpt.h, backends/dpdk/dpdkUtils.cpp, backends/dpdk/dpdkUtils.h, testdata/p4_16_samples/psa-dpdk-checksum-arg-header.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header-first.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header-frontend.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header-midend.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4.p4info.txt, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4.spec, testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_2.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_2.p4.spec, testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_4.p4.bfrt.json, testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_4.p4.spec, testdata/p4_16_samples_outputs/psa-example-incremental-checksum.p4.spec, testdata/p4_16_samples_outputs/psa-example-parser-checksum.p4.spec
Emit a pseudo header, for dpdk instructions which require it's operands to be in a header.
This patch does following:
create a pseudo header
move concerned instruction's operand to the header fields created in step 1
make the newly created header fields part of header.
=> [dpdk] Emit a pseudo header, for dpdk instructions which require

backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
Choosing the same clone port as the current egress port will throw an error. This is an attempt at a workaround.
=> Avoiding choosing the same port as egress port for clone.

backends/dpdk/dpdkArch.cpp, backends/dpdk/dpdkArch.h, testdata/p4_16_samples/psa-dpdk-checksum-arg-header.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header-first.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header-frontend.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header-midend.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4, testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4.spec
This patch consider header also as valid argument to Checksum methods add/sum.
=> Fix ckadd argument

backends/dpdk/dpdkContext.cpp, backends/dpdk/main.cpp
Emit action selector and profile id same as in bfrt
=> Emit action sel id as in bfrt

ir/visitor.cpp, ir/visitor.h
- pause flag to inhibit running while still setting things up + ready hook for subclasses to do something more complex.
- any child visitor may be the base one, or they may be cancelled out by setting them to nullptr
- extra debugging code (disabled by default)
=> SplitFlowVisitor improvements

backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.cpp, backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.h, backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_restrictions_2.p4, backends/p4tools/modules/testgen/test/small-step/p4_asserts_parser_test.cpp
Clean up and refactor the refers_to parser of P4Testgen, which parsers `@refers_to` annotations. In some cases these annotations were not parsed correctly.
=> Fix up the refers_to parser.

backends/ebpf/tests/p4testdata/wide-field-tables.p4, backends/ebpf/tests/ptf/test.py
Support already done by earlier PR, but add test cases for ActionProfile and ActionSelector externs.
CC: @osinstom
=> ebpf/PSA: Test support for wide fields in ActionProfile and ActionSelector

testdata/p4_16_samples_outputs/dash/dash-pipeline-midend.p4
Fix the CI errors that have been popping up lately.
=> Update reference files for the dash program. 

frontends/p4/evaluator/evaluator.cpp, testdata/p4_16_samples/typedef-constructor.p4, testdata/p4_16_samples_outputs/typedef-constructor-first.p4, testdata/p4_16_samples_outputs/typedef-constructor-frontend.p4, testdata/p4_16_samples_outputs/typedef-constructor-midend.p4, testdata/p4_16_samples_outputs/typedef-constructor.p4
=> Eliminate typedefs when resolving constructor type declaration

tools/cpplint.py
Explicit use of python3 is preferred here.
=> Make cpplint use python3 explicitely.

docs/README.md
=> Add documentation on adding test data

backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
Small PR that adds a statement to resolve the input type as needed in some internal P4Testgen externs.
=> P4Testgen: Resolve types in the prepend/append internal extern.

backends/graphs/graph_visitor.h
Initialize `json` to `nullptr` in declaration.
=> initialize json pointer (coverity fix)

ir/base.def, lib/big_int_util.cpp, lib/error_reporter.h, lib/match.cpp, tools/ir-generator/ir-generator-lex.l, tools/ir-generator/ir-generator.ypp, tools/ir-generator/irclass.cpp, tools/ir-generator/irclass.h, tools/ir-generator/type.cpp, tools/ir-generator/type.h
Fix the error reporing (which was corrupting the messages) and clean up enum handling.
=> ir generator fixes + cleanup

frontends/common/parser_options.cpp, test/gtest/helpers.cpp
Minor patches for building on FreeBSD.
=> FreeBSD patches

ir/ir.def, ir/json_generator.h, ir/json_loader.h, ir/visitor.h, lib/source_file.cpp, lib/source_file.h
Some minor useful helper functions, plus a fix for JSON string output to escape "/tab/newline properly
=> misc helper functions

backends/tc/tc.def, testdata/p4tc_samples_outputs/default_action_example.template, testdata/p4tc_samples_outputs/default_hit_const_example.template, testdata/p4tc_samples_outputs/drop_packet_example.template, testdata/p4tc_samples_outputs/global_action_example_01.template, testdata/p4tc_samples_outputs/global_action_example_02.template, testdata/p4tc_samples_outputs/mix_matchtype_example.template, testdata/p4tc_samples_outputs/multiple_tables_example_01.template, testdata/p4tc_samples_outputs/multiple_tables_example_02.template, testdata/p4tc_samples_outputs/name_annotation_example.template, testdata/p4tc_samples_outputs/noaction_example_01.template, testdata/p4tc_samples_outputs/noaction_example_02.template, testdata/p4tc_samples_outputs/nummask_annotation_example.template, testdata/p4tc_samples_outputs/send_to_port_example.template, testdata/p4tc_samples_outputs/simple_exact_example.template, testdata/p4tc_samples_outputs/simple_lpm_example.template, testdata/p4tc_samples_outputs/simple_ternary_example.template, testdata/p4tc_samples_outputs/size_param_example.template, testdata/p4tc_samples_outputs/tc_type_annotation_example.template
This PR fixes the table type in template file for tc backend.
Fixes #4041
=> Fixed tc table type

backends/p4tools/BUILD.bazel, backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt, backends/p4tools/modules/testgen/targets/bmv2/program_info.h, backends/p4tools/modules/testgen/targets/bmv2/test/backend/ptf.cpp, backends/p4tools/modules/testgen/targets/bmv2/test/backend/ptf.h, backends/p4tools/modules/testgen/targets/bmv2/test/backend/stf.cpp, backends/p4tools/modules/testgen/targets/bmv2/test/backend/stf.h, cmake/GoogleTest.cmake
Proof-of-concept demonstrating how to add P4Testgen-extension-specific GTests.
@nikil21
=> [P4Testgen] Add target-specifc P4Testgen gtests

control-plane/p4RuntimeArchHandler.h, control-plane/p4RuntimeArchStandard.h, control-plane/p4RuntimeSerializer.cpp, control-plane/p4RuntimeSymbolTable.cpp
- arch-specific hooks to allow more control of the generation of p4info
=> Added hooks in p4RuntimeArch and p4RuntimeSerializer

backends/dpdk/run-dpdk-ptf-test.py
Previously the test driver `run-dpdk-ptf-test.py` modified the host's network config which caused side-effects like disabling IPv6. Using namespace, which would be cleaned up after the test, resolved this. Code is mostly from `run-bmv2-ptf-test.py`.
=> Use namespace for dpdk PTF tests

frontends/common/constantFolding.cpp, testdata/p4_16_errors/issue4136.p4, testdata/p4_16_errors_outputs/issue4136.p4, testdata/p4_16_errors_outputs/issue4136.p4-stderr
=> Add error message for slice with negative indexes

midend/expandLookahead.cpp, testdata/p4_16_samples/issue4143.p4, testdata/p4_16_samples_outputs/issue4143-first.p4, testdata/p4_16_samples_outputs/issue4143-frontend.p4, testdata/p4_16_samples_outputs/issue4143-midend.p4, testdata/p4_16_samples_outputs/issue4143.p4
=> Allow lookahead of structs with size of 0

frontends/p4/checkCoreMethods.cpp, frontends/parsers/p4/p4parser.ypp, testdata/p4_16_errors/issue4146.p4, testdata/p4_16_errors_outputs/issue4146.p4, testdata/p4_16_errors_outputs/issue4146.p4-stderr, testdata/p4_16_errors_outputs/virtual2.p4-stderr
=> Do not allow 'void' for lookahead type

frontends/common/options.cpp, frontends/common/options.h, frontends/p4/frontend.cpp
- disable inlining in frontend with -O0
=> generic -O option to set optimization level/options

backends/p4tools/modules/testgen/benchmarks/plots.py, backends/p4tools/modules/testgen/benchmarks/test_coverage.py, backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.cpp, backends/p4tools/modules/testgen/targets/pna/backend/ptf/ptf.cpp, tools/testutils.py
More edits for the artifact evaluation for P4Testgen. Fixes usability bugs in the plotting and benchmarking scripts and also cleans up the PNA PTF test case generation.
=> [P4Testgen] Clean up small issues with test back ends and plotting scripts.

backends/p4tools/modules/testgen/CMakeLists.txt, backends/p4tools/modules/testgen/lib/test_backend.cpp, backends/p4tools/modules/testgen/lib/test_backend.h, backends/p4tools/modules/testgen/lib/test_framework.cpp, backends/p4tools/modules/testgen/lib/test_framework.h, backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.cpp, backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.h, backends/p4tools/modules/testgen/targets/bmv2/test_backend/metadata.cpp, backends/p4tools/modules/testgen/targets/bmv2/test_backend/metadata.h, backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.cpp, backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.h, backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.cpp, backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.h, backends/p4tools/modules/testgen/targets/bmv2/test_backend/stf.cpp, backends/p4tools/modules/testgen/targets/bmv2/test_backend/stf.h, backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.cpp, backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.h, backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.cpp, backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.h, backends/p4tools/modules/testgen/targets/pna/backend/ptf/ptf.cpp, backends/p4tools/modules/testgen/targets/pna/backend/ptf/ptf.h
=> [P4Testgen] Rename TF to TestFramework

README.md, backends/ebpf/README.md, backends/ebpf/run-ebpf-test.py
Split this out of #4327 since it's really not part of those changes.
@fruffy
=> Documentation & testfix follow-up to #4160

README.md, backends/bmv2/run-bmv2-test.py, bootstrap.sh
Some fixes I needed to make things build on my MacOS system
=> Fixes for MacOS/macports

.github/workflows/ci-ubuntu-18-nightly.yml, .github/workflows/ci-ubuntu-20-sanitizer-nightly.yml, .github/workflows/ci-validation-nightly.yml, backends/bmv2/CMakeLists.txt, backends/bmv2/run-bmv2-ptf-test.py, backends/tc/ebpfCodeGen.h
Try to improve the execution of optional CI runs. You can only really test whether things are working by running this "live".
=> Tweak optional CI run execution.

.github/workflows/ci-ubuntu-18-nightly.yml, .github/workflows/ci-ubuntu-20-sanitizer-nightly.yml, .github/workflows/ci-validation-nightly.yml
The condition was always true. Maybe this syntax works.
=> Try to fix Github actions syntax.

backends/tc/run-tc-test.py
=> backends/tc: Honour P4TEST_REPLACE environment variable like other backends

.github/workflows/ci-bazel.yml, BUILD.bazel, WORKSPACE.bazel, backends/p4tools/BUILD.bazel, bazel/BUILD.inja.bazel, bazel/BUILD.json.bazel, bazel/example/BUILD.bazel, bazel/example/WORKSPACE.bazel, bazel/example/p4/BUILD.bazel, bazel/p4_library.bzl, bazel/p4c_deps.bzl
Maybe we can make this part of CI, but I am not quite sure yet how to do this.
Also the indirect test currently fails because it tries to pull in buildifier also. Is there a way to make this check optional?
=> Add buildifier to Bazel workspace and run it on the bazel build files.

test/CMakeLists.txt, test/gtest/constant_folding.cpp
Add a test for ConstantFolding and ConstantFoldingPolicy.
Ported test from abandoned #4402.
=> test for ContantFolding + policy

frontends/p4/inlining.cpp
Missed adding the srcInfo when creating the final state
=> add missing srcInfo to ParserState

CMakeLists.txt, README.md, backends/dpdk/CMakeLists.txt, backends/p4tools/common/CMakeLists.txt, backends/p4tools/modules/testgen/CMakeLists.txt, bazel/p4c_deps.bzl, cmake/Abseil.cmake, cmake/Protobuf.cmake, lib/json.cpp, lib/json.h
Fix some missed dependencies here and there
=> Bump protobuf version and add Abseil as compiler dependency. 

.github/workflows/ci-test.yml, tools/install_mac_deps.sh
Let's see if this would help M1
=> Fetch latest brew formulae

docs/README.md
#4502 
Added control plane directory and the description
=> [docs] subdirectories and description for control plane

backends/tc/ebpfCodeGen.cpp, backends/tc/runtime/pna.h, testdata/p4tc_samples_outputs/calculator_control_blocks.c, testdata/p4tc_samples_outputs/checksum_control_blocks.c, testdata/p4tc_samples_outputs/const_entries_range_mask_control_blocks.c, testdata/p4tc_samples_outputs/default_action_example_control_blocks.c, testdata/p4tc_samples_outputs/default_action_with_param_01_control_blocks.c, testdata/p4tc_samples_outputs/default_action_with_param_control_blocks.c, testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c, testdata/p4tc_samples_outputs/drop_packet_example_control_blocks.c, testdata/p4tc_samples_outputs/global_action_example_01_control_blocks.c, testdata/p4tc_samples_outputs/global_action_example_02_control_blocks.c, testdata/p4tc_samples_outputs/ipip_control_blocks.c, testdata/p4tc_samples_outputs/matchtype_control_blocks.c, testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c, testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c, testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c, testdata/p4tc_samples_outputs/name_annotation_example_control_blocks.c, testdata/p4tc_samples_outputs/noaction_example_01_control_blocks.c, testdata/p4tc_samples_outputs/noaction_example_02_control_blocks.c, testdata/p4tc_samples_outputs/nummask_annotation_example_control_blocks.c, testdata/p4tc_samples_outputs/send_to_port_example_control_blocks.c, testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c, testdata/p4tc_samples_outputs/simple_exact_example_control_blocks.c, testdata/p4tc_samples_outputs/simple_lpm_example_control_blocks.c, testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c, testdata/p4tc_samples_outputs/size_param_example_control_blocks.c, testdata/p4tc_samples_outputs/tc_type_annotation_example_control_blocks.c, testdata/p4tc_samples_outputs/test_ipv6_example_control_blocks.c
* Addition of fields in table key value structure in tc backend
* Memory initialization of key structure
* Updated testcase outputs
=> tc struct fields addition and memory initialization

README.md
This pull request updates the README.md file to reflect the correct versions of dependencies specified in the `requirements.txt` file.
Changes made include:
- Corrected the installation command in the "Source files" section to match the versions specified in the `requirements.txt` file (clang-format==18.1.0, isort==5.13.2, black==24.3.0).
- Ensured consistency between the README.md file and the `requirements.txt` file by updating the version.
=> Corrected version in README.md

backends/tc/ebpfCodeGen.cpp, backends/tc/ebpfCodeGen.h, testdata/p4tc_samples_outputs/tc_may_override_example_01_control_blocks.c, testdata/p4tc_samples_outputs/tc_may_override_example_04_control_blocks.c, testdata/p4tc_samples_outputs/tc_may_override_example_05_control_blocks.c, testdata/p4tc_samples_outputs/tc_may_override_example_06_control_blocks.c
* Added default action code in control block for tc backend
*  Updated testcase outputs
=> Added default action code for tc backend

README.md
Currently, there are different formatting for commands in `README.md` . 
Formatting all the command in consistent formatting [ Using Bash format ]
=> [Docs] Improve formatting for consistency 

frontends/p4/typeChecking/typeChecker.cpp, frontends/p4/typeChecking/typeChecker.h, testdata/p4_16_samples/issue4625_remove_compile_time_bool_methodcall_of_mcs.p4, testdata/p4_16_samples/issue4625_remove_compile_time_const_methodcall_of_mcs.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs-first.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs-frontend.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs-midend.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs-first.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs-frontend.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs-midend.p4, testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs.p4
=> [#4625] Prune `MethodCallStatement`s if child `MethodCallExpression` resolves to a compile-time constant.

tools/install_mac_deps.sh
=> Update MacOS brew version.

frontends/p4/alias.h, testdata/p4_16_samples/issue4760_dontcare_action_out_arg.p4, testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg-first.p4, testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg-frontend.p4, testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg-midend.p4, testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg.p4
=> [#4760] Create empty `SetOfLocations` for don't care arguments passed as action `out` args

CHANGELOG.md
Added changelogs for version 1.2.4.13 release.
Still figuring out a way to automate this.
=> Docs : Changelogs release update for v1.2.4.13 

testdata/p4_16_samples/issue4507_1.p4, testdata/p4_16_samples/issue4507_2.p4, testdata/p4_16_samples_outputs/issue4507_1-first.p4, testdata/p4_16_samples_outputs/issue4507_1-frontend.p4, testdata/p4_16_samples_outputs/issue4507_1-midend.p4, testdata/p4_16_samples_outputs/issue4507_1.p4, testdata/p4_16_samples_outputs/issue4507_1.p4-stderr, testdata/p4_16_samples_outputs/issue4507_2-first.p4, testdata/p4_16_samples_outputs/issue4507_2-frontend.p4, testdata/p4_16_samples_outputs/issue4507_2-midend.p4, testdata/p4_16_samples_outputs/issue4507_2.p4, testdata/p4_16_samples_outputs/issue4507_2.p4-stderr
The crashes were fixed by either #4539 or #4727
=> Add tests from issue #4507

BUILD.bazel, backends/p4tools/BUILD.bazel
Signed-off-by: Matthew Lam <matthew.lam.qwerty@gmail.com>
=> Add missing BUILD file dependencies.

CHANGELOG.md
Added changelogs for[ version 1.2.4.14](https://github.com/p4lang/p4c/pull/4844) release.
=> Docs : Changelogs release update for v1.2.4.14 

ir/dump.cpp, ir/dump.h
And some minor code re-ordering for cleanup while there.
=> Sync dump.h with dump.cpp

.gdbinit
Addresses https://github.com/p4lang/p4c/issues/4707#issuecomment-2299475531.
=> Update namespace usage in .gdbinit

backends/tc/backend.cpp, backends/tc/backend.h, backends/tc/introspection.cpp, backends/tc/introspection.h, backends/tc/tc.def, testdata/p4tc_samples_outputs/direct_counter_example.json, testdata/p4tc_samples_outputs/direct_meter.json, testdata/p4tc_samples_outputs/direct_meter_color.json, testdata/p4tc_samples_outputs/indirect_counter_01_example.json, testdata/p4tc_samples_outputs/meter.json, testdata/p4tc_samples_outputs/meter.template, testdata/p4tc_samples_outputs/meter_color.json
Change type as "rate" for Meter PACKETS "cir" and "pir" field
=> Added "inst_type" field in introspection.json.

lib/flat_map.h
=> Add missed include

frontends/p4/unusedDeclarations.cpp, testdata/p4_16_errors_outputs/structure-valued-expr-errs-1.p4-stderr, testdata/p4_16_samples/issue4883_dup_has_returned_decl.p4, testdata/p4_16_samples/issue4883_dup_has_returned_decl2.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl-first.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl-frontend.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl-midend.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl.p4-stderr, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2-first.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2-frontend.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2-midend.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2.p4, testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2.p4-stderr
=> [#4883] Remove unused actions whose `@name` name starts with "__"

.github/workflows/ci-test-mac.yml
=> Remove the workaround that was required for MacOS CI installation.

CHANGELOG.md
Changelogs for [`v1.2.4.15`](https://github.com/p4lang/p4c/pull/4893)
=> Docs : Changelogs release update for v1.2.4.15

docs/README.md
It would be nice to lump this together with some other useful enhancement, but I don't have one right now.
=> Fix a recently introduced typo

tools/install_mac_deps.sh
Not quite sure whether this change is needed. I am seeing failures in other PRs. Need to test when we try to commit something to the merge queue.
=> Fix Mac dependency installation.

backends/tofino/bf-p4c/bf-p4c-options.cpp
Fix a bug uncovered in #5038. We were not checking whether the annotation needs to be parsed.
=> Fix incorrect annotation parsing in Tofino. 

CHANGELOG.md
Changelogs update for  `v1.2.5.1` & `v1.2.5.2`
=> Docs : Changelogs update for  `v1.2.5.1` & `v1.2.5.2` 

ir/indexed_vector.h
=> Add iterator constructor to IndexedVector

.github/workflows/ci-bazel.yml, BUILD.bazel, WORKSPACE.bazel, bazel/example/WORKSPACE.bazel, tools/format-bazel-files.sh
=> Use prebuilt buildifier binary: it's faster and less brittle.

p4include/dpdk/psa.p4, testdata/p4_16_psa_errors_outputs/psa-example-dpdk-directmeter-err.p4-error
A few spacing adjustments to reduce the delta between bmv2/psa.p4 and dpdk/psa.p4
NO FUNCTIONAL CHANGE
=> [psa]: minor spacing adjustments in dpdk/psa.p4

ir/dump.cpp
=> Clean up IRDumper to use visitor infra properly

backends/p4test/midend.cpp, frontends/p4/entryPriorities.cpp, lib/error_catalog.cpp, lib/error_catalog.h, midend/CMakeLists.txt, midend/checkTableEntries.cpp, midend/checkTableEntries.h, testdata/p4_16_errors/table-entries-error.p4, testdata/p4_16_errors_outputs/table-entries-error-first.p4, testdata/p4_16_errors_outputs/table-entries-error-frontend.p4, testdata/p4_16_errors_outputs/table-entries-error.p4, testdata/p4_16_errors_outputs/table-entries-error.p4-stderr, testdata/p4_16_samples_outputs/init-entries-bmv2-first.p4, testdata/p4_16_samples_outputs/init-entries-bmv2-frontend.p4, testdata/p4_16_samples_outputs/init-entries-bmv2-midend.p4, testdata/p4_16_samples_outputs/init-entries-bmv2.p4.entries.txtpb, testdata/p4_16_samples_outputs/table-entries-priority-bmv2.p4-stderr
- duplicate keys can be either errors or warnings (per arch)
- unmatchable ternary keys (due to prior key that covers it) are warnings
=> Midend pass to detect entries with duplicate or unmatchable keys

frontends/p4/frontend.cpp, frontends/p4/typeChecking/typeCheckStmt.cpp, testdata/p4_16_errors/issue3611.p4, testdata/p4_16_errors/issue5254_dup_switch_case_label_error.p4, testdata/p4_16_errors_outputs/duplicate-label.p4-stderr, testdata/p4_16_errors_outputs/issue3611.p4, testdata/p4_16_errors_outputs/issue3611.p4-stderr, testdata/p4_16_errors_outputs/issue5254_dup_switch_case_label_error.p4, testdata/p4_16_errors_outputs/issue5254_dup_switch_case_label_error.p4-stderr
=> [#5254] Emit error message for duplicate `switch` case labels

backends/tofino/bf-asm/asm-types.h, backends/tofino/bf-asm/atcam_match.cpp, backends/tofino/bf-asm/deparser.cpp, backends/tofino/bf-asm/exact_match.cpp, backends/tofino/bf-asm/gtest/gtestasm.cpp, backends/tofino/bf-asm/input_xbar.h, backends/tofino/bf-asm/json.h, backends/tofino/bf-asm/proxy_hash.cpp, backends/tofino/bf-asm/sram_match.cpp, backends/tofino/bf-asm/tables.cpp, backends/tofino/bf-asm/tables.h, backends/tofino/bf-p4c/common/extract_maupipe.cpp, backends/tofino/bf-p4c/mau/asm_output.cpp, backends/tofino/bf-p4c/mau/gateway.cpp, backends/tofino/bf-p4c/mau/instruction_selection.cpp, backends/tofino/bf-p4c/mau/stateful_alu.cpp, backends/tofino/bf-p4c/midend/check_unsupported.cpp, backends/tofino/bf-p4c/parde/extract_parser.cpp, backends/tofino/bf-p4c/parde/lowered/hoist_common_match_operations.cpp, backends/tofino/bf-p4c/phv/utils/utils.h, backends/tofino/bf-p4c/phv/v2/utils_v2.h, ir/pattern.h
=> Compilation fixes for C++20.

ir/irutils.cpp, testdata/p4_16_samples/issue5335_default_initialized_non_header_stack.p4, testdata/p4_16_samples/issue5335_default_initialized_non_header_stack_nested.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack-first.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack-frontend.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack-midend.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack_nested-first.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack_nested-frontend.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack_nested-midend.p4, testdata/p4_16_samples_outputs/issue5335_default_initialized_non_header_stack_nested.p4
=> [#5335] Properly handle default-initialized stacks of non-header types.

backends/p4test/run-p4-sample.py
May help avoid confusion when looking at successful test that looks like it should have failed.
Example:
```
$ ./p4/testdata/p4_16_samples/pragma-string.p4.test 2>/dev/null
./p4test --pp /home/b/p4lang/src/p4c/build/tmphvqwt49p/pragma-string.p4 --dump /home/b/p4lang/src/p4c/build/tmphvqwt49p --top4 FrontEndDump,FrontEndLast,MidEndLast --testJson --maxErrorCount 100 /home/b/p4lang/src/p4c/testdata/p4_16_samples/pragma-string.p4
(Ignoring stderr differences for file pragma-string.p4-stderr due to P4TEST_IGNORE_STDERR in sample file)
./p4test -I. --pp /home/b/p4lang/src/p4c/build/tmphvqwt49p/pragma-string.p4-x --std p4-16 /home/b/p4lang/src/p4c/build/tmphvqwt49p/pragma-string.p4 --maxErrorCount 100
./p4test -I. --pp /home/b/p4lang/src/p4c/build/tmphvqwt49p/pragma-string-midend.p4-x --std …
```
=> Print message when P4TEST_IGNORE_STDERR is used

CMakeLists.txt, control-plane/CMakeLists.txt, test/CMakeLists.txt
=> Make building the control-plane (and protobuf) optional.

.github/workflows/ci-test-mac.yml, .github/workflows/ci-ubuntu-p4tc-stf.yml, README.md
* Remove reference to nonexistent matrix vars
* Remove reference to nonexistent submodules
=> Small build cleanups
