- midend/replaceSelectRange.cpp
- midend/replaceSelectRange.h
- test/gtest/midend_test.cpp
- testdata/p4_16_samples/issue2800a.p4
- testdata/p4_16_samples/issue2800b.p4
- testdata/p4_16_samples/issue2800c.p4
- testdata/p4_16_samples/issue2800d.p4
- testdata/p4_16_samples_outputs/issue2800a-first.p4
- testdata/p4_16_samples_outputs/issue2800a-frontend.p4
- testdata/p4_16_samples_outputs/issue2800a-midend.p4
- testdata/p4_16_samples_outputs/issue2800a.p4
- testdata/p4_16_samples_outputs/issue2800b-first.p4
- testdata/p4_16_samples_outputs/issue2800b-frontend.p4
- testdata/p4_16_samples_outputs/issue2800b-midend.p4
- testdata/p4_16_samples_outputs/issue2800b.p4
- testdata/p4_16_samples_outputs/issue2800c-first.p4
- testdata/p4_16_samples_outputs/issue2800c-frontend.p4
- testdata/p4_16_samples_outputs/issue2800c-midend.p4
- testdata/p4_16_samples_outputs/issue2800c.p4
- testdata/p4_16_samples_outputs/issue2800d-first.p4
- testdata/p4_16_samples_outputs/issue2800d-frontend.p4
- testdata/p4_16_samples_outputs/issue2800d-midend.p4
- testdata/p4_16_samples_outputs/issue2800d.p4
This fixes "#2800 Check whether the expansion of a range into ternary values is correct for signed numbers".
> Fix expansion of signed ranges to masks

- frontends/p4/strengthReduction.cpp
- testdata/p4_16_samples/issue3225.p4
- testdata/p4_16_samples_outputs/issue3225-first.p4
- testdata/p4_16_samples_outputs/issue3225-frontend.p4
- testdata/p4_16_samples_outputs/issue3225-midend.p4
- testdata/p4_16_samples_outputs/issue3225.p4
- testdata/p4_16_samples_outputs/issue3225.p4.p4info.txt
> Strength reduction should not remove some casts

- backends/ebpf/CMakeLists.txt
- backends/ebpf/psa/README.md
- backends/ebpf/psa/ebpfPipeline.h
- backends/ebpf/psa/ebpfPsaControl.cpp
- backends/ebpf/psa/ebpfPsaControl.h
- backends/ebpf/psa/ebpfPsaGen.cpp
- backends/ebpf/psa/ebpfPsaTable.h
- backends/ebpf/psa/externs/ebpfPsaCounter.cpp
- backends/ebpf/psa/externs/ebpfPsaMeter.cpp
- backends/ebpf/psa/externs/ebpfPsaMeter.h
- backends/ebpf/tests/p4testdata/meters-action.p4
- backends/ebpf/tests/p4testdata/meters-color-aware.p4
- backends/ebpf/tests/p4testdata/meters-packets.p4
- backends/ebpf/tests/p4testdata/meters.p4
- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/meters.py
> Implement Meter extern for eBPF backend

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3233.p4
- testdata/p4_16_errors_outputs/issue3233.p4
- testdata/p4_16_errors_outputs/issue3233.p4-stderr
> Do not allow casts to struct types

- frontends/common/parser_options.cpp
> Allow P4 filenames containing spaces

- ir/visitor.cpp
- ir/visitor.h
All three `Visitor` implementations hold a data structure containing information about all visited IR nodes in the `visited` attribute. This attribute is a pointer to an object dynamically allocated in `init_apply`, which is later set to `nullptr` when the visitor no longer needs it. The garbare collector is then supposed to destroy these objects.
This memory management mechanism doesn't work perfectly, however. In our backend implementation, managing lifetime of `visited` objects by refcounting  (as submitted in this PR) leads to  3x (!) peak memory usage decrease on large P4 programs. It seems the garbage collector isn't able to release the `visited` hashtable properly, leaving piles of IR nodes in the memory. This should also bring the codebase closer to proper memory management in …
> manage lifetime of Visitor::visited

- lib/bitvec.h
BitRef was missing the [iterator traits](https://en.cppreference.com/w/cpp/iterator/iterator_traits), which is required by recent versions of boost in some circumstances.
> Add iterator traits to bitref

- README.md
This PR modifies the main README to point to the PSA implementation for eBPF. 
Also, it fixes a typo in the p4c-ubpf.
> Point to PSA/eBPF implementation in main README

- backends/bmv2/simple_switch/simpleSwitch.cpp
- backends/dpdk/control-plane/bfruntime_arch_handler.h
- backends/dpdk/control-plane/bfruntime_ext.cpp
- backends/dpdk/control-plane/bfruntime_ext.h
- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- backends/dpdk/dpdkHelpers.cpp
- backends/dpdk/dpdkProgramStructure.cpp
- backends/dpdk/main.cpp
- backends/dpdk/printUtils.cpp
- backends/dpdk/spec.cpp
- backends/ebpf/codeGen.cpp
- backends/ebpf/psa/ebpfPipeline.cpp
- control-plane/bfruntime.cpp
- control-plane/bfruntime.h
- frontends/p4/directCalls.cpp
- frontends/p4/fromv1.0/converters.h
- frontends/p4/fromv1.0/programStructure.cpp
- frontends/p4/typeChecking/syntacticEquivalence.cpp
- frontends/parsers/p4/p4parser.ypp
- ir/expression.def
- midend/checkExternInvocationCommon.h
- midend/singleArgumentSelect.cpp
- testdata/p4_14_errors_outputs/issue747.p4-stderr
- testdata/p4_16_samples/spec-issue1068.p4
- testdata/p4_16_samples_outputs/spec-issue1068-first.p4
- testdata/p4_16_samples_outputs/spec-issue1068.p4
- testdata/p4_16_samples_outputs/spec-issue1068.p4-stderr
Fixes https://github.com/p4lang/p4-spec/issues/1068
It also fixes many calls to ::error that were not using the appropriate API.
> Allow specialized types for direct control/parser invocations

- .github/workflows/ci-validation.yml
This ensures that tests do not fail when Gauntlet does not compile. This check was lost when #3073 was merged.
> Preserve build failure semantics

- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/meters.py
- backends/ebpf/tests/ptf/test.py
- tools/ci-build.sh
It adds support, compared to earlier version, for:
- DirectMeter;
- DirectCounter;
- set default action;
- get table entry (limited to single entry for table without implementation).
CC: @osinstom @kmateuszssak
> Update used psabpf library for PTF tests (PSA/eBPF)

- CMakeLists.txt
A somewhat different approach to the same problem as  in #3262, where @grg wrote:
> LLD is much faster than gold in testing, so prefer LLD if it is found.
>
> Test results for a debug build with the Intel Tofino backend after
> touching a single file:
> 
>     gold: 313.410 s (averaged across 10 runs)
>     lld: 151.783 s (averaged across 10 runs)
> 
The difference is mainly in the options to enable/disable lookup for linkers.
Tested with GCC & Clang. Since the detection fails if the `-fuse-ld=???` is not supported by the given gcc/clang version there is no need for version checks.
> Add support for LLD linker, cmake options for LLD and Gold

- testdata/p4_16_samples/spec-issue1060.p4
- testdata/p4_16_samples_outputs/spec-issue1060-first.p4
- testdata/p4_16_samples_outputs/spec-issue1060-frontend.p4
- testdata/p4_16_samples_outputs/spec-issue1060-midend.p4
- testdata/p4_16_samples_outputs/spec-issue1060.p4
From https://github.com/p4lang/p4-spec/issues/1060
> Test for isValid as a header field

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3293.p4
- testdata/p4_16_errors_outputs/issue3293.p4
- testdata/p4_16_errors_outputs/issue3293.p4-stderr
> Require generic return types to be specialized

- ir/v1.def
For things like `pkg.lookahead<some_struct_t>().foo[4]` the `base_` in this code does not point to a header and therefore calls to `baseRef` cause SIGSEGV. Instead I propese it returns `nullptr` which can be handled by the callee if needed.
> Avoid dereferencing nullptr in GetStackItemRef::baseRef

- backends/bmv2/common/lower.cpp
- frontends/common/constantFolding.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue2332-1.p4
- testdata/p4_16_errors_outputs/issue2332-1.p4
- testdata/p4_16_errors_outputs/issue2332-1.p4-stderr
- testdata/p4_16_samples/issue3287.p4
- testdata/p4_16_samples_outputs/issue3287-first.p4
- testdata/p4_16_samples_outputs/issue3287-frontend.p4
- testdata/p4_16_samples_outputs/issue3287-midend.p4
- testdata/p4_16_samples_outputs/issue3287.p4
- testdata/p4_16_samples_outputs/issue3287.p4-stderr
I have deleted a test that was rejected originally but now should be fine.
> Allow shifts with constant signed positive amounts

- backends/ebpf/psa/xdpHelpProgram.h
Currently, clang generates the following warnings when compiling XDP helper program:
```
out.c:313:26: warning: cast to 'struct ethhdr *' from smaller integer type '__u32' (aka 'unsigned int') [-Wint-to-pointer-cast] 
struct ethhdr *eth = (struct ethhdr *) skb->data;
^ 
out.c:329:60: warning: cast to 'void *' from smaller integer type '__u32' (aka 'unsigned int') [-Wint-to-void-pointer-cast]                                                                              
if ((void *) ((struct internal_metadata *) meta + 1) > (void *) skb->data)
^ 
2 warnings generated.   
```
They don't impact the functionality, but might be annoying for users. This PR fixes the XDP helper program.
> p4-ebpf: Fix warnings generated by clang when compiling XDP helper program

- backends/ebpf/ebpfDeparser.cpp
- backends/ebpf/midend.cpp
Fixes #3318
There is no attached test because our testsuite does not run tests for the psa ebfp backend in the standard way.
> Expand 'emit' calls in the ebpf backend

- backends/ebpf/psa/README.md
We've recently discovered some missing steps in the installation guide (thanks @vgurevich @mestery). This PR adds the missing installation steps.
Also, I've updated other parts of the PSA-eBPF documentation to make it consistent with an actual state of implementation.
> Update PSA-eBPF documentation

- control-plane/flattenHeader.cpp
- control-plane/flattenHeader.h
- control-plane/p4RuntimeArchHandler.h
- control-plane/p4RuntimeArchStandard.cpp
- control-plane/p4RuntimeArchStandard.h
- control-plane/typeSpecConverter.cpp
- control-plane/typeSpecConverter.h
- testdata/p4_16_samples/issue3329-bmv2.p4
- testdata/p4_16_samples/v1model-p4runtime-most-types1.p4
- testdata/p4_16_samples_outputs/issue3329-bmv2-first.p4
- testdata/p4_16_samples_outputs/issue3329-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/issue3329-bmv2-midend.p4
- testdata/p4_16_samples_outputs/issue3329-bmv2.p4
- testdata/p4_16_samples_outputs/issue3329-bmv2.p4.p4info.txt
> Fix control-plane generation for headers containing structs

- testdata/p4_16_samples/p4rt_digest_complex.p4
- testdata/p4_16_samples_outputs/p4rt_digest_complex-first.p4
- testdata/p4_16_samples_outputs/p4rt_digest_complex-frontend.p4
- testdata/p4_16_samples_outputs/p4rt_digest_complex-midend.p4
- testdata/p4_16_samples_outputs/p4rt_digest_complex.p4
- testdata/p4_16_samples_outputs/p4rt_digest_complex.p4.p4info.txt
To show how they are represented in the P4Info.
> Add generic structs to P4Runtime digest example

- frontends/p4/specializeGenericFunctions.cpp
- testdata/p4_16_samples/issue3324.p4
- testdata/p4_16_samples_outputs/issue3324-first.p4
- testdata/p4_16_samples_outputs/issue3324.p4
- testdata/p4_16_samples_outputs/issue3324.p4-stderr
> Do not specialize functions when arguments are type variables

- backends/ebpf/tests/p4testdata/register-action.p4
- backends/ebpf/tests/p4testdata/register-apply.p4
- backends/ebpf/tests/p4testdata/register-big-key.p4
- backends/ebpf/tests/p4testdata/register-default.p4
- backends/ebpf/tests/p4testdata/register-structs.p4
- backends/ebpf/tests/ptf/bng.py
- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/l2l3_acl.py
- backends/ebpf/tests/ptf/meters.py
- backends/ebpf/tests/ptf/register.py
- backends/ebpf/tests/ptf/table_implementation.py
- backends/ebpf/tests/ptf/test.py
- backends/ebpf/tests/ptf/upf.py
- tools/ci-build.sh
> Use psabpf-ctl register command in PTF tests

- frontends/p4/validateParsedProgram.h
- testdata/p4_16_errors/issue3338.p4
- testdata/p4_16_errors_outputs/accept_e.p4-stderr
- testdata/p4_16_errors_outputs/issue3338.p4
- testdata/p4_16_errors_outputs/issue3338.p4-stderr
- testdata/p4_16_errors_outputs/nostart.p4-stderr
> Require a start state in parsers

- backends/ebpf/psa/README.md
- backends/ebpf/psa/ebpfPipeline.cpp
- backends/ebpf/psa/ebpfPipeline.h
- backends/ebpf/psa/ebpfPsaGen.cpp
The PSA-eBPF compiler will optimzie the TC Egress program out. This leads to a noticeable performance gain as the empty TC Egress program consumes some CPU cycles and, thus, introduces a performance overhead.
> Do not generate TC Egress program if PSA Egress pipeline is empty

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3346.p4
- testdata/p4_16_errors_outputs/issue3346.p4
- testdata/p4_16_errors_outputs/issue3346.p4-stderr
> Validate value_set element types

- frontends/p4/fromv1.0/converters.h
- testdata/p4_14_samples/packet_entry_to_start.p4
- testdata/p4_14_samples_outputs/packet_entry_to_start-first.p4
- testdata/p4_14_samples_outputs/packet_entry_to_start-frontend.p4
- testdata/p4_14_samples_outputs/packet_entry_to_start-midend.p4
- testdata/p4_14_samples_outputs/packet_entry_to_start.p4
The issue was that if there was a transition into the start state (for example from one of the @packet_entry states) and @packet_entry used, the compiler renamed the original start state to replace it with a new one. However these transitions into the original start state were not renamed.
> Fixed start state renaming for p4-14 translation using @packet_entry

- frontends/p4/typeChecking/typeUnification.cpp
- testdata/p4_16_errors_outputs/enumCast.p4-stderr
- testdata/p4_16_errors_outputs/issue2220.p4-stderr
- testdata/p4_16_samples/issue3333.p4
- testdata/p4_16_samples_outputs/issue3333-first.p4
- testdata/p4_16_samples_outputs/issue3333.p4
- testdata/p4_16_samples_outputs/issue3333.p4-stderr
> Allow unification between serenum and underlying type

- frontends/common/constantFolding.cpp
- testdata/p4_16_samples/issue3343.p4
- testdata/p4_16_samples_outputs/issue3343-first.p4
- testdata/p4_16_samples_outputs/issue3343.p4
- testdata/p4_16_samples_outputs/issue3343.p4-stderr
> Allow value sets as labels when select() is done on a constant

- backends/ebpf/psa/ebpfPsaGen.cpp
- backends/ebpf/psa/ebpfPsaTable.cpp
- backends/ebpf/psa/ebpfPsaTable.h
- backends/ebpf/tests/p4testdata/action-default-ternary.p4
- backends/ebpf/tests/p4testdata/const-entry-ternary.p4
- backends/ebpf/tests/ptf/test.py
This PR adds possibility to use const entries with ternary tables.
> Add support for ternary const entries

- midend/parserUnroll.cpp
These changes allow to save parser state for case where ExpressionEvaluator returns an error, otherwise this state could be eliminated from the result.
To repeat this problem, please, run the following command:
`./p4test -I . /p4include --target bmv2 --std p4-16 --loopsUnroll --arch v1model --dump 11 --top4 End ../testdata/p4_16_samples/issue314.p4`
The parser doesn't have start state after ParserUnroll without these changes.
> Add old parser state in loopsUnroll if ExpressionEvaluator returns a error

- frontends/p4/methodInstance.cpp
- ir/node.cpp
- lib/cstring.cpp
- lib/cstring.h
> String utility functions

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3359.p4
- testdata/p4_16_errors_outputs/issue3359.p4
- testdata/p4_16_errors_outputs/issue3359.p4-stderr
- testdata/p4_16_errors_outputs/issue394.p4-stderr
- testdata/p4_16_errors_outputs/issue807.p4-stderr
- testdata/p4_16_errors_outputs/issue816-1.p4-stderr
> Do not allow variables with type Type_Parser/Control

- backends/dpdk/DPDK_context_schema.json
- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkContext.cpp
- backends/dpdk/dpdkContext.h
This PR adds target_name field for tables to context json. This holds the name of the table in spec file.
> Dpdk backend: Add target_name field for tables to context json. 

- midend/hsIndexSimplify.cpp
- midend/hsIndexSimplify.h
- testdata/p4_16_samples/issue3374.p4
- testdata/p4_16_samples_outputs/control-hs-index-test6-midend.p4
- testdata/p4_16_samples_outputs/issue3374-first.p4
- testdata/p4_16_samples_outputs/issue3374-frontend.p4
- testdata/p4_16_samples_outputs/issue3374-midend.p4
- testdata/p4_16_samples_outputs/issue3374.p4
- testdata/p4_16_samples_outputs/issue3374.p4.p4info.txt
These changes fix bug in HSIndexSimplifier according to the issue #3374
> Fixing bug in HSIndexSimplifier path

- .github/workflows/ci-auto-release.yml
This pull request adds a new GitHub action that automatically increments the version of p4c on the first day of every month and creates a pull request. When that pull request is merged, a new GitHub release would be automatically created.
Example: 
- Auto-generated pull request: https://github.com/rst0git/p4c-1/pull/16
- Auto-generated release: https://github.com/rst0git/p4c-1/releases/tag/v1.2.2.3
The change in this pull request was discussed at the P4.org open source developer days meeting on June 7, 2022.
> [RFC] Enable Automated Releases

- backends/dpdk/dpdkHelpers.cpp
- testdata/p4_16_samples_outputs/pna-example-pass-parser.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_1.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_6.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_7.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_8.p4.spec
- testdata/p4_16_samples_outputs/psa-header-stack.p4.spec
some of the metadata fields were being removed as unused. Root cause is that some metadata fields are added as Path expressions instead of Member expressions
> Add metadata field uses as Member Expression

- lib/bitvec.cpp
- lib/bitvec.h
- remove code duplication
- `count_{leading,trailing}_zeroes` + `popcount` are now available globally to use on built-in integral types
- builtin_* helpers + the aforementioned new functions are defined in `namespace bv` to avoid possible collisions
> Make bitvec helpers available as global, don't polute top-level namespace

- CMakeLists.txt
BUILD_USE_COLOR=OFF currently does not do what I would expect and what I need - it fails to disable colors (ansi control characters) - note, gcc default mode is "auto", not "never".
Either we should proceed with a patch like this one, or rename the original option to something like "BUILD_FORCE_COLORS". I prefer the former as I have an use case for BUILD_USE_COLOR=OFF.
> BUILD_USE_COLOR=OFF disables colors for the C++ compiler

- frontends/common/constantFolding.cpp
`width_bits` fulfills the same functionality but can be overridden. This makes the pass a bit more flexible.
> Use width_bits() instead of size for constantFolding

- backends/dpdk/dpdkHelpers.h
- testdata/p4_16_samples_outputs/pna-example-varIndex-2.p4.spec
- testdata/p4_16_samples_outputs/pna-example-varIndex.p4.spec
- testdata/p4_16_samples_outputs/psa-action-selector4.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-if-1.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-if.p4.spec
DPDK target does not accept table keys from different structures, hence compiler moves the keys coming from different structures to metadata.
Each table apply statement should be preceded with mov instructions corresponding to the assignment statements for moving the key fields to metadata(Example below)
```
table table1 {
key = {
hdr.ipv4.srcAddr : exact;
hdr.ipv4.dstAddr : exact;
hdr.ipv4.protocol : exact;
hdr.tcp.srcPort : exact;    
hdr.tcp.dstPort : exact;
}
....
}
apply {
if (cond){
table.apply();
flag = true;
table1.apply();
} else {
flag = false;
table1.apply();
}
}
```
is translated into
```
table table1 {
key = {
m.MainControlImpl_table1_ipv4_srcAddr : exact @name("hdr.ipv4.srcAddr") ;
m.MainControlImpl_table1_ipv4_dstAddr : exact @name("hdr.ipv4.dstAddr") ; …
```
> DPDK Backend: Fix missing key initialization when header/metadata fields used as table keys

- tools/driver/p4c_src/driver.py
- avoid leaving orphaned command subprocesses
- don't let CTRL+C kill the driver, forward it instead
> Improve the way we wait for commands in driver

- midend/local_copyprop.cpp
- testdata/p4_16_samples/copyprop1.p4
- testdata/p4_16_samples_outputs/copyprop1-first.p4
- testdata/p4_16_samples_outputs/copyprop1-frontend.p4
- testdata/p4_16_samples_outputs/copyprop1-midend.p4
- testdata/p4_16_samples_outputs/copyprop1.p4
- testdata/p4_16_samples_outputs/copyprop1.p4.p4info.txt
If table is applied at multiple places, local copy propagation must ensure expressions are propagated only if all control flow paths to all apply method calls assign the same expression to a variable. Currently, LocalCopyPropagation correctly inhibits copy propagation into match key `k` if two different paths to apply() call assign a different (not equivalent) expressions into `k`. But if one path does not assign any value to `k`, and all other assign `k=a`, e.g.:
```
if (cond) {
k = a;
t.apply();
} else {
t.apply();
}
```
the current implementation incorrectly propagates `a` into the table's match key (rewriting `k` to `a`).
This PR fixes this problem by forbidding copy propagation of a match key in presence of a path without any remap. Before this change, the testcase …
> Fix incorrect copy propagation into table match keys

- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/table_implementation.py
- tools/ci-build.sh
New version of `psabpf-ctl`:
- now use `empty_gruop_action` instead of `default_group_action`
- use `-` instead `_` in commands
> PSA-eBPF PTF tests: update psabpf to the latest version

- frontends/p4/toP4/toP4.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
- ir/node.cpp
- testdata/p4_16_samples/issue3394.p4
- testdata/p4_16_samples_outputs/issue3394-first.p4
- testdata/p4_16_samples_outputs/issue3394-frontend.p4
- testdata/p4_16_samples_outputs/issue3394-midend.p4
- testdata/p4_16_samples_outputs/issue3394.p4
- testdata/p4_16_samples_outputs/issue3394.p4.p4info.txt
> Values with type int are legal constants

- bazel/p4_library.bzl
Part of bazelbuild/bazel#14727
Missed this in 2645f654add2e0a3f9eaaf2ae294d0677576922d
> Use a helper to to define the cpp toolchain type

- .github/workflows/ci-test.yml
- lib/gc.cpp
Apparently, clang could optimize realloc(nullptr, size) down to malloc(size) causing infinite loops. Rearrange the code
a bit to use realloc() code path only when GC is not initialized. This also makes a clean fast-path to GC_malloc() call.
> Inhibit compiler optimizations in GC malloc() implementation

- midend/parserUnroll.cpp
- testdata/p4_16_samples/parser-unroll-test1.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1-first.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test1-first.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test1-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test1-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-test1.p4
These small changes allow to store annotations of the parsers states after application of loops unrolling.
> Store annotations after parser unroll application

- frontends/p4/unusedDeclarations.cpp
- frontends/p4/unusedDeclarations.h
- testdata/p4_16_samples_outputs/annotations-frontend.p4
- testdata/p4_16_samples_outputs/cast-call-frontend.p4
- testdata/p4_16_samples_outputs/crash-typechecker-frontend.p4
- testdata/p4_16_samples_outputs/generic-frontend.p4
- testdata/p4_16_samples_outputs/hashext-frontend.p4
- testdata/p4_16_samples_outputs/initializer-frontend.p4
- testdata/p4_16_samples_outputs/issue1172-frontend.p4
- testdata/p4_16_samples_outputs/issue1586-frontend.p4
- testdata/p4_16_samples_outputs/issue2036-3-frontend.p4
- testdata/p4_16_samples_outputs/issue2265-1-frontend.p4
- testdata/p4_16_samples_outputs/issue3292-frontend.p4
- testdata/p4_16_samples_outputs/issue940-frontend.p4
- testdata/p4_16_samples_outputs/pragma-deprecated-frontend.p4
- testdata/p4_16_samples_outputs/pragmas-frontend.p4
- testdata/p4_16_samples_outputs/precedence-frontend.p4
- testdata/p4_16_samples_outputs/spec-ex06-frontend.p4
- testdata/p4_16_samples_outputs/specialization-frontend.p4
- testdata/p4_16_samples_outputs/template-frontend.p4
Nodes of extern methods calls could be created by different paths (for example, verify in loopsUnroll, noMatch).  These extern methods could be defined not just in "system" files and this class can't remove them in that case. All extern methods represented by IR::Method class. To leave extern method as is we need to remove content of the preorder(IR::Method* method).
> Do not remove externs which are defined not in system files.

- midend/parserUnroll.h
std::variant isn't actually used. This include also prevents gcc-6 based builds as variant is supported only by newer gccs.
> remove unused include

- backends/ebpf/psa/ebpfPipeline.cpp
Fixes #3426 
Unfortunately there is no test attached since we don't have a simple way to run ebpf tests for the psa architecture.
> Avoid crash in ebpf backend by checking expected IR node kinds

- frontends/parsers/p4/p4lexer.hpp
- frontends/parsers/p4/p4lexer.ll
- frontends/parsers/p4/p4lexer_internal.hpp
- frontends/parsers/p4/p4parser.ypp
- frontends/parsers/v1/v1lexer.hpp
- frontends/parsers/v1/v1lexer.ll
- frontends/parsers/v1/v1lexer_internal.hpp
- frontends/parsers/v1/v1parser.ypp
First, UBSan found issue here:
> [2022-04-27T21:17:41.988Z] /bfn/bf-p4c-compilers/p4c/frontends/parsers/v1/v1lexer.hpp:20:7: runtime error: member call on address 0x7ffeb47d6800 which does not point to an object of type 'p4FlexLexer' [2022-04-27T21:17:41.988Z] 0x7ffeb47d6800: note: object is of type 'V1::V1Lexer' [2022-04-27T21:17:41.988Z] fe 7f 00 00 78 44 cd 13 46 56 00 00 00 10 b9 26 46 56 00 00 01 00 00 00 01 00 00 00 00 00 00 00 [2022-04-27T21:17:41.988Z] ^~~~~~~~~~~~~~~~~~~~~~~ [2022-04-27T21:17:41.988Z] vptr for 'V1::V1Lexer'
I analyzed it and we should drop "yyFlexLexerOnce" hacks and use recommended ways to do it. Fixes bugs and follows bison guidelines.
Nicely explained here:
https://stackoverflow.com/questions/35606354/multiple-parsers-in-flex-bison-include-fails
While here, I …
> Fixed usage of yyFlexLexer with multiple parsers

- BUILD.bazel
- bazel/example/p4/BUILD.bazel
- bazel/example/p4/vxlan.p4
- bazel/p4_library.bzl
1. Made `p4c` atribute of the p4_library rule configurable, so the
`p4c-dpdk` compiler can be selected if needed. The default
compiler is still `p4c-bm2-ss`.
2. Added DPDK backend specific bf-rt-schema and context output files.
3. Added everything under `p4include` folder into the default include.
5. updated blaze example with dpdk pna program vxlan.p4.
Note: This vxlan.p4 program  already exist in `backends/dpdk/examples/vxlan.p4`
> Add bazel support for p4c-dpdk compiler

- backends/dpdk/constants.h
- backends/dpdk/control-plane/bfruntime_ext.cpp
- backends/dpdk/control-plane/bfruntime_ext.h
- backends/dpdk/main.cpp
- backends/dpdk/options.h
Tdi json file needs to be emitted from p4c-dpdk to interface with the [TDI](https://github.com/p4lang/tdi) .The contents of tdi json file is same as bfrt json with few additional program/environment related fields given below
```
{
"program_name" : "psa-example-mask-range",
"build_date" : "Mon Jun 27 13:36:57 2022",
"compile_command" : "./p4c-dpdk --arch psa -o test.spec ../testdata/p4_16_samples/psa-example-mask-range.p4 --bf-rt-schema bfrt.json --tdi tdi.json --p4runtime-files p4info.txt --context context.json",
"compiler_version" : "0.1 (SHA: ad5b4a2d1 BUILD: RELEASE)",
"schema_version" : "0.1",
"target" : "DPDK",
<< bfrt json contents >>
}
```
Attached sample tdi json and corresponding bfrt json.
[bfrt.json.txt](https://github.com/p4lang/p4c/files/9120183/bfrt.json.txt) …
> DPDK Backend: Add support for tdi.json

- backends/dpdk/dpdkProgram.cpp
- testdata/p4_16_samples_outputs/psa-dpdk-errorcode-1.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-errorcode-2.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-errorcode.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err4.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err5.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-valid.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-if-1.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-if.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-1.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-2.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-3.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-switch.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid1.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid2.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid3.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid4.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid5.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid6.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid7.p4.spec
- testdata/p4_16_samples_outputs/psa-example-mask-range.p4.spec
- testdata/p4_16_samples_outputs/psa-example-mask-range1.p4.spec
- testdata/p4_16_samples_outputs/psa-example-select_tuple-1.p4.spec
- testdata/p4_16_samples_outputs/psa-example-select_tuple-mask.p4.spec
- testdata/p4_16_samples_outputs/psa-example-select_tuple-wc.p4.spec
- testdata/p4_16_samples_outputs/psa-example-select_tuple.p4.spec
- testdata/p4_16_samples_outputs/psa-switch-expression-without-default.p4.spec
The unused metadata elimination pass removes some of the used metadata variables created for Mask operation.
Metadata elimination pass works on Member type node and these variables are created as PathExpressions, hence these were also eliminated.
Changing these to be added as Member resolves the issue.
> Dpdk Backend: Fix Missing metadata for temporary variables added for Mask operation

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/parsers/p4/p4parser.ypp
- ir/ir.def
- midend/eliminateSwitch.cpp
- testdata/p4_16_samples/issue3442.p4
- testdata/p4_16_samples_outputs/issue3442-first.p4
- testdata/p4_16_samples_outputs/issue3442-frontend.p4
- testdata/p4_16_samples_outputs/issue3442-midend.p4
- testdata/p4_16_samples_outputs/issue3442.p4
Fixes #3442
For this to work we need to remember whether the original expression was _ or { _ }.
That's why the IR class had to be augmented.
(We may need to do the same for select expressions, which suffer from a similar confusion.)
> Use Type_Dontcare for _ expressions in table entries

- lib/stringify.cpp
- lib/stringify.h
This is the fix from #3295; github doesn't let me merge that one.
> Fix include headers for lib/stringify.h

- frontends/p4/frontend.cpp
`1062: +pass_manager.h:43:5: runtime error: load of value 160, which is not a valid value for type 'bool'
1062: +    #0 0x558499773b3d in PassRepeated::clone() const (/home/dbolvans/speed/p4c/build/backends/p4test/p4test+0x89f8b3d)
1062: +    #1 0x55849977433e in covariant return thunk to PassRepeated::clone() const (/home/dbolvans/speed/p4c/build/backends/p4test/p4test+0x89f933e)
1062: +    #2 0x55849d53ed42 in P4::FrontEnd::run(CompilerOptions const&, IR::P4Program const*, bool, std::ostream*) (/home/dbolvans/speed/p4c/build/backends/p4test/p4test+0xc7c3d42)
1062: +    #3 0x5584998c49b9 in main (/home/dbolvans/speed/p4c/build/backends/p4test/p4test+0x8b499b9)
1062: +    #4 0x7efca3c380b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
1062: +    #5 0x55849969a4cd in …
> Remove undefined behaviour in pass manager initialization

- frontends/p4/typeMap.cpp
- testdata/p4_16_samples/issue3238.p4
- testdata/p4_16_samples_outputs/issue3238-first.p4
- testdata/p4_16_samples_outputs/issue3238.p4
- testdata/p4_16_samples_outputs/issue3238.p4-stderr
> Implicit casts between InfInt and Bit are allowed

- CMakeLists.txt
- backends/ubpf/ubpfControl.cpp
- backends/ubpf/ubpfTable.cpp
- test/CMakeLists.txt
- test/gtest/arch_test.cpp
- test/gtest/parser_unroll.cpp
Forces back ends and extensions to use consistent include paths
> Remove "frontends" from the include directories.

- backends/dpdk/spec.cpp
- testdata/p4_16_samples/psa-example-optional-match.p4
- testdata/p4_16_samples/psa-example-range-match.p4
- testdata/p4_16_samples_outputs/psa-example-optional-match-first.p4
- testdata/p4_16_samples_outputs/psa-example-optional-match-frontend.p4
- testdata/p4_16_samples_outputs/psa-example-optional-match-midend.p4
- testdata/p4_16_samples_outputs/psa-example-optional-match.p4
- testdata/p4_16_samples_outputs/psa-example-optional-match.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-optional-match.p4.p4info.txt
- testdata/p4_16_samples_outputs/psa-example-optional-match.p4.spec
- testdata/p4_16_samples_outputs/psa-example-range-match-first.p4
- testdata/p4_16_samples_outputs/psa-example-range-match-frontend.p4
- testdata/p4_16_samples_outputs/psa-example-range-match-midend.p4
- testdata/p4_16_samples_outputs/psa-example-range-match.p4
- testdata/p4_16_samples_outputs/psa-example-range-match.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-range-match.p4.p4info.txt
- testdata/p4_16_samples_outputs/psa-example-range-match.p4.spec
Dpdk target implements both optional and range match_kind as ternary (wildcard) match
Optional match kind is essentially a ternary match where the mask is restricted to be either “every bit matches exactly”, or “every bit is wildcard”.
For the range match_kind, p4-dpdk supports it via wildcard match as long as the range can be expressed by a mask. For ex: 0..7 can be expressed using mask /0x7
P4C only needs to emit wildcard for both of these match_kinds
> Dpdk backend: optional and range match kinds translate to wildcard match for dpdk

- BUILD.bazel
Expose all header files in `backends` folder as textual headers for `ir_frontend_midend_control_plane` library.
> Fix ir_frontend_midend_control_plane build target

- README.md
With the last release of p4c, we have also enabled Ubuntu 22.04 support. This pull request updates the readme file accordingly.
https://build.opensuse.org/package/show/home:p4lang/p4lang-p4c
> readme: Update supported Ubuntu versions

- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
- frontends/p4/simplifyDefUse.cpp
- lib/indent.h
- lib/log.cpp
- lib/log.h
- midend/nestedStructs.h
- new TempIndent for temporary indents (in logs or elsewhere) that go
away when the dtor runs
- Code should generally use Log:: methods which should work even with
non-logging ostreams (log extra functionality becomes noop in that case)
> Log/IndentCtl sanity/cleanup

- backends/dpdk/dpdkHelpers.cpp
- backends/dpdk/dpdkUtils.cpp
- backends/dpdk/dpdkUtils.h
- testdata/p4_16_samples/pna-example-mirror-packet-1.p4
- testdata/p4_16_samples_outputs/pna-example-mirror-packet-1-first.p4
- testdata/p4_16_samples_outputs/pna-example-mirror-packet-1-frontend.p4
- testdata/p4_16_samples_outputs/pna-example-mirror-packet-1-midend.p4
- testdata/p4_16_samples_outputs/pna-example-mirror-packet-1.p4
- testdata/p4_16_samples_outputs/pna-example-mirror-packet-1.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-example-mirror-packet-1.p4.spec
Removed the checks for allowing only constant arguments to mirror_packet extern.
The "mirror" instruction in DPDK assembly expects both the arguments in metadata. Hence, move instruction is inserted to move the argument to metadata if not already present in metadata
> Dpdk Backend: Allow non-constant arguments to mirror_packet extern

- lib/log.cpp
Of course, immediately after merging my change I found a ciritcal bug that somehow the CI failed to notice...
This *should* be a compile error (and is if you use a new enough version of gcc), but apparently is not with the old version that CI uses.
> missing return

- frontends/common/parser_options.cpp
- lib/options.cpp
- tools/driver/p4c_src/main.py
These options just need to get passed through to the C preprocessor, which
implements them itself.
Signed-off-by: Ben Pfaff <bpfaff@vmware.com>
> Support GCC-style options for writing dependencies to a file.

- backends/dpdk/dpdkContext.cpp
The internal name of action is used to create the struct to hold its parameters. While fetching this information for emitting in context json, external name was being used which caused params to be null.
Attached difference in output. with this fix.
[diff.txt](https://github.com/p4lang/p4c/files/9430241/diff.txt)
> Dpdk Backend: Fix action param processing for context json

- backends/dpdk/dpdkArch.cpp
- testdata/p4_16_samples/pna-action-selector-1.p4
- testdata/p4_16_samples_outputs/pna-action-selector-1-first.p4
- testdata/p4_16_samples_outputs/pna-action-selector-1-frontend.p4
- testdata/p4_16_samples_outputs/pna-action-selector-1-midend.p4
- testdata/p4_16_samples_outputs/pna-action-selector-1.p4
- testdata/p4_16_samples_outputs/pna-action-selector-1.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-action-selector-1.p4.spec
When a table has psa/pna_implementation property set to Action selector, it is split into 3 tables, namely group table, member table and base table. 
- The action list of the base table after split contains a compiler generated action` <tblname>_set_group_id` and the default action from the original table in input P4 program.  While creating the action list, the default action was added along with its arguments causing typechecking error. 
```
"Werror=type-error] error: 32w0: parameter vport cannot be bound: it is set by the control plane
const default_action = a1(vport);
^^^^^^
```
The fix in this PR handles this issue and also adds code to preserve the const-ness of default action.
> Dpdk Backend: Fix support for non-zero action arguments for default action in a table using action selector

- midend/parserUnroll.cpp
loopsUnroll has a bug for unrolling loops with one parser state where such loop is restricted by header stack size only. These changes fix this bug. To see the problem, please, run:
`./backends/p4test/p4test  -I "p4include" --target  bmv2 --std p4-16 --loopsUnroll --arch v1model ../testdata/p4_16_samples/stack_complex-bmv2.p4`
> Bug of loopsUnroll for loops with one parser state

- backends/ubpf/ubpfControl.cpp
- testdata/p4_16_samples/issue3483_ubpf.p4
- testdata/p4_16_samples_outputs/issue3483_ubpf-first.p4
- testdata/p4_16_samples_outputs/issue3483_ubpf-frontend.p4
- testdata/p4_16_samples_outputs/issue3483_ubpf-midend.p4
- testdata/p4_16_samples_outputs/issue3483_ubpf.p4
- testdata/p4_16_samples_outputs/issue3483_ubpf.p4.p4info.txt
> Handle table.apply().hit correctly in ubpf backend

- CMakeLists.txt
- README.md
Adds new CMAKE option to enable LTO build.
Adds a check if the combo gcc+lto+lld is detected and prints the warning that LLD does not work with GCC's LTO and switch to Gold linker.
Updated README with new option, also documented a few relevant ones related to linker selection.
> Add new option to build p4c with LTO

- CMakeLists.txt
Currently, this variable is broken - if you print BUILD_USE_COLOR you will see:
-- BUILD_USE_COLOR= OFF;CACHE;BOOL;Use color in C++ compiler output (even if ;the compiler does not detect terminal, e.g. when using ccache
So even if BUILD_USE_COLOR is OFF, inside if(...) this variable as evaluated as true ("OFF;CACHE;BOOL;Use color in C++ compiler output (even if ;the compiler does not detect terminal, e.g. when using ccache" is not empty")
Solution: Use \ for line continuation.
> cmake: Fixed multi line comment

- backends/dpdk/CMakeLists.txt
- control-plane/CMakeLists.txt
Reason: https://github.com/protocolbuffers/protobuf/issues/7140
As there is no easy way to workaround it (generated code), silence it, to avoid breakages eg. for builds with -Werror.
> Silence -Warray-bounds for generated code for protobuf

- frontends/p4/def_use.cpp
- frontends/p4/frontend.cpp
- frontends/p4/specializeGenericFunctions.cpp
- frontends/p4/specializeGenericFunctions.h
- frontends/p4/specializeGenericTypes.cpp
- frontends/p4/toP4/toP4.h
- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3291.p4
- testdata/p4_16_errors_outputs/issue1296.p4-stderr
- testdata/p4_16_errors_outputs/issue3291.p4
- testdata/p4_16_errors_outputs/issue3291.p4-stderr
- testdata/p4_16_errors_outputs/issue819-1.p4-stderr
- testdata/p4_16_errors_outputs/issue819.p4-stderr
- testdata/p4_16_samples/issue3291-1.p4
- testdata/p4_16_samples_outputs/issue1830-first.p4
- testdata/p4_16_samples_outputs/issue2260-2-first.p4
- testdata/p4_16_samples_outputs/issue3291-1-first.p4
- testdata/p4_16_samples_outputs/issue3291-1-frontend.p4
- testdata/p4_16_samples_outputs/issue3291-1-midend.p4
- testdata/p4_16_samples_outputs/issue3291-1.p4
Fixes #3291 
The fix is in the typechecking code.
But the tests revealed some bugs in the specialization code: now we insert the specialized function code in a different place in the source code, to make sure it's after all type declarations that it may depend on. So the function specialization code is more similar to the existing type specialization code.
> Fixes related to type and function specialization

- backends/dpdk/dpdkAsmOpt.cpp
- backends/dpdk/dpdkAsmOpt.h
- testdata/p4_16_samples_outputs/psa-dpdk-token-too-big.p4.spec
dpdk does not expect operands of some of the statements as constant this pr prevent copy prop and elimination for those stmts.
> Fix: prevent copy elimination for statement which does not support constant values

- midend/parserUnroll.cpp
- midend/parserUnroll.h
These changes allow to unroll loops in the following examples: issue692-bmv2, issue2090, gauntlet_parser_test2, gautlet_parser_test4, spec-ex19.
To check, please, run the following command:
`./backends/p4test/p4test  -I "./p4include" --target bmv2 --std p4-16 --loopsUnroll --arch v1model "../testdata/p4_16_samples/example_name.p4"`
> Fixing bug in parserUnroll

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_14_errors_outputs/issue1853.p4-stderr
- testdata/p4_16_errors/issue3522.p4
- testdata/p4_16_errors_outputs/issue3522.p4
- testdata/p4_16_errors_outputs/issue3522.p4-stderr
- testdata/p4_16_errors_outputs/next.p4-stderr
- testdata/p4_16_errors_outputs/stack2.p4-stderr
> Forbid use of .lastIndex outside of parsers

- midend/parserUnroll.cpp
- testdata/p4_16_samples/parser-unroll-issue3537-1.p4
- testdata/p4_16_samples/parser-unroll-issue3537.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-1-first.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-1-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-1-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-1.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-1.p4.p4info.txt
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-first.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue3537.p4.p4info.txt
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-1-first.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-1-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-1-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-1.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-1.p4-stderr
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-first.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537.p4-stderr
These changes allow leaving as is the infinite loops for programs without extraction of the header stack (#3537)
> Fixing bug in ParserUnroll for infinite loops without header stacks 

- CMakeLists.txt
This change allows cleaner inclusion of p4c into projects that set `CMAKE_CXX_STANDARD` to value greater then 11, it does not change anything if p4c is built standalone.
Essentially, in Intel we have top-level target that includes p4c and p4c then includes our extensions. We build our extensions with C++17, but we would like to build p4c with C++17  too to avoid having some code compiled with older standard. In particular, problem can be in the code that is built as part of `p4c`, but is coming from extensions (such as additional IR defs). With this change, we would be able to use C++17 cleanly.
Of course, anyone setting `CMAKE_CXX_STANDARD` > 11 takes the risk it will break something in p4c. This risk is very small for C++17 (bigger for C++20 if anyone would be brave enough to try it).
> Set C++ standard only if it is not set at parent scope

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- testdata/p4_16_samples_outputs/pna-action-selector-1.p4.spec
- testdata/p4_16_samples_outputs/pna-action-selector.p4.spec
- testdata/p4_16_samples_outputs/psa-action-selector1.p4.spec
- testdata/p4_16_samples_outputs/psa-action-selector2.p4.spec
- testdata/p4_16_samples_outputs/psa-action-selector4.p4.spec
- testdata/p4_16_samples_outputs/psa-action-selector5.p4.spec
From PSA specification: A table with an action action selector implementation consists of entries that point to either an action profile member reference or an action profile group reference.
In DPDK backend implementation, we were handling only entries pointing to a group reference and not member reference. Adding implicit action set_member_id to enable this.
> Dpdk Backend: add implicit action set_member_id in action list for action selector

- .github/workflows/ci-ptf-kernels-weekly.yml
- Dockerfile
- tools/ci-build.sh
- tools/ci-ptf/build_vm.sh
- tools/ci-ptf/default_network.xml
- tools/ci-ptf/install_docker.sh
- tools/ci-ptf/install_vm.sh
- tools/ci-ptf/netcfg.yaml
- tools/ci-ptf/prepare_runner.sh
- tools/ci-ptf/run_for_each_kernel.sh
- tools/ci-ptf/run_test.sh
This PR allows to run PTF-ebpf tests on different kernel versions using public GitHub runners.
Why this PR is needed:
- Ensure some sort of backward compatibility for ebpf backend.
- Test new features with older kernels (see below).
Because GitHub runners do not support KVM acceleration and tests last long (2-3h, see [example workflow run](https://github.com/tatry/p4c/actions/runs/3096196743) in my fork), with @osinstom we made following decisions:
- Do not run on pull requests or pushes, but in weekly manner using `cron`. When tests fails this would require more investigation to debug, but current work flow is not changed nor extended in time.
- Each kernel is tested in a separate job, which should ensure that timeout 6h is not met. Testing more kernels in one may not be successful due …
> Run PTF tests under different kernel versions

- midend/parserUnroll.cpp
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537-1.p4-stderr
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue3537.p4-stderr
These changes were done according to #3544. ParserUnroll hasn't any deep analysis for the real reason of non-unrolled loops. I think that such analysis will need the same efforts for implementation as ParserUnroll. So, I think that the warning messages should be changed:  ParserUnroll can't detect the number of loop iterations without an explanation of the real reason.
> Change warrning messages in ParserUnroll

- backends/ebpf/psa/README.md
- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/table_implementation.py
- backends/ebpf/tests/ptf/test.py
- tools/ci-build.sh
Changes in `psabpf` from previous version:
- Member/group reference is printed using JSON, not by a pure number on `stdout`.
- Added support for `ActionProfile` and `value_set`.
At this point, `psabpf-ctl` is used to handle all the externs in PTF tests and no maps are written directly. `bpftool` is still used for reading maps but only for validation purposes where `psabpf-ctl` hides internal state of the extern.
> PSA/ebpf backed: update psabpf-ctl to the latest version

- CMakeLists.txt
Hi,
I found two spelling mistakes in the comments in CMakeLists.txt and decided to fix them.
> fixed spelling in CMakelists.txt in 2 different lines

- ir/visitor.h
to() and is() methods were removed from Backtrack::trigger in commit: 7e5040f85c570160c027405893abd7fbc4b6a170
but some backends use and need these methods.
> add ICastable interface to Backtrack::trigger

- .gitmodules
Cloning using https fails
```
Cloning into 'p4c/backends/p4tools/submodules/gsl-lite'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:gsl-lite/gsl-lite' into submodule path 'p4c/backends/p4tools/submodules/gsl-lite' failed
Failed to clone 'backends/p4tools/submodules/gsl-lite'. Retry scheduled
```
> Update gitmodule to fix cloning with https

- .github/workflows/ci-test.yml
- README.md
Github actions with macos 10.15 are broken due to ongoing brownout period as macos 10.15 support is deprecated.
Please see:
https://github.com/actions/runner-images/issues/5583
So either we drop "official" support for macOS 10.15 or p4c will still support 10.15 "unofficially, without CI" as CI has to switch to macOS 11 anyway.
> Switch to macOS 11

- .github/CODEOWNERS
[Add mandatory reviewers for the P4Tools back end](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). Only one owner has to approve a review.
> Add CODEOWNERS file for P4Tools.

- CMakeLists.txt
- Dockerfile
- README.md
- backends/dpdk/dpdkContext.cpp
- tools/ci-build.sh
CI should now guarantee that patches are warning-free.
Also really helps downstream users of p4c who build their own version of p4c compiler with -Werror.
> Introduce cmake option to enable -Werror; use it for CI/docker builds

- backends/bmv2/common/lower.cpp
- backends/dpdk/DpdkXfail.cmake
- testdata/p4_16_samples_outputs/psa-example-register2-bmv2.p4.spec
Bit slice operations are lowered into shift and mask operations. While creating the shift operation, the type of shift amount is also set same as the left operand which is not correct. The shift operation handling assumes that the constant is of Type_InfInt and handles constant of only Type_infInt type.
To fix this , the type of constant shift amount is set to Type_InfInt.
> Dpdk Backend: Fix shift overlimit error for valid bit slicing operation

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- testdata/p4_16_samples/psa-dpdk-large-header-fields.p4
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields-first.p4
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields-frontend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields-midend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields.p4
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields.p4.p4info.txt
- testdata/p4_16_samples_outputs/psa-dpdk-large-header-fields.p4.spec
dpdk target accepts larger fields size
> Remove header field size constraints, now

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3589.p4
- testdata/p4_16_errors_outputs/issue3589.p4
- testdata/p4_16_errors_outputs/issue3589.p4-stderr
> Tables cannot be compared

- lib/CMakeLists.txt
Fixes https://github.com/p4lang/p4c/issues/3584
I was able to compile p4c with Clang 12.
> Disable libcall optimizations for wrappers of memory allocation functions

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
- testdata/p4_16_errors_outputs/serenum-type.p4-stderr
- testdata/p4_16_errors_outputs/serenum-typedef.p4-stderr
- testdata/p4_16_samples/issue3616.p4
- testdata/p4_16_samples_outputs/issue3616-first.p4
- testdata/p4_16_samples_outputs/issue3616.p4
- testdata/p4_16_samples_outputs/issue3616.p4-stderr
> Allow serenum members initializers refer to other serenum members

- backends/p4tools/testgen/test/small-step/reachability.cpp
gtest was failing because one of the programs had a spurious brackets. I am not quite sure why this was not caught.
> Fix typo in test program for reachability tests. 

- .github/CODEOWNERS
This is not meant as obligation. The primary purpose is that others can approve PRs that touch code in the tools back end.
> Add more code owners to tools back end.

- backends/p4tools/testgen/core/small_step/small_step.cpp
- backends/p4tools/testgen/lib/execution_state.cpp
- backends/p4tools/testgen/lib/execution_state.h
- backends/p4tools/testgen/test/small-step/reachability.cpp
Fix CI failure that was triggered after a stale merge.
> Fix compilation issues after reachability merge

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3623-2.p4
- testdata/p4_16_errors/issue3623-3.p4
- testdata/p4_16_errors_outputs/equality-fail.p4-stderr
- testdata/p4_16_errors_outputs/issue2317.p4-stderr
- testdata/p4_16_errors_outputs/issue3589.p4-stderr
- testdata/p4_16_errors_outputs/issue3623-2.p4
- testdata/p4_16_errors_outputs/issue3623-2.p4-stderr
- testdata/p4_16_errors_outputs/issue3623-3.p4
- testdata/p4_16_errors_outputs/issue3623-3.p4-stderr
- testdata/p4_16_samples/issue3623-1.p4
- testdata/p4_16_samples/issue3623.p4
- testdata/p4_16_samples_outputs/issue3623-1-first.p4
- testdata/p4_16_samples_outputs/issue3623-1.p4
- testdata/p4_16_samples_outputs/issue3623-1.p4-stderr
- testdata/p4_16_samples_outputs/issue3623-first.p4
- testdata/p4_16_samples_outputs/issue3623.p4
- testdata/p4_16_samples_outputs/issue3623.p4-stderr
> Allow implicit casts in switch labels; improve error message

- lib/ordered_map.h
- lib/ordered_set.h
- test/gtest/ordered_map.cpp
- test/gtest/ordered_set.cpp
* Fix erase in ordered_{set,map}
- The original implementation used non-const iterator which makes the interface
different from the standard set/map.
- ordered_map::{insert,emplace}(iterator hint, ...) overloads have the same
problem, but I kept them. These functions don't really make sense for
insertion-order-preserving containers so it would be best to remove them. But
that is not possible as they are used. The {insert,emplace} for a
iterator-range with hint is very broken as it inserts values in the reverse
order to whay they are in the input range.
* Do not expose modifying iterator from ordered_set
- It is very unsafe -- if the value was changed using the iterator there is a
risk of introducing duplicates in the set.
- Therefore both iterator and const_iterator are now the same -- …
> Fix and improve ordered_map & ordered_set

- midend/eliminateSwitch.cpp
- midend/eliminateSwitch.h
- testdata/p4_16_errors/issue3613.p4
- testdata/p4_16_errors_outputs/issue3613-first.p4
- testdata/p4_16_errors_outputs/issue3613-frontend.p4
- testdata/p4_16_errors_outputs/issue3613.p4
- testdata/p4_16_errors_outputs/issue3613.p4-stderr
> Check if 'match_kind.exact' is defined when expanding switch statements

- backends/bmv2/CMakeLists.txt
- backends/ebpf/targets/xdp_target.py
- backends/p4tools/testgen/targets/bmv2/test/BMV2Xfail.cmake
- frontends/common/programMap.h
- frontends/common/resolveReferences/referenceMap.cpp
- frontends/p4/frontend.cpp
- frontends/p4/simplifyDefUse.h
- frontends/p4/typeMap.cpp
- frontends/p4/unusedDeclarations.cpp
- frontends/p4/unusedDeclarations.h
- testdata/p4_16_samples/issue3650.p4
- testdata/p4_16_samples_outputs/issue3650-first.p4
- testdata/p4_16_samples_outputs/issue3650-frontend.p4
- testdata/p4_16_samples_outputs/issue3650-midend.p4
- testdata/p4_16_samples_outputs/issue3650.p4
- testdata/p4_16_samples_outputs/issue3650.p4.p4info.txt
Fixes #3650 
This was harder to fix than I expected. The visitor infra is too smart for its own good: it wouldn't duplicate empty blocks since it realizes they are identical. So you have to add annotations to empty blocks to make then different, then remove them again.
This also uncovered a bug in the frontend where RemoveUnusedDeclarations was called instead of RemoveAllUnusedDeclarations. That won't happen again, since I made the constructor private.
> Clone empty blocks before def-use analysis

- backends/ebpf/midend.cpp
- testdata/p4_16_samples/calc-ebpf.p4
- testdata/p4_16_samples_outputs/calc-ebpf-first.p4
- testdata/p4_16_samples_outputs/calc-ebpf-frontend.p4
- testdata/p4_16_samples_outputs/calc-ebpf-midend.p4
- testdata/p4_16_samples_outputs/calc-ebpf.p4
> 'size' is always a legal table property

- frontends/parsers/p4/p4parser.ypp
- testdata/p4_16_errors/typedef-and-type-definitions.p4
- testdata/p4_16_errors_outputs/typedef-and-type-definitions.p4
- testdata/p4_16_errors_outputs/typedef-and-type-definitions.p4-stderr
Turns out that `type` declarations are restricted to base types, so the grammar rule that allows derived types is useless.
This could technically be a backwards-incompatible change. To be discussed by the LDWG together with https://github.com/p4lang/p4-spec/issues/1044
> Remove useless grammar rule

- frontends/p4/unusedDeclarations.h
Such that the constructor can still be inherited by other classes. This fixes the compilation of the Gauntlet module, which extends the RemoveUnusedDeclarations class.
> Make RemoveUnusedDeclarations constructor protected.

- backends/dpdk/DpdkXfail.cmake
- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- backends/dpdk/dpdkContext.cpp
- testdata/p4_16_samples/pna-add-on-miss-err1.p4
- testdata/p4_16_samples_outputs/pna-add-on-miss-err1-first.p4
- testdata/p4_16_samples_outputs/pna-add-on-miss-err1-frontend.p4
- testdata/p4_16_samples_outputs/pna-add-on-miss-err1-midend.p4
- testdata/p4_16_samples_outputs/pna-add-on-miss-err1.p4
1) Error if learner table exists with non-exact match keys 
2) Removed explicit from constructor with more than one parameters 
3) Typo in condition check in context json generation
`4) Added new test
> DPDK Backend : Minor fixes

- .github/workflows/ci-lint.yaml
- .github/workflows/ci-test.yml
- CMakeLists.txt
The `CPPLINT_FILES` variable is not an empty string, it is not defined actually. 
Fixes #3682.
> Fix cpplint CMake check.

- backends/p4tools/testgen/core/exploration_strategy/incremental_max_coverage_stack.cpp
- backends/p4tools/testgen/core/exploration_strategy/incremental_stack.cpp
- backends/p4tools/testgen/core/exploration_strategy/linear_enumeration.cpp
- backends/p4tools/testgen/core/exploration_strategy/random_access_max_coverage.cpp
- backends/p4tools/testgen/core/exploration_strategy/random_access_stack.cpp
- backends/p4tools/testgen/options.cpp
- backends/p4tools/testgen/options.h
- backends/p4tools/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/testgen/targets/ebpf/test/P4Tests.cmake
A usability improvement. P4Testgen will not automatically throw an error when it encounters unsafe states. Instead, it will move on to the next branch.
> Enable permissive by default.

- .github/workflows/ci-test.yml
- CMakeLists.txt
- backends/bmv2/simple_switch/simpleSwitch.h
- backends/dpdk/backend.cpp
- backends/dpdk/backend.h
- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- backends/dpdk/dpdkContext.h
- backends/dpdk/dpdkMetadata.h
- backends/dpdk/main.cpp
- backends/ebpf/psa/backend.cpp
- backends/ebpf/psa/ebpfPsaGen.cpp
- backends/ebpf/psa/ebpfPsaGen.h
- backends/graphs/p4c-graphs.cpp
- backends/graphs/parsers.cpp
- backends/graphs/parsers.h
- cmake/P4CUtils.cmake
- frontends/p4/typeChecking/typeConstraints.h
- midend/convertErrors.h
- midend/eliminateInvalidHeaders.h
- midend/flattenLogMsg.h
- midend/flattenUnions.h
Mostly unused private fields and missing overrides.
> Cleanup warnings produced by Clang

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3305.p4
- testdata/p4_16_errors_outputs/issue3305.p4
- testdata/p4_16_errors_outputs/issue3305.p4-stderr
> Do not allow type arguments that are generic if they are not specialized

- backends/bmv2/bmv2stf.py
- backends/p4tools/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/testgen/core/small_step/table_stepper.h
- backends/p4tools/testgen/lib/tf.h
- backends/p4tools/testgen/targets/bmv2/backend/protobuf/protobuf.cpp
- backends/p4tools/testgen/targets/bmv2/backend/protobuf/protobuf.h
- backends/p4tools/testgen/targets/bmv2/backend/ptf/ptf.cpp
- backends/p4tools/testgen/targets/bmv2/backend/ptf/ptf.h
- backends/p4tools/testgen/targets/bmv2/backend/stf/stf.cpp
- backends/p4tools/testgen/targets/bmv2/backend/stf/stf.h
- backends/p4tools/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/testgen/targets/bmv2/table_stepper.h
- backends/p4tools/testgen/targets/bmv2/test/BMV2Xfail.cmake
- backends/p4tools/testgen/targets/bmv2/test/p4-programs/bmv2_table_default.p4
- backends/p4tools/testgen/targets/ebpf/backend/stf/stf.cpp
- backends/p4tools/testgen/targets/ebpf/backend/stf/stf.h
- backends/p4tools/testgen/targets/ebpf/table_stepper.cpp
- backends/p4tools/testgen/targets/ebpf/table_stepper.h
This PR implements default action overrides for P4Testgen's BMv2 extension. Only for the STF back end so far. 
If a table does not have a key, it can not match and pick an action. However, it might still be possible to override the default action and choose a different path. This PR implements the logic to override a table's default action.
Also fixes #3557.
> P4Tools: Implement default action override for BMv2 STF.

- backends/ebpf/targets/ebpfenv.py
- backends/p4tools/common/options.cpp
- backends/p4tools/common/options.h
- backends/p4tools/testgen/README.md
- backends/p4tools/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/testgen/lib/execution_state.cpp
- backends/p4tools/testgen/lib/execution_state.h
- backends/p4tools/testgen/options.cpp
- backends/p4tools/testgen/options.h
- backends/p4tools/testgen/targets/ebpf/target.cpp
Consolidate several packet sizing options into one. Packet sizes are now defined as range (`[min]:[max]`). The maximum packet size is now jumbo frame size (9000 byte). Extensions which do not support this size will have to override or implement their own checks (see the eBPF back end). 
Fixes #3559.
> P4Tools: Unify packet sizing options.

- backends/p4tools/common/lib/taint.cpp
- backends/p4tools/modules/testgen/test/lib/taint.cpp
Exposed by P4 programs which slice one bit from a tainted expression.
> P4Testgen: Fix off-by-one bug in taint checking for slices

- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2Xfail.cmake
There was a condition missing for the calculation of advance conditions for non-constant extracts or advance statements. This PR adds this condition.
> Fix advance condition calculation.

- frontends/p4/typeChecking/typeChecker.cpp
- lib/gc.cpp
Fixes #3719 
Also fixed a couple of warnings in gc.cpp
There is no simple test, but hopefully @smolkaj can confirm that the bug is fixed.
> Fix bug caused by uninitialized variable in typechecker

- frontends/common/constantFolding.cpp
- testdata/p4_16_samples/issue3289.p4
- testdata/p4_16_samples_outputs/issue3289-first.p4
- testdata/p4_16_samples_outputs/issue3289.p4
- testdata/p4_16_samples_outputs/issue3289.p4-stderr
> Off by one warning error in constant-folding for large shifts

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
- testdata/p4_16_errors_outputs/binary_e.p4-stderr
- testdata/p4_16_samples/enumCast.p4
- testdata/p4_16_samples/issue3635.p4
- testdata/p4_16_samples_outputs/enumCast-first.p4
- testdata/p4_16_samples_outputs/issue3056-first.p4
- testdata/p4_16_samples_outputs/issue3635-first.p4
- testdata/p4_16_samples_outputs/issue3635.p4
- testdata/p4_16_samples_outputs/issue3635.p4-stderr
Fixes #3635 
Arithmetic of Serializable enums always needs to insert casts
> Arithmetic and bitwise operations are typechecked the same way

- .github/workflows/ci-test.yml
- CMakeLists.txt
- Dockerfile
- tools/ci-build.sh
Motivation: https://github.com/p4lang/p4c/pull/3720
GCC also have this feature so one with GCC 12 or newer can use it too. In our CI there is GCC 10 so I enabled it only for Clang.
> Enable auto var initialization with pattern in Clang CI build

- backends/dpdk/backend.cpp
- backends/dpdk/dpdk.def
- backends/dpdk/dpdkAsmOpt.cpp
- backends/dpdk/dpdkAsmOpt.h
- testdata/p4_16_samples/psa-dpdk-table-entries-exact-ternary.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary-first.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary-frontend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary-midend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4-error
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4-stderr
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4.entries.txt
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4.p4info.txt
- testdata/p4_16_samples_outputs/psa-dpdk-table-entries-exact-ternary.p4.spec
Here is table config for added test.
```
match 0x1 0x1/0xF priority 0x4 action a_with_control_params x 0x1 
match 0x2 0x1181/0xFFFF priority 0x3 action a_with_control_params x 0x2 
match 0x3 0x1000/0xF000 priority 0x2 action a_with_control_params x 0x3 
match 0x4 0x0/0x0 priority 0x1 action a_with_control_params x 0x4 
```
references: https://elixir.bootlin.com/dpdk/latest/source/examples/pipeline/examples/fib_nexthop_table.txt
> Emit table config

- control-plane/p4RuntimeSerializer.cpp
The target specific extern instance and table properties are using the google.protobuf.Any message ([p4info.proto](https://github.com/p4lang/p4runtime/blob/main/proto/p4/config/v1/p4info.proto#L160)). The google.protobuf.Any messages in runtime is required to be emitted in text format (human readable), not as serialized content. But the p4info text serializer outputs cryptic text (e.g. octal numbers) for google.protobuf.Any message.
This PR addresses this issue by using text format printer to serialize the messages to text. This printer instance allows us to set flag to expand the google.protobuf.Any message.
**p4info.txt output before this change:**
```
info {
type_url: "type.googleapis.com/..."
value: "\022\030\010\001\022\020object \010(\002\032\017\010\001\022\ttype\030\001...."
}
``` …
> Expand google.protobuf.Any when emit p4info in text format

- backends/dpdk/control-plane/bfruntime_arch_handler.h
- backends/dpdk/control-plane/bfruntime_ext.cpp
- control-plane/bfruntime.cpp
- control-plane/bfruntime.h
- testdata/p4_16_samples_outputs/psa-end-of-ingress-test-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_1.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_3.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_5.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_6.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_7.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_8.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_9.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-dpdk-externs.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-example-register2-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-register-complex-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-register-read-write-2-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-register-read-write-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-register1.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-register2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-register3.p4.bfrt.json
This PR adds support for register extern in bfrt.json.
A new table is emitted for the register instance. This is as expected by the p4-dpdk-target.
{
"name" : "ip.MyIC.reg",
"id" : 369588800,
"table_type" : "Register",
"size" : 1024,
"annotations" : [],
"depends_on" : [],
"key" : [
{
"id" : 65557,
"name" : "$REGISTER_INDEX",
"repeated" : false,
"annotations" : [],
"mandatory" : true,
"match_type" : "Exact",
"type" : {
"type" : "uint32"
}
}
],
"data" : [
{
"mandatory" : false,
"read_only" : false,
"singleton" : {
"id" : 65557,
"name" : "$REGISTER_INDEX",
"repeated" : false,
"annotations" : [],
"type" : {
"type" : "bytes",
"width" : 16
}
}
}
],
"supported_operations" : ["Sync"],
"attributes" : []
}
> Dpdk Backend: Register extern support for bfrt.json

- backends/ebpf/ebpfControl.cpp
- backends/ebpf/ebpfOptions.cpp
- backends/ebpf/ebpfOptions.h
- backends/ebpf/ebpfTable.cpp
- backends/ebpf/ebpfTable.h
- backends/ebpf/psa/README.md
- backends/ebpf/psa/ebpfPsaTable.cpp
- backends/ebpf/psa/ebpfPsaTable.h
- backends/ebpf/psa/externs/ebpfPsaTableImplementation.cpp
- backends/ebpf/psa/externs/ebpfPsaTableImplementation.h
- backends/ebpf/tests/p4testdata/table-cache-lpm.p4
- backends/ebpf/tests/p4testdata/table-cache-ternary.p4
- backends/ebpf/tests/ptf/bng.py
- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/table_implementation.py
- backends/ebpf/tests/ptf/test.py
- backends/ebpf/tests/ptf/upf.py
This PR introduces optimization for the PSA/eBPF backend called `table caching` which adds cache table with only `exact` match keys for time consuming look-ups. We identified three situations where this optimization can improve performance:
- Table with `ternary` (and/or `lpm`, `exact`) key - skip slow TSS algorithm if the key was earlier matched.
- Table with `lpm` (and/or `exact`) key - skip slow `LPM_TRIE` map (especially when there is many entries) if the key was earlier matched.
- `ActionSelector` member selection from group - skip slow checksum calculation for `selector` key if it was earlier calculated.
This optimization may not improve performance in every case, so it must be explicitly enabled by compiler option `--table-caching`.
Limitations/to do:
- `DirectCounter` and …
> eBPF/PSA: Implement caching for ActionSelector, LPM and ternary tables

- backends/p4tools/CMakeLists.txt
- backends/p4tools/modules/testgen/CMakeLists.txt
Some P4tools modules and their extensions may use their `.def` files. Propagate that list upwards and maintain the right order of def files, such that P4Tools definitions can be inherited properly.
> Propagate def files upwards in the correct order from extensions/modules

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3750-1.p4
- testdata/p4_16_errors/issue3750.p4
- testdata/p4_16_errors_outputs/issue3378.p4-stderr
- testdata/p4_16_errors_outputs/issue3750-1.p4
- testdata/p4_16_errors_outputs/issue3750-1.p4-stderr
- testdata/p4_16_errors_outputs/issue3750.p4
- testdata/p4_16_errors_outputs/issue3750.p4-stderr
> Disallow Type_Control as a tuple argument

- CMakeLists.txt
- README.md
- frontends/CMakeLists.txt
This PR is a proposal to raise the minimum required CMake version to 3.10.2, which is the default Ubuntu 18.04 version. Our CI only tests that version and support for older CMake versions can not be guaranteed. 
The number is tentative, it could also be 3.6, since the current CMake has code that requires at least 3.6.
> Raise minimum required CMake version to Ubuntu 18.04 version.

- frontends/CMakeLists.txt
- frontends/p4/frontend.cpp
- frontends/p4/validateValueSets.h
- testdata/p4_16_errors/issue3751.p4
- testdata/p4_16_errors_outputs/issue3751.p4
- testdata/p4_16_errors_outputs/issue3751.p4-stderr
> Check that value sets have a constant constructor argument

- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
Testgen did not model the case where a switch case matches, but falls through to another case. This PR keeps track of a match boolean causes any downstream switch cases to be executed.
> Testgen: Switch cases can fall through.

- backends/dpdk/dpdkArch.cpp
- testdata/p4_16_samples/psa-dpdk-table-key-consolidation-mixed-keys-10.p4
- testdata/p4_16_samples_outputs/pna-dpdk-table-key-consolidation-learner-1.p4.spec
- testdata/p4_16_samples_outputs/pna-dpdk-table-key-consolidation-learner-6.p4.spec
- testdata/p4_16_samples_outputs/pna-dpdk-table-key-consolidation-learner-7.p4.spec
- testdata/p4_16_samples_outputs/pna-example-tunnel.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10-first.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10-frontend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10-midend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10.p4
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10.p4-error
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10.p4.p4info.txt
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-10.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-5.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-error.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_3.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_9.p4.spec
For Add_on_miss tables, DPDK target expects the table keys to be in consecutive location in the underlying structure.
When tables keys are combination of header and metadata fields, only header field was getting copied to metadata where we should also copy the metadata fields to make them consecutive in metadata structure.  The metadata copy should always be done for learner table if the keys are not contiguous.
> Dpdk Backend: Fix non-consecutive table keys for add_on_miss table

- frontends/parsers/p4/p4parser.ypp
This omission does not seem to have caused any functional problems.  I only noticed it while doing diffs between an updated version of the P4 language spec repo's grammar.mdk file and this one.
> Add missing semicolon at end of Bison rule in p4parser.ypp

- backends/dpdk/dpdkArch.cpp
- testdata/p4_16_samples_outputs/pna-dpdk-table-key-consolidation-learner-1.p4.spec
- testdata/p4_16_samples_outputs/pna-example-tcp-connection-tracking.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-3.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-5.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-consolidation-mixed-keys-7.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid2.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid3.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid5.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-table-key-isValid6.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_3.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_9.p4.spec
Fix non-contiguous table keys when keys come from different header and metadata struct but existing metadata keys are already contiguous.
> Fix non-contiguous table keys for learner and exact match tables

- backends/p4tools/modules/testgen/README.md
- backends/p4tools/modules/testgen/core/exploration_strategy/exploration_strategy.cpp
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
Enforces the test generation of tests with an output packet.
> Option to produce tests exclusively with output packets

- .github/workflows/ci-test.yml
- tools/install_mac_deps.sh
Turns out MacOS tests have not run in a while. ctest was not executed in the right folder.
> Run MacOS tests in correct directory.

- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/lib/test_backend.h
- backends/p4tools/modules/testgen/testgen.cpp
Reimplementation from #3776 . Generalized case.
> Generate warning when 0 tests are produced

- README.md
- tools/ci-build.sh
This pull request updates the links to download.opensuse.org to use https instead of http.
> Use https with opensuse repositories

- backends/ebpf/ebpfDeparser.cpp
- backends/ebpf/ebpfTable.cpp
- backends/ebpf/ebpfTable.h
- backends/ebpf/psa/ebpfPsaTable.cpp
- backends/ebpf/psa/ebpfPsaTable.h
- backends/ebpf/tests/p4testdata/common_headers.p4
- backends/ebpf/tests/p4testdata/wide-field-tables.p4
- backends/ebpf/tests/ptf/test.py
- tools/ci-build.sh
This PR improves support for fields wider than 64 bits. This is done mostly by fixing bugs and some refactors.
The assumption for fields wider than 64 bits is that byte order of them is network byte order, which means that byte order is preserved during parser or deparser.
To achieve initial support for wide fields, the following changes has been made:
- Fixed byte order of bytes emitted in deparser. Parser had proper implementation of this.
- Allow to assign one field to another.
- Improved code for generating table key during lookup. `exact`, `lpm` or `ternary` match type can used.
- Improved generation of table const entries (now mostly using Visitors).
- Improved prefix length calculation for LPM table.
The current PR allows to parse, deparse, match in tables and assign wide fields. …
> ebpf/PSA: improve support for wide fields

- frontends/common/constantFolding.cpp
- frontends/p4/simplifyDefUse.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_samples/issue3779.p4
- testdata/p4_16_samples_outputs/issue3779-first.p4
- testdata/p4_16_samples_outputs/issue3779-frontend.p4
- testdata/p4_16_samples_outputs/issue3779-midend.p4
- testdata/p4_16_samples_outputs/issue3779.p4
> Constant-fold isValid calls when possible

- backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
- backends/ebpf/tests/p4testdata/hash-wide-field.p4
- backends/ebpf/tests/ptf/checksum.py
This PR adds support for fields wider than 64 bits in implemented checksum algorithms.
CC: @osinstom
> ebpf/PSA: Checksum support for fields wider than 64 bits

- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/exploration_strategy.cpp
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- lib/CMakeLists.txt
- lib/timer.cpp
- lib/timer.h
This moves the ScopedTimer class of P4Tools into the general lib folder. A scoped timer measures and logs the lifetime of the timer object from creation to destruction. This is a handy class as it only needs to be instantiated to record the time some functions take.
> Move timer from testgen to lib folder.

- .github/workflows/ci-lint.yaml
- .github/workflows/ci-p4tools.yml
- .github/workflows/ci-ptf.yml
- .github/workflows/ci-static-build-test.yml
- .github/workflows/ci-test.yml
- .github/workflows/ci-validation.yml
- Dockerfile
- tools/ci-build.sh
Refactor the `ci-build` script.
- Remove unnecessary `.ccache` copy calls from Github action scripts.
- Only use sudo calls in `ci-build` script where necessary. Gets the script one step closer to be run as a normal dependency install script.
- Add a check for building with Docker in `ci-build` script.
> Refactor ci-build.sh script.

- ir/indexed_vector.h
- test/CMakeLists.txt
- test/gtest/indexed_vector.cpp
This fixes `IndexedVector::pop_back` and a constructor from `safe_vector`. These do not compile if instantiated, therefore it is not possible to call `pop_back` on `IndexedVector`. This is required for a bugfix in the Intel Tofino P4 compiler.
> Fix IndexedVector methods and constructor

- frontends/p4/typeMap.cpp
- testdata/p4_16_errors/issue3699.p4
- testdata/p4_16_errors_outputs/issue3699.p4
- testdata/p4_16_errors_outputs/issue3699.p4-stderr
> Equal types are always equivalent

- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/proto/p4testgen.proto
Make the protobuf format consistent with the output. It is strange that protoc has not complained. Likely because all output port values are single digits which do not require formatting.
@kheradmandG In general, ports are a 9-bit type but they are represented as int32. If they ever expand to larger bit-widths we can change the format.
> Make ports an int32 type for the Protobuf BMv2 back end.

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeConstraints.cpp
- frontends/p4/typeChecking/typeSubstitution.cpp
- frontends/p4/typeChecking/typeSubstitution.h
- testdata/p4_16_samples/issue3806.p4
- testdata/p4_16_samples_outputs/issue3806-first.p4
- testdata/p4_16_samples_outputs/issue3806-frontend.p4
- testdata/p4_16_samples_outputs/issue3806.p4
- testdata/p4_16_samples_outputs/issue3806.p4-stderr
> Not all Type_InfInt are the same - keep track of ones that need to be unified

- frontends/common/constantFolding.cpp
This pull request aims to follow up on https://github.com/p4lang/p4c/pull/3794 to simplify `DoConstantFolding::postorder(IR::Member* e)` by removing unnecessary if-else statements.
> Simplify constant-fold method

- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
This option is flawed and will not produce useful output. Better to remove it and add it back once we have a proper implementation.
Fixes #3560.
> Drop flawed input-packet-only option.

- backends/dpdk/backend.cpp
- backends/dpdk/backend.h
- backends/dpdk/dpdkContext.cpp
- backends/dpdk/dpdkContext.h
- backends/dpdk/main.cpp
Emit same handle id in context json as in p4info and bfrt.
> Unify ctxt json's id with other runtime files

- frontends/parsers/p4/p4parser.ypp
- testdata/p4_16_errors_outputs/structure-valued-expr-errs-2.p4-stderr
- testdata/p4_16_errors_outputs/structured-annotation-e.p4-stderr
- testdata/p4_16_samples/trailing-comma.p4
- testdata/p4_16_samples_outputs/trailing-comma-first.p4
- testdata/p4_16_samples_outputs/trailing-comma-frontend.p4
- testdata/p4_16_samples_outputs/trailing-comma.p4
- testdata/p4_16_samples_outputs/trailing-comma.p4-stderr
Fixes https://github.com/p4lang/p4-spec/issues/1205
> Experimental: support for trailing commas

- frontends/p4/toP4/toP4.cpp
- frontends/p4/toP4/toP4.h
- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
- frontends/parsers/p4/p4lexer.ll
- frontends/parsers/p4/p4parser.ypp
- ir/dbprint-expression.cpp
- ir/expression.def
- testdata/p4_16_errors/invalid-invalid.p4
- testdata/p4_16_errors_outputs/invalid-invalid.p4-stderr
As discussed during the January 2023 LDWG meeting.
https://github.com/p4lang/p4-spec/pull/1184 will have to be updated.
This PR also refactors the IR to make it easier to add invalid header unions in a future PR.
> Make {#} a single token

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3363.p4
- testdata/p4_16_errors_outputs/issue3363.p4
- testdata/p4_16_errors_outputs/issue3363.p4-stderr
Fixes #3363 
As discussed during LDWG January 2023.
> Cannot compare externs

- README.md
- requirements.txt
- test/gtest/indexed_vector.cpp
- tools/ci-build.sh
Also fix pip package versions using a requirements.txt file.
> Fix clang_format mismatch.

- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.h
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.h
initializeBlockParams default (zero) initializes all parameters, however most fields of our target have unspecified/uncontrollable initial value. To avoid double-initialization, this PR allows for optional intialization with tainted expressions.
> Testgen: allow block param initialization with taintexpr

- backends/p4tools/common/lib/util.h
- backends/p4tools/common/options.cpp
- backends/p4tools/modules/testgen/README.md
- backends/p4tools/modules/testgen/core/exploration_strategy/linear_enumeration.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/linear_enumeration.h
- backends/p4tools/modules/testgen/core/exploration_strategy/rnd_access_max_coverage.cpp
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/lib/test_backend.h
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.h
- backends/p4tools/modules/testgen/testgen.cpp
- Introduce a stop metric for P4Testgen en. If a stop metric argument is provided, P4Testgen will stop producing test if that particular metric is satisfied. 
- max-tests inputs with values less than 0 will cause P4Testgen to exhaustively generate tests.
- Sanitize inputs for various options and make sure to reject invalid inputs.
@hannelita I also modified the input valuation and arguments for exploration strategies since the options behave similar to stop metrics. Happy to hear suggestions on how to improve this.
> Add stop metrics for P4Testgen. Sanitize some P4Testgen options.

- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/common/lib/util.cpp
- backends/p4tools/common/options.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/exploration_strategy.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/exploration_strategy.h
- backends/p4tools/modules/testgen/core/exploration_strategy/inc_max_coverage_stack.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/inc_max_coverage_stack.h
- backends/p4tools/modules/testgen/core/exploration_strategy/incremental_stack.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/incremental_stack.h
- backends/p4tools/modules/testgen/core/exploration_strategy/linear_enumeration.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/linear_enumeration.h
- backends/p4tools/modules/testgen/core/exploration_strategy/random_access_stack.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/random_access_stack.h
- backends/p4tools/modules/testgen/core/exploration_strategy/rnd_access_max_coverage.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/rnd_access_max_coverage.h
- backends/p4tools/modules/testgen/core/exploration_strategy/selected_branches.cpp
- backends/p4tools/modules/testgen/core/exploration_strategy/selected_branches.h
- backends/p4tools/modules/testgen/lib/concolic.h
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2Xfail.cmake
- backends/p4tools/modules/testgen/testgen.cpp
Use ordered_map instead of std::map to iterate based on insertion order, not key order. This is needed in some cases where pointers are map keys.
> Remove nondeterminism in P4Testgen.

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
- testdata/p4_16_errors/issue3846.p4
- testdata/p4_16_errors_outputs/issue3846.p4
- testdata/p4_16_errors_outputs/issue3846.p4-stderr
> Table application results are not comparable

- frontends/p4/sideEffects.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/issue3847.p4
- testdata/p4_16_errors_outputs/issue3847.p4
- testdata/p4_16_errors_outputs/issue3847.p4-stderr
> Require action_run to be within a switch statement

- backends/bmv2/base_test.py
- backends/bmv2/run-bmv2-ptf-test.py
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.h
- backends/p4tools/modules/testgen/targets/bmv2/cmd_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/constants.h
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.h
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2Xfail.cmake
- tools/testutils.py
Work on adding support for external clone function for BMV2 PTF tests. We are based on the idea that with `clone` two packets will be sent to one port, but we need to check one, so we used `verify_any_packet_any_port` which will check all packets on the specified port, and will give a positive result if there is an expected packet
>  Support "clone" function for BMV2 PTF

- backends/ebpf/codeGen.cpp
- backends/ebpf/codeGen.h
- backends/ebpf/ebpfParser.cpp
- backends/ebpf/ebpfParser.h
- backends/ebpf/ebpfType.cpp
- backends/ebpf/ebpfType.h
- backends/ebpf/psa/README.md
- backends/ebpf/psa/ebpfPsaTable.cpp
- backends/ebpf/psa/externs/ebpfPsaRegister.cpp
- backends/ebpf/tests/p4testdata/wide-field-meters.p4
- backends/ebpf/tests/p4testdata/wide-field-register.p4
- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/meters.py
- backends/ebpf/tests/ptf/register.py
- tools/ci-build.sh
This commit allows to use Registers and Meters with fields wider than 64 bits.
CC: @osinstom
> ebpf/PSA: Support for wide fields in Register and Meter

- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/ebpf/test/P4Tests.cmake
A circular, hard-coded test path was left in the CMake test script. This will break if the folder is not named `p4c.`
> [P4Testgen] Fix hardcoded test search line.

- backends/bmv2/CMakeLists.txt
- backends/p4test/CMakeLists.txt
- backends/p4tools/benchmarks/test_coverage.py
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2Xfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/up4.p4
- testdata/p4_16_samples/omec/README.md
- testdata/p4_16_samples/omec/up4.p4
- testdata/p4_16_samples/pins/pins_fabric.p4
- testdata/p4_16_samples/pins/pins_middleblock.p4
- testdata/p4_16_samples/pins/pins_wbb.p4
- testdata/p4_16_samples_outputs/omec/up4-first.p4
- testdata/p4_16_samples_outputs/omec/up4-frontend.p4
- testdata/p4_16_samples_outputs/omec/up4-midend.p4
- testdata/p4_16_samples_outputs/omec/up4.p4
- testdata/p4_16_samples_outputs/omec/up4.p4.p4info.txt
- testdata/p4_16_samples_outputs/pins/pins_fabric-first.p4
- testdata/p4_16_samples_outputs/pins/pins_fabric-frontend.p4
- testdata/p4_16_samples_outputs/pins/pins_fabric.p4
- testdata/p4_16_samples_outputs/pins/pins_fabric.p4.p4info.txt
- testdata/p4_16_samples_outputs/pins/pins_middleblock-first.p4
- testdata/p4_16_samples_outputs/pins/pins_middleblock-frontend.p4
- testdata/p4_16_samples_outputs/pins/pins_middleblock.p4
- testdata/p4_16_samples_outputs/pins/pins_middleblock.p4.p4info.txt
- testdata/p4_16_samples_outputs/pins/pins_wbb-first.p4
- testdata/p4_16_samples_outputs/pins/pins_wbb-frontend.p4
- testdata/p4_16_samples_outputs/pins/pins_wbb.p4
- testdata/p4_16_samples_outputs/pins/pins_wbb.p4.p4info.txt
`up.p4` was not checking whether the IPv4 header is valid before applying the routing control, which reads from the IPv4 header.
The PINS programs uses the `p4runtime_translation` annotation, which is currently not supported by PI (https://github.com/p4lang/behavioral-model/issues/1176).
> Fix flawed code in up4.p4 and the pins switch models.

- control-plane/p4RuntimeArchStandard.cpp
- control-plane/p4RuntimeArchStandard.h
The backend targets may need to extend the standard arch handler classes to add support for their target specific P4 extern types. It would be cleaner to extend the existing arch handler classes accordingly. This commit moves all p4runtime arch handler classes into header files so that backend targets shall use this to extend.
> Move p4runtime arch handler class declaration to header file

- lib/log.h
This allows quick writing of `operator<<` for custom container classes that should be serializable into log/streams.
> log: Add a format_container helper & use it

- midend/parserUnroll.cpp
These small changes allow getting the same result for TLV_parser.p4 after the second application of the parserUnroll.
> Fix bug in parserUnroll

- ir/expression.def
- ir/ir-inline.h
- ir/ir.def
- ir/v1.def
- ir/visitor.cpp
- ir/visitor.h
- midend/local_copyprop.cpp
- midend/local_copyprop.h
- SplitFlowVisitor manages the flow_clone/flow_merge calls for nodes that want to visit children "in parallel".
- join_flows can visit other parallel branches on the stack in order to (try to) visit all parents before visiting the child.
- flow_copy method needed for ControlFlowVisitors to update(replace) the state rather than merging.
- BackwardCompatibleBroken flag to preserve/restore old behavior, for incremental update
> SplitFlowVisitor to better capture split/join in ControlFlowVisitor

- backends/p4tools/modules/testgen/cmake/TestUtils.cmake
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/targets/bmv2/test/AssumeAssertTests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_1.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_2.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_assume_1.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_assume_2.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_assume_3.p4
- backends/p4tools/modules/testgen/testgen.cpp
This PR adds assert and assume mode to P4Testgen. These modes can be enabled via the `--assumption-mode` and `--assertion-mode` flags.
- If only `--assumption-mode` is active, P4Testgen will only generate tests that satisfy all assert and assume conditions.
- If also `--assertion-mode` is active, P4Testgen will try to only produce tests that violate assertions also including assumptions in assume calls.
- If only `--assertion-mode` is active, P4Testgen will not add assumptions to the path and only generate tests that violate asserts.
> Add assert and assume mode for testgen.

- tools/ci-build.sh
Ubuntu 18 comes with GCC 7, but we don't officianlly support it, our support start with GCC 9. Therefore, it is expected that anyone using Ubuntu 18 will have to use GCC from elsewhere. The https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test PPA seems like the most likely source.
> Install & use GCC 9 in Ubuntu 18 build

- CMakeLists.txt
- backends/bmv2/common/options.h
- backends/bmv2/psa_switch/options.h
- backends/bmv2/simple_switch/options.h
- backends/dpdk/dpdkArch.h
- backends/dpdk/options.cpp
- backends/ebpf/psa/ebpfPsaTable.cpp
- backends/p4tools/common/compiler/reachability.cpp
- control-plane/typeSpecConverter.cpp
- frontends/parsers/p4/p4lexer.ll
- frontends/parsers/v1/v1lexer.ll
- lib/exceptions.h
I think that `-pedantic` would be beneficial compilation flag on top of the existing warnings. Some positives and negatives:
- \+ it catches some edge cases that are ignored by gcc by default, e.g. operators defined both as member and as global function (if the class is not templated)
- \+ we should follow standard C++
- \+ it should make compilation by e.g. clang easier (which enables use of tools such as `clang-tidy`)
- \- it could be too strict (e.g. designated initalizers, see below)
- \- even this does not guarantee that the code is purely according to standard
This PR enables it and fixes the problems that `-pedantic` has with the current code:
- most often these are semicolons that should not be present (e.g. at end of namespaces)
- also badly-escaped string literals
- designated …
> Build with -pedantic, fix problems

- README.md
- backends/ebpf/CMakeLists.txt
- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeSubstitution.cpp
- frontends/p4/typeChecking/typeSubstitution.h
- testdata/p4_16_samples/issue3884-1.p4
- testdata/p4_16_samples/issue3884.p4
- testdata/p4_16_samples_outputs/issue3884-1-first.p4
- testdata/p4_16_samples_outputs/issue3884-1-frontend.p4
- testdata/p4_16_samples_outputs/issue3884-1-midend.p4
- testdata/p4_16_samples_outputs/issue3884-1.p4
- testdata/p4_16_samples_outputs/issue3884-first.p4
- testdata/p4_16_samples_outputs/issue3884-frontend.p4
- testdata/p4_16_samples_outputs/issue3884-midend.p4
- testdata/p4_16_samples_outputs/issue3884.p4
Fixes #3886
The problem is the following: given a constructor like `control C()(int x)`, the type of x is unified with the argument in every invocation of the constructor. But not all invocations must have the exact same argument type. 
In other parts of the compiler type 'int' (Type_InfInt) is treated like a type variable - and unification is used to decide the actual concrete type of an int expression. Here we do the same: when the control C is instantiated, we treat the type of x as a fresh type variable; in this way, the arguments of two separate instantiations of C do not need to unify with each other (via the common constructor type).
```
C(5) c1;
C(4) c2;
```
We do not require 4 and 5 to have the exact same type, they are different `int` types.
> Container arguments with type infint are treated as type variables

- backends/dpdk/dpdkContext.cpp
- backends/ubpf/ubpfTable.cpp
- frontends/parsers/p4/p4parser.ypp
Newer clang (13+) has some extra warnings for variables that are set and modified (e.g. `++`), but their value is never used. With these changes, build passes again with clang 15 and `-Werror`. I had to suppress the warning in `p4parser` as it is in generated code.
> Fix warnings in compilation using clang 15

- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
Instead of enriching the program IR by a custom varbit type which remembers extracted size, assign bit<extracted_size> directly to varbit members.
The original approach with custom Extracted_Varbit type is problematic: the type inherits from bit<X> type where X is the maximum size of corresponding varbit type, however the width_bits method is also overridden to return the actually extracted varbit size.
> Testgen: fix varbit handling

- backends/ebpf/CMakeLists.txt
- backends/ebpf/codeGen.cpp
- backends/ebpf/codeGen.h
- backends/ebpf/psa/ebpfPsaDeparser.cpp
- backends/ebpf/psa/ebpfPsaDeparser.h
- backends/ebpf/psa/ebpfPsaGen.cpp
- backends/ebpf/psa/ebpfPsaGen.h
- backends/ebpf/psa/externs/ebpfPsaDigest.cpp
- backends/ebpf/psa/externs/ebpfPsaDigest.h
- backends/ebpf/tests/p4testdata/wide-field-digest.p4
- backends/ebpf/tests/ptf/test.py
This PR adds support for wide fields in Digest extern.
Also small refactor has been done - Digest implementation was placed in a separate file, like any other PSA externs.
CC: @osinstom
> ebpf/PSA: Support for wide fields in Digest

- CMakeLists.txt
- backends/dpdk/CMakeLists.txt
- control-plane/CMakeLists.txt
- frontends/CMakeLists.txt
- tools/ir-generator/CMakeLists.txt
A smaller chunk size can help with compilation performance, it seems. Remove some commands that are no longer needed.
> CMake build tweaks

- CMakeLists.txt
- README.md
- cmake/UnifiedBuild.cmake
Addresses #3913.
Reinclude the deprecated unified build code, but add a warning.
> Add an explanation for unity builds. Add a deprecation warning.

- backends/bmv2/common/lower.cpp
- testdata/p4_16_samples/psa-dpdk-binary-operations.p4
- testdata/p4_16_samples_outputs/psa-dpdk-binary-operations-first.p4
- testdata/p4_16_samples_outputs/psa-dpdk-binary-operations-frontend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-binary-operations-midend.p4
- testdata/p4_16_samples_outputs/psa-dpdk-binary-operations.p4
- testdata/p4_16_samples_outputs/psa-dpdk-binary-operations.p4.spec
` bit<16> word0 = hdr.ipv4.version_ihl ++ hdr.ipv4.diffserv;`
is translated to
` word0_0 = (bit<16>)hdr.ipv4.version_ihl << 8 | (bit<16>)hdr.ipv4.diffserv & 16w0x1ff;`
The mask value should be **0xff** instead of **0x1ff**
> Fix mask calculation for concat operator in bmv2/dpdk expression lowering

- backends/ebpf/codeGen.cpp
- backends/ebpf/ebpfParser.cpp
- backends/ebpf/ebpfTable.cpp
- backends/ebpf/tests/p4testdata/wide-field-pvs.p4
- backends/ebpf/tests/ptf/test.py
This PR adds ability to match fields wider than 64 bits in parser value set.
CC: @osinstom
> ebpf/PSA: Add support for wide fields in parser value_set

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- backends/dpdk/dpdkUtils.cpp
- backends/dpdk/dpdkUtils.h
- p4include/dpdk/pna.p4
- testdata/p4_16_dpdk_errors/pna-dpdk-large-constants.p4
- testdata/p4_16_dpdk_errors_outputs/pna-dpdk-large-constants.p4-error
- testdata/p4_16_dpdk_errors_outputs/pna-dpdk-large-constants.p4.bfrt.json
- testdata/p4_16_dpdk_errors_outputs/pna-example-ipsec-err3.p4-error
- testdata/p4_16_pna_errors_outputs/pna-dpdk-direct-counter-err-3.p4-error
- testdata/p4_16_samples/pna-ipv6-actions.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-union-stack.p4.spec
- testdata/p4_16_samples_outputs/pna-dpdk-header-union-stack1.p4.spec
- testdata/p4_16_samples_outputs/pna-ipv6-actions-first.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions-frontend.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions-midend.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4-error
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4-stderr
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.spec
- testdata/p4_16_samples_outputs/psa-example-register2-bmv2.p4.spec
To support assignments between variables <= 64-bit(small) and >64-bit (large) variables, the smaller operand must be a header field.
For ex:
```
bit<128> var1;
bit<32> var2;
var 1 = (bit<128>) var2  
```
var2 should be moved to a header to make this assignment work on the DPDK target.
Compiler creates a pseudo header for holding the variables that need to be a header field and inserts additional assignments to move the smaller operand in a pseudo header field
```
header pseudo_hdr {
bit<32> pseudo;
}
struct mainHeader{
....
pseudo_hdr p;
}
h.p.pseudo = var2
var1 = (bit<128>)h.p.pseudo;
```
In case, large operand is being assigned with a constant, the constant is capped to 64-bits and is moved in a header field. The new header field then replaces the constant in the assignment.
> Dpdk Backend: Add support for assignments to and from large (>64-bit) operand

- .git-blame-ignore-revs
- backends/bmv2/CMakeLists.txt
- backends/p4test/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2Xfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- frontends/p4/inlining.cpp
- testdata/p4_16_samples/dash/README.md
- testdata/p4_16_samples/dash/dash-pipeline.p4
- testdata/p4_16_samples/nonstandard_table_names-bmv2.p4
- testdata/p4_16_samples/omec/README.md
- testdata/p4_16_samples_outputs/dash/dash-pipeline-first.p4
- testdata/p4_16_samples_outputs/dash/dash-pipeline-frontend.p4
- testdata/p4_16_samples_outputs/dash/dash-pipeline-midend.p4
- testdata/p4_16_samples_outputs/dash/dash-pipeline.p4
- testdata/p4_16_samples_outputs/dash/dash-pipeline.p4.p4info.txt
- testdata/p4_16_samples_outputs/nonstandard_table_names-bmv2-first.p4
- testdata/p4_16_samples_outputs/nonstandard_table_names-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/nonstandard_table_names-bmv2-midend.p4
- testdata/p4_16_samples_outputs/nonstandard_table_names-bmv2.p4
- testdata/p4_16_samples_outputs/nonstandard_table_names-bmv2.p4.p4info.txt
Another large BMv2 program to test on.
> Add the DASH BMv2 model to the tested programs.

- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/table_stepper.h
- backends/p4tools/modules/testgen/lib/test_spec.cpp
- backends/p4tools/modules/testgen/lib/test_spec.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/stf/stf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/stf/stf.h
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.h
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_table_opt.p4
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.h
- backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.cpp
- backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.h
- backends/p4tools/modules/testgen/targets/ebpf/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/ebpf/table_stepper.h
As per discussion in https://github.com/p4lang/PI/issues/587 P4Testgen should handle optional matches explicitly instead of ignoring them. If the optional match is tainted, ignore it, but still add the priority. 
This PR also makes match keys target-independent. Now every target extension can add their own match key types without affecting other back ends.
> Add an explicit optional match key type.

- CMakeLists.txt
* This is done to suppress the -pedantic warnings in some versions of google protobuf and boost
> Third party libraries are now included as SYSTEM

- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
We do not need the restriction that the advance size must be larger than the buffer. In fact, it can lead to incorrect tests.
> P4Testgen: Try out a simpler advance expression calculation

- backends/p4tools/CMakeLists.txt
- backends/p4tools/cmake/FindZ3.cmake
- backends/p4tools/common/CMakeLists.txt
This fixes build with Z3 in non-standard location & it also improves documentation of the FindZ3 cmake module.
> p4tool: Fix build with Z3 installed in non-standard path

- backends/dpdk/dpdkContext.cpp
- backends/dpdk/dpdkContext.h
For bfrt.json, an additional pipe_name prefix is added to the table and extern names.
Context json uses the table and action ids from p4info. Since the name of table is different when bfrt json is generated whereas when it is not generated, while generating context json, we remove the pipe_name prefix added by the bfrt generator.
Fixes https://github.com/p4lang/p4c/issues/3928
> Dpdk Backend: Strip pipename prefix added to table and extern names for bfrt.json while generating context json

- backends/p4tools/modules/testgen/cmake/TestUtils.cmake
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.h
- backends/p4tools/modules/testgen/targets/bmv2/program_info.h
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/AssumeAssertTests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.h
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.h
- backends/p4tools/modules/testgen/targets/ebpf/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/ebpf/test/TestTemplate.cmake
This pull request adds a new test back end that only serializes user metadata from the appropriate target. For v1model, this is the `meta` variable. We can refine this output as needed. 
For example, for `pins_middleblock.p4` which has the local metadata
```
struct local_metadata_t {
bool                admit_to_l3;
vrf_id_t            vrf_id;
packet_rewrites_t   packet_rewrites;
bit<16>             l4_src_port;
bit<16>             l4_dst_port;
bit<16>             wcmp_selector_input;
bool                apply_tunnel_encap_at_egress;
ipv6_addr_t         tunnel_encap_src_ipv6;
ipv6_addr_t         tunnel_encap_dst_ipv6;
bool                mirror_session_id_valid;
mirror_session_id_t mirror_session_id_value;
@field_list(PreservedFieldList.CLONE_I2E)
ipv4_addr_t         mirroring_src_ip; …
```
> Add a metadata collection mode to the STF back end.

- backends/p4test/CMakeLists.txt
- frontends/common/constantFolding.cpp
- frontends/p4/alias.h
- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
- frontends/p4/inlining.cpp
- frontends/p4/simplifyDefUse.cpp
- frontends/p4/toP4/toP4.cpp
- frontends/p4/toP4/toP4.h
- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
- ir/dbprint-expression.cpp
- ir/expression.def
- ir/node.cpp
- midend/copyStructures.cpp
- midend/eliminateInvalidHeaders.cpp
- midend/eliminateInvalidHeaders.h
- midend/flattenUnions.h
- testdata/p4_16_samples/invalid-union.p4
- testdata/p4_16_samples_outputs/dash/dash-pipeline-midend.p4
- testdata/p4_16_samples_outputs/invalid-hdr-warnings5-midend.p4
- testdata/p4_16_samples_outputs/invalid-union-first.p4
- testdata/p4_16_samples_outputs/invalid-union-frontend.p4
- testdata/p4_16_samples_outputs/invalid-union-midend.p4
- testdata/p4_16_samples_outputs/invalid-union.p4
- testdata/p4_16_samples_outputs/issue1897-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/issue3051.p4-stderr
- testdata/p4_16_samples_outputs/parser-inline/parser-inline-test13.p4-stderr
However, see #3842; that would need to be fixed to make this complete.
> Support for invalid union expressions

- tools/cpplint.diff
- tools/cpplint.py
New cpplint includes some useful features such as ignoring `// NOLINT` comments meant for other linters.
It is also required for #3937.
> Update cpplint.py to the latest version

- lib/indent.h
- lib/log.h
Basically the idea is to identify objects that take multiple lines when they appear in a log (using ostream `<<` or dbprint) and tweak the set/vector overload of `<<` to display them more cleanly.
> Better logging for lists/sets of things that take multiple lines

- .gitmodules
- CMakeLists.txt
- backends/p4tools/CMakeLists.txt
This makes sure that we only pull the dependency conditionally when P4Tools is enabled, not all the time. 
This also introduces CMake's [fetchcontent](https://cmake.org/cmake/help/latest/module/FetchContent.html) to our scripts, which is a useful CMake submodule. It makes Git submodule dependency management much easier.
> Remove the inja submodule and replace it with a CMake fetchcontent

- backends/dpdk/dpdkContext.cpp
- backends/dpdk/dpdkContext.h
- testdata/p4_16_samples/psa-header-stack.p4
- testdata/p4_16_samples_outputs/psa-header-stack-first.p4
- testdata/p4_16_samples_outputs/psa-header-stack-frontend.p4
- testdata/p4_16_samples_outputs/psa-header-stack-midend.p4
- testdata/p4_16_samples_outputs/psa-header-stack.p4
- testdata/p4_16_samples_outputs/psa-header-stack.p4-error
- testdata/p4_16_samples_outputs/psa-header-stack.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-header-stack.p4.p4info.txt
- testdata/p4_16_samples_outputs/psa-header-stack.p4.spec
> DPDK Backend: Change array index[] in table keys in context.json to $ to match with the key name in bfrt.json

- CMakeLists.txt
- backends/dpdk/CMakeLists.txt
- backends/dpdk/main.cpp
- backends/p4test/p4test.cpp
- backends/p4tools/CMakeLists.txt
- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- cmake/Linters.cmake
- control-plane/CMakeLists.txt
- control-plane/p4RuntimeArchHandler.h
- control-plane/p4RuntimeSerializer.cpp
- frontends/CMakeLists.txt
- frontends/p4/callGraph.h
- frontends/p4/def_use.h
- ir/CMakeLists.txt
- ir/ir.h
- lib/log.cpp
- lib/nullstream.cpp
- test/gtest/helpers.cpp
Factoring some changes out of #3767 to make reviewing easier. 
These changes make it possible to run IWYU across the compiler. The main change necessary was to factor out generated files such that IWYU does not try to fix includes for them. This mostly concerns protobuf files. 
With this PR, it is now possible to run IWYU across the entire compiler. 
https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md#why-include-what-you-use
> Set up P4C for IWYU

- frontends/p4/strengthReduction.cpp
StrengthReduction was missing some type information, which could lead to problems (e.g., instances of `Type_Unknown`) when using [optimizeExpression](https://github.com/p4lang/p4c/blob/main/frontends/p4/optimizeExpressions.h). 
Try to add some more type information, which can be derived from the input expressions.
> Add some more type information to the strength reduction pass.

- backends/bmv2/base_test.py
- backends/bmv2/run-bmv2-ptf-test.py
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.h
- backends/p4tools/modules/testgen/targets/bmv2/constants.h
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.cpp
- backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.h
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.h
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_direct_meter_1.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_meter_1.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_meter_2.p4
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.h
- backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.cpp
Implement P4Testgen BMv2 support for meters and direct meters.
- Add an interface to the `base_test.py` file to configure meters.
- Also add a helper function to the PTF test back end to make sure we are able to set the color we want. For green, we set the thresholds to the maximum, for red we set the thresholds to the minimum, for yellow we use a mix.
- direct meters can only be used if they are attached to a table and the table has an entry. Implement a new pass that creates a direct meter <-> table mapping. Look up this mapping when executing the extern. If there is no table entry in the table associated with the meter, skip meter execution since we can not configure it.
> [P4Testgen] Implement meter support for the BMv2 V1model PTF test back end

- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/ebpf/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/pna/test/TestTemplate.cmake
- frontends/common/parser_options.h
P4-14 is effectively deprecated. Reflect this in the default settings for the options parser.
> Make P4-16 the default parser option.

- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/ebpf/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/pna/test/P4Tests.cmake
> [P4Testgen] Fix include paths

- backends/p4tools/CMakeLists.txt
- backends/p4tools/common/lib/model.cpp
- backends/p4tools/common/lib/taint.cpp
- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/common/lib/trace_event_types.h
- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/core/program_info.cpp
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/greedy_stmt_cov.cpp
- backends/p4tools/modules/testgen/lib/collect_coverable_nodes.cpp
- backends/p4tools/modules/testgen/lib/collect_coverable_nodes.h
- backends/p4tools/modules/testgen/lib/test_spec.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/ebpf/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/ebpf/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
- backends/p4tools/modules/testgen/targets/pna/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/pna/test/TestTemplate.cmake
- frontends/p4/defaultValues.cpp
- frontends/p4/defaultValues.h
- ir/irutils.cpp
- ir/irutils.h
- midend/coverage.cpp
- midend/coverage.h
- Merge the `defaultValue` from `defaultValues.h` with `getDefaultValue` from `irutils.h`
- Fix up small issues with the metadata collection test back ends. Also collect the parser states that were traversed.
- Clean up some incorrect naming after the expanding coverage from IR statements to IR nodes.
- Do not use source info for coverage sets, instead use the clone id.
- Move the inja submodule initialization into the testgen extension. 
- Fix incorrect variable setting in the CMake test backend files.
> [P4Testgen] Fix small issues with metadata test backend. Add more functions to IR utilities. Merge default value function.

- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/common/resolveReferences/resolveReferences.h
- frontends/p4/methodInstance.cpp
- fix ConstructorCall::resolve to work without typeMap when just a ResolutionContext is available
> Open up ResolutionContext interface a bit

- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/lib/gen_eq.cpp
- backends/p4tools/common/lib/gen_eq.h
- backends/p4tools/common/lib/table_utils.cpp
- backends/p4tools/common/lib/table_utils.h
- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- frontends/p4/optimizeExpressions.h
Also simplify `optimizeExpressions.h`. The function does not need to be a template.
> [P4Testgen] Move some table code into helper functions, move gen_eq to "common" folder

- backends/p4tools/modules/testgen/CMakeLists.txt
@fruffy The change in https://github.com/p4lang/p4c/commit/38ba8dfd57d23aec71931b663f84d4eb86b0380a#diff-b2d8f4059a838269ba2d86ef0f39a84301da327327cd0415e56e7e6d68507e92R117 broke build of testgen on systems where Z3 does not have includes in the default system directory. The reason is that `add_dependencies` only affects ordering, not include-/link- search paths. Instead if I set the (static) `testgen` library to be linked to Z3 and `inja` with the `PUBLIC` option it will mean that both the library itself, and anything that it is linked to will see the include paths for both Z3 and inja and any resulting binaries will be linked to both. This not only fixes the problem, but it is also cleaner (except for the cmake weirdness that `target_link_libraries` affects both include- and …
> cmake: Fix include search for Z3 in testgen library

- backends/p4tools/common/compiler/compiler_target.cpp
- backends/p4tools/common/compiler/convert_hs_index.cpp
- backends/p4tools/common/compiler/convert_hs_index.h
- backends/p4tools/common/core/abstract_execution_state.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/p4tools.def
- midend/hsIndexSimplify.h
This PR adds support for ArrayIndices within P4Testgen. We extend the compare function of state variables to also support indices and add an additional visitor function.
With this change, we can remove some of the conversion passes that caused the P4 IR to not type check after the mid end.
> [P4Testgen] Resolve array indices in the interpreter instead of converting them in a compiler pass. 

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkContext.cpp
- backends/dpdk/dpdkUtils.cpp
- backends/dpdk/dpdkUtils.h
Fixes the following:
1) The "target_name" attribute in context json is incorrectly prefixed with control block name. This is not required as the external name of the table is captured in "name" attribute"
2) Fixed the bitwidth of action parameters as DPDK target needs all metadata to be byte aligned. The bitwidth is updated to 32 if the original bitwidth is <32, 64 otherwise.
> Dpdk Backend: Fixed target_name and action parameter bitwidth

- backends/p4tools/common/lib/taint.cpp
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
Sometimes we can overtaint because an expression that technically short-circuits is treated as taint. Implement an optimization for this behavior in the taint checker. Also try to eliminate sources of taint in some externs by exiting early (verify and update checksum).
Fixes #3887.
> [P4Testgen] Reduce overtainting by short-circuiting some expressions and extern invocations

- backends/p4tools/modules/testgen/core/small_step/small_step.cpp
- backends/p4tools/modules/testgen/core/small_step/small_step.h
- backends/p4tools/modules/testgen/core/symbolic_executor/depth_first.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/depth_first.h
- backends/p4tools/modules/testgen/core/symbolic_executor/greedy_stmt_cov.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/greedy_stmt_cov.h
- backends/p4tools/modules/testgen/core/symbolic_executor/max_stmt_cov.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/max_stmt_cov.h
- backends/p4tools/modules/testgen/core/symbolic_executor/random_backtrack.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/random_backtrack.h
- backends/p4tools/modules/testgen/core/symbolic_executor/selected_branches.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/selected_branches.h
- backends/p4tools/modules/testgen/core/symbolic_executor/symbolic_executor.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/symbolic_executor.h
- backends/p4tools/modules/testgen/lib/execution_state.h
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/testgen.cpp
Execution state should only live as long as the `run` function of the symbolic executor is active. This also makes sure we do not access some stale execution state via the symbolic executor. 
This impacts the SelectedBranches implementation, which is now simplified.
> [P4Testgen] Remove execution state from the symbolic executor, make it a parameter.

- backends/p4tools/README.md
- backends/p4tools/common/lib/variables.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/metadata/metadata.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/stf/stf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/stf/stf.h
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.cpp
- backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.h
- backends/p4tools/modules/testgen/targets/ebpf/test_backend.cpp
- backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.h
- backends/p4tools/modules/testgen/targets/pna/test_backend.cpp
- Unify test numbering and the name of the variable in the test back ends. They all start from 0 now. Also make sure the test name does not have a duplicate `.`. 
- Provide hints on available test back ends. 
- Verify that no other packets are present if the packet is dropped in PTF.
- Add some hints on the support Z3 versions. #4034 will fix this, too.
- Support array indices when converting references.
Fixes #4033.
> [P4Testgen] Miscellaneous fixes for P4testgen

- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_parser_bool_cast.p4
Fixes #4038.
Casts from bit<1> to boolean were not handled correctly in the solver. They always evaluated to false, producing fewer branches than actually possible.
Thanks for bringing attention to this @vlstill, this is a nasty one.
> [P4Testgen] Fix incorrect boolean cast in the Z3 solver implementation.

- backends/bmv2/run-bmv2-ptf-test.py
- tools/testutils.py
The P4Tools PTF tests using nanomsg are failing because the device ID and TCP ports are conflicting during parallel execution. 
Use network namespaces as a bandaid to avoid the spurious CI failures until I find a better solution.
> Fix race condition for parallel PTF nanomsg tests by using network namespaces.

- backends/tc/backend.cpp
- backends/tc/backend.h
- backends/tc/introspection.cpp
- backends/tc/tc.def
- backends/tc/tc_defines.h
> Wrap the TC defines in a namespace, use constexpr.

- .github/workflows/ci-test.yml
- Dockerfile
Build p4tools into p4c docker image by default. In particular, this will make p4testgen easily available in the prebuilt docker image on dockerhub/p4lang/p4c.
Impact:
* On my x86 platform, the p4c docker image build time increased from 29 min to 37 min. Since the main intent is to simplify developers' lives by using a prebuilt image, this seems like a good tradeoff. Building is done in the background in a CI pipeline.
* The docker p4c image size increased from 1.59GB to 1.70GB.
> Change Dockerfile to build p4tools by default.

- backends/bmv2/run-bmv2-ptf-test.py
- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/common/core/z3_solver.h
- backends/p4tools/modules/testgen/core/symbolic_executor/symbolic_executor.cpp
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/lib/test_backend.h
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
- backends/p4tools/modules/testgen/test/z3-solver/accessor.h
- midend/coverage.cpp
- Use source information as the comparison operator again, not clone ID.
- Clean up the Z3 solver. Do not keep context around and reset memory usage periodically to avoid running out of memory.
- Reduce the PTF wait time to accelerate PTF testing.
- Clean up the `entry_restriction` parser and print a warning if a restriction is not satisfiable. Also ensure argument and parameter names are consistent. 
- Change the optional implementation once again. Convert it into a ternary match that either matches exactly or is wildcarded.
> [P4Testgen] BMv2 test generation improvements

- backends/p4tools/modules/testgen/core/symbolic_executor/greedy_stmt_cov.cpp
- backends/p4tools/modules/testgen/core/symbolic_executor/random_backtrack.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.h
- backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.h
- Clean up table reference lookups for the refers_to parser. The refers_to parser was never checking the table references in the annotation. 
- Make sure string conversions to `boost::multiprecision:cpp_int` are safe by converting the `std::string_view` to a std::string first.  This is an additional copy, but older versions of boost do not safely convert `std::string_view`
- General cleanup and edits. 
- Fix a bug with path selection strategies (they did not update the execution state).
We should really use a proper lexer/parser for the P4Constraints implementation here.
> [P4Testgen] More fixes to the refers_to and p4_asserts parser

- frontends/parsers/p4/p4parser.ypp
We could refactor things so that `keysetExpression` always returns a `ListExpression` to simplify the duplication a bit (then the `if` in the `entry` actions goes away.)  This likely also means changing the `keyset` field in `SelectExpression` to be a `ListExpression` as well, which could simplify many places in the code where those are handled using an explicit check for `ListExpression`.
> Fix parser so that `priority` can be used in expressions

- midend/eliminateTuples.cpp
- testdata/p4_16_samples/issue4057.p4
- testdata/p4_16_samples_outputs/issue4057-first.p4
- testdata/p4_16_samples_outputs/issue4057-frontend.p4
- testdata/p4_16_samples_outputs/issue4057-midend.p4
- testdata/p4_16_samples_outputs/issue4057.p4
- testdata/p4_16_samples_outputs/issue4057.p4.p4info.txt
Fixes #4057 
In general, one should use getOriginal() when looking up something in a map.
> Fix crash in eliminateTuples

- ir/dbprint-p4.cpp
Before this change, the statements of the `P4Control`'s "body"/`apply` block were printed directly after the variables and tables declared in the control. With this change, the dbprint more closely resembles the original P4 code and is more readable.
> Don't omit the apply block label in P4Control::dbprint

- test/gtest/parser_unroll.cpp
The parser unroll gtest was using compiler version macro from P4TEST. As there is no global version macro, I opted for not setting the version at all in the test.
> Allow building the compiler without P4TEST enabled

- backends/bmv2/run-bmv2-ptf-test.py
- backends/p4tools/common/options.h
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/targets/bmv2/cmd_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.h
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
Previously, we hard-coded the range of supported ports in the target code. Different testing setups may have different levels of port support, so make this setting configurable. Since ports are a top-level primitive in P4Testgen, we can make this a top-level option. 
Fixes #4035.
> [P4Testgen] Make the ranges of supported ports a command line parameter for P4Testgen

- .github/workflows/ci-test.yml
- tools/install_mac_deps.sh
With that, MacOS GTests pass again :raised_hands: .
> Fix MacOS installation typo.

- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
Code updates suggested by Fabian Ruffy, and verified by building with these changes on a Fedora 37 Linux system running G++ 12.3.1.
> Fix #4067: Add static casts required by newer versions of G++

- backends/p4tools/modules/testgen/lib/collect_coverable_nodes.cpp
The parser ID was added too late. If a parser state references itself, the scanner will loop infinitely.
> [P4Testgen] Fix an infinite loop in the coverable nodes scanner.

- README.md
- tools/ci-build.sh
The OpenSuse repository keeps failing to download the p4lang debian packages. Maybe updating the deprecated key installation technique can help?
@rst0git I can not quite figure out how to fix this. Do maybe know how to fix the key installation issue? 
I believe the OpenSuse repository is malformed? It does not have a `dists` folder. I managed to work around that, but I still run into key issues.
> Try to fix Opensuse certificate errors.

- backends/dpdk/CMakeLists.txt
- backends/dpdk/main.cpp
- backends/dpdk/options.h
- backends/dpdk/tdiConf.cpp
- backends/dpdk/tdiConf.h
This PR adds the parameter `--tdi-builder-conf` to the p4c-dpdk compiler. This parameter emits the configuration necessary for the `tdi-pipeline_builder`. I am not a direct user, so I simply guessed the parameters necessary. Please let me know if there is anything else to add or remove.
Sidenote:
The `p4c-dpdk` compiler now has about four to five different parameters to create a configuration and output file.
```
--bf-rt-schema file        Generate and write BF-RT JSON schema to the specified file
-o outfile                 Write output to outfile
--tdi file                 Generate and write TDI JSON to the specified file
--context file             Generate and write context JSON to the specified file
--tdi-builder-conf file    Generate and write the TDI builder configuration to the …
```
> Add an option to the DPDK P4C back end to generate TDI builder configurations.

- backends/p4tools/modules/testgen/test/small-step/p4_asserts_parser_test.cpp
- backends/p4tools/modules/testgen/test/small-step/reachability.cpp
This follows on #4065 where I already fixed build of the compiler without p4test, but I had accidentally disabled testgen when testing the build. Apparently the exact same pattern is repeated in testgen tests, so I propose the same solution.
> Allow building testgen without P4TEST enabled

- lib/hex.h
Add include directive for cstdint which is necessary to use std::intmax_t, also qualify intmax_t with std namespace because of the use of C++ header instead of C.
> Fix missing header for intmax_t typedef

- CMakeLists.txt
- backends/dpdk/CMakeLists.txt
- backends/dpdk/control-plane/bfruntime_arch_handler.h
- cmake/Protobuf.cmake
- control-plane/CMakeLists.txt
- control-plane/bfruntime.h
- control-plane/p4RuntimeArchHandler.h
- control-plane/p4RuntimeSerializer.cpp
- control-plane/typeSpecConverter.cpp
- control-plane/typeSpecConverter.h
This PR does two things. 
- Depending on the compiler and options enabled (warnings as errors) compilation can fail. Make sure we ignore Protobuf code and warnings since we have not control over it. We do this by both setting the appropriate CMake options and also wrapping `#pragmas` around the relevant Protobuf includes.
- In CMake, the control-plane is instantiated after extensions. If an extension requires P4Runtime, we may grab the dependency too late. Ideally, we would fix initialization order such that extensions are instantiated after we are done with the compiler front end.  Consider cleaning up the initialization order in a separate PR.
> Make sure we ignore warnings in the Protobuf dependency source code.

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkHelpers.cpp
- testdata/p4_16_samples/pna-dpdk-header-stack-assignment.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment-first.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment-frontend.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment-midend.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment.p4.spec
> Dpdk Backend :Fix header stack assignment in p4c-dpdk

- .github/workflows/ci-dpdk-ptf-tests.yml
- backends/dpdk/CMakeLists.txt
- backends/dpdk/run-dpdk-ptf-test.py
- testdata/p4_16_samples/pna-dpdk-add_on_miss0.p4
- testdata/p4_16_samples/pna-dpdk-add_on_miss0.py
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0-first.p4
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0-frontend.p4
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0-midend.p4
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0.p4
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0.p4-error
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-dpdk-add_on_miss0.p4.spec
- tools/dpdk-ci-build.sh
This PR sets up a PTF test CI pipeline for p4c-dpdk and the dpdk-target. 
- [PTF(Packet Testing Framework)](https://github.com/p4lang/ptf) is a Python based dataplane test framework.
- [p4c-dpdk](https://github.com/p4lang/p4c/blob/main/backends/dpdk) is the p4 dpdk compiler backend that translates the P4-16 programs to DPDK API to configure the DPDK software switch (SWX) pipeline.
- [DPDK-target](https://github.com/p4lang/p4-dpdk-target/tree/main) implements the P4 pipeline,driven by artifacts generated by the P4 compiler.
A PTF test CI pipeline for p4c-dpdk on the DPDK SWX is currently missing. Adding such tests is beneficial for both the development of the compiler backend and DPDK SWX pipeline.
- Make sure `infrap4d` and `p4sde/dpdk-target` are properly …
> Add a PTF test CI pipeline for p4c-dpdk on the DPDK SoftNIC

- BUILD.bazel
- CMakeLists.txt
- README.md
- cmake/config.h.cmake
- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
- lib/CMakeLists.txt
- lib/alloc_trace.cpp
- lib/alloc_trace.h
- lib/backtrace_exception.cpp
- lib/backtrace_exception.h
- lib/crash.cpp
- lib/gc.cpp
- lib/gc.h
- Memory allocation tracing hooks to track where memory is being allocated and print summary with stack trace of each allocation site.  Used when logging in ComputeWriteSet to understand how/why it is using so much memory.
> Use libbacktrace for stack dumps if available

- bazel/p4_library.bzl
This is a step forward for the full migration of Automatic Exec Groups (AEGs). This change will be effective once AEGs are enabled.
Goal of this migration:
* Each toolchain type should have its own execution platform. Before this change, the execution platform was selected on a rule base, not on a toolchain type base.
* Each action which uses a tool coming from a toolchain should specify the toolchain type inside ctx.action.{run, run_shell} toolchain attribute.
The affected action uses tools from cpp toolchain. Hence, cpp toolchain is added to the `toolchain` param.
> Migrate Automatic Exec Groups by adding a toolchain parameter to the affected actions

- .github/CODEOWNERS
The way code owners is currently implemented generates a lot of unnecessary spam. Also, we do not have the resources to review all PRs, so instead we delegate to general approval.
> Remove P4Testgen codeowners file

- ir/ir.cpp
- testdata/p4_16_errors/issue4144.p4
- testdata/p4_16_errors_outputs/issue4144-first.p4
- testdata/p4_16_errors_outputs/issue4144-frontend.p4
- testdata/p4_16_errors_outputs/issue4144.p4
- testdata/p4_16_errors_outputs/issue4144.p4-stderr
> Fix invalid string format specifier

- tools/driver/p4c_src/main.py
These envarrs specify the default target/arch/version to use only if NOT specified on the command line.  Command line take priority.
> Sane handling of P4C_DEFAULT_X envvars in p4c

- backends/ebpf/p4c-ebpf.cpp
- backends/ebpf/psa/examples/bng.p4info.txt
- backends/ebpf/psa/examples/l2l3-acl.p4
- backends/ebpf/psa/examples/l2l3-acl.p4info.txt
- backends/ebpf/psa/examples/upf.p4info.txt
- backends/ebpf/tests/p4testdata/action-profile2.p4info.txt
- backends/ebpf/tests/p4testdata/action-selector2.p4info.txt
- backends/ebpf/tests/p4testdata/counters.p4info.txt
- backends/ebpf/tests/p4testdata/digest.p4info.txt
- backends/ebpf/tests/p4testdata/meters-direct.p4info.txt
- backends/ebpf/tests/p4testdata/meters.p4info.txt
- backends/ebpf/tests/p4testdata/pvs.p4info.txt
- backends/ebpf/tests/p4testdata/register-apply.p4info.txt
- backends/ebpf/tests/ptf/bng.py
- backends/ebpf/tests/ptf/common.py
- backends/ebpf/tests/ptf/l2l3_acl.py
- backends/ebpf/tests/ptf/meters.py
- backends/ebpf/tests/ptf/register.py
- backends/ebpf/tests/ptf/table_implementation.py
- backends/ebpf/tests/ptf/test.py
- backends/ebpf/tests/ptf/upf.py
Allow to generate P4Runtime files by ebpf backend, because options related to them are ignored.
Supports only PSA architecture. For ebpf filer model options for generating P4info files are (still) ignored.
> eBPF backend: generate P4Runtime files if required

- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
Fixes #4151. This was a silly bug. Earlier, P4Testgen only had to option to fix packet size to a particular value. After transitioning to ranges, the equality was not converted into a greater-equals relation.
> [P4Testgen] Do not use Equ for mandating a minimum size.

- ir/ir.cpp
- testdata/p4_16_errors/issue4140.p4
- testdata/p4_16_errors_outputs/issue4140-first.p4
- testdata/p4_16_errors_outputs/issue4140-frontend.p4
- testdata/p4_16_errors_outputs/issue4140.p4
- testdata/p4_16_errors_outputs/issue4140.p4-stderr
> Add error message for non-package main declaration

- backends/dpdk/backend.cpp
- backends/dpdk/dpdkArch.h
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment.p4.spec
Due to missing type information, header copy elimination was not expanding whole header copy to member-wise copy in some cases. Added passes to update refmap and typemap before the header copy elimination pass.
Fixes #3965 #4114
> Dpdk Backend: Fix whole header move instructions for DPDK

- frontends/p4/def_use.h
- lib/CMakeLists.txt
- lib/hashvec.cpp
- lib/hashvec.h
- lib/hvec_map.h
- test/CMakeLists.txt
- test/gtest/hvec_map.cpp
The impetus for this comes from a customer case that is blowing up (memory-use-wise) in the frontend ComputeWriteSets code -- it turns out that the overhead for an ordered_map where both the key and value are just pointers is quite extreme.
This code is old C code that I've repurposed to be the base class of an improve C++ map class -- it keeps the map elements in a simple `vector<pair<KEY, VALUE>>` and has a separate hash table of indexes into the vector for fast lookup.  So the overhead is just a few bytes per entry, compared to the ~48 bytes (6 pointers) per entry used by ordered_map.  This reduces the peak memory use for our case from 12GB to 5.1GB.  Speed is pretty much unchanged.
This could trivially be extended to support more efficient ordered_sets as well (and multimaps and …
> Hashvec-based maps to save memory

- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
Collection of small P4Testgen fixes/improvements.
- Reduce the default packet size back to 1500 byte MTU. 9000 byte is overwhelming
- Rename the BMv2 tests to appropriately reflect the test back end.
> [P4Testgen] Minor improvements and fixes for P4Testgen. 

- backends/p4test/CMakeLists.txt
Maybe this can help with the sporadic test failures. I wonder whether we should even still bother with testing p4-14.
> Increase the timeout of the switch.p4 p4_14 program

- backends/ebpf/ebpfControl.cpp
- backends/ebpf/ebpfDeparser.cpp
- backends/ebpf/ebpfProgram.cpp
- backends/ebpf/ebpfProgram.h
- backends/ebpf/psa/ebpfPsaGen.cpp
As mentioned in the issue, we have conflicting versions of this macro. This patch avoids the issue by renaming the second version.
In an ideal world, all call sites would make use of the second, more general version. But that felt like too invasive a change, so instead I went for a minimalist approach.
The issue never arose before, because the only flow which made use of `ebpfDeparser` was within the PSA target.
> backends/ebpf: Fix #4098 by renaming conflicting write_partial macro.

- backends/p4tools/modules/testgen/targets/pna/constants.h
Some stale BMv2 code caused a type mismatch.
> [P4Testgen] Change PNA port width to 32 instead of 9

- cmake/Protobuf.cmake
In `cmake/Protobuf.cmake`, when `P4C_USE_PREINSTALLED_PROTOBUF` is enabled (which is the default case), the `protoc` binary is directly fetched from GitHub releases. However, there was an issue with the hardcoded assumption that the downloaded `.zip` archive is for the `x86_64` architecture, which resulted in compilation errors on `arm64` systems such as Apple M1/M2 silicons or when building multi-platform Docker containers.
This pull request addresses the problem by dynamically selecting the appropriate `.zip` archive based on the host architecture. It achieves this by utilizing the `CMAKE_HOST_SYSTEM_PROCESSOR` variable in CMake, which leverages `uname -r` to identify the target architecture.
Currently, this selection logic has been implemented for the `arm64` architecture, but it can …
> Get host architecture dynamically while downloading `protoc` binary

- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/common/lib/trace_event_types.h
- backends/p4tools/modules/testgen/benchmarks/test_coverage.py
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/backend/ptf/ptf.cpp
- ir/irutils.cpp
- ir/irutils.h
- lib/source_file.cpp
- lib/source_file.h
Add some more tracing information to P4Testgen:
- Assignment statements
- Method calls
- Switch cases
Also augment the IR utility functions with SourceInfo as parameter so that we can trace back certain literals to their original expression.
> [P4Testgen] Add more trace information to P4Testgen

- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
See also https://github.com/p4lang/p4-constraints/pull/101
> [P4Testgen] Encode more P4Runtime constraints for the behavioral model

- ir/dbprint-p4.cpp
This shall change allows seeing annotations in action's dbprint output where it was missing previously
e.g.
```
@hidden @Foo(1) action action_1() {...
```
> Show annotations in actions' dbprint

- .github/workflows/ci-test.yml
- .github/workflows/ci-ubuntu-18-nightly.yml
- .github/workflows/ci-ubuntu-20-sanitizer-nightly.yml
- .github/workflows/ci-validation-nightly.yml
Save some CI resources on PRs.
> Run Gauntlet validation, sanitizers, and Ubuntu 18 build/test as nightly actions.

- backends/ebpf/CMakeLists.txt
- backends/ebpf/ebpfParser.cpp
- backends/ebpf/run-ebpf-test.py
- backends/ebpf/targets/target.py
- testdata/p4_16_ebpf_errors/header_unaligned.p4
- testdata/p4_16_ebpf_errors_outputs/header_unaligned.p4-stderr
- tools/testutils.py
Also adds support for testing error messages in the eBPF backend (separate commit).
Previously, declaring such a header would not have caused any compile-time errors but generated functionally incorrect code. With this patch, the user is made aware and compilation fails.
Fixes #4176
> backends/ebpf: Output error if a header is not byte-aligned (#4176).

- backends/p4tools/common/core/z3_solver.cpp
We support string literals already, but not the symbolic string type `string_sort`. Fix that.
> [P4Testgen] Support string types in the Z3 solver.

- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/lib/collect_coverable_nodes.cpp
Also check for null in node coverage.
> [P4Testgen] Only look ahead for the else branch when it is not null.

- frontends/common/parser_options.cpp
- lib/error_catalog.h
The PR ensures that error messages cannot be demoted to info messages.
With `p4c --Winfo=invalid ...`, the following error is printed out:
`[--Werror=invalid] error: Error invalid cannot be demoted`
> Ensured that error messages cannot be demoted to info messages

- backends/p4tools/modules/testgen/benchmarks/test_coverage.py
- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
With the same reasoning as #4066. `.proto` is usually used for the schema definition file, while `.txtpb` is the current recommendation for the [text format file](https://protobuf.dev/reference/protobuf/textformat-spec/#text-format-files).
> [P4Testgen] Change Protobuf backend test case file extension to `.txtpb`

- backends/p4tools/common/lib/symbolic_env.cpp
- backends/p4tools/common/lib/table_utils.h
- backends/p4tools/modules/testgen/benchmarks/plots.py
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.h
- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/table_stepper.h
- backends/p4tools/modules/testgen/lib/continuation.cpp
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
This PR simplifies the way we handle `action_return`. Instead of returning an index and then trying to reconstruction the action from the index and the table, we simply return a string expression. This string expression contains the action name, which we can directly match.
> [P4Testgen] Match switch labels directly using string literal expressions

- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
Avoid passing a nullptr to the CoverableNodesScanner.
> [P4Testgen] Fix another segmentation fault when using the coverable nodes scanner.

- backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/proto/p4testgen.proto
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
Cheap workaround to deal with double quote characters within a trace object. Also fix up the Protobuf format for P4Testgen test messages. We are currently not testing these, so breakages were not detected.
Fixes #4202. @qobilidop
> [P4Testgen] Fix textproto generation and escape traces properly.

- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/p4include/testgen.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_1.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_2.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_assume_1.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_assume_2.p4
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/assert_assume_tests/bmv2_testgen_assert_assume_3.p4
For starters, this defines `testgen_assume` and `testgen_assert`. This makes it easier to add these externs to a program.
> [P4Testgen] Add a testgen.p4 file with custom extern definitions

- backends/bmv2/run-bmv2-test.py
Small quality-of-life improvement. Still parse STF files even though the BMv2 model cannot be run.
> Still parse STF files, even when BMv2 model is not present in system

- backends/p4tools/modules/testgen/targets/ebpf/test/P4Tests.cmake
This test has been failing in CI recently. Unclear why. Might be a kernel or dependency change.
> [P4Testgen] Ignore flaky test in P4Testgen eBPF back end.

- ir/ir.def
- tools/ir-generator/ir-generator-lex.l
- tools/ir-generator/methods.cpp
The JSONLoader constructor is not omitted when the `#noconstructor` directive is active. This is because it is generated via a non-standard way. 
This PR  adds a `#no_methodconstructor` directive, which allows you to ignore constructors generated via these special methods.
This PR also supports casing for the `#noXXX` directive. Some functions can not be ignored because they are written in camelcase.
> #noconstructor should also include the json loader constructor

- backends/p4tools/BUILD.bazel
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/metadata.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/metadata.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/stf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/stf.h
This is the second PR of a series of three to refactor the BMv2 test back ends. 
This PR moves code that is common to the increasing amount of  test back ends into a `common` class. This makes it easier to add new test back ends to the BMv2 P4Testgen extension. 
It also renables the BMv2 Protobuf back end and updates its Xfails.
> [P4Testgen] Move common code of BMv2 test back ends into a common class.

- backends/bmv2/bmv2stf.py
- backends/bmv2/run-bmv2-test.py
- backends/p4test/run-p4-sample.py
- backends/tc/run-tc-test.py
- tools/install_fedora_deps.sh
The fedora:latest container now comes with Python 3.12. Older gRPC versions do not support this Python version. See
https://github.com/grpc/grpc/issues/33063.
An alternative would be to pin the fedora container version, but then someone has to remember to update it periodically...
> Update gRPC python version in install_fedora_deps.sh

- backends/bmv2/common/action.cpp
- backends/bmv2/common/action.h
- backends/bmv2/common/parser.cpp
- backends/bmv2/common/parser.h
The inParser parameter is not actually used. I think it was introduced back when both converters shared the same implementation.
> Simplify jsonAssignment in ParserConverter and ActionConverter

- midend/hsIndexSimplify.cpp
Before this, the compiler would fail i.e. on
```
hdr.h2.f3 = hdr.hs[r0.read((bit<32>)hdr.h0.idx0)].f0;
-->
Internal error: In file: ./build/p4c/ir/ir-generated.cpp:4173
Compiler Bug: ./build/p4c/ir/ir-generated.cpp:4173: Null left
```
The failure is in `validate()` method because the `aiFinder.newVariable` is null when creating `Eq` constraint in `eliminateArrayIndexes`.
> Allow method calls in index expressions in hsIndexSimplify

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeChecker.h
Currently, the compiler would produce only a very vague error message if type checking runs in immutable mode and the IR tree is actually modified. This is extremely annoying to debug. Therefore, I've added the check after each node is processed and the check now reports the offending node.
I've also modified the `end_apply` function (which still prints the generic check, although it is probably redundant):
- calling parent `end_apply`
- the nodes should be comparend for exact pointer equality, not for internal semantic equality -- it is not OK if the transform produces new tree that is equivalent in the readOnly mode. It must keep the original tree.
> Report offending node in the type-checker immutability check

- backends/p4tools/common/compiler/midend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_valid_lit.p4
Previously, testgen would fail will errors like this (when #4238 is applied to make the error readable):
```
Internal error: In file: ./p4c/frontends/p4/typeChecking/typeChecker.cpp:172
Compiler Bug: build/init.p4(78): At this point in the compilation typechecking should not infer new types anymore, but it did: node (hdr_0_t){#}.isValid(); changed to 0;
hdr.hdr_0 = (hdr_0_t){#};
^
build/init.p4(78)
hdr.hdr_0 = (hdr_0_t){#};
^
```
> [P4Testgen] Add EliminateInvalidHeaders midend pass

- frontends/common/constantFolding.h
- frontends/p4/coreLibrary.h
- frontends/p4/fromv1.0/converters.h
- frontends/p4/fromv1.0/programStructure.h
- frontends/p4/fromv1.0/v1model.h
- ir/dbprint.h
- ir/node.h
- ir/visitor.h
- lib/compile_context.h
- lib/error_catalog.h
- lib/error_message.h
- lib/hashvec.cpp
- lib/indent.h
- lib/log.h
- lib/ordered_map.h
- lib/safe_vector.h
- lib/sourceCodeBuilder.h
- lib/source_file.h
- lib/stringref.h
All these are found by the clang-tidy static analyzer. At this point, I've been only running in on the headers as this is mainly a byproduct of linting a downstream tool. Some of these changes are in the readability category rather than possible bugs, but I think they are all worth applying.
> Fix some problems and suggestions found by clang-tidy

- lib/options.h
This change allows to override default usage() method in Options.
> Allow overriding of 'usage' method in the Options class

- lib/castable.h
`ICastable` was missing a `checkedTo` cast for writable objects. We already had a `to`, but no `checkedTo`.
> Allow non-const checkedTo cast.

- backends/p4tools/common/core/abstract_execution_state.cpp
- backends/p4tools/common/core/abstract_execution_state.h
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.h
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/pna/test_backend.cpp
This PR tightens the API around state management:
- Make typing stricter for P4Testgen functions that work with StateVariables. Do not allow generic IR::Expression anymore.  
- Clean up `getFlatFields`, we do not actually need to pass in the struct type. Also make sure we handle header stacks correctly.
> [P4Testgen] Ensure accurate typing for functions that work with references.

- lib/error_catalog.cpp
- lib/error_catalog.h
The PR adds named constants for min and max values of error, warning, and info message codes to be used in backends. Also, the `ErrorCatalog::add` method now expects a code type so that it can perform range check. E.g.:
`ErrorCatalog::getCatalog().add<ErrorMessage::MessageType::Info, INFO_USER_CODE>("user-code");`
If the range check fails, a bug is triggered.
In addition, a new info code INFO_PROGRESS is added.
> Added range check of error codes

- backends/p4tools/modules/testgen/main.cpp
Changed messages emitted when Testgen crashes to differentiate them from the ones reported by the compiler. Example:
```
Internal error: In file: ./p4c/backends/p4tools/modules/testgen/lib/execution_state.cpp:301
Testgen Bug: Did not find exception handler for Exception::NoMatch.
Please submit a bug report with your code.
```
I think this will be useful for example for CI flows where first Testgen is used to generate test cases and then a compiler is used on the same input. Currently it's not obvious if Testgen crashes because the message contains `Compiler Bug`.
> [P4Testgen] Change crash message

- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/lib/test_backend.h
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/testgen.cpp
This is intended for running testgen in CI and catching cases when the test is not properly covered, either through test or testgen fault.
Example output on uncoverable tests:
```
============ Test 0: Nodes covered: 0.266667 (4/15) ============
============ Test 1: Nodes covered: 0.4 (6/15) ============
============ Test 2: Nodes covered: 0.533333 (8/15) ============
============ Test 3: Nodes covered: 0.6 (9/15) ============
error: The tests did not achieve requested coverage of 1, the coverage is 0.6.
```
> [P4Testgen] Add --assert-min-coverage option to check coverage of generated test cases

- backends/p4tools/common/lib/trace_event_types.h
... to match the implementation: https://github.com/p4lang/p4c/blob/main/backends/p4tools/common/lib/trace_event_types.cpp#L31.
> [P4Testgen] Fix argument names in GenericDescription trace event

- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
Previously, the testgen would generate `NoMatch` exception in parser only if it was caused by explicitly set value, but not when it was an implicit option based on symbolic input. This is now fixed. If there is no default a new successor (guarded by composite `missCondition`) will be added to the select expression.
I've opted to implementing this explicitly in the stepper as opposed to adding the `HandleNoMatch` midend pass as the latter would explicitly set the `error` instead of raising the exception. Note that for header stack overflow, testgen already uses a midend pass that sets the error using `verify` and this might be wrong.
@fruffy, I'm not sure if I need to change anything else (e.g. `P4ProgramDCGCreator::preorder(const IR::SelectExpression *selectExpression)`. Also, I don't …
> [P4Testgen] Generate NoMatch for selects without default

- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/compiler/convert_struct_expr.cpp
- backends/p4tools/common/compiler/convert_struct_expr.h
- backends/p4tools/common/compiler/midend.cpp
- ir/expression.def
~~In some cases, one may want to create a struct expression, which contains the relevant type directly, without having to use a `Type_Name` as indirection. This PR relaxes the constraints around the creation of struct expressions to make this possible. We simply add a new parameter that allows us to toggle whether or not to accept `IR::Type_StructLike` types.~~
When resolving struct expressions, simply preserve Type_Name for structType but assign the resolved type to type. This works for all dependent PRs and preserves functionality of passes such as toP4 etc.
> [P4Testgen] Add a compiler pass to resolve Type_Name in StructExpressions.

- backends/p4tools/common/lib/gen_eq.cpp
- backends/p4tools/common/lib/gen_eq.h
- ir/irutils.cpp
- ir/irutils.h
Simplify `genEq` by performing all checks within a single function and resolving nested expressions recursively. Also ensure support of struct expressions. Note that this assumes that the elements within the struct expression are already ordered, i.e, they are enumerated the same way the underlying type is. The struct expression comparison is also on the basis of the contained expressions. We do not check whether the names are the same.
> [P4Testgen] Flatten the genEq function and support struct expressions.

- .clang-tidy
`AnalyzeTemporaryDtors` is deprecated and throws and error. 
`--std=c++17` does not have any effect, it seems. It only throws an error.
> Fix clang-tidy config file.

- backends/p4tools/common/compiler/convert_struct_expr.cpp
- backends/p4tools/common/compiler/convert_struct_expr.h
- backends/p4tools/common/core/abstract_execution_state.cpp
- backends/p4tools/common/core/abstract_execution_state.h
- backends/p4tools/common/lib/model.cpp
- backends/p4tools/common/lib/model.h
- backends/p4tools/common/lib/symbolic_env.cpp
- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.h
- backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
- backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.cpp
- backends/p4tools/p4tools.def
This PR adds support for struct expressions in P4Testgen. Concretely, it adds utility functions to handle assignments and pass struct expressions as full argument. It also generalizes some utility functions to support BaseListExpressions, StructExpressions, and HeaderStackExpressions.
The goal of these changes is to enable two features:
- Support of meta information of complex P4 objects (such as validity and the `next` index of header stacks)
- Support of struct expressions as method call arguments. This will make implementation of externs significantly easier because we do not have to resolve the arguments within the extern any longer. Instead, we are able to access all necessary arguments directly. 
It also introduces a new IR type. HeaderExpressions. HeaderExpressions track the …
> [P4Testgen]  Add struct and header expressions as a first-class expression to P4Testgen. 

- backends/p4tools/BUILD.bazel
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/proto/ir.proto
- backends/p4tools/modules/testgen/targets/bmv2/proto/p4testgen_ir.proto
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.h
- control-plane/google/rpc/code.proto
- control-plane/google/rpc/status.proto
This test back end reuses much of the PTF test back end code, but instead produces a text protobuf file. This text protobuf file uses the  [p4_pdpi](https://github.com/sonic-net/sonic-pins/tree/main/p4_pdpi) format. This format uses human-readable control-plane names (similar to STF and PTF) instead of requiring P4Runtime IDs for configuration. 
A couple changes were necessary for this to work: 
1. Copy the `ir.proto` to the P4Testgen BMv2 `proto` folder since we do not want to depend on the large pins repository. 
2. Add `code.proto` to `control-plane/google/rpc/code.proto` and refresh `status.proto`
3. Add a new `PROTOBUF_IR` back end and start to deprecate the original PROTOBUF back end. Much of the functionality of PROTOBUF is covered by PROTOBUF_IR.
> [P4Testgen] Introduce a new Protobuf backend which uses P4 PDPI instead of P4Runtime 

- backends/p4tools/common/lib/symbolic_env.cpp
- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/common/lib/trace_event_types.h
- backends/p4tools/common/lib/util.cpp
- backends/p4tools/common/lib/util.h
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/ebpf/program_info.cpp
- backends/p4tools/modules/testgen/targets/pna/dpdk/program_info.cpp
- backends/p4tools/p4tools.def
Finally fixing this longstanding issue. We always had to resolve method call arguments within an extern, which often resulted in unnecessary redundant code. Further, for `InOut` parameters, the original reference was lost.
Now we frontload this directly in the method call expression. We resolve arguments `In` and `InOut` parameters before stepping into the extern. For `InOut` arguments, we replace the expression with an `InOutReference`, which preserves the reference. This way we can read the input argument and also write to the original reference once we step into an extern. With #4215 merged, we can also pass in any complex expression such as header or struct expressions as arguments.
> [P4Testgen] Resolve method call arguments before stepping into an extern - preserve InOut references

- backends/p4tools/common/CMakeLists.txt
Some files were accidentally classified as system files, although they were local. This causes problems with such as tools as include-fixer.
> [P4Testgen] Fix accidental system file categorization.

- lib/ordered_map.h
This standard utility has been removed with C++17. The common advice seems to be to just remove it. 
https://stackoverflow.com/a/22387805/3215972
https://stackoverflow.com/a/57236882/3215972
https://stackoverflow.com/a/33115341/3215972
> Remove deprecated inheritance from std:binary_function

- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/lib/constants.h
- backends/p4tools/common/lib/logging.cpp
- backends/p4tools/common/lib/logging.h
- backends/p4tools/modules/testgen/lib/logging.cpp
- backends/p4tools/modules/testgen/lib/logging.h
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/lib/test_backend.h
- backends/p4tools/modules/testgen/lib/test_framework.cpp
- backends/p4tools/modules/testgen/lib/test_framework.h
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/testgen.cpp
Some logging code such as info or performance collection and recording is generally useful for the tools framework. Move it into the `common/lib` folder.
> [P4Testgen] Move P4Testgen's logging function into the common library.

- test/gtest/helpers.h
In #4287 I've accidentally create use of unitialized value in test because of initialization order of the `RedirectStderr`. This fixes it by making sure the stringstream is initialized first.
> Fix initialization order in gtest helper

- bazel/p4_library.bzl
Now that Bazel 7.0 has been released, it's time to remove this tech debt.
This has been a no-op since Bazel 5.0, I've been waiting to remove the code for two years, it's time.
Part of https://github.com/bazelbuild/bazel/issues/14127.
> Remove uses of `incompatible_use_toolchain_transition`.

- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/expressions.cpp
- backends/p4tools/modules/testgen/test/z3-solver/constraints.cpp
Quite the subtle issue I ran into. In the Z3 solver, string_constants are not constants but functions. We need to assign a value instead to get the correct semantic behavior. Otherwise, the solver can freely assign a value to the function.
> [P4Testgen] Fix stringliteral conversion. Value must be a literal, NOT a constant

- backends/dpdk/dpdkArch.cpp
- testdata/p4_16_samples/pna-dpdk-parser-wrong-arith.p4
- testdata/p4_16_samples_outputs/pna-dpdk-header-stack-assignment.p4.spec
- testdata/p4_16_samples_outputs/pna-dpdk-parser-wrong-arith-first.p4
- testdata/p4_16_samples_outputs/pna-dpdk-parser-wrong-arith-frontend.p4
- testdata/p4_16_samples_outputs/pna-dpdk-parser-wrong-arith-midend.p4
- testdata/p4_16_samples_outputs/pna-dpdk-parser-wrong-arith.p4
- testdata/p4_16_samples_outputs/pna-dpdk-parser-wrong-arith.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-dpdk-parser-wrong-arith.p4.spec
- testdata/p4_16_samples_outputs/pna-example-varIndex-1.p4.spec
- testdata/p4_16_samples_outputs/pna-example-varIndex-2.p4.spec
- testdata/p4_16_samples_outputs/pna-example-varIndex.p4.spec
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.spec
- testdata/p4_16_samples_outputs/pna-issue3041.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-checksum-arg-header.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-tmp-mask-align.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_1.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_2.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_3.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_5.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_6.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_7.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_8.p4.spec
- testdata/p4_16_samples_outputs/psa-example-dpdk-byte-alignment_9.p4.spec
- testdata/p4_16_samples_outputs/psa-example-parser-checksum.p4.spec
- testdata/p4_16_samples_outputs/psa-variable-index.p4.spec
when multiple non-byte aligned header fields are combined into single byte aligned field. The references of these fields are updated with incorrect slice operation.
For ex: when 
```
header ipv4_t {
...
bit<3>  flags;
bit<13> fragOffset;
...
}
```
is converted into
```
header ipv4_t {
...
bit<16>  flags_fragOffset;
...
}
```
_flags_ field should be converted to _flags_fragOffset[15:13]_
_fragOffset_ should be converted to _flags_fragOffset[12:0]_
But currently the conversion happens like this
_flags_ field is converted to  _flags_fragOffset[2:0]_
_fragOffset_ is converted to  _flags_fragOffset[15:3]_
Fixes https://github.com/p4lang/p4c/issues/4077
> Dpdk Backend: Fix incorrect field extraction arithmetic

- .github/workflows/ci-static-build-test.yml
- CMakeLists.txt
- Dockerfile
- tools/ci-build.sh
- tools/debian-build/packaging.conf
Turns out we can not really build a clean static binary on Linux because of limitations of the glibc library. 
https://stackoverflow.com/questions/3430400/linux-static-linking-is-dead
Also, linking with `-static` causes problems when building Protobuf and [bdwgc](https://github.com/ivmai/bdwgc) from scratch. Hence, we remove `-static` from our build process and rename the CMake parameters appropriately.
> Remove -static and rename static build appropriately.

- backends/p4tools/common/lib/format_int.cpp
- backends/p4tools/common/lib/format_int.h
- backends/p4tools/modules/testgen/targets/bmv2/concolic.cpp
- backends/p4tools/modules/testgen/targets/bmv2/concolic.h
- backends/p4tools/modules/testgen/targets/bmv2/contrib/bmv2_hash/calculations.cpp
- backends/p4tools/modules/testgen/targets/bmv2/contrib/bmv2_hash/calculations.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.h
- backends/p4tools/modules/testgen/test/lib/format_int.cpp
P4 SAI annotations such as `@format` dictate a specific format, which must be respected by P4Testgen when generating Protobuf PDPI tests. Hence, we add a couple utility functions to the Protobuf PDPI test back end to produce the right format in the case that a key has such an annotation. 
Fixes #4273.
> [P4Testgen] Add support for @format annotations in P4 programs for protobuf-ir tests

- backends/p4tools/modules/testgen/core/program_info.h
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/core/target.cpp
- backends/p4tools/modules/testgen/core/target.h
- backends/p4tools/modules/testgen/targets/bmv2/cmd_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.h
- backends/p4tools/modules/testgen/targets/bmv2/target.cpp
- backends/p4tools/modules/testgen/targets/bmv2/target.h
- backends/p4tools/modules/testgen/targets/ebpf/cmd_stepper.cpp
- backends/p4tools/modules/testgen/targets/ebpf/program_info.cpp
- backends/p4tools/modules/testgen/targets/ebpf/program_info.h
- backends/p4tools/modules/testgen/targets/ebpf/target.cpp
- backends/p4tools/modules/testgen/targets/ebpf/target.h
- backends/p4tools/modules/testgen/targets/pna/dpdk/cmd_stepper.cpp
- backends/p4tools/modules/testgen/targets/pna/dpdk/program_info.cpp
- backends/p4tools/modules/testgen/targets/pna/dpdk/program_info.h
- backends/p4tools/modules/testgen/targets/pna/shared_program_info.cpp
- backends/p4tools/modules/testgen/targets/pna/target.cpp
- backends/p4tools/modules/testgen/targets/pna/target.h
Before this change, the `ArchSpec` was defined in each target. However, this approach is too restrictive for the targets that allow variability in the exact signature of the pipeline. In these cases, it is necessary to have the ArchSpec depend not only on the architecture itself, but also on the actual P4 code (on the instances used in the `main` package). Therefore, I propose moving the ArchSpec definition to program info.
This should not pose any problem as:
* the places that use it either have access to ProgramInfo
* or it is accessed when program info is being created (i.e. `TestgenTarget::initProgramImpl`) 
* For existing targets I make the arch spec also available as static const value member of the `*ProgramInfo` class so it can be accessed -- this also demostrates clearly that it …
> [P4Testgen] Move arch spec to ProgramInfo to allow it to depend on P4 program

- backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/lib/collect_coverable_nodes.cpp
- backends/p4tools/modules/testgen/lib/collect_coverable_nodes.h
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/P4Tests.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/p4-programs/bmv2_table_actions_coverage.p4
- midend/coverage.cpp
- midend/coverage.h
Resolves #4305.
This PR adds a new coverage tracking option for P4Testgen: `--track-coverage ACTIONS`. This makes it possible to track coverage of action invocation, including empty actions which are not included in the statement coverage because they don't contain any statements.
I've added a test that exercises this feature and that I have used to test it manually. However, I don't see a way we can currently automatically test that this testgen will generate all the right tests for this test case. This could be tested better if/when #4304 is implemented.
> [P4Testgen] Implement coverage tracking of actions

- frontends/p4/moveDeclarations.cpp
- test/gtest/frontend_test.cpp
Ensure that MoveInitializers keeps the srcInfo when creating a new body for a P4Control.
Fix for issue #4315
> keep P4Control->body->srcInfo during init move

- ir/pass_manager.h
... and add `explicit` to the constructors that could be accidentally invoced by implicit casts otherwise
> Allow constructing PassRepeated from a PassManager

- backends/p4tools/common/compiler/convert_varbits.h
- backends/p4tools/common/lib/symbolic_env.cpp
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- frontends/common/constantFolding.cpp
- frontends/p4/strengthReduction.cpp
Fixes this error:
```
Internal error: In file: ./p4c/backends/p4tools/modules/testgen/lib/continuation.cpp:124
P4Testgen Bug: Continuation v; has parameter of type bit<32>, but was given an argument (|*packetLen_bits(bit<32>)| >> 3) + 4294967238; of type <Type_Unknown>(2)
```
Which is caused by `P4::optimizeExpression` not preserving type when changing `x - CONST` to `x + (-CONST)`.
The change is mainly in two passes: ConstantFolding and StrengthReduction -- I've tried to make sure the types of expressions are preserved by these passes. I've also added propagation of source info to a few places.
> Make sure P4 expression optimization does not strip away types

- frontends/common/constantFolding.cpp
- testdata/p4_16_samples/constant-fold-infint.p4
- testdata/p4_16_samples_outputs/constant-fold-infint-first.p4
- testdata/p4_16_samples_outputs/constant-fold-infint.p4
- testdata/p4_16_samples_outputs/constant-fold-infint.p4-stderr
- testdata/p4_16_samples_outputs/issue2444-first.p4
- testdata/p4_16_samples_outputs/issue3219-first.p4
- testdata/p4_16_samples_outputs/issue3219-frontend.p4
- testdata/p4_16_samples_outputs/issue3219-midend.p4
This showed as bug in testgen, but the core of the issue is that the constant folder was not handling `(int)` cast. That is fixed by this PR.
> Allow constant-folding of arbitrary-precision integer casts

- backends/p4tools/common/compiler/compiler_target.cpp
- backends/p4tools/common/compiler/compiler_target.h
- backends/p4tools/common/p4ctool.h
- backends/p4tools/modules/testgen/main.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/binary.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/unary.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/value.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/transformations/saturation_arithm.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/asrt_model.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/expressions.cpp
- backends/p4tools/modules/testgen/test/gtest_utils.cpp
- backends/p4tools/modules/testgen/test/gtest_utils.h
- backends/p4tools/modules/testgen/test/small-step/util.h
- backends/p4tools/modules/testgen/testgen.cpp
- backends/p4tools/modules/testgen/testgen.h
Major rewrite of the ProgramInfo and CompilerTarget infrastructure. The basic idea is to compute all necessary static analysis information in the compilation phase, then pass this information forward to ProgramInfo.
For this, we introduce a CompilerResult object. This object is produced in the compilation phase. Any P4Tools module can add arbitrary information to this class. The results object is then passed to ProgramInfo.
This PR is part 1. It introduces the `CompilerResult` data structure, which records information produces by the compiler which runs before P4Testgen is invoked. This includes the P4 program after the mid end for now.
> [P4Testgen] Extend the CompilerTarget runProgram function with data structures which can pass on more information.

- .clang-tidy
Fix a minor annoyance. We can't change the macros we currently use, which expand to do-while loops.
> Ignore clang-tidy complaints about macro do-while loops.

- frontends/common/constantFolding.h
The DoConstantFolding constructor takes a `TypeMap` parameter (`typeMap`) and stores it in a `const TypeMap` variable. Add the `const` keyword for the parameter. (It does not need to be non-const.)
> DoConstantFolding: make typeMap param const

- .github/workflows/ci-ubuntu-18-nightly.yml
- .github/workflows/ci-ubuntu-20-sanitizer-nightly.yml
- .github/workflows/ci-validation-nightly.yml
- requirements.txt
This PR does two things. 
First, it adds a mechanism to optionally trigger certain CI runs (sanitizers, ubuntu18, validation) by adding the corresponding label to the PR. 
Second, it makes the installation of Python packages for Protobuf subject to the Python version. This way we can install the correct version of a Python package depending on the version being used. This fixes the Ubuntu 18 build issues.
> Trigger CI workflows based on assigned label.

- backends/p4tools/common/lib/format_int.cpp
- backends/p4tools/common/lib/format_int.h
- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/stf.cpp
- backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.cpp
- backends/p4tools/modules/testgen/targets/pna/backend/metadata/metadata.cpp
- backends/p4tools/modules/testgen/targets/pna/backend/ptf/ptf.cpp
- backends/p4tools/modules/testgen/test/lib/format_int.cpp
Also add an options structure to the library
> [P4Testgen] Introduce the option to produce lowercase hex for the formatting library.

- cmake/Linters.cmake
- cmake/P4CUtils.cmake
Provide some helpful hints on how to fix the linter complaints.
> Provide hints on how to fix CI complaints.

- test/gtest/gtestp4c.cpp
The compiler gtest were always hard to use because the compiler options class shadows the actual gtest parameters. The compiler options are never used, so remove them. 
Now we can use flags such as `--gtest_filter=` to select for a particular gtest.
> Remove P4C options from gtest binary.

- ir/type.def
`Type_Any` has a `declid` member but does not have a corresponding equiv function that ignores. All other IR nodes with `declid` have this implementation, it seems it was forgotten here. Fix it.
> Add missing equiv implementation to Type_Any.

- lib/options.cpp
This option was never working because `-` was interpreted as a flag parameter. This little change fixes that. Now it is possible to directly pipe a program to the compiler instead of reading a file. 
Open to suggestions on how to improve this option. The parser options in general are old and quite messy.
> Fix the option to pipe stdin to the compiler.

- backends/tc/ebpfCodeGen.cpp
- testdata/p4tc_samples_outputs/calculator_control_blocks.c
- testdata/p4tc_samples_outputs/checksum_control_blocks.c
- testdata/p4tc_samples_outputs/const_entries_range_mask_control_blocks.c
- testdata/p4tc_samples_outputs/default_action_example_control_blocks.c
- testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c
- testdata/p4tc_samples_outputs/drop_packet_example_control_blocks.c
- testdata/p4tc_samples_outputs/global_action_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/global_action_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/hash1_control_blocks.c
- testdata/p4tc_samples_outputs/ipip_control_blocks.c
- testdata/p4tc_samples_outputs/matchtype_control_blocks.c
- testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
- testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/name_annotation_example_control_blocks.c
- testdata/p4tc_samples_outputs/no_table_example_control_blocks.c
- testdata/p4tc_samples_outputs/noaction_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/noaction_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/nummask_annotation_example_control_blocks.c
- testdata/p4tc_samples_outputs/send_to_port_example_control_blocks.c
- testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c
- testdata/p4tc_samples_outputs/simple_exact_example_control_blocks.c
- testdata/p4tc_samples_outputs/simple_lpm_example_control_blocks.c
- testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c
- testdata/p4tc_samples_outputs/size_param_example_control_blocks.c
- testdata/p4tc_samples_outputs/tc_type_annotation_example_control_blocks.c
- testdata/p4tc_samples_outputs/test_ipv6_example_control_blocks.c
Remove XDP section that is always generated for the TC backend. This XDP code generated for TC was responsible for setting the skb->protocol field which is not writable in TC. We have a found better way to do that with an extern, hence this XDP section isn't needed anymore.
> Remove XDP code generated for TC

- tools/ci-build.sh
We do not need this piece of code anymore now that these packages are part of `requirements.txt`
> Remove redundant protobuf installation in the CI build scripts.

- frontends/p4/frontend.cpp
- frontends/p4/redundantParsers.cpp
- frontends/p4/redundantParsers.h
- testdata/p4_16_samples/redundant_parsers_dangling_unused_parser_decl.p4
- testdata/p4_16_samples_outputs/redundant_parsers_dangling_unused_parser_decl-first.p4
- testdata/p4_16_samples_outputs/redundant_parsers_dangling_unused_parser_decl-frontend.p4
- testdata/p4_16_samples_outputs/redundant_parsers_dangling_unused_parser_decl-midend.p4
- testdata/p4_16_samples_outputs/redundant_parsers_dangling_unused_parser_decl.p4
This fixes the following `Compiler Bug` that occurs when building the attached test:
```
In file: /home/kyle/repos/p4c/frontends/p4/inlining.cpp:522
Compiler Bug: /home/kyle/repos/p4c/frontends/p4/inlining.cpp:522: Null firstCall
```
Please see the test comments for details.
> Remove unused parser declarations and unused parser type declarations that result from `RemoveRedundantParsers` pass.

- frontends/p4/specialize.cpp
- testdata/p4_16_samples/issue4288.p4
- testdata/p4_16_samples_outputs/issue4288-first.p4
- testdata/p4_16_samples_outputs/issue4288-frontend.p4
- testdata/p4_16_samples_outputs/issue4288-midend.p4
- testdata/p4_16_samples_outputs/issue4288.p4
This is not the most principled fix, but hopefully it will work.
A principled fix would require more work.
I can describe the principled solution if anyone is interested to do it.
It basically boils down to improving `TypeChecking::containerInstantiation` to treat arguments like the `assign` function does.
> Allow one more round of type inference after specialization

- backends/p4tools/common/lib/variables.h
- backends/p4tools/modules/testgen/targets/bmv2/bmv2.cpp
- backends/p4tools/modules/testgen/targets/bmv2/bmv2.h
- backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.h
- backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.h
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/p4_asserts_parser_test.cpp
- Add a small builtin map to the refers_to parser. Builtin objects are prefixed by `builtin::`
- Improve the readability and error handling of the refers_to parser. 
- Fix a crash in the `entry_restriction` parser when comparing to a negative constant. 
- Add support for `referenced_by` and `action_restriction`. 
- Add some type aliases.
> [P4Testgen] Hotfixes and improvements to the P4Constraints parsers.

- frontends/common/constantParsing.cpp
- frontends/common/parseInput.h
- frontends/common/parser_options.cpp
- frontends/common/parser_options.h
- frontends/p4/alias.h
- frontends/p4/fromv1.0/programStructure.cpp
- frontends/p4/reassociation.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- lib/error_reporter.h
- lib/options.cpp
- midend/convertErrors.cpp
- midend/removeComplexExpressions.cpp
Fixes for issues found by coverity.
> Fixes from static analysis

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkArch.h
- backends/dpdk/dpdkUtils.cpp
- backends/dpdk/dpdkUtils.h
This is required for https://github.com/p4lang/p4c/pull/4354#issuecomment-1914141950
No changes in test output currently, however once above PR is merged in main, some dpdk tests will be broken. Hence, fixing it before merging @kfcripps  PR #4354 .
> Dpdk backend:Explicitly use method toString() while moving isValid() Methodcall used as table key, to metadata.

- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/p4_asserts_parser_test.cpp
I missed fixing a check in #4387.
std:vector<std::vector>> was flattened into std::vector<>, which is why this check is failing. We have a structure of `[a,b,c]` instead of `[[a,b,c]]` now.
> [P4Testgen] Fix failing P4Testgen gtest.

- backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/common.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.h
Also move  the hex separator utility to the common class.
> [P4Testgen] Fix generation of specific fields in the Protobuf-IR test backend.

- lib/hvec_map.h
- test/gtest/hvec_map.cpp
We cannot use a default one since it would involved copying of std::pair<const KEY, VAL> that had its copy ctor explicitly disabled.
Instead, go the "standard way" for maps via clear() and reinsert().
Fixes #4331
> Implement copy assignment operator for hvec_map

- backends/p4tools/common/options.cpp
- backends/p4tools/common/options.h
- backends/p4tools/common/p4ctool.h
- backends/p4tools/modules/testgen/main.cpp
- backends/p4tools/modules/testgen/testgen.cpp
Add an option to disable printing any information to standard output. This does not disable warnings, errors, or outputs which may be enabled by other options. 
Also add a timer to the top-level and print metrics there for better collection of statics.
> [P4Testgen] Add a silent mode to P4Tools. Add performance counting at the top level.

- frontends/common/resolveReferences/referenceMap.cpp
- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/p4/actionsInlining.cpp
- frontends/p4/actionsInlining.h
- frontends/p4/frontend.cpp
- frontends/p4/functionsInlining.cpp
- frontends/p4/inlining.cpp
- frontends/p4/inlining.h
We found that checking shadowing in `ResolveReferences` was a big bottleneck for one of our apps, and it is done each time an inlining pass is repeated. We turned this off and added a new `ResolveReferences` pass to check shadowing after all inlining is completed. This greatly helped to speed up these passes, which were taking the longest.
Compilation times for one of our apps without these changes:
```
real    22m7.669s
user    21m55.887s
sys     0m14.823s
```
and with them:
```
real    16m36.850s
user    16m24.559s
sys     0m15.304s
```
> Do not check for shadowing repeatedly in inlining passes.

- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/common/resolveReferences/resolveReferences.h
- lib/enumerator.h
Improves performance of the `ResolveReferences` pass by using memoization.
For one of our backend apps, this improved compile-time performance by ~3x.
`time ninja check` on this branch:
```
real    1m14.940s
user    42m25.675s
sys     5m39.234s
```
`time ninja check` on `main` branch:
```
real    1m23.792s
user    49m4.392s
sys     5m39.192s
```
I can also run other benchmarks if requested.
> Memoize & improve name lookup in `ResolveReferences` 

- backends/tc/tc.cpp
- frontends/common/constantFolding.cpp
- frontends/common/constantFolding.h
- frontends/common/options.cpp
- frontends/p4/frontend.cpp
- frontends/p4/frontend.h
- test/gtest/helpers.cpp
- test/gtest/helpers.h
- test/gtest/p4runtime.cpp
This was spurred by #4402, but the scope is a bit more general. I've tried to allow customization (almost) all the customizations of frontend into one class that a backend tool can override to tweak certain behaviours.
On top of the things that were already there, and the customization of constant folding that @grg had in #4402, I've added a hook for deciding if optimizations should run -- that is a use case that I have.
> Introduce a frontend policy as a customization point for frontend

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/type-in-expr-lex0.p4
- testdata/p4_16_errors/type-in-expr-lex1.p4
- testdata/p4_16_errors/type-in-expr.p4
- testdata/p4_16_errors_outputs/type-in-expr-lex0.p4-stderr
- testdata/p4_16_errors_outputs/type-in-expr-lex1.p4-stderr
- testdata/p4_16_errors_outputs/type-in-expr.p4
- testdata/p4_16_errors_outputs/type-in-expr.p4-stderr
Found by fuzzy testing. Fuzzer created an annotation that contained something like `val=4<H>2` where `H` is a type variable. ~Interestingly, I was not able to reproduce this with p4test, I am getting parsing errors there (both when trying to use type name in annotation and in expression in a control).~ It seems like the only place where this can trigger is in an annotation on the thing that is parametrized by the type variable. The annotation is seemingly (and for parser) *before* the variable declaration, but `findDeclaration` finds it, probably since the declaration is semantically inside the object that introduces the variable. This is a very niche case, but still it should not hit a BUG as it did before (`type-in-expr.p4(4): Could not find type of <Type_Var>(201) H/7 H/7`).
> Emit a reasonable error if someone uses type in place where expression is exprected

- ir/irutils.cpp
- ir/irutils.h
- test/gtest/transforms.cpp
Example of use is in the test: https://github.com/p4lang/p4c/pull/4414/files#diff-c05e1bbc752f9a1299cec11e3e39374bcd48de0eb2939bdca8b4fca6c0aa65d8R51.
> Add IR utility that helps with return of multiple statements from Transform

- test/gtest/arch_test.cpp
- test/gtest/bitvec_test.cpp
- test/gtest/call_graph_test.cpp
- test/gtest/complex_bitwise.cpp
- test/gtest/constant_expr_test.cpp
- test/gtest/cstring.cpp
- test/gtest/diagnostics.cpp
- test/gtest/dumpjson.cpp
- test/gtest/enumerator_test.cpp
- test/gtest/equiv_test.cpp
- test/gtest/exception_test.cpp
- test/gtest/expr_uses_test.cpp
- test/gtest/format_test.cpp
- test/gtest/frontend_test.cpp
- test/gtest/gtestp4c.cpp
- test/gtest/hvec_map.cpp
- test/gtest/indexed_vector.cpp
- test/gtest/json_test.cpp
- test/gtest/load_ir_from_json.cpp
- test/gtest/midend_test.cpp
- test/gtest/opeq_test.cpp
- test/gtest/ordered_map.cpp
- test/gtest/ordered_set.cpp
- test/gtest/parser_unroll.cpp
- test/gtest/path_test.cpp
- test/gtest/rtti_test.cpp
- test/gtest/source_file_test.cpp
- test/gtest/stringify.cpp
- test/gtest/transforms.cpp
Convert quotes to angle brackets in `#include "gtest/gtest.h"`. Suggested by @fruffy in #4421.
> gtest include: quotes -> angled brackets

- frontends/p4/frontend.cpp
- frontends/p4/specialize.cpp
- frontends/p4/specialize.h
Pass the ConstantFoldingPolicy instance to the ConstantFolding instance in SpecializeAll. This was missed in #4406.
> frontend policy fix: missed ConstantFolding instance

- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/lib/test_backend.h
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/api_test.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/output_option_test.cpp
Add an option to P4Testgen to only generate tests where the packet is dropped. This PR also shows the benefits of the new API. We can now write targeted gtests to exercise a feature. Very useful! 
I added tests for both `--dropped-packet-only` and `--output-packet-only`.
> [P4Testgen] Add an option to only generate tests with dropped packets. 

- backends/bmv2/common/annotations.h
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/bmv2.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4runtime_translation.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4runtime_translation.h
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/protobuf_ir.h
- frontends/p4/parseAnnotations.h
This PR adds support for `@p4runtime_translation` and `@p4runtime_translation_mappings` in the Protobuf IR back end of P4Testgen.  There are two phases.
1. Since the P4Runtime translation annotations are only attached to the basic type definitions, we add a pass which propagates the annotations to any control plane element which uses the type. We can now reference the annotations when generating tests. 
2. In the Protobuf IR back end, we add two checks for `@p4runtime_translation` and `@p4runtime_translation_mappings`. For @p4runtime_translation, we simply override the behavior of the `getFormatOfNode` function. If a `@p4runtime_translation` annotation is present, we return the value mapped in the annotation. Otherwise we default for normal behavior. 
3. `@p4runtime_translation_mappings` …
> [P4Testgen] Basic support for `@p4runtime_translation` and `@p4runtime_translation_mappings`.

- frontends/p4/frontend.cpp
- frontends/p4/frontend.h
- test/gtest/helpers.cpp
- test/gtest/helpers.h
- test/gtest/p4runtime.cpp
**Breaking change (dev/test)**: Side-effects ordering is enabled in frontend tests (by #4406).
I've accidentally **enabled side-effects ordering in all frontend tests** throughout the code base in https://github.com/p4lang/p4c/pull/4406 😢. I am sorry about this.
Arguably this could be a good thing (that is the indented use of the frotnend), but it could be surprising to downstream projects. Also, as the policy itself was not exposed, it was not possible to change this behaviour in downstream tests. This PR mitigates the second problem, it exposes frontend policy in tests so that tools can set it in any way they desire. **The side-effects ordering is still enabled by default**, which I think is a more reasonable default (it is the default used in frontend after all).
I don't see a way of …
> Pass FrontEndPolicy to unit tests

- lib/cstring.cpp
- lib/cstring.h
- lib/hash.cpp
- lib/hash.h
- midend/parserUnroll.cpp
- test/CMakeLists.txt
- test/gtest/hash.cpp
This PR provides a bit more comprehensive implementation of hashes that could be used within compiler. In particular:
- FNV1A and Murmur2 are removed
- 64-bit xxHash3 was imported with few simplifications from xxhash_clean project and without workarounds for old compilers
- Particular hash algorithm is considered implementation detail, one should not bother about this. Few low-level functions are provided: hash itself, hash avalanche and hash combining
- On top of that some useful hash boilerplate was added. Since C++ standard committee is still bikeshedding the particular better hashing interface implementation (see https://gist.github.com/dietmarkuehl/b0767e76bc85e29e74f61e994f105ad9?permalink_comment_id=3923250 for some summary), we do not have anything that is even currently under …
> Provide better hash functions and boilerplate

- bootstrap.sh
- frontends/common/constantFolding.cpp
Trivial corner case that should not be allowed according to the spec
> Error casting bool const to other than bit<1>

- backends/p4tools/common/p4ctool.h
- backends/p4tools/modules/testgen/testgen.cpp
The seed is a top-level option. Move logging information to the top-level.
> [P4Testgen] Move seed logging to toplevel.

- frontends/p4/typeChecking/typeChecker.cpp
These calls are redundant and cost extra. While this probably has little impact of the compiler speed with the new RTTI, this way of using `to` also makes it easier to see the cast is properly checker.
> Avoid to-after-is double calls to RTTI in the type checker

- backends/tc/ebpfCodeGen.cpp
- testdata/p4tc_samples_outputs/calculator_control_blocks.c
- testdata/p4tc_samples_outputs/checksum_control_blocks.c
- testdata/p4tc_samples_outputs/const_entries_range_mask_control_blocks.c
- testdata/p4tc_samples_outputs/default_action_example_control_blocks.c
- testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c
- testdata/p4tc_samples_outputs/drop_packet_example_control_blocks.c
- testdata/p4tc_samples_outputs/global_action_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/global_action_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/ipip_control_blocks.c
- testdata/p4tc_samples_outputs/matchtype_control_blocks.c
- testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
- testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/name_annotation_example_control_blocks.c
- testdata/p4tc_samples_outputs/noaction_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/noaction_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/nummask_annotation_example_control_blocks.c
- testdata/p4tc_samples_outputs/send_to_port_example_control_blocks.c
- testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c
- testdata/p4tc_samples_outputs/simple_exact_example_control_blocks.c
- testdata/p4tc_samples_outputs/simple_lpm_example_control_blocks.c
- testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c
- testdata/p4tc_samples_outputs/size_param_example_control_blocks.c
- testdata/p4tc_samples_outputs/tc_type_annotation_example_control_blocks.c
- testdata/p4tc_samples_outputs/test_ipv6_example_control_blocks.c
Change minimum key struct alignment to 8 to better fit with the P4TC subsystem.
> Change minimum key struct alignment to 8

- .github/dependabot.yml
No one keeps track of Github actions versioning so try to refresh them automatically using Dependabot. There is little harm in automating this because the bot effectively checks itself using CI when updating a dependency.
> Create a dependabot.yml for Github actions

- ir/visitor.cpp
- ir/visitor.h
This is a first step towards #4418
The particular set of changes includes:
- Refactor `Inspector`'s visiting tracking to be similar to `ChangeTracker` of `Modifier` / `Transform`. Albeit very similar, there are important differences here and there
- Fixed subtle iterator invalidation bug in `Inspector::apply_visitor`. It was not exposed due to way `std::unordered_map` is implemented in libc++ / libstdc++. Long story short: iterator was kept across possible insertion. It will be invalidated in case of rehash
- Ensured no internal guts of visiting process is exposed for the purposes of `visitOnce` / `visitAgain`. Previously we had a pointer to a field inside map's value stored in `Visitor`. So we risked a lot to obtain some dangling pointer to freed memory. It worked due to guarantees we …
> Refactor some visitor internals

- backends/p4tools/common/compiler/reachability.cpp
- backends/p4tools/common/lib/namespace_context.cpp
- backends/p4tools/common/lib/util.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/transformations/saturation_arithm.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/asrt_model.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/expressions.cpp
- backends/p4tools/modules/testgen/test/small-step/util.h
- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/common/resolveReferences/resolveReferences.h
- frontends/p4/createBuiltins.cpp
- ir/ir.cpp
- lib/enumerator.h
- lib/iterator_range.h
- midend/noMatch.cpp
- test/gtest/parser_unroll.cpp
Refactor ReferenceResolver to get rid of majority of unnecessary heap allocations due to obsessive `Enumerator<>` usage:
- Use iterators and iterator ranges where possible
- Ensure we do not allocate on heap temporary objects and exploit move semantics as much as possible returning vectors by value
- Do some refactoring around `Enumerator<>->toVector()`: make it return result by value. It seems that the use in the tree is always about creating some temporaries. And it does not make any sense to allocate vectors on heap then
- Few small improvements here and there, e.g. removing dependence from boost adapters here
Partially addresses https://github.com/p4lang/p4c/issues/4412
Ideally, we'd switch from memory allocation at `getDeclarations` / `getDeclsByName`, but it's a bit long way to go …
> Refactor ReferenceResolver to use native C++-enumerators in some places

- .github/workflows/ci-bazel.yml
- .github/workflows/ci-container-image.yml
- .github/workflows/ci-lint.yaml
- .github/workflows/ci-p4tools.yml
- .github/workflows/ci-ptf.yml
- .github/workflows/ci-static-build-test.yml
- .github/workflows/ci-test.yml
Context: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Fixes #4461.
> Add merge group label to relevant CI runs.

- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/testgen.cpp
- backends/p4tools/modules/testgen/testgen.h
- Make it possible to write tests using the API.
- Also make it possible to read in a program from a file instead of directly passing in the program string.
> [P4Testgen] Add more API options to the P4Testgen api.

- lib/hvec_map.h
- should not replace the value if the key is already present
> Fix hvec_map insert/emplace

- lib/gc.cpp
- Aligned new / delete
- Nothrow variants
Note that the former is required if e.g. LLVM is used with P4C (for backend).
Some cleanups here as well
> Add some more global operator new / delete overrides

- .github/workflows/ci-test.yml
- tools/ci-build.sh
- tools/install_fedora_deps.sh
Runners have 4 cores now: Add ```-j$((`nproc`+1))``` where possible. 
Fixes #4469.
> Try to speed up the CI build process

- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/control_plane/CMakeLists.txt
- backends/p4tools/common/control_plane/symbolic_variables.cpp
- backends/p4tools/common/control_plane/symbolic_variables.h
- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.cpp
- backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/p4_asserts_parser_test.cpp
- backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
This is the first PR in a series of many to build a control-plane semantics for the P4Tools framework. For now, we just introduce a library which includes definitions for common control-plane-influenced symbolic variables. 
I have decided to keep BMv2-specific variables in the top level. The reason is that these variables may be used by multiple P4Tools frameworks. I do not have a good approach to handle common target-specific variables across multiple frameworks yet.
> [P4Testgen] Implement a library for common control-plane symbolic variables.

- ir/CMakeLists.txt
- ir/visitor.cpp
This PR imports modern hash map implementation from https://github.com/greg7mdp/parallel-hashmap Essentially it's a hash map extracted from Abseil plus some additional stuff on top of that. Note that while it is a drop-in replacement of `std::unordered_map` it has different guarantees wrt iterator invalidation as it uses open-addressing scheme.
Advantages of this map is:
- Much faster lookups
- Much less malloc traffic
- Better memory usage
On our downstream codebase just this switch alone yields ~2.1x compile time reduction on some large P4C apps.
The PR contains several commits to measure effects:
- Use of map itself (`gtestp4c-phmap` below)
- Preallocation of 16 slots (we know that in majority of cases this would be enough) (`gtestp4c-phmap-16` below)
- Switch from `std::hash` to …
> Use better maps to store visitor state

- backends/dpdk/CMakeLists.txt
- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/control_plane/CMakeLists.txt
- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- control-plane/CMakeLists.txt
The control plane target depends on Protobuf and Abseil. At least for Protobuf, it should export this dependency such that other downstream targets do not need to include the Protobuf include directories all the time. 
Unclear what to do about Abseil. It is more or less a core compiler dependency and libraries should be linked by each target individually. 
This is tangentially related to https://github.com/p4lang/p4c/issues/4420. Because the control plane pulls in all this stuff, it should be optional.
> Try to clean up the Protobuf includes.

- .github/workflows/ci-test.yml
- requirements.txt
- tools/install_mac_deps.sh
Fixes #4390. Build P4C for MacOS Sonoma (M1) and Ventura. 
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
TODO: Add support for the behavioral model and P4Testgen. I might do that in a separate PR.
> Update MacOS runner to Ventura, add MacOS Sonoma (M1) runner

- BUILD.bazel
There is no build cleaner available open-source as far as I can tell. We have to keep track of this manually.
> Add missing Bazel targets.

- BUILD.bazel
- CMakeLists.txt
- backends/bmv2/CMakeLists.txt
- backends/dpdk/CMakeLists.txt
- backends/graphs/CMakeLists.txt
- backends/p4tools/common/CMakeLists.txt
- frontends/CMakeLists.txt
- frontends/common/resolveReferences/referenceMap.cpp
- frontends/common/resolveReferences/referenceMap.h
- frontends/common/resolveReferences/resolveReferences.h
- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
- frontends/p4/simplifyDefUse.cpp
- frontends/p4/typeMap.cpp
- frontends/p4/typeMap.h
- midend/CMakeLists.txt
This is PR on top of https://github.com/p4lang/p4c/pull/4459 to show how we can improve the things even more with better data structures.
Essentially, this uses more efficient data structures on some hot code paths:
- abseil hash maps / sets in reference resolver and type map
- abseil maps / sets & pre-allocated vector in use-def analisys
- remove some useless allocations and memory traffic in use def
Here are results:
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `gtestp4c-abseil --gtest_filter=P4CParserUnroll.switch_20160512` | 6.056 ± 0.232 | 5.773 | 6.465 | 1.29 ± 0.05 |
| `gtestp4c --gtest_filter=P4CParserUnroll.switch_20160512` | 4.701 ± 0.061 | 4.600 | 4.783 | 1.00 |
`gtestp4c-abseil` is https://github.com/p4lang/p4c/pull/4459 (so yes 78% faster …
> Use abseil maps even more

- lib/gc.cpp
Based on the git history (https://github.com/p4lang/p4c/commit/27ab2c796672383d0d8388ed2e1e9d6d677b9818#diff-3f329039fda7acd3a6dfa342bcf5181e5aeca86642c0c96bb8ccf1086a887028R13), it seems like it belongs somewhere around `#ifdef HAVE_LIBGC`, which has already been moved
> Move out of place comment in gc.cpp

- backends/p4tools/modules/testgen/lib/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
- backends/p4tools/modules/testgen/testgen.cpp
- test/gtest/helpers.cpp
- test/gtest/helpers.h
Generate 1000 P4Testgen tests for the fabric P4 program. This should take around 30 seconds. 
GTest is not really intended for this but it seems to work well enough.
> [P4Testgen] Add a rudimentary P4Testgen benchmark with via GTest.

- test/gtest/p4runtime.cpp
Restore the underscore after DISABLED to tell googletest that the test should be excluded.
I believe the underscore was accidentally deleted in #4381.
> restore underscore after DISABLED in test name

- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/common/core/z3_solver.h
The Z3 translator and some utility functions of the solver are generally useful. Make them public.
Also add some functions, which directly work with z3 expressions. In some cases we want to assert an expression earlier in the solver and rely on incrementality.
> [P4Testgen] Make more functions of the P4Tools Z3 API accessible.

- .github/workflows/ci-lint.yaml
- .github/workflows/ci-p4tools.yml
- .github/workflows/ci-ptf.yml
- .github/workflows/ci-static-build-test.yml
- .github/workflows/ci-test-debian.yml
- .github/workflows/ci-test-fedora.yml
- .github/workflows/ci-test-mac.yml
- .github/workflows/ci-test.yml
- .github/workflows/ci-ubuntu-18-nightly.yml
- .github/workflows/ci-ubuntu-20-sanitizer-nightly.yml
We are bundling too many tests in one job. Factor out the MacOS and Fedora tests into a separate file. They are functionally different enough in workflow.
> Move CI Mac and Fedora tests to separate test runs.

- backends/p4tools/modules/testgen/test/small-step/util.cpp
- control-plane/CMakeLists.txt
- control-plane/p4RuntimeSymbolTable.cpp
- frontends/CMakeLists.txt
- frontends/p4/typeChecking/typeConstraints.cpp
- frontends/p4/typeChecking/typeConstraints.h
- frontends/parsers/parserDriver.cpp
- frontends/parsers/v1/v1lexer.ll
- frontends/parsers/v1/v1lexer_internal.hpp
- ir/namemap.h
- lib/README.md
- lib/cstring.h
- lib/source_file.cpp
- lib/source_file.h
- lib/stringify.cpp
- lib/stringify.h
- lib/stringref.h
- test/gtest/complex_bitwise.cpp
- test/gtest/diagnostics.cpp
- test/gtest/p4runtime.cpp
- test/gtest/path_test.cpp
- tools/ir-generator/ir-generator.ypp
Some refactoring and cleanup while there:
- Code moved from headers down to cpp
- `StringRef` replaced with `std::string_view` (header is not removed as I do not know how this might affect downstream)
> Replace boost string algorithms with their abseil counterparts

- .github/workflows/ci-test-mac.yml
Make sure we can also build P4Testgen on MacOS. This does not run tests. We still need to enable BMv2 support for that.
> Build P4Testgen on MacOS.

- README.md
The link to the bazel build is broken or rather it is not provided, I have added the right link for the same.
> Link Bazel badge in the Bazel README section to the actual CI test

- backends/bmv2/common/parser.cpp
- backends/bmv2/psa_switch/psaSwitch.cpp
- backends/dpdk/spec.cpp
- backends/ebpf/target.h
- backends/p4tools/common/version.cpp
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- backends/p4tools/modules/testgen/main.cpp
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_spec.cpp
- backends/p4tools/modules/testgen/targets/pna/shared_program_info.cpp
- backends/ubpf/target.h
- frontends/common/constantFolding.cpp
- ir/v1.cpp
- ir/visitor.cpp
- lib/algorithm.h
- lib/hashvec.cpp
- lib/json.cpp
- midend/convertEnums.cpp
- requirements.txt
- tools/ir-generator/methods.cpp
It's been a while since we have last updated the formatters. clang-format in particular has implemented a variety of changes.
> Update formatters (clang-format, isort, black)

- docs/README.md
- #4502
Updated tools list in the structure of [Compiler source code organization](https://github.com/p4lang/p4c/tree/main/docs#compiler-source-code-organization)
> [Docs] Added tools to directory structure

- .github/workflows/ci-auto-release.yml
- .github/workflows/ci-bazel.yml
- .github/workflows/ci-container-image.yml
- .github/workflows/ci-lint.yaml
- .github/workflows/ci-p4tools.yml
- .github/workflows/ci-ptf-kernels-weekly.yml
- .github/workflows/ci-ptf.yml
- .github/workflows/ci-release.yml
- .github/workflows/ci-static-build-test.yml
- .github/workflows/ci-test-debian.yml
- .github/workflows/ci-test-fedora.yml
- .github/workflows/ci-test-mac.yml
https://github.com/redhat-developer/yaml-language-server includes an auto-formatter.
>  YAML formatting from Redhead YAML language server.

- BUILD.bazel
- lib/CMakeLists.txt
- lib/bitrange.h
Add additional test to assist compiler folding to perform these replacements when the divisor is a power-of-two compile-time constant:
- divideFloor -> right-shift
- moduloFloor -> bitwise and
This is in response to this [PR comment](https://github.com/p4lang/p4c/pull/4496#discussion_r1515132560) from @ChrisDodd:
> Does this get properly folded to a shift when divisor is a constant power of 2? Similarly, moduloFloor should get folded to an and
The proposed solution adds a test that helps the compiler with optimization for a power-of-two compile-time constant:
```
if (__builtin_constant_p(divisor) && isPowerOfTwo(divisor))
```
`__builtin_constant_p()` and `__builtin_clz` are not supported by all compilers and so are protected by #if guards for gcc/clang.
This [Compiler Explorer …
> help compiler folding for divideFloor/moduloFloor

- frontends/common/parser_options.cpp
- frontends/common/parser_options.h
I noticed an issue with dumping passes that get called more than once, generally in a `PassRepeated` -- the filename generated is the same, so the dumps overwrite and you end up with only the last iteration of the pass.  This change adds a unique index number so you get mulitple files, and as a bonus, the files will be sorted in order in `ls`
> Add 4 digit uid to dump file names

- frontends/parsers/p4/p4parser.ypp
- ir/ir.def
Probably an oversight that this wasn't allowed before.  Use case is to specify which hardware resource(s) should be used to implement a specific function
> Allow annotations on functions

- frontends/parsers/p4/p4parser.ypp
- testdata/p4_16_samples/lvalue-parens.p4
- testdata/p4_16_samples_outputs/lvalue-parens-first.p4
- testdata/p4_16_samples_outputs/lvalue-parens-frontend.p4
- testdata/p4_16_samples_outputs/lvalue-parens-midend.p4
- testdata/p4_16_samples_outputs/lvalue-parens.p4
> Extend parser to allow parentheses in lvalues

- .github/workflows/ci-lint.yaml
- .github/workflows/ci-p4tools.yml
- .github/workflows/ci-ptf.yml
- .github/workflows/ci-static-build-test.yml
- .github/workflows/ci-test-debian.yml
- .github/workflows/ci-test-fedora.yml
- .github/workflows/ci-test-mac.yml
- backends/bmv2/CMakeLists.txt
- bootstrap.sh
- tools/ci-build.sh
- tools/install_fedora_deps.sh
- tools/install_mac_deps.sh
Fixes #4471.
Needs a bit more work. There are lot of different build systems and options scattered around.
> Add ninja as a default build system for some runners.

- backends/dpdk/README.md
- backends/p4tools/README.md
- Needs Help for description of `compiler` and `control_plane`
PS -
Reverted   `Added directory link for examples directory in DPDK backend's Guide` to maintain focus on P4tools and keep the commit history clear.
> [docs] Sync Directory structure of P4tools 

- backends/p4test/midend.cpp
- midend/CMakeLists.txt
- midend/def_use.cpp
- midend/def_use.h
- test/CMakeLists.txt
- test/gtest/midend_def_use.cpp
- test/gtest/midend_pass.cpp
- test/gtest/midend_pass.h
- test/gtest/parser_unroll.cpp
Contributing a midend def-use analysis pass.
The pass is an inspector named ComputeDefUse. The pass populates a private attribute named `defuse`. This defuse information is queried via one of two functions: `getDefs` and `getUses`. Both functions take a `const IR::Node*` parameter and return the defs or uses for that node.
There is also a ostream operator that takes a ComputeDefUse object and prints the defuse information in human-readable form. For example:
```
defs:
h.h1.f1<146088>(control:4:17): { <93152>(control:0:47) }
inout ParsedHeaders h<93152>(control:0:47): { <93152>(control:0:47), <146097>(control:5:17), <146080>(control:2:13) }
inout Metadata m<93156>(control:0:65): { <93156>(control:0:65) }
uses:
inout ParsedHeaders h<93152>(control:0:47): { <146088>(control:4:17), …
```
> Midend def-use pass

- backends/p4tools/cmake/common.cmake
- backends/p4tools/common/CMakeLists.txt
- backends/p4tools/common/control_plane/CMakeLists.txt
- backends/p4tools/modules/testgen/CMakeLists.txt
- backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
- control-plane/CMakeLists.txt
- frontends/CMakeLists.txt
- midend/CMakeLists.txt
Make sure we only export what is necessary and link most libraries privately. Also remove the `add_p4tools_library` function, it is too inflexible and `add_library` works just fine.
> Clean up P4Tools and control-plane linking.

- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
@pkotikal This should help with the problems you have encountered in https://github.com/p4lang/p4c/commit/689e013d3d870fa906852d93acd76cfc5bbe5634#r135134661
Since we are recording an expression, fix also the way we print expressions. I should implement a more disciplined way to format these inputs without introducing linebreaks.
> [P4Testgen] Fix append and prepend invocation.

- bazel/bison.bzl
This is a no-op for Bazel, which enables `--incompatible_merge_genfiles_directory` by default.
> Remove obsolete `output_to_genfiles = True`.

- backends/dpdk/README.md
- backends/tc/README.md
- backends/ubpf/README.md
- Added directory link for examples directory in DPDK backend's Guide.
- Added Directory link for "testdata/p4tc_samples" in Guide of "tc" Backend.
- Added directory link for "examples" directory in "ubpf" backend's Guide.
> [documentation] Add hyperlinks to the actual directory in the README file.

- BUILD.bazel
- backends/p4tools/modules/testgen/test/small-step/util.cpp
- bazel/abseil.patch
- bazel/p4c_deps.bzl
- control-plane/p4RuntimeSymbolTable.cpp
- frontends/common/resolveReferences/referenceMap.h
- frontends/common/resolveReferences/resolveReferences.h
- frontends/p4/def_use.h
- frontends/p4/simplifyDefUse.cpp
- frontends/p4/typeChecking/typeConstraints.cpp
- frontends/p4/typeMap.h
- ir/visitor.cpp
- test/gtest/complex_bitwise.cpp
- test/gtest/diagnostics.cpp
- test/gtest/p4runtime.cpp
Partially addresses #4523. Try to patch Abseil.
> Use Abseil system includes

- backends/bmv2/psa_switch/psaSwitch.cpp
- backends/bmv2/simple_switch/simpleSwitch.cpp
- backends/dpdk/backend.cpp
- frontends/p4/actionsInlining.h
- frontends/p4/frontend.cpp
- frontends/p4/frontend.h
- frontends/p4/functionsInlining.h
- frontends/p4/inlining.h
- frontends/p4/localizeActions.h
- frontends/p4/redundantParsers.h
- frontends/p4/specialize.cpp
- frontends/p4/specialize.h
- frontends/p4/unusedDeclarations.cpp
- frontends/p4/unusedDeclarations.h
- midend/flattenUnions.h
This allows the target to define an override of RemoveUnusedDeclarations that changes the what gets removed and what doesn't, by defining a simple subclass of `P4::RemoveUnusedDeclarations` that only overrides one or two methods and is otherwise the same.
- allow removing unused externs when that is apropriate for the target
- allow not removing unused functions when that is appropriate
I tried just defining a hook function that is called for each IDeclaration, but using that ends up doing a whole series or dynamic_casts, which seems ugly and duplicates what Visitor is already doing for the preorder/postorder methods, so this ends up being more efficient and clearer.
> Add policy controlling RemoveUnusedDeclarations

- ir/id.h
- midend/def_use.h
- also add missing `override` (fix warning)
> Allow constructing an IR::ID from a std::string

- lib/nethash.cpp
- lib/nethash.h
- test/gtest/nethash.cpp
I am not sure what was the motivation for choice of the exact CRC variants for BMv2, but some targets use different variants, this PR adds some. These particular variants are similar to those in BMv2, but they lack bit reflection.
I am not super happy about the naming, but I did not find any good catalog of variants.
> Add 2 more CRC checksum variants to lib/nethash

- backends/p4tools/common/compiler/reachability.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/p4/parameterSubstitution.h
- ir/dbprint-p4.cpp
- ir/indexed_vector.h
- ir/ir.cpp
- ir/namemap.h
- ir/vector.h
- lib/enumerator.h
- lib/iterator_range.h
- lib/map.h
- midend/flattenInterfaceStructs.h
- test/gtest/enumerator_test.cpp
- tools/ir-generator/irclass.cpp
- tools/ir-generator/methods.cpp
- Simplify interface
- Introduce special-case for `ICastable` for `AsEnumerator`
- Remove non-sense `std::function` type-erasure for `FilterEnumerator`, make it less memory hog
- Make `ConcatEnumerator` sane, do not do tons of memory allocations each time `ConcatEnumerator` is created
- Some convenient helpers (`enumerate` / `concat`)
- Make `EnumeratorHandle` behave as `ForwardIterator`, so STL `insert`, etc. are working with `Enumerator`
- Make sure `Values` and other things from `lib/map.h` could be used with `Enumerator`, improve here const-correctness & remove deprecated `std::iterator` usage in favor of iterator traits
- Normalize doxygen comments and reorganize code inside `lib/enumerator.h`, make it `cstring`-less
> Refactor Util::Enumerator

- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeConstraints.cpp
- frontends/p4/typeChecking/typeConstraints.h
- testdata/p4_16_errors/serEnumImplCast.p4
- testdata/p4_16_errors_outputs/serEnumImplCast.p4
- testdata/p4_16_errors_outputs/serEnumImplCast.p4-stderr
- testdata/p4_16_samples/serEnumImplCast.p4
- testdata/p4_16_samples_outputs/serEnumImplCast-first.p4
- testdata/p4_16_samples_outputs/serEnumImplCast-frontend.p4
- testdata/p4_16_samples_outputs/serEnumImplCast-midend.p4
- testdata/p4_16_samples_outputs/serEnumImplCast.p4
- Allow implicit casts between serializable enums and their underlying type in action calls
> Implict cast fix

- backends/p4tools/modules/testgen/targets/bmv2/bmv2.cpp
- backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.cpp
- backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.h
- backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
- lib/bitrange.h
- Use cstring instead of the declaration pointer in the direct extern map.
- Check for all implementations.
- Create an explicit static array of implementations.
> [P4Testgen] Clean up the direct extern map implementation for BMv2.

- README.md
The Main build image has been removed for improved readability
> Fix broken Debian CI test badge in the README. Add Fedora and MacOS CI badge. 

- docs/doxygen/01_overview.md
Resource links within the "Additional Documentation" section are not correctly pointing to their intended locations.
Updated the resource links
> Fix Resource links in Doxygen documentation.

- bazel/p4c_deps.bzl
Wild story: https://www.openwall.com/lists/oss-security/2024/03/29/4
rules_boost issue: https://github.com/nelhage/rules_boost/issues/555
> Update rules_boost which pulled in the compromised xz dependency.

- docs/README.md
- #4563
Based on discussion 
- https://github.com/p4lang/p4c/pull/4568#discussion_r1542970252
Should wo include this section somewhere around the [Coding Conventions section](https://github.com/p4lang/p4c/tree/main/docs#coding-conventions)
> [docs] Add Comment Style Guide

- backends/bmv2/common/JsonObjects.cpp
- backends/bmv2/common/JsonObjects.h
1. Class Overview:
- Provides an overview of the JsonObjects class, explaining its purpose and namespace.
2. Constructor:
- Documented the constructor `JsonObjects::JsonObjects()` with a brief description of its purpose and initialization of member variables.
3. Member Functions:
- Each member function of the JsonObjects class is documented with detailed descriptions.
- Special attention is given to functions with complex logic or multiple parameters to ensure detailed documentation.
Overall, this commit enhances the understanding of the BMV2 JSON Objects class by providing a Doxygen-style documentation.
> doc: backends: Add Doxygen-style documentation for BMV2 JSONObjects

- backends/bmv2/run-bmv2-ptf-test.py
It can happen that test A deletes `ptf.log` and then test B tries to delete the log a second later. This will cause the following error: 
```
WARNING: Traceback (most recent call last):
WARNING:   File "/usr/local/bin/ptf", line 684, in <module>
WARNING:     logging_setup(config)
WARNING:   File "/usr/local/bin/ptf", line 449, in logging_setup
WARNING:     os.remove(config["log_file"])
WARNING: FileNotFoundError: [Errno 2] No such file or directory: 'ptf.log'
```
To avoid that from happening we make sure the log is saved in the unique temporary directory instead. We already did this for the actual PTF test, but not for the initial PTF check. 
Ideally, we would fix this error from occurring at all in PTF.
> Fix spurious failure when two tests try to remove `ptf.log` at the same time.

- lib/map.h
- test/CMakeLists.txt
- test/gtest/map.cpp
Restore parentheses that were accidentally dropped from begin call as part of recent code improvements (#4513).
> restore missing parentheses

- frontends/p4/fromv1.0/programStructure.cpp
- test/gtest/bitrange.cpp
Context: https://github.com/google/googletest/issues/2271#issuecomment-665742471
> Fix a warning emerging from a testsuite in GTest on newer versions of Clang. 

- ir/visitor.cpp
- test/CMakeLists.txt
- test/gtest/visitor.cpp
Set the done flag to false when revisiting a node in Tracker::try_start. Fixes a small regression introduced in #4447.
Without this fix, a Tofino pass errors out with an assertion failure from the Visitor infrastructure: `Assertion `current.depth < 10000' failed.` Without resetting the done flag in the tracker, the Inspector::apply_visitor method will always follow the "New or Revisit" path instead of the "Busy" path after a node has been visited once.
The associated test program mimics the Tofino pass that shows the problem.
> Inspector: clear the done flag when revisiting node

- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/common/lib/gen_eq.cpp
- backends/p4tools/modules/testgen/core/program_info.cpp
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
- backends/p4tools/modules/testgen/targets/ebpf/constants.cpp
- backends/p4tools/modules/testgen/targets/pna/constants.cpp
- backends/p4tools/modules/testgen/test/z3-solver/constraints.cpp
- test/gtest/visitor.cpp
- Remove ir-generated includes.
- Use `IR::getBoolLiteral` where possible.
- Reduce the amount of unnecessary `IR::Boolliteral(true)` use.
> Miscellaneous cleanups for P4Testgen.

- cmake/Linters.cmake
Some downstream repositories do not seem to pick up the right black configuration. This can happen with out-of-tree builds. Unclear why for me. 
Forcing the configuration path fixes this problem.
> Force black to use the pytoml file as configuration.

- CONTRIBUTING.md
- README.md
- backends/graphs/README.md
- backends/p4tools/modules/testgen/targets/bmv2/test/README.md
- bazel/example/README.md
- docs/CodingStandardPhilosophy.md
- docs/Eclipse-readme.md
- docs/README.md
-  #4585
Refactor : Current Compiler Acronym i.e. `p4c` to `P4C`  in Documentation
> This PR only focuses on the Documentation text.
> Without modifying any link, command, directory name and "p4c" Repository name .
> [Docs] Non-Breaking change of "p4c" to "P4C"

- .github/workflows/ci-test-debian.yml
- lib/gc.cpp
Some systems (e.g. those with GNU libc) declare posix_memalign with an exception specifier. Compilers (clang including) might have special handling of this to allow posix_memalign redeclaration with / without exception specifier. As we override posix_memalign for GC purposes we really need to ensure the proper include order to workaround this weirdness.
> Ensure we take compiler-provided declaration of posix_memalign

- frontends/common/parser_options.cpp
- ir/pass_manager.cpp
- ir/pass_manager.h
**breaking change**: Debug hooks in `PassManager` can now be called with the IR::Node being `nullptr`. This indicates that the last executed pass failed and did not return any value.
This allows running a debug hook also after a failing pass too. This can be useful e.g. to check diagnostic counts for the pass in the debug hook.
> Call PassManager's debug hook even after a failing pass

- .github/workflows/ci-ubuntu-18-nightly.yml
- README.md
- backends/bmv2/common/helpers.h
- backends/ebpf/runtime/contrib/uthash.h
- control-plane/p4RuntimeArchStandard.h
- docs/README.md
- ir/vector.h
- ir/visitor.cpp
- lib/log.cpp
- lib/rtti.h
- test/gtest/bitrange.cpp
- test/gtest/bitvec_test.cpp
- testdata/p4_16_samples/op_bin.p4
- tools/cpplint.py
`GCC` acronym Capitalized to keep documentation consistent. 
Based on this review on PR 
- https://github.com/p4lang/p4c/pull/4624#discussion_r1570860358
> [Docs]  capitalize "GCC" acronym in docs and comment

- frontends/p4/frontend.cpp
- frontends/p4/frontend.h
- frontends/p4/strengthReduction.cpp
- frontends/p4/strengthReduction.h
- test/CMakeLists.txt
- test/gtest/strength_reduction.cpp
Add mechanism to allow the the transform that changes `a - const` -> `a + (-const)` to be disabled.
This change adds a new function to the FrontEndPolicy object to control this optimization. We may eventually want to change to some other mechanism (e.g., breaking out some of the optimizations that aren't universally useful), but for now this provides the ability to turn the optimization off.
> allow disabling of subtraction transform

- backends/p4test/p4test.cpp
- ir/CMakeLists.txt
- ir/pass_utils.cpp
- ir/pass_utils.h
This is the reason behind #4626. A pass manager hook that is useful for testing (p4test-like) the compiler output or just for the developers to see what passes emit diagnostic messages.
Example output (with the hook in driver added and running with `-TdiagnosticCountInPass:1`):
```
main.p4(65): [--Wwarn=parser-transition] warning: sub_parser: implicit transition to `reject'
state sub_parser{
^^^^^^^^^^
PASS FrontEnd ~> CreateBuiltins emitted 1 warning
[--Wwarn=parser-transition] warning: SelectCase: unreachable case
PASS MidEnd ~> PassRepeated emitted 1 warning
```
> Contribute DiagnosticCountInPassHook

- BUILD.bazel
- CMakeLists.txt
- cmake/config.h.cmake
- lib/gc.cpp
> Introduce guard for aarch64 GCC compilation.

- .github/workflows/ci-static-build-test.yml
- CMakeLists.txt
- lib/gc.cpp
It looks like the other function never finds `mm_malloc.h`
> Use check_include_file_cxx instead of check_include_file to find mm_malloc.h

- frontends/p4/typeChecking/typeChecker.cpp
- testdata/p4_16_errors/shift-int-non-const.p4
- testdata/p4_16_errors_outputs/issue2206.p4-stderr
- testdata/p4_16_errors_outputs/shift-int-non-const.p4
- testdata/p4_16_errors_outputs/shift-int-non-const.p4-stderr
- testdata/p4_16_samples/shift-int-const.p4
- testdata/p4_16_samples_outputs/shift-int-const-first.p4
- testdata/p4_16_samples_outputs/shift-int-const-frontend.p4
- testdata/p4_16_samples_outputs/shift-int-const-midend.p4
- testdata/p4_16_samples_outputs/shift-int-const.p4
Fixes #4652. Note that besides changing the error I've also allowed the case when the right operand is `bit<N>`/`int<N>` but it is also constant. This case should be allowed and it does actually work in most cases in practice, it is just covered by constant folding.
---
BTW: I did not realize until now that the type checker actually *does constant folding* too! This will make any "small frontend" quite hard to do if it was to not do constant folding.
> Improve error message when shifting int by non-const

- BUILD.bazel
- backends/p4tools/common/lib/symbolic_env.cpp
- ir/expression.cpp
- lib/alloc_trace.cpp
- lib/alloc_trace.h
- lib/big_int.h
- lib/big_int_util.h
- lib/hash.h
A couple fixes after #4623 has been merged.
- Move the boost definition of `boost::multiprecision::cpp_int` into its own header file.
- Fix missing of typing for BoolLiterals with SourceInfo.
- Move `big_int` hashing to `big_int_utils`.
> Fixes to lib/hash and lib/big_int_util.

- CMakeLists.txt
- backends/p4tools/cmake/common.cmake
- backends/p4tools/common/control_plane/CMakeLists.txt
- cmake/BDWGC.cmake
- cmake/bdwgc.patch
- frontends/CMakeLists.txt
- ir/CMakeLists.txt
- ir/visitor.cpp
- lib/CMakeLists.txt
- lib/bitvec.h
- lib/gc.cpp
- lib/indent.cpp
- lib/log.cpp
- tools/ci-build.sh
- tools/install_fedora_deps.sh
- tools/install_mac_deps.sh
To have more control over linking and setup of the Boehm-Demers-Weiser garbage collector P4C uses we add it as a FetchContent dependency. For compatibility users can still choose to link with an external dependency. Several other changes were necessary to make this work: 
- We build and link the static libraries of the garbage collection library. This way we do not run into missing library problems. To be able to do so we had to disable some definitions in `gc_cpp.cpp`.
- We enable threads and fork support by default to ensure parallelism support.
- We do not link bdwgc's include directories globally. Instead we use the Abseil approach and mandate that every target links to library that pulls in the BDWGC headers.
- Clean up the top-level CMakelists a little and move all the module …
> Link against the Boehm-Demers-Weiser Garbage Collector using FetchContent.

- lib/big_int_util.h
A workaround until #4663 is ready. Fixes #4659.
> Explicitly include hash.hpp for Ubuntu 18.04.

- frontends/p4/uniqueNames.cpp
- frontends/p4/uniqueNames.h
This is a slight generalization and refactor of `P4::RenameMap`. The existing interface stays the same, but there are two more ways to use it:
- `setNewName` can now accept an optional `bool` argument. If set to `true`, the bug check for the case an an existing renaming is going to be replaced is disabled.
- `get` member function that returns `std::optional<cstring>` was added. If the name has no mapping, this will return `std::nullopt`, while in `getName` there was a failure. This allows the user of the map to skip double searching the map.
> Generalization & minor refactoring in RenameMap

- lib/cstring.cpp
- lib/cstring.h
The `cstring` type is used a lot in the codebase as it is the type of names in the IR. It is, however not a good idea to perform operations on `cstring` unless the result of the operations is intended to be persistent. In these cases, the operations should be rather performed on `std::string` or `std::string_view` (based on what kind of operations is desired). Note that creating a `std::string_view` from a `cstring` is currently always safe as `cstring` is persistent.
This PR adds explicit operators for conversion to both string and string_view as well as functions which serve the same purpose. I've opted to add these too as I find it syntactically more pleasing to do something like `dec->name.name.string()` than `std::string(dec->name.name)`.
> Add string_view and string conversion operators and functions to cstring

- frontends/p4/uniqueNames.cpp
- frontends/p4/uniqueNames.h
Until this change, passes inheriting from `P4::RenameSymbols` pass could not make use of it because of important `private` members. These are now `protected` and more protected functions were added to avoid code duplication.
> Facilitate inheritance from RenameSymbols pass, deduplicate code

- ir/expression.def
I ran into issues where I created a `IR::Land(new IR::BoolLiteral(new IR::Type_Boolean(), false), new IR::BoolLiteral(new IR::Type_Boolean(), false))` and the resulting type of the `IR::LAnd` was `IR::Type_Unknown`. This happens because https://github.com/p4lang/p4c/blob/main/ir/expression.def#L39 is comparing pointers, not the actual type. 
Correct me if I am wrong but I believe the default type for Logical AND and OR should be `Type_Boolean`. Do this only when the type is unknown.
> Set type for LAnd, LOr, LNot to be Type_Boolean if unknown.

- backends/bmv2/common/lower.cpp
- backends/dpdk/dpdkArch.h
- backends/ebpf/ebpfType.cpp
- backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
- backends/p4tools/modules/testgen/targets/pna/constants.cpp
- backends/p4tools/p4tools.def
- control-plane/addMissingIds.cpp
- frontends/common/constantFolding.cpp
- frontends/p4/defaultArguments.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- frontends/parsers/p4/p4parser.ypp
- frontends/parsers/v1/v1parser.ypp
- ir/base.def
- ir/expression.def
- ir/irutils.cpp
- ir/type.cpp
- ir/type.def
- midend/convertEnums.h
- midend/parserUnroll.cpp
- midend/parserUnroll.h
- midend/replaceSelectRange.cpp
- midend/singleArgumentSelect.cpp
- test/gtest/p4runtime.cpp
- testdata/p4_16_errors_outputs/issue3285.p4-stderr
Addresses some of the points raised in #4612. Note that #4612 is still required. Type pointers can still not be unique because of the source information associated with the type and the `clone` call.
> Make the new operator protected for some IR types.

- ir/id.h
- ir/namemap.h
- lib/cstring.h
TLDR: workaround for problems compiling p4c with gcc 11.4 (and probably others) with `-std=c++2x`
A late draft of the C++2x spec introduced a non-backwards compatible change in the way overloading for operator ==/!= is handled; this was considered a defect and was fixed in the final C++20 spec.  However, the default version of gcc on Ubuntu 22.04 (gcc 11.4) happens to implement that spec draft, so gives errors with our code.
More recent versions of gcc (and older versions too!) don't have this problem.  So this change isn't really necessary, but is pretty small and may help others who run into this specific problem.
> Workaround for gcc-11.4/draft 2x spec flaw

- tools/ir-generator/irclass.cpp
- tools/ir-generator/irclass.h
- explicit instantiations for all Vector and IndexedVector used in any .def file
> irgen: Generate explicit instantiations

- .github/release.yml
- .github/workflows/ci-auto-release.yml
- .github/workflows/ci-release.yml
This follows the guide listed here: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
I am not sure whether this will work. Fixes #4690.
@AdarshRawat1 We are also trying to improve our release logs. Do you have any ideas or suggestions how to have better information or templates here? We usually release on a monthly cadence. 
@rst0git Do you know whether this will work with the automated release we use?
> Add a release template to the compiler.

- BUILD.bazel
- backends/p4tools/common/core/z3_solver.cpp
- backends/p4tools/modules/testgen/lib/exceptions.h
- frontends/p4/typeChecking/typeChecker.h
- ir/expression.def
- ir/visitor.h
- lib/backtrace_exception.h
- lib/big_int_fwd.h
- lib/bug_helper.h
- lib/error.h
- lib/error_helper.h
- lib/error_message.h
- lib/error_reporter.h
- lib/log.h
- lib/options.h
- lib/source_file.cpp
- lib/source_file.h
- lib/stringify.cpp
- lib/stringify.h
- midend/def_use.cpp
- test/gtest/source_file_test.cpp
- tools/ir-generator/ir-generator.ypp
- tools/ir-generator/irclass.cpp
This is a next step around messages emission refactoring. Essentially:
- Use C++17 features to reduce code duplication and modernize code, use universal references instead of passing by value
- Get rid of varargs for parser errors, use variadic templates instead
- Simplify code here and there getting rid of cstrings
- Unify object => string conversion
Things are a bit messy for the latter. We are having: `toString`, `dbprint` (that are different) and sometimes explicit `operator<<`. Plus, we define `operator<<` in a global namespace (in `log.g`, and some IR classes depend on this!) and call `dbprint` from there. However, for error messages, etc. we do not want to use `operator<<` (that is default implementation for `boost::format` for user-defined types) and use explicit `toString`.
So, …
> Refactor error_helper and around

- lib/bitvec.h
- lib/hvec_map.h
Two more small fixes for C++20 support. Add the equality comparison operators to `copy_bitref` and make the equality operator const for `hvec_map`.
> More compilation fixes for C++20: hvec_map and copy_bitref 

- backends/p4fmt/p4fmt.cpp
> Invalid include fix in `p4fmt.cpp`

- .github/workflows/ci-test-debian.yml
- tools/ci-build.sh
In #4715, some building issues with `ENABLE_GTESTS=OFF` have been identified. Adding this variation in CI can help catch such issues early on in the future.
> Test building P4C with `ENABLE_GTESTS=OFF` in CI

- BUILD.bazel
Let's see whether this helps with the spurious failures. The sed command had two `$OUTS`, which could have led to the nondeterminism. 
Edit: I reran tests about 5 times and experienced no failures. Let's hope this one is the final fix.
> Fix up the Bazel sed command.

- frontends/p4/frontend.cpp
- testdata/p4_16_samples/issue4548.p4
- testdata/p4_16_samples_outputs/gauntlet_hdr_in_value-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/issue1638-frontend.p4
- testdata/p4_16_samples_outputs/issue1638-midend.p4
- testdata/p4_16_samples_outputs/issue1937-2-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/issue1937-3-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/issue1937-frontend.p4
- testdata/p4_16_samples_outputs/issue2303-frontend.p4
- testdata/p4_16_samples_outputs/issue2648-frontend.p4
- testdata/p4_16_samples_outputs/issue4500-frontend.p4
- testdata/p4_16_samples_outputs/issue4548-first.p4
- testdata/p4_16_samples_outputs/issue4548-frontend.p4
- testdata/p4_16_samples_outputs/issue4548-midend.p4
- testdata/p4_16_samples_outputs/issue4548.p4
- testdata/p4_16_samples_outputs/named-arg1-frontend.p4
> Add a constant folding pass after inlining

- frontends/p4/coreLibrary.h
- lib/error_catalog.cpp
- lib/error_catalog.h
- midend/interpreter.cpp
- testdata/p4_16_samples/parser-unroll-issue4006_twice_extracted_header.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header-first.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4-stderr
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4.entries.txtpb
- testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4.p4info.txtpb
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header-first.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header.p4
- testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header.p4-stderr
In #4006, there are suggestions to just improve the warning instead of removing it. This PR just removes it, as I believe that having no warning is better than having a bad warning, and I don't want to spend time finding a better place for it (but if you have a suggestion that is relatively easy I will happily try it out). I don't think it belongs in `ParsersUnroll`, because if this is going to be a warning at all, then it should also be a warning when parsers are not unrolled. We can leave #4006 open to add a better warning elsewhere if that is desired.
> [#4006] Remove confusing warning when the same header is extracted multiple times in a parse path

- README.md
P4 have migrated from [Slack](https://p4-lang.slack.com/) to [Zulip](https://p4lang.zulipchat.com/) . 
[P4 Organization Migration Announcement ](https://p4.org/p4-org-is-moving-to-zulip-for-messaging/)
> Docs : Update community link from Slack to Zulip

- backends/dpdk/dpdkArch.cpp
- backends/dpdk/dpdkContext.cpp
- backends/dpdk/dpdkContext.h
- backends/ebpf/ebpfParser.cpp
- backends/ebpf/psa/ebpfPsaDeparser.cpp
- backends/ebpf/psa/ebpfPsaGen.cpp
- backends/ebpf/psa/ebpfPsaTable.cpp
- backends/ebpf/psa/externs/ebpfPsaMeter.cpp
- backends/tc/ebpfCodeGen.cpp
- lib/cstring.cpp
- lib/cstring.h
- test/gtest/cstring.cpp
- tools/ir-generator/irclass.cpp
- Switch to `std::string_view` for some cstring API
> cstring-related cleanup, switch to std::string_view for some cstring API

- docs/doxygen/doxygen.cfg
Error in rendering images, in documentation due to the relative path of images stored in resources directory. - [View](https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2backends_2graphs_2_r_e_a_d_m_e.html#autotoc_md110) 
Added resource path to Doxygen config.
> Minor Fix: Graphs Backend Example Images

- backends/bmv2/run-bmv2-ptf-test.py
Originally part of #4667 but that PR is stuck.
> Fix spurious P4Testgen failure occuring because of a problem when running PTF tests in parallel. 

- docs/doxygen/doxygen.cfg
Fixing the issue of diagrams not being rendered in Doxygen output by adding them to the path throughout the documentation.
> Docs: Fixing diagram paths in generated docs

- backends/p4tools/modules/smith/README.md
- backends/p4tools/modules/testgen/README.md
This makes the auto-generated doxygen index easier to distinguish this files from others, instead of merely being called "README" there.
> Add back in heading for P4Smith README file

- docs/doxygen/doxygen.cfg
Reordered the sequence of topics in generated documentation. _View mockup for Changes [live here](https://6679d5c80692ef2a416f96fb--bespoke-douhua-c67c10.netlify.app/)_ 
- https://github.com/p4lang/p4c/blob/main/backends/p4tools/cmake/README.md
- https://github.com/p4lang/p4c/blob/main/backends/p4tools/common/lib/README.md
- https://github.com/p4lang/p4c/blob/main/backends/p4tools/common/README.md
- https://github.com/p4lang/p4c/blob/main/backends/p4tools/modules/testgen/lib/README.md
Updated sequence of files listed by Doxygen output based on discussion in
- #4746  
| List |
|--------|
| [P4C](https://p4lang.github.io/p4c/index.html)
[Repository](https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2docs_2_r_e_a_d_m_e.html)
[Revision …
> Docs: Initial sequence of pages in Documentation

- .github/workflows/ci-test-fedora.yml
- .github/workflows/ci-test-mac.yml
- tools/ci-build.sh
- tools/debian-build/packaging.conf
The casing for build types is CamelCase: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html#variable:CMAKE_BUILD_TYPE
> Fix naming of CMake Release configuration.

- .github/dependabot.yml
Dependabot was adding new labels. Stop that.
> Simplify dependabot label generation.

- .github/dco.yml
- CONTRIBUTING.md
Now that we are part of the Linux foundation we will switch away from the ONF CLA to [DCO](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) for Github pull requests and contributions. DCO is the main mode of license management for LF projects. The nice part is that, compared to the ONF CLA, it does not require manager approval for company contributions. This should greatly simplify the contribution process.
We will selectively enable DCO on some repositories to test it. Nothing much should change for contributors. The only thing that is necessary is to sign your commits on PRs with Signed-off-by: <Name> <email>.
https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md
Provides good tips on how to manage contributing to a DCO repository. Commit hooks are the …
> Add DCO description to the contribution guidelines.

- .github/workflows/ci-auto-release.yml
Reusing the current signature of the bot, but maybe there is a better one. @rst0git
> Add a signature for the release bot for DCO support. 

- backends/p4tools/common/lib/logging.cpp
- backends/p4tools/common/lib/logging.h
- backends/p4tools/common/lib/util.h
- backends/p4tools/modules/testgen/lib/test_backend.cpp
- Move the log helpers from `utils.h` to `logging.h`
- Use `printInfo` instead of `printFeature` where possible.
- Qualify the logging labels with a "tools_" prefix.
> P4Testgen logging cleanups.

- BUILD.bazel
- lib/cstring.cpp
- lib/cstring.h
- test/gtest/cstring.cpp
- Add cache introspection methods (`is_cached` / `get_cached`) without implicitly constructing cstrings
- Refactor caching to use only single map lookup regardless whether we'd need to insert something into cache or the value is already there
- Switch to better underlying map
This is a spin-off from https://github.com/p4lang/p4c/pull/4774
> Improve cstring cache internals

- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
- frontends/p4/simplifyDefUse.cpp
- midend/def_use.cpp
- midend/def_use.h
- midend/unrollLoops.cpp
- midend/unrollLoops.h
- testdata/p4_16_samples/issue4739.p4
- testdata/p4_16_samples_outputs/issue4739-first.p4
- testdata/p4_16_samples_outputs/issue4739-frontend.p4
- testdata/p4_16_samples_outputs/issue4739-midend.p4
- testdata/p4_16_samples_outputs/issue4739.p4
- testdata/p4_16_samples_outputs/issue4739.p4.entries.txtpb
- testdata/p4_16_samples_outputs/issue4739.p4.p4info.txtpb
- fix FindUninitialized in simplifyDefUse.cpp to correctly get live state for for loop bodies, so as to not dead-code eliminate things unused after the loop exit
- fix midend/def_use.cpp ComputeDefUse to visit assignments right then left to get correct info for assignments that read the old value of the lhs
- fix loopUnrolling.cpp UnrollLoops to not unroll loops where the index is modified in the loop body in addition to the loop increment.
- more logging in ComputeDefUse to see help debugging
> Fix loop unrolling bugs related to issue4739

- BUILD.bazel
- CMakeLists.txt
- backends/bmv2/CMakeLists.txt
- backends/bmv2/common/backend.h
- backends/bmv2/common/expression.h
- backends/bmv2/common/extern.h
- backends/bmv2/common/header.h
- backends/bmv2/common/helpers.h
- backends/bmv2/psa_switch/psaSwitch.cpp
- backends/bmv2/psa_switch/psaSwitch.h
- backends/bmv2/simple_switch/simpleSwitch.cpp
- backends/bmv2/simple_switch/simpleSwitch.h
- backends/common/CMakeLists.txt
- backends/common/metermap.cpp
- backends/common/metermap.h
- backends/common/programStructure.cpp
- backends/common/programStructure.h
- backends/common/psaProgramStructure.cpp
- backends/common/psaProgramStructure.h
- backends/ebpf/CMakeLists.txt
- backends/ebpf/ebpfBackend.cpp
- backends/ebpf/psa/backend.cpp
- backends/ebpf/psa/ebpfPsaGen.h
- backends/tc/CMakeLists.txt
- backends/tc/backend.cpp
- backends/tc/pnaProgramStructure.cpp
- backends/tc/pnaProgramStructure.h
The ProgramStructure class in the BMv2 back end was used all across other back ends. The abstraction here was a bit leaky. I pulled it out and moved it in the "common" folder in `backends`. Refactoring suggestions or ideas are welcome here. There are still a bunch of leaky abstractions. The program structure class should ideally work for all back ends. 
@qobilidop @rupesh-chiluka-marvell
> Move ProgramStructure out the BMv2 folder such that it can be used in other back ends.

- backends/dpdk/dpdkArch.cpp
- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/p4/sideEffects.cpp
- frontends/p4/sideEffects.h
- midend/hsIndexSimplify.cpp
- midend/simplifyKey.cpp
- testdata/p4_16_samples/issue4775-2.p4
- testdata/p4_16_samples/issue4775.p4
- testdata/p4_16_samples_outputs/issue4775-2-first.p4
- testdata/p4_16_samples_outputs/issue4775-2-frontend.p4
- testdata/p4_16_samples_outputs/issue4775-2-midend.p4
- testdata/p4_16_samples_outputs/issue4775-2.p4
- testdata/p4_16_samples_outputs/issue4775-first.p4
- testdata/p4_16_samples_outputs/issue4775-frontend.p4
- testdata/p4_16_samples_outputs/issue4775-midend.p4
- testdata/p4_16_samples_outputs/issue4775.p4
> Make HasTableApply a resolution context, so it could resolve declarations on its own if desired

- backends/p4tools/common/options.h
- frontends/common/options.cpp
- frontends/common/options.h
- frontends/common/parser_options.cpp
- frontends/common/parser_options.h
- lib/options.cpp
- lib/options.h
- ~Move `P4CContextWithOptions` into the context header and generalize it.~ This is not possible yet. The problem is that `P4CContext::get()` expects a P4CContext object but for back ends a `P4CContextWithOptions<Target>` object is returned.  
- Add validate function to all Option classes.
- Triple slashes for comments. 
- Make the option message configurable.
This could be considered a breaking change.
> P4C Options cleanup

- backends/p4fmt/CMakeLists.txt
- backends/p4fmt/README.md
- backends/p4fmt/main.cpp
- backends/p4fmt/p4fmt.cpp
- backends/p4fmt/p4fmt.h
- backends/p4fmt/ref.p4
- backends/p4fmt/refcheck.cpp
- backends/p4fmt/sample.p4
reference checker for `p4fmt` formatter
> P4Fmt reference checker

- midend/def_use.h
Found while working on https://github.com/p4lang/p4c/pull/4797: Bad things will happen in `loc_t::operator<` when `parent` is `nullptr`.
> Fix `loc_t::operator<` when `parent` is `nullptr`

- backends/dpdk/options.cpp
- backends/dpdk/options.h
- backends/p4tools/modules/smith/options.cpp
- backends/p4tools/modules/smith/options.h
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- frontends/common/parseInput.cpp
- frontends/common/parseInput.h
- frontends/common/parser_options.cpp
- frontends/common/parser_options.h
- frontends/p4/fromv1.0/programStructure.cpp
- lib/options.h
- test/gtest/midend_def_use.cpp
- test/gtest/p4runtime.cpp
- test/gtest/parser_unroll.cpp
There is no compelling reason why the preprocessing function and the `getIncludePath` function should not be the const. I changed the interface such that these functions can be used as const functions. The only thing that doesn't work is `file = "<stdin>", not clear to me how it is used.
> Make preprocess and getIncludePath const functions.

- frontends/p4/actionsInlining.cpp
- frontends/p4/actionsInlining.h
- frontends/p4/commonInlining.h
- frontends/p4/functionsInlining.cpp
- frontends/p4/functionsInlining.h
- testdata/p4_16_samples/issue4796.p4
- testdata/p4_16_samples_outputs/issue4796-first.p4
- testdata/p4_16_samples_outputs/issue4796-frontend.p4
- testdata/p4_16_samples_outputs/issue4796-midend.p4
- testdata/p4_16_samples_outputs/issue4796.p4
- testdata/p4_16_samples_outputs/issue4796.p4-stderr
- Ensure it really can do multiple iterations via clearing stale worklist
- Allow inlining for more complex cases: LHS of assignment and variable initializers
Some cleanup while there
Fixes #4796
> Extend & fix FunctionInliner

- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
Adds a modified version of `loc_t` from the midend def_use pass to the frontend one. Please see discussions in #4500, #4507, #4548 for more context. I did not add any test cases as @mihaibudiu's PRs #4539 and #4727 mask the root problem, but I did verify that these changes also fix the test cases from the below issues with an older version of the compiler that did not have Mihai's fixes yet.
Fixes #4500
Fixes #4507
Fixes #4548
> Map written `LocationSet`s to program locations (`loc_t`) instead of `IR::Expression*`s

- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/doxygen/01_overview.md
- docs/doxygen/Doxymain.md
- docs/doxygen/doxygen.cfg
For better Presentation of content in generated documentation.
- Card links on "p4 Compiler Onboarding" and "Getting Started" 
- migration guide
- compiler design
- "guidelines" link https://p4lang.github.io/p4c/CodingStandardPhilosophy.md#git-commits-and-pull-requests
- "guidelines" link https://p4lang.github.io/p4c/CodingStandardPhilosophy.md#handling-errors
- CI installation script link 
- dependencies installation script
- "rule" link
- bazel/example
- "unsupported P4_16 language features" link https://p4lang.github.io/p4c/backends/bmv2/README.md#unsupported-p4_16-language-features
> Fix: Links in Generated Documentation

- frontends/parsers/p4/p4parser.ypp
- ir/dbprint-p4.cpp
- ir/dbprint-stmt.cpp
- lib/hashvec.cpp
- lib/hvec_map.h
- lib/hvec_set.h
- midend/def_use.cpp
- midend/def_use.h
- test/CMakeLists.txt
- test/gtest/hvec_set.cpp
3 independent changes here
- don't lose annotations on for, and print them properly in dbprint/logging messages
- compute def/use info in functions in midend ComputeDefUse
- use hvec_set instead of ordered_set in midend ComputeDefUse
> misc fixes/additions

- CONTRIBUTING.md
- backends/p4tools/modules/smith/README.md
- #4823
Refactored Absolute links in contribution guidelines to relative links.
This change ensures that the generated documents refer to the correct sections within the Generated docs themselves, instead of redirecting users to GitHub. 
Note: The Changes are compatible in GitHub-flavor Markdown as well.
> Minor Fix: links in P4Smith page

- frontends/common/resolveReferences/resolveReferences.cpp
- frontends/common/resolveReferences/resolveReferences.h
- lib/enumerator.h
Use used `std::unordered_multimap` to store declarations within a namespace having the same name. It turned out it was a bit of overkill:
- In the vast majority of cases namespace only has unique declarations
- There was no multimap in Abseil, so we were unable to use these more efficient maps
- Profiling shows some elevated malloc traffic around these multimaps in downstream applications
This PR switches to:
- Abseil flat_hash_map to store declarations given name
- Use inlined vector to store up to 2 declarations inline within a map (so no additional memory allocation is required in the vast majority of cases)
Few improvements along the way. No functionality change
> Remove multimap usage from `memoizeDeclsByName`

- frontends/p4/dontcareArgs.h
- test/CMakeLists.txt
- test/gtest/remove_dontcare_args_test.cpp
- test/gtest/strength_reduction.cpp
- testdata/p4_16_samples/localize_action_dont_care_args.p4
- testdata/p4_16_samples_outputs/localize_action_dont_care_args-first.p4
- testdata/p4_16_samples_outputs/localize_action_dont_care_args-frontend.p4
- testdata/p4_16_samples_outputs/localize_action_dont_care_args-midend.p4
- testdata/p4_16_samples_outputs/localize_action_dont_care_args.p4
It may be easier for some passes to process action-locals that are actually action-local variables instead of control-local variables in the IR. Also note that we already do this in the `DontcareArgs` pass for functions, but not actions for some reason:
```
const IR::Node *postorder(IR::Function *function) override {
IR::IndexedVector<IR::StatOrDecl> body;
for (auto d : toAdd) body.push_back(d);
body.append(function->body->components);
function->body = new IR::BlockStatement(function->body->srcInfo, body);
toAdd.clear();
return function;
}
```
On `main` branch, the output of `--top4 RemoveDontcareArgs` for the attached test is:
```
struct S {
bit<64> f;
}
control C(inout S s) {
bit<64> arg;
@name("d") action d_0(@name("b") out bit<64> b_0) {
b_0 = 64w4;
}
@name("foo") action foo_0() { …
```
> Make don't care args action-local when used in actions

- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
- backends/p4tools/modules/testgen/testgen.cpp
This is a problem that was not caught in testing. 
The failure isn't caught by the tests because of a nasty side effect of static allocation. gtest initializes the target at some point for another tests and it remains initialized for the tests that should fail.
https://github.com/p4lang/p4c/issues/4286 is relevant here.
> [P4Testgen] Initialize the testgen targets when invoking the library API

- frontends/common/constantFolding.cpp
String literals can also be compared and folded if they are equal or unequal. There might be more cases but I think the changes include the major ones.
> Add string literal support in constant folding.

- frontends/common/constantFolding.cpp
- testdata/p4_16_samples_outputs/constant_folding.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_various_ops-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/issue3289.p4-stderr
IR::Constant throws a warning when the provided value overflows. This can lead to throwing unnecessary duplicated warnings in constant folding when working with shifts.
Instead, we just truncate the shifted bit value to the maximum and pass this value. We still have the option to throw a warning with the `warnings` flag.
> Truncate shifts to the maximum constant bit-width in the constant folding pass.

- backends/p4tools/common/compiler/compiler_target.cpp
- backends/p4tools/common/compiler/compiler_target.h
- backends/p4tools/common/options.h
- backends/p4tools/common/p4ctool.h
- backends/p4tools/modules/testgen/core/target.cpp
- backends/p4tools/modules/testgen/core/target.h
- backends/p4tools/modules/testgen/targets/bmv2/target.cpp
- backends/p4tools/modules/testgen/targets/bmv2/target.h
- backends/p4tools/modules/testgen/test/gtest_utils.cpp
- backends/p4tools/modules/testgen/testgen.cpp
This is a first step of cleaning up dependence on static methods in P4Testgen. Instead of using get(), we pass the compiler options as argument for (most) functions.
This is setup for #4787.
> [P4Testgen] Pass compiler options as argument, instead of getting them with static methods.

- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
- backends/p4tools/modules/testgen/testgen.cpp
More motivation for getting rid of static options. It's just a mess when trying to use P4C as a library.
> [P4Testgen] Hotfix for failing P4Testgen benchmark test.

- backends/p4tools/common/compiler/reachability.cpp
- backends/p4tools/common/compiler/reachability.h
- backends/p4tools/modules/smith/common/statements.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
- frontends/p4/callGraph.h
Clean up some issues with the reachability pass and modernize the code. This pass is barely used so the changes are not of much consequence. This fixes are useful for better control-flow analysis and statistics on program complexity. Hoping to contribute some of this code soon. 
Also add some more getter/setter helper functions to `callgraph.h`.
> [P4Testgen] Fix problems with the reachability pass.

- backends/p4tools/p4tools.def
- ir/expression.def
[solver.h](https://github.com/p4lang/p4c/blob/main/ir/solver.h) is part of the IR folder and uses `IR::SymbolicVariable`. But `IR::SymbolicVariable` is only usable when the p4tools back end is enabled. Move `IR::SymbolicVariable` to the top-level IR.
We can also move `solver.h` into the p4tools folder again. I do not think it is used by other back ends.
> Make SymbolicVariable part of the core IR.

- BUILD.bazel
- backends/p4tools/BUILD.bazel
- backends/p4tools/common/lib/ir_compare.h
- backends/p4tools/common/lib/model.cpp
- backends/p4tools/common/lib/model.h
- backends/p4tools/common/lib/symbolic_env.cpp
- backends/p4tools/common/options.h
- backends/p4tools/modules/testgen/lib/execution_state.cpp
- backends/p4tools/modules/testgen/lib/final_state.cpp
- backends/p4tools/p4tools.def
- ir/compare.h
- ir/expression.def
- ir/solver.h
Yet another variant of #4667 and #4713 but a bit more conservative. 
`btree_map` is a memory-efficient variant of `std::map` which does not require hashing. We can use it to replace `boost::container::flat_map` in P4Tools.
Reason why I am splitting this PR out: 
#4667 introduces some hash functions which are still too inefficient and needs improvement.
#4713 introduces a new data structure (flat_map) which should be reviewed separately. 
The other two PRs will be rebased after this one is in.
> Replace boost::container::flat_map with absl::btree_map in P4Tools.

- backends/bmv2/portable_common/README.md
> Minor fix : Heading of portable_common

- backends/common/portableProgramStructure.cpp
- backends/common/portableProgramStructure.h
The common folder included a bmv2 specific header. This is not necessary. 
@rupesh-chiluka-marvell
> Fix incorrect BMv2 include.

- .github/workflows/deploy-docs.yml
This PR improves the existing functionality of deploying the main branch to GitHub Pages, providing an additional layer of testing for Documentation PRs by enabling previewing pull requests via GitHub Pages.
- **PR Preview:** Each pull request with `documentation` tag will trigger a preview build that is deployed to a unique GitHub Pages URL. The preview is _dynamically updated with the latest changes_ from the PR.
- **Comment Updates:**  automatic comments on PRs with deployment status and links to the preview environment.
- **Handling Broken Builds:** The workflow includes functionality to detect and comment on broken builds,.
This update enhances Documentation PR review process & provides faster Iterations by offering a real-time preview of documentation changes on GitHub Pages. The …
> Feat: PR Preview Workflow via GitHub Pages

- lib/error_reporter.h
- lib/source_file.h
- testdata/p4_16_errors_outputs/issue3727.p4-stderr
- testdata/p4_16_errors_outputs/minWidth.p4-stderr
- testdata/p4_16_errors_outputs/stack_e.p4-stderr
- testdata/p4_16_errors_outputs/type-in-expr.p4-stderr
- testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err5.p4-error
- testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err5.p4-stderr
This ensures we do not see duplicate diagnostics from there.
Some small cleanup while there.
> Ensure correct overload for diagnose() is called even in Transform context

- .github/workflows/deploy-docs.yml
I noticed that when a workflow is triggered by a user commits from a fork, the preview link points to their repository due to the DOMAIN setting using `${{ github.actor }}`. This was causing the preview to point to the forked repository rather than the base repository. I have updated the DOMAIN to use `${{ github.event.pull_request.base.repo.owner.login }}.github.io`, which ensures that the preview link always points to the base repository, regardless of who triggers the workflow.
> Fix: PR Preview URL to Use Base Repository

- backends/bmv2/common/control.h
- backends/bmv2/psa_switch/psaSwitch.h
- backends/p4tools/common/lib/variables.cpp
- backends/p4tools/modules/testgen/test/lib/taint.cpp
- ir/base.def
- ir/expression.def
- ir/type.def
This method is used by backends to get the size of a type, and should only be used for Types for which the concept of `size in bits' makes sense.  Having it return 0 for types that it should not be called for adds to the confusion and possible bugs when it gets called when it shouldn't.  It is suprising to me that having it return 0 for stacks and serializable enums hasn't caused problems before -- bugs waiting to happen.
The existence of this method goes back to the very earliest days of the compiler -- it can be argued that this does not belong here, and it really should be target specific, but the fact that almost all targets will have the same sizes for many things, plus the inability to do multiple dispatch in C++ is what caused it to be implements as a IR::Type virtual method.
> Fixup/cleanup IR::Type::width_bits()

- backends/p4tools/common/lib/format_int.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.cpp
- backends/p4tools/modules/testgen/test/lib/format_int.cpp
Do not return "something" when the bitwidth is zero. Instead handle this case separately. This fixes some problems when trying to test for 0 bit packets emitted in the packet test framework.
> [P4Testgen] Represent bits of width zero as an empty string.

- lib/cstring.cpp
- lib/cstring.h
Signed-off-by: Matthew Lam [matthew.lam.qwerty@gmail.com](mailto:matthew.lam.qwerty@gmail.com)
> Fix ASAN issue in lib/cstring.

- frontends/common/constantFolding.cpp
- frontends/p4/frontend.cpp
- frontends/p4/parseAnnotations.cpp
- frontends/p4/typeChecking/bindVariables.cpp
- frontends/p4/typeChecking/bindVariables.h
- frontends/p4/typeChecking/typeCheckExpr.cpp
- frontends/p4/validateStringAnnotations.h
- testdata/p4_16_errors/spec-issue1297-string-cat-err-0.p4
- testdata/p4_16_errors/spec-issue1297-string-cat-err-1.p4
- testdata/p4_16_errors/spec-issue1297-string-cat-err-2-anno.p4
- testdata/p4_16_errors/spec-issue1297-string-cat-err-3-anno.p4
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-0.p4
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-0.p4-stderr
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-1.p4
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-1.p4-stderr
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-2-anno.p4
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-2-anno.p4-stderr
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-3-anno.p4
- testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-3-anno.p4-stderr
- testdata/p4_16_samples/spec-issue1297-string-cat.p4
- testdata/p4_16_samples_outputs/spec-issue1297-string-cat-first.p4
- testdata/p4_16_samples_outputs/spec-issue1297-string-cat-frontend.p4
- testdata/p4_16_samples_outputs/spec-issue1297-string-cat-midend.p4
- testdata/p4_16_samples_outputs/spec-issue1297-string-cat.p4
- testdata/p4_16_samples_outputs/spec-issue1297-string-cat.p4-stderr
Compiler-side support for https://github.com/p4lang/p4-spec/issues/1297, that is support for compile-time string literal concatenation with `++`.
The type checker and constant folding changes are rather straight forward. For the annotations, the constant folding will run automatically in the structured annotations (`@foo[...]`) but not in the unstructured (`@foo(...)`) unless they are parsed by the compiler explicitly. I've opted to explicitly allow `@name`, `@deprecated` and `@noWarn` to contain expressions, not just strings, which allows using `++` in them. A further catch was that `BindTypeVariables` can try to re-save expression's type into a type map, but if the expression is part of unstructured annotation (e.g. `@deprecated`), it was not type checked and therefore it is not in a …
> Allow concatenation of string literals at compile time

- backends/tc/runtime/pna.h
eBPF has, currently, a stack limit of 512 bytes.
In a scenario where we have declared one instance of struct p4tc_ext_bpf_params, another of struct p4tc_ext_bpf_val and one of struct p4tc_table_entry_act_bpf we have already 420 bytes of stack usage. With a few extra stack variables it's possible to see how the limit will be trivially exceeded. To avoid exceeding this limit so easily, reduce the size of the parameters in the extern structs. As of now, we don't have a use case that would require more than 64 bytes.
> Reduce extern parameters size to 64 bytes

- backends/tc/ebpfCodeGen.cpp
- testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c
- testdata/p4tc_samples_outputs/matchtype_control_blocks.c
- testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
- testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c
- testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c
- testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c
In P4TC, the kernel doesn't expand the returned bpf action with a priority field because, at least as of now, there is no need for such field. So when this priority field is emitted by the compiler, it causes a mismatch between what the kernel returns and what the eBPF program is expecting
> Remove priority field from ternary table's action

- lib/source_file.cpp
- lib/source_file.h
- testdata/p4_14_samples_outputs/sai_p4.p4-stderr
- testdata/p4_16_errors_outputs/issue2835-bmv2.p4-stderr
- testdata/p4_16_pna_errors_outputs/pna-add-on-miss-err.p4-error
- testdata/p4_16_pna_errors_outputs/pna-example-addhit.p4-error
- testdata/p4_16_pna_errors_outputs/pna-example-miss.p4-error
- testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk.p4-stderr
- testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/invalid-hdr-warnings1.p4-stderr
- testdata/p4_16_samples_outputs/invalid-hdr-warnings6.p4-stderr
- testdata/p4_16_samples_outputs/issue4796.p4-stderr
- testdata/p4_16_samples_outputs/issue982.p4-stderr
- testdata/p4_16_samples_outputs/pins/pins_fabric.p4-stderr
- testdata/p4_16_samples_outputs/pins/pins_middleblock.p4-stderr
- testdata/p4_16_samples_outputs/pna-dpdk-invalid-hdr-warnings6.p4-stderr
- testdata/p4tc_samples_outputs/global_action_example_01.p4-stderr
- too-long source lines (particularly those that come from preprocessor macros) tend to give unreadble error messages.  Ideally they should be trimmed based on the width of the output terminal.
This code is a compromise that defaults the trim width to 100 when the `useMarker` flag is defaulted to true (the way this is used for user-facing error messages) and to 0 (no trimming) when the flag is set explicit (generally to false) -- one place this is used is in some logging code.
> Trim overlong source fragments in error messages

- frontends/common/constantParsing.cpp
- frontends/common/constantParsing.h
- ir/id.h
- lib/ordered_map.h
- lib/ordered_set.h
- tools/ir-generator/irclass.cpp
- tools/ir-generator/irclass.h
- tools/ir-generator/methods.cpp
Small changes forked from #4302. 
1. Add operator< to some more nodes.
2. Move the check for `hasNoDirective` in IRClass into a separate helper. 
3. Use this helper to skip generating `operator==` if requested. Also ensure `operator==` is moved to the implementation.
> Add operator< to some compiler classes

- frontends/p4/simplifyDefUse.cpp
- testdata/p4_16_samples_outputs/annotation-bug.p4-stderr
- testdata/p4_16_samples_outputs/equality.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_hdr_out_in_action-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_infinite_loop.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_invalid_hdr_assign-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_invalid_hdr_short_circuit-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_mux_hdr-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_switch_nested_table_apply-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_uninitialized_bool_struct-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/invalid-hdr-warnings4.p4-stderr
- testdata/p4_16_samples_outputs/issue1717.p4-stderr
- testdata/p4_16_samples_outputs/issue1897-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/issue1955.p4-stderr
- testdata/p4_16_samples_outputs/issue2314.p4-stderr
- testdata/p4_16_samples_outputs/issue2957.p4-stderr
- testdata/p4_16_samples_outputs/issue3001-1.p4-stderr
- testdata/p4_16_samples_outputs/issue3001.p4-stderr
- testdata/p4_16_samples_outputs/issue982.p4-stderr
- testdata/p4_16_samples_outputs/parser-inline/parser-inline-test13.p4-stderr
- testdata/p4_16_samples_outputs/subparser-with-header-stack-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/uninit.p4-stderr
Rather than reporting the whole struct, report the specific field(s) that is(are) uninitialized.
> simplifyDefUse: Report the specific uninitialized struct field

- backends/p4tools/modules/smith/common/expressions.cpp
- frontends/common/parser_options.cpp
- frontends/common/parser_options.h
- frontends/p4/toP4/toP4.cpp
- frontends/p4/toP4/toP4.h
This function is static and checks the p4IncludePath which is part of the parser options file. It should be part of this file such that it can be used in other contexts. 
Among others, this call can be used by the formatter or to determine whether a particular source info objects comes from a systems file.
> Make isSystemFile() part of the parser options file.

- frontends/p4/simplify.cpp
- testdata/p4_16_samples_outputs/cases-first.p4
- testdata/p4_16_samples_outputs/issue2617-first.p4
- testdata/p4_16_samples_outputs/issue3619-first.p4
- testdata/p4_16_samples_outputs/psa-switch-expression-without-default-first.p4
- testdata/p4_16_samples_outputs/psa-switch-expression-without-default-frontend.p4
- testdata/p4_16_samples_outputs/psa-switch-expression-without-default-midend.p4
Per 12.7.3 in the spec, a trailing case label in a switch with no code is treated as if it has a `{}` after it; we were instead just removing it.
The main effect here is properly generate an error (later) if that case label is a duplicate, rather than silently removing it.
> Add empty block for trailing case(s) with no code.

- docs/README.md
> [!NOTE]  
> This PR updates the documentation guidelines with improved style guides, Doxygen usage instructions, and new comment markup standards. It’s a work in progress and will be refined once the above PR is merged.
> Docs: Update Documentation Instructions

- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
- frontends/p4/simplifyDefUse.cpp
- lib/flat_map.h
- test/CMakeLists.txt
- test/gtest/flat_map.cpp
As stated in https://github.com/p4lang/p4c/issues/4872 we are seeing high peak memory usage during def-use run. def-use creates lots of temporary objects and expects GC to clean them. However, it seems this does not happen reliably and therefore the peak memory usage could be very high. Especially given that def-use internal state objects (`AllDefinitions`) could be quite large. This PR tries to improve this situation in many aspects:
* Shrink the lifetime of transient objects (this seems to be enough to reduce the memory consumption in the downstream testcase from 16+ Gb down to 2 Gb)
* Reduce the amount of leaks - less work for GC and in many cases less allocation as we are allocating transient things on stack
* Some improvements in internal structures as well
As a result:
- The peak …
> Reduce the number of memory allocations in def-use

- frontends/p4/moveDeclarations.cpp
- frontends/p4/moveDeclarations.h
- testdata/p4_16_samples/issue4901_new_start_with_no_start_loopback.p4
- testdata/p4_16_samples/issue4901_new_start_with_start_state_loopback.p4
- testdata/p4_16_samples/issue4901_new_start_with_start_state_loopback2.p4
- testdata/p4_16_samples_outputs/default-frontend.p4
- testdata/p4_16_samples_outputs/fabric_20190420/fabric-frontend.p4
- testdata/p4_16_samples_outputs/initializers-frontend.p4
- testdata/p4_16_samples_outputs/issue1538-frontend.p4
- testdata/p4_16_samples_outputs/issue2314-frontend.p4
- testdata/p4_16_samples_outputs/issue281-frontend.p4
- testdata/p4_16_samples_outputs/issue2957-frontend.p4
- testdata/p4_16_samples_outputs/issue361-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback-first.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback-frontend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback-midend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback-first.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback-frontend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback-midend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2-first.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2-frontend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2-midend.p4
- testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2.p4
- testdata/p4_16_samples_outputs/parser-conditional-frontend.p4
- testdata/p4_16_samples_outputs/parser-conditional-midend.p4
1. Currently, the `start` state always gets split when a parser contains declaration initializations. The following:
```
parser ...
bit<16> local = 2;
state start {
...
}
...
```
always gets split into:
```
parser ...
bit<16> local = 2;
state start {
...
transition start_0;
}
state start_0 {
...
}
...
```
However, this is only necessary when `start` is reachable from some other state(s). This PR makes it so that the split only happens when `start` is actually reachable from some other state(s).
2. Coincidentally, also fixes #4901
> Split the `start` state more conservatively when a parser contains decl initializers

- frontends/p4/moveDeclarations.cpp
> Only process `IR::Path`s inside of `IR::ParserState` contexts in `MoveInitializers`

- frontends/common/parser_options.h
- frontends/p4/fromv1.0/programStructure.cpp
- lib/compile_context.cpp
- lib/compile_context.h
- lib/error.h
- lib/error_catalog.cpp
- lib/error_catalog.h
- lib/error_reporter.h
- midend/parserUnroll.cpp
~~This reverts a change that was introduced by #4366, and is in fact redundant for the purpose of #4366 (it was originally necessary, but later became redundant after updates were made to that PR). Not only was it redundant, but it also introduced some undesired behavior (see https://github.com/p4lang/p4c/issues/4365#issuecomment-2289309964 and related discussion).~~ Edit: See https://github.com/p4lang/p4c/pull/4894#issuecomment-2332162119
For the following P4 program:
```
header h_t {
bit<28> f1;
bit<4> f2;
}
extern void __e(in bit<28> arg);
control C() {
action foo() {
h_t h;
__e(h.f1);
}
table t {
actions = { foo; }
default_action = foo;
}
apply {
t.apply();
}
}
control proto();
package top(proto p);
top(C()) main;
```
The command-line options `p4test tmp.p4 --dump tmp --Werror …
> Allow `--Wdisable` to take precedence over `--Werror` for warning messages

- frontends/parsers/p4/p4parser.ypp
The P4 spec says that keywords can be used freely in annotation *bodies* with no special meaning.  That sort-of implies they can be used as an annotation name as well, which we previously weren't allowing.
> Allow keywords to be used as annotation names.

- frontends/p4/functionsInlining.cpp
- frontends/p4/functionsInlining.h
- frontends/p4/parameterSubstitution.h
- testdata/p4_16_samples_outputs/issue2345-2-frontend.p4
- testdata/p4_16_samples_outputs/issue2345-2-midend.p4
This is a proposal/work in progress for a way of reducing the number of copies introduced when inlining.
On particularly problematic case is when you have a big struct (eg, all the headers) that is passed around to functions as an `inout` argument so they can access/modify it.  Introducing a copy of all the headers is particularly inefficient, and tough to later optimize away if it was unnecessary.
This change just has a minimal check -- if the actual argument passed to an `inout` or `out` argument is local to the caller, it can't possibly be accessed by the callee directly, so no copy is needed -- the inlined code can just access it directly.
A more general check would be to actually look at the callee -- if it does not access whatever is passed as an argument directly or indirectly, …
> Avoid copying out/inout args when inlining functions

- frontends/common/parser_options.cpp
- frontends/common/parser_options.h
- frontends/p4/frontend.cpp
- frontends/p4/toP4/toP4.h
- Replaced the `cstring` argument in `ToP4` with `std::filesystem::path`. This is the breaking change.
- Cleaned up its constructors to avoid duplication.
- Allow re-using the dumper in `ParserOptions` with a descendant of `ToP4` -- the way I did this is not exactly nice, but I don't see other clear way to create the instance on demand.
- The `ToP4` pass is a good candidate for larger refactoring, but I don't have time for that now.
> Allow extending ToP4, clean its constructors

- ir/type.def
This bug is a mis-translation from java to C++ so has been present in the code for many years and noone ever noticed.
Arguably, this should be done/checked in the irgenerator -- all methods of an interface class should be `virtual`
> Fix Type_Indexed::at

- frontends/common/parser_options.cpp
Came up in #4923. I do not see a reason why the pattern matching here needs to be case-sensitive. Case-insensitive matching can be more convenient.
> Make --top4 matching case-insensitive.

- backends/p4tools/BUILD.bazel
- backends/p4tools/common/compiler/compiler_target.cpp
- backends/p4tools/common/compiler/compiler_target.h
- backends/p4tools/common/compiler/context.h
- backends/p4tools/common/core/target.cpp
- backends/p4tools/common/core/target.h
- backends/p4tools/common/options.cpp
- backends/p4tools/common/options.h
- backends/p4tools/common/p4ctool.h
- backends/p4tools/modules/smith/core/target.cpp
- backends/p4tools/modules/smith/core/target.h
- backends/p4tools/modules/smith/options.cpp
- backends/p4tools/modules/smith/options.h
- backends/p4tools/modules/smith/smith.cpp
- backends/p4tools/modules/testgen/core/target.cpp
- backends/p4tools/modules/testgen/core/target.h
- backends/p4tools/modules/testgen/options.cpp
- backends/p4tools/modules/testgen/options.h
- backends/p4tools/modules/testgen/targets/bmv2/test/gtest_utils.h
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/api_test.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/control_plane_filter_test.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/output_option_test.cpp
- backends/p4tools/modules/testgen/test/gtest_utils.cpp
- backends/p4tools/modules/testgen/test/gtest_utils.h
- backends/p4tools/modules/testgen/testgen.cpp
- backends/p4tools/modules/testgen/testgen.h
- lib/stringify.cpp
- lib/stringify.h
This is a larger rewrite of the core parts of P4Testgen's target initialization. The goal is to fix several problems when trying to use P4Testgen and other tools as a library. We need to make sure that the CompileContext we are accessing is the correct one. 
- We decouple initialization of the options and the initialization of the target. This way we can initialize a target before we even know which options we need. This means we can make the options target-dependent (e.g., different options for BMv2, Tofino, etc). This can be really nice for usability since we can create bespoke options per target. 
- To reduce the amount of random static objects floating around we fold P4ToolsOptions and the CompilerOptions together. There is no reason why need two classes here.
- Options are only …
> [P4Testgen] Unify compiler options and tool options. Ensure options context is always initialized correctly.

- midend/interpreter.cpp
- midend/interpreter.h
- test/gtest/parser_unroll.cpp
- testdata/p4_16_samples/issue4932.p4
- testdata/p4_16_samples_outputs/issue4932-first.p4
- testdata/p4_16_samples_outputs/issue4932-frontend.p4
- testdata/p4_16_samples_outputs/issue4932-midend.p4
- testdata/p4_16_samples_outputs/issue4932.p4
Add support for StringLiteral in ExpressionEvaluator. Fixes #4932
> Fix parser symbolic interpreter to evaluate StringLiteral

- backends/p4tools/common/lib/trace_event_types.cpp
- backends/p4tools/modules/testgen/lib/test_framework.h
- backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
... I think this makes more sense. There is nothing saying traces can't contain newlines, or that the newline can only occur from a limited set of expressions. But test frameworks (presumably both STF and PTF, due to their comment styles) have problems with it. So I move newline stripping to `TestFramework`. This should resolve the problem found in #4943.
> [P4Testgen] Move newline stripping from trace to TestFramework

- ir/indexed_vector.h
- ir/vector.h
`IR::Vector` and `IR::IndexedVector` are often used in other IR nodes (such us `BlockStatement` or `P4Control`), and therefore is often processed by passes. However, up until now it had only un-useful default debug printer. This PR adds simple debug printer for indexed vector. It is mainly useful in debugger, in tests to add context to failed assertion, or in `LOG*` functions.
> Add Vector::dbprint

- CMakeLists.txt
Move add_subdirectory commands for frontends, midend, and control-plane before the extension processing loop. This ensures that classes declared in ir-generated.h from the frontends is available when processing extensions.
> Reorder subdirectory additions in CMakeLists.txt

- lib/log.h
While there is a `LOGGING` macro for checking if given log-level is enabled for the current file, there was no feature counterpart for it. This simple change adds it.
> Add LOGGING_FEATURE macro

- midend/expandLookahead.cpp
Don't leave the PathExpression as Type_Unknown when expanding a lookahead.
Fixes an issue I hit in Tofino code where an expanded lookahead triggers a failure in another pass because `width_bits()` is called on a Type_Unknown object.
> set PathExpression type in ExpandLookahead

- .github/workflows/ci-test-fedora.yml
- tools/install_fedora_deps.sh
The Fedora installation is failing because execution of sudo is not viable any more in the installation script. Let's see whether this workaround can fix it. 
This is the error that occurs within Docker:
```
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
```
> Fix Fedora CI build.

- backends/tc/ebpfCodeGen.cpp
- backends/tc/ebpfCodeGen.h
- p4include/tc/pna.p4
- testdata/p4tc_samples/digest_parser_meta.p4
- testdata/p4tc_samples_outputs/digest_parser_meta.json
- testdata/p4tc_samples_outputs/digest_parser_meta.template
- testdata/p4tc_samples_outputs/digest_parser_meta_control_blocks.c
- testdata/p4tc_samples_outputs/digest_parser_meta_parser.c
- testdata/p4tc_samples_outputs/digest_parser_meta_parser.h
As of now, referencing a field of pna_main_parser_input_metadata_t will cause the it to be generated in eBPF without any translation.
For example:
```
parser Ingress_Parser(
packet_in pkt,
out   my_ingress_headers_t  hdr,
inout my_ingress_metadata_t meta,
in    pna_main_parser_input_metadata_t istd)
{
state mystate {
...
meta->ingress_port = istd.input_port;
...
}
...
}
```
Will generate something like:
```
mystate: {
...
meta->ingress_port = istd.input_port;
...
}
```
This will cause a compilation error because istd is not defined in the ebpf code. This PR fixes this by either translating the fields to something ebpf understands or simply throwing an error if the field is unsupported.
> Handle pna_main_parser_input_metadata_t fields in the tc backend's parser

- tools/driver/CMakeLists.txt
- tools/driver/test_scripts/driver_inputs_test_1___one_bad_pathname.bash
- tools/driver/test_scripts/driver_inputs_test_2___two_bad_pathnames.bash
- tools/driver/test_scripts/driver_inputs_test_3___three_bad_pathnames.bash
- tools/driver/test_scripts/driver_inputs_test_4___two_good_pathnames___check_for_no_misleading_error_messages.bash
- tools/driver/test_scripts/driver_inputs_test___shared_code.bash
Instead of trying to find it via hardcoded paths.
> Require the driver binary as a test input.

- backends/dpdk/CMakeLists.txt
- backends/dpdk/DpdkXfail.cmake
- backends/dpdk/dbprint-dpdk.cpp
- backends/dpdk/dpdk.def
- backends/dpdk/dpdkArch.h
- backends/dpdk/dpdkHelpers.cpp
- backends/dpdk/dpdkHelpers.h
- backends/dpdk/dpdkProgram.cpp
- backends/dpdk/dpdkProgramStructure.h
- backends/dpdk/spec.cpp
- testdata/p4_16_dpdk_errors/dash-pipeline-pna-dpdk.p4
- testdata/p4_16_dpdk_errors_outputs/dash-pipeline-pna-dpdk.p4-error
- testdata/p4_16_dpdk_errors_outputs/dash-pipeline-pna-dpdk.p4.bfrt.json
- testdata/p4_16_samples/pna-ipv6-actions.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions-first.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions-frontend.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions-midend.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4-error
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4-stderr
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.bfrt.json
- testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.spec
- testdata/p4_16_samples_outputs/psa-dpdk-128bitCast.p4.spec
* Added movh statement definition
* Added support for 128 bitwise operation
* Updated testcase and output
> Support for 128 bit bitwise operation

- backends/p4tools/common/compiler/compiler_target.cpp
- backends/p4tools/common/compiler/midend.cpp
- backends/p4tools/common/compiler/midend.h
Ensure that the program is still well-typed at this step. In some scenarios it can happen that a front or mid end pass leaves typing information incomplete or inaccurate which requires a rerun of type checking. There is no invariant enforcing well-typedness of the program.
> [P4Testgen] Run typechecking after front and mid end.

- backends/p4tools/p4tools.def
- ir/type.def
New gcc versions (11+) give a slew of warnings about a mismatched operator delete being called from a new expression.  This trivial change fixes those warnings.
> Fix warning about delete not matching new

- backends/tofino/bf-p4c/CMakeLists.txt
- backends/tofino/bf-p4c/arch/arch.cpp
- backends/tofino/bf-p4c/arch/fromv1.0/programStructure.cpp
- backends/tofino/bf-p4c/arch/fromv1.0/v1_converters.cpp
- backends/tofino/bf-p4c/control-plane/bfruntime_arch_handler.h
- backends/tofino/bf-p4c/ir/mau.cpp
- backends/tofino/bf-p4c/mau/add_always_run.cpp
- backends/tofino/bf-p4c/mau/instruction_selection.cpp
- backends/tofino/bf-p4c/mau/mau_power.cpp
- backends/tofino/bf-p4c/mau/simple_power_graph.cpp
- backends/tofino/bf-p4c/phv/phv_fields.cpp
`BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP` was removed from main P4C a while ago.
> Miscellaneous small Tofino fixes for compilation.

- CHANGELOG.md
Changelogs for [`v1.2.4.16`](https://github.com/p4lang/p4c/pull/4935) & [`v1.2.4.17`](https://github.com/p4lang/p4c/pull/4990)
> Docs : Changelogs release update for `v1.2.4.16` & `v1.2.4.17`

- backends/tc/ebpfCodeGen.cpp
- backends/tc/runtime/pna.h
- backends/tc/tc.def
- testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c
- testdata/p4tc_samples_outputs/tc_may_override_example_04_parser.h
- testdata/p4tc_samples_outputs/tc_may_override_example_05_parser.h
- testdata/p4tc_samples_outputs/tc_may_override_example_06_parser.h
Whilst writing the automated test tools for the tc backend, I ended up finding some compilation bugs when compiling some generated C files from the testdata samples directory
This PR fixes those issues, describes them in more detail in the commit messages and updates `pna.h`
> Small TC fixes

- frontends/p4/def_use.cpp
- frontends/p4/def_use.h
- frontends/p4/moveDeclarations.cpp
- frontends/p4/moveDeclarations.h
- frontends/p4/parserControlFlow.cpp
- frontends/p4/removeParameters.cpp
- frontends/p4/removeReturns.cpp
- frontends/p4/setHeaders.cpp
- frontends/p4/setHeaders.h
- frontends/p4/sideEffects.cpp
- frontends/p4/simplifyParsers.cpp
- frontends/p4/specialize.cpp
- frontends/p4/specialize.h
- frontends/p4/structInitializers.cpp
- frontends/p4/typeChecking/bindVariables.cpp
- frontends/p4/typeChecking/bindVariables.h
- frontends/p4/typeChecking/typeCheckDecl.cpp
- frontends/p4/typeChecking/typeCheckExpr.cpp
- frontends/p4/typeChecking/typeChecker.cpp
- frontends/p4/typeChecking/typeUnification.cpp
- frontends/parsers/p4/p4parser.ypp
- ir/visitor.h
- midend/copyStructures.cpp
- midend/eliminateInvalidHeaders.cpp
- midend/expandEmit.cpp
- midend/flattenInterfaceStructs.h
- midend/flattenUnions.cpp
- midend/local_copyprop.cpp
- midend/local_copyprop.h
- midend/simplifyKey.cpp
The codebase contains some trivial leaks, e.g. when a vector is allocated on heap for no particular reason (it is further used by value) and then just dropped.
Try to fix this in certain places of frontend and midend.
> Remove some trivial leaks in codebase

- backends/tc/introspection.cpp
- testdata/p4tc_samples_outputs/default_action_example_01.json
- testdata/p4tc_samples_outputs/multiple_tables_example_01.json
- testdata/p4tc_samples_outputs/multiple_tables_example_02.json
- testdata/p4tc_samples_outputs/noaction_example_02.json
- testdata/p4tc_samples_outputs/tc_type_annotation_example.json
Generate JSON actions, keys fields array even when they are empty
Also generate keysize = 0 whenever the keysize is zero instead of
omitting it from the JSON file
> Generate JSON actions and keys fields array even when they are empty 

- ir/base.def
- ir/expression.def
- ir/ir.def
- ir/type.cpp
- ir/type.def
- lib/error_reporter.h
- tools/ir-generator/ir-generator.ypp
- tools/ir-generator/irclass.cpp
It does not really make sense to emit them in `ir-generated.cpp` as they are mostly one-liners and could be further simplified.
> Inline some IR methods and constructors

- BUILD.bazel
This file was empty but still present in the PR. Remove it and fix the associated Bazel build file.
> Remove empty v1.def

- CHANGELOG.md
> Docs: Changelogs for `v1.2.5.0`

- .github/workflows/ci-lint.yaml
- backends/tofino/CMakeLists.txt
- backends/tofino/bf-p4c/CMakeLists.txt
- cmake/Linters.cmake
These files are already covered by the scan in `cmake/Linters.cmake`
Also enable linting for Tofino and P4Testgen.
> Remove unnecessary file lists from Tofino CMake.

- ir/base.def
Provide more useful feedback when trying to retrieve content from an annotation the wrong way.
> Add checks to annotation getters.

- backends/tofino/bf-p4c/driver/barefoot.py
- backends/tofino/bf-p4c/driver/p4c.tofino.cfg
- backends/tofino/bf-p4c/driver/p4c.tofino2.cfg
@pkotikal Can you try whether this option works. I do not have a machine with the studio available currently.
> Add a bf-asm command line option in addition to environment variables.

- frontends/p4/specializeGenericTypes.cpp
This pass expects struct expressions in unstructured annotations to have explicit types. Using { } in unstructured annotation is actually allowed by the language spec, it does not make sense for the frontend to prevent this (in fact any sequence of tokens can be used as long as parentheses are balanced).
> Ignore typeless structs in unstructured annotations

- frontends/p4/functionsInlining.cpp
- frontends/p4/functionsInlining.h
- testdata/p4_16_samples/inline-function2.p4
- testdata/p4_16_samples_outputs/inline-function2-first.p4
- testdata/p4_16_samples_outputs/inline-function2-frontend.p4
- testdata/p4_16_samples_outputs/inline-function2-midend.p4
- testdata/p4_16_samples_outputs/inline-function2.p4
The problem is hidden in many cases by side effects ordering, however, it could be further exposed for action arguments after actions inlining.
Without this PR we're ending in ICE trying to perform an inline as inliner can only do this for plain `MethodCallStatement` and `AssignmentStatement`.
> Teach functions inliner to inline into if condition

- lib/error.h
- test/gtest/diagnostics.cpp
There is `errorCount` and `diagnosticCount` but no `warningCount` and no `infoCount`. This PR adds them.
> lib: Add P4::warningCount() and P4::infoCount()

- BUILD.bazel
- CMakeLists.txt
- cmake/GoogleTest.cmake
- cmake/config.h.cmake
- lib/json.h
- lib/source_file.h
There are multiple reasons for this:
- Control fine-grained inclusion. If option changed, not the whole project need to be rebuilt
- `CONFIG_PKGDATADIR` / `CONFIG_PREFIX` are paths and might contain special symbols that might be not so good on command line
- Overall uniformity
> Move all config handling into a single place – a config.h file, do not clutter the command line with these additional project-wide defines.

- lib/enumerator.h
> Fix EnumeratorHandle compilation

- frontends/common/constantFolding.h
- frontends/common/resolveReferences/referenceMap.h
- frontends/common/resolveReferences/resolveReferences.h
- frontends/p4-14/fromv1.0/converters.h
- frontends/p4-14/fromv1.0/programStructure.h
- frontends/p4/parameterSubstitution.h
- frontends/p4/typeChecking/typeSubstitution.h
- frontends/p4/typeMap.h
- frontends/p4/unusedDeclarations.h
- frontends/parsers/p4/abstractP4Lexer.hpp
- frontends/parsers/p4/p4AnnotationLexer.hpp
- ir/configuration.h
- lib/enumerator.h
- lib/error_reporter.h
- lib/exceptions.h
- lib/options.h
- missed overrides
- lack of virtual distructors in the classes with virtual functions
- mised CTAD guides Also, it seems that .hpp files somehow used old p4c coding style and were not updated. Fix is while there.
> Silence some warnings

- ir/indexed_vector.h
- ir/vector.h
Long overdue cleanup I noticed when working on #5133. Apparently these are workarounds for GCC 4.*, we are safe to remove them as we require GCC 9+. A small potential for breaking change due to the `GetImpl` namespace being removed and the `get` for `IR::Vector` moving to `P4::IR` to facilitate ADL. If anyone calls the `get` with explicit namespace (or has explicit `using` on it) they should just remove the namespaces and rely on argument-dependent lookup.
When there, I also slightly modernized parts of the code & fixed some weirdness.
> Remove old vector workarounds, slightly modernize

- backends/p4tools/p4tools.def
- backends/tofino/bf-p4c/ir/arch.def
- backends/tofino/bf-p4c/ir/mau.cpp
- backends/tofino/bf-p4c/ir/mau.def
- backends/tofino/bf-p4c/ir/parde-lowered.def
- backends/tofino/bf-p4c/ir/parde.def
- backends/tofino/bf-p4c/ir/tofino.def
- backends/tofino/bf-p4c/mau/asm_output.cpp
- backends/tofino/bf-p4c/parde/clot/header_validity_analysis.cpp
- backends/tofino/bf-p4c/phv/analysis/build_mutex.cpp
- frontends/p4-14/ir-v1.def
- frontends/p4/functionsInlining.cpp
- ir/base.def
- ir/expression.def
- ir/indexed_vector.h
- ir/ir-inline.h
- ir/ir.def
- ir/loop-visitor.cpp
- ir/namemap.h
- ir/node.h
- ir/nodemap.h
- ir/vector.h
- ir/visitor.cpp
- ir/visitor.h
- tools/ir-generator/methods.cpp
- tools/ir-generator/type.cpp
- tools/ir-generator/type.h
`child_name` is only updated on the context if it is non-empty. Looks like it was a ad-hoc approach to propagate `child_name` for `Vector` / `IndexedVector` as these do not have context and visitation of them looks like as we just unroll the vector.
However, these caused unwanted side effects in many places (and could be easily seen via e.g. dumper pass). Consider, for example, `P4Parser`:
```c++
void IR::P4Parser::visit_children(Visitor & v) const {
Type_Declaration::visit_children(v);
v.visit(type, "type");
v.visit(constructorParams, "constructorParams");
parserLocals.visit_children(v);
states.visit_children(v);
}
```
Here the `child_name` inside `parserLocals.visit_children(v)` and `states.visit_children(v)` would be `constructorParams` and this is not something we'd want (note …
> Consistently set & propagate child names

- .bazelrc
- WORKSPACE.bazel
- bazel/BUILD.z3.bazel
- bazel/example/.bazelrc
- bazel/example/WORKSPACE.bazel
- bazel/p4c_deps.bzl
This is is preparation for migrating to Bzlmod ( #5066), which requires up-to-date versions of all dependencies.
> Bazel build: use Clang and bump rules_foreign and protobuf versions.

- backends/p4test/CMakeLists.txt
- backends/p4test/midend.cpp
- backends/p4test/midend.h
- backends/p4test/p4test.cpp
- backends/p4test/p4test.h
- midend/CMakeLists.txt
- midend/eliminateActionRun.cpp
- midend/eliminateActionRun.h
- testdata/p4_16_samples/elimActRun1.p4
- testdata/p4_16_samples_outputs/elimActRun1-first.p4
- testdata/p4_16_samples_outputs/elimActRun1-frontend.p4
- testdata/p4_16_samples_outputs/elimActRun1-midend.p4
- testdata/p4_16_samples_outputs/elimActRun1.p4
- testdata/p4_16_samples_outputs/elimActRun1.p4-stderr
- testdata/p4_16_samples_outputs/elimActRun1.p4.entries.txtpb
- testdata/p4_16_samples_outputs/elimActRun1.p4.p4info.txtpb
This is a general midend pass for any target that does not support `action_run` directly.  It rewrites the actions in a table that uses action_run to set a newly introduced metadata tmp enum that records which action was run, and changes the switch statement to use that.
It is kind-of logically the reverse of EliminateSwitch, which converts switch statements that *don't* use `action_run()` into ones that do, so it would never make sense to use both passes for a backend.
Need to update p4test so we can select which pass(es) to run in a test by some annotation in the test program to better allow testing this.
> Pass to get rid of action_run() calls

- .github/workflows/ci-ubuntu-p4tc-stf.yml
- backends/tc/CMakeLists.txt
- tools/ci-build.sh
- tools/install_fedora_deps.sh
Opening on behalf of @vbnogueira.
Fixes #5171 temporarily.
> Update p4tc's iproute2 to v17-rc8

- frontends/common/constantFolding.cpp
- frontends/p4/dontcareArgs.h
- frontends/p4/parseAnnotations.cpp
- frontends/p4/removeParameters.cpp
- frontends/p4/removeReturns.cpp
- frontends/p4/sideEffects.cpp
- frontends/p4/simplify.cpp
- ir/annotations.cpp
- ir/base.def
- lib/error_catalog.cpp
- lib/error_catalog.h
- lib/error_reporter.h
- midend/flattenUnions.cpp
- midend/removeExits.cpp
- testdata/p4_16_samples/annotation-likely.p4
- testdata/p4_16_samples_outputs/annotation-likely-first.p4
- testdata/p4_16_samples_outputs/annotation-likely-frontend.p4
- testdata/p4_16_samples_outputs/annotation-likely-midend.p4
- testdata/p4_16_samples_outputs/annotation-likely.p4
- testdata/p4_16_samples_outputs/annotation-likely.p4-stderr
- testdata/p4_16_samples_outputs/fabric_20190420/fabric-midend.p4
- testdata/p4_16_samples_outputs/omec/up4-midend.p4
These will generally be used by backends and simply passed through the frontend/midend, so not much is needed here.
Perhaps some frontend passes (in particular,  DoSimplifyControlFlow in frontends/p4/simplify.cpp) could be extended to understand these -- currently, any annotations on a block will inhibit combining the blocks, whereas `@likely`/`@unlikely` on a block should not inhibit combining it with a block with no annotation (the annotation should be on the resulting combined block).
See discussion in https://github.com/p4lang/p4-spec/issues/1308
> Add @likely/@unlikely annotations for blocks

- testdata/p4_16_errors/issue4365_no_demote_error_to_info.p4
- testdata/p4_16_errors/issue4365_no_demote_error_to_warning.p4
- testdata/p4_16_errors/issue4365_no_disable_error.p4
- testdata/p4_16_errors_outputs/issue4365_no_demote_error_to_info.p4
- testdata/p4_16_errors_outputs/issue4365_no_demote_error_to_info.p4-stderr
- testdata/p4_16_errors_outputs/issue4365_no_demote_error_to_warning.p4
- testdata/p4_16_errors_outputs/issue4365_no_demote_error_to_warning.p4-stderr
- testdata/p4_16_errors_outputs/issue4365_no_disable_error.p4
- testdata/p4_16_errors_outputs/issue4365_no_disable_error.p4-stderr
- testdata/p4_16_samples/issue4365_wdisable_precedence_over_werror.p4
- testdata/p4_16_samples/issue4365_wdisable_precedence_over_werror_control.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror-first.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror-frontend.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror-midend.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror_control-first.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror_control-frontend.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror_control-midend.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror_control.p4
- testdata/p4_16_samples_outputs/issue4365_wdisable_precedence_over_werror_control.p4-stderr
https://github.com/p4lang/p4c/pull/5123 made it very easy to add tests for functionality that is dependent on command-line options, so this PR does that and adds the following test cases:
- Ensure that errors cannot be disabled or demoted to warning or info messages (https://github.com/p4lang/p4c/pull/4366)
- Ensure that `--Wdisable` takes precedence over `--Werror` for warnings (https://github.com/p4lang/p4c/pull/4894)
This also closes #4907.
> [#4365] [#4907] Add test cases related to issue #4365

- .github/workflows/auto-label.yml
This feature provides an automated labeling system for GitHub issues and pull requests based on standardized tags in their titles. The system automatically detects bracketed keywords in titles and applies corresponding labels, streamlining triaging and categorization of contributions.
When an issue or pull request is created or edited, the GitHub Action workflow analyzes its title for bracketed keywords (e.g., `[bug]`, `[feature]`, `[core]`) and automatically applies the relevant labels to the item. This reduces manual labeling work for maintainers and ensures consistent categorization.
https://github.com/user-attachments/assets/8046b884-f24d-4370-833b-23c52f1edbed
The system recognizes the following tags in both issue and PR titles:
- `[core]` → "core"
- `[midend]` → "core"
- `[parser]` …
> Add Auto-Labeling for Issues using GitHub Actions

- frontends/p4/toP4/toP4.cpp
Fixes a problem introduced by #5036 that leads to mismatched output when producing reference files. The error enum is missing some whitespace. I am actually confused why this doesn't trigger mismatches. Possibly because our diff ignores whitespace.
> Fix missing space when emitting error enum with toP4.

- tools/testutils.py
Instead use the standard logging facilities. Also just reuse the initial args for logging instead of the command associated with the process.
> Do not throw a Python exception when the binary to execute is not found.

- backends/bmv2/pna_nic/pnaNic.cpp
- backends/bmv2/portable_common/portable.cpp
- backends/bmv2/psa_switch/psaSwitch.cpp
Fix a pair of BMv2 issues for PNA/PSA:
* DirectCounter: `ExternConverter_DirectCounter::convertExternInstance` was trying to access the 2nd parameter, but DirectCounter only takes a single parameter (the counter type). Adjust to access the 1st parameter.
* InternetChecksum: `ExternConverter_InternetChecksum::convertExternInstance` was incorrectly using `cstring::trim()` instead of `cstring::before` when identifying the block name.
> BMv2: DirectCounter and InternetChecksum fixes

- backends/bmv2/CMakeLists.txt
- backends/bmv2/portable_common/portable.cpp
- tools/driver/p4c_src/p4c.bmv2.cfg
Changes:
* ActionSelector: The`ExternConverter::convertHashAlgorithm()` function expects v1model names (lowercase). Convert PSA/PNA names to v1model names before invoking this function.
* Enable psa and pna backens for BMv2, but print warning messages that these are experimental.
* Add additional psa tests for bmv2:
* Add any psa-* tests in testdata/p4_16_samples that are not dpdk tests. (Although some of these do pass.)
* Update xfails for the handful of fails.
> BMv2: ActionSelector fix + enable backends

- backends/bmv2/CMakeLists.txt
- backends/bmv2/pna_nic/midend.cpp
- backends/bmv2/portable_common/portable.cpp
- backends/bmv2/run-bmv2-test.py
BMv2 PNA fixes:
* Convert `PNA_Direction_t` to a 32b value. (`PNA_Direction_t` is defined in p4include/pna.p4 but not p4include/bmv2/pna.p4)
* Convert TARGET_DEFAULT to CRC16 for the hash algorithm.
Enable some PNA tests in ctest
Note: There are currently multiple versions of pna.p4 that differ from one another (p4include/pna.p4, p4include/bmv2/pna.p4, p4include/tc/pna.p4 and p4include/dpdk/pna.p4). This PR attempts to provide some base-level compatibility with the p4include/pna.p4 file.
> [BMv2] PNA: hash default + enum fix

- backends/bmv2/common/control.h
- testdata/p4_16_samples/psa-bool-ternary-const-entry-bmv2.p4
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2-first.p4
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2-midend.p4
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2.p4
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2.p4-error
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2.p4.entries.txtpb
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2.p4.p4info.txtpb
- testdata/p4_16_samples_outputs/psa-bool-ternary-const-entry-bmv2.p4.spec
Allow use of BoolLiteral (true/false) in a table const entry in ternary field.
Example (from test case):
```
table test_table {
key = {
hdr.ethernet.isValid() : ternary;
}
actions = { ... }
const entries = {
(true) : DummyAction();
}
}
```
@fruffy / @jafingerhut : Please let me know if this is in violation of the P4 spec. AFAIK, it should be fine.
> [bmv2]: allow BoolLiteral in ternary table entry

- backends/bmv2/portable_common/portable.cpp
- testdata/p4_16_samples/psa-metadata-bmv2.p4
- testdata/p4_16_samples_outputs/psa-metadata-bmv2-first.p4
- testdata/p4_16_samples_outputs/psa-metadata-bmv2-frontend.p4
- testdata/p4_16_samples_outputs/psa-metadata-bmv2-midend.p4
- testdata/p4_16_samples_outputs/psa-metadata-bmv2.p4
- testdata/p4_16_samples_outputs/psa-metadata-bmv2.p4.bfrt.json
- testdata/p4_16_samples_outputs/psa-metadata-bmv2.p4.entries.txtpb
- testdata/p4_16_samples_outputs/psa-metadata-bmv2.p4.p4info.txtpb
- testdata/p4_16_samples_outputs/psa-metadata-bmv2.p4.spec
Metadata is added to the `scalarMetadataFields` map in `PortableProgramStructure`. If it's not emitted, then the behavioral model reports errors because fields are not found.
This PR:
* Outputs the content of `scalarMetadataFields`.
* Handles an edge case with the scalar instance name if the `scalars` map is empty.
* Adds a test that fails prior to the fix and passes afterwards.
> [bmv2]: output the scalar metadata fields

- backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tofino1_only/tna_varbit_extract.p4
- backends/tofino/bf-p4c/midend/desugar_varbit_extract.h
- backends/tofino/bf-p4c/parde/extract_parser.cpp
Looks like the annotation was not constructed correctly. Also unsure whether this annotation ever worked in the first place. This attempt tries to fix it. Since we do not know the direction at this point I added an annotation for both directions.
Fixes #5138.
I added the test program to the Tofino tests. Might be worthwhile to add all the tests to a dedicated Tofino directory instead and run the compiler with reference files.
> Correctly attach the dontmerge annotation in the desugar_varbit_extract pass.

- backends/bmv2/CMakeLists.txt
- backends/bmv2/common/action.cpp
- backends/bmv2/portable_common/portable.cpp
Fix the following error with PSA/PNA Random:
```
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```
> [bmv2]: support Random extern for psa/pna

- frontends/p4/frontend.cpp
- frontends/p4/simplifyParsers.h
- testdata/p4_16_samples/issue5211_simplify_parsers_dup_state_local_var_decl.p4
- testdata/p4_16_samples_outputs/issue2176-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl-first.p4
- testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl-frontend.p4
- testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl-midend.p4
- testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl.p4
- testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl.p4-stderr
Fixes #5211 by renaming all state-local variables with equal names before merging states in `SimplifyParsers`
> [#5211] Run `UniqueNames` before `SimplifyParsers` pass

- ir/irutils.h
`Transform` was not wrapped in the P4 namespace.
> [Core] Fix namespace mismatch in irutils.h

- backends/tofino/bf-asm/CMakeLists.txt
It can happen that the generation of `uptr_sizes.h` occurs before `mksizes` has been built.
> [Tofino] Try to fix the dependency of mksizes in bf-asm CMake.

- frontends/p4/sideEffects.cpp
- frontends/p4/sideEffects.h
- frontends/p4/simplify.cpp
- frontends/p4/simplifyDefUse.cpp
- frontends/p4/strengthReduction.cpp
- testdata/p4_16_samples_outputs/issue1985-first.p4
- testdata/p4_16_samples_outputs/strength-first.p4
* use ResolutionContext in P4::SideEffects so a refMap is not needed
* improve StrengthReduction of && and ||
- A && false -> false iff A has no side effects
- A || true -> true iff A has no side effects
> improve SideEffects and StrengthReduction

- cmake/FindBMV2.cmake
Two changes for finding BMv2:
- Remove "build" from the search paths. BMv2 targets are built in `behavioral-model/targets/...` and not in `behavioral-model/build/targets/...`
- Correct search path variable name in pna_nic error message.
Is there any env where BMv2 targets are built in `build/targets`? The README.md instructions always build in `targets`.
> [bmv2] path fixes for finding BMv2

- frontends/common/constantFolding.cpp
- testdata/p4_16_samples/issue5231-const-int-concat.p4
- testdata/p4_16_samples_outputs/issue5231-const-int-concat-first.p4
- testdata/p4_16_samples_outputs/issue5231-const-int-concat-frontend.p4
- testdata/p4_16_samples_outputs/issue5231-const-int-concat-midend.p4
- testdata/p4_16_samples_outputs/issue5231-const-int-concat.p4
- testdata/p4_16_samples_outputs/issue5231-const-int-concat.p4-stderr
Fixes #5231. The problem is most likely in the binary representation of the `big_int` for negative numbers. The solution is to always convert the right operand to a unsigned value with the same representation as does the signed value have.
> Fix compile-time concatenation with negative right operand

- backends/ebpf/runtime/ebpf_common.h
- backends/ebpf/runtime/ebpf_kernel.h
- backends/ebpf/runtime/ebpf_test.h
- tools/install_fedora_deps.sh
- Install missing awk tool.
- Shuffle some includes around for the eBPF tests.
The PTF eBPF failure is unrelated.
> Fix failing Fedora tests.

- backends/tofino/bf-p4c/common/alloc.h
Fixes a compilation error on GCC 12+ where std::tuple<int, int, int> is used without including the <tuple> header.
```
In file included from /builddir/build/BUILD/p4c-1.2.5.5/backends/tofino/bf-p4c/mau/memories.h:24,
from /builddir/build/BUILD/p4c-1.2.5.5/backends/tofino/bf-p4c/mau/jbay_next_table.h:23,
from /builddir/build/BUILD/p4c-1.2.5.5/backends/tofino/bf-p4c/mau/jbay_next_table.cpp:19:
/builddir/build/BUILD/p4c-1.2.5.5/backends/tofino/bf-p4c/common/alloc.h:213:45: error: 'i' has incomplete type
213 |     T &operator[](std::tuple<int, int, int> i) {
|                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /usr/include/c++/12/bits/stl_algobase.h:64,
from /usr/include/c++/12/vector:60,
from /builddir/build/BUILD/p4c-1.2.5.5/backends/tofino/bf-p4c/lib/dyn_vector.h:22,
from …
```
> Fix missing <tuple> include in alloc.h causing compilation failure

- .github/workflows/ci-container-image.yml
We are pushing the CI container image also in merge queues because the check condition is too liberal. Make it more specific.
> Only push docker image when the branch is main. Not on the merge queue.

- backends/p4tools/common/lib/util.cpp
- backends/p4tools/modules/testgen/targets/bmv2/target.cpp
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
- backends/p4tools/modules/testgen/targets/ebpf/target.cpp
- backends/p4tools/modules/testgen/targets/pna/target.cpp
> [P4Testgen] Print and error instead of throwing a BUG when the architecture package does not match.

- frontends/p4/def_use.cpp
When merging `ProgramPoints` for a given location when joining two `Definitions` objects, detect the case where one `ProgramPoints` set is a subset of the other, and avoid the explicit merge.  This avoids unnecessary allocations.
> def_use: Avoid ProgramPoints merge where possible

- frontends/p4/typeChecking/typeCheckStmt.cpp
- testdata/p4_16_errors_outputs/no_warn_const_switch_expr-first.p4
- testdata/p4_16_errors_outputs/no_warn_const_switch_expr-frontend.p4
- testdata/p4_16_errors_outputs/no_warn_const_switch_expr.p4
- testdata/p4_16_errors_outputs/no_warn_const_switch_expr.p4-stderr
- testdata/p4_16_samples_outputs/issue2617.p4-stderr
- testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args.p4-stderr
- testdata/p4_16_samples_outputs/pragma-string.p4-stderr
- testdata/p4_16_samples_outputs/psa-example-switch-with-constant-expr.p4-error
- testdata/p4_16_samples_outputs/psa-example-switch-with-constant-expr.p4-stderr
- testdata/p4_16_samples_outputs/psa-switch-expression-without-default.p4-error
- testdata/p4_16_samples_outputs/psa-switch-expression-without-default.p4-stderr
- testdata/p4_16_samples_outputs/string_anno.p4-stderr
This warning is not very useful IMO, as there are many ways that a `switch` expression that is originally non-constant could become constant after a number of transformations are applied. For example, it could become constant after inlining and copy-propagation. The effects of having a const `switch` expression are benign - the entire `switch` statement will likely just be optimized away.
> Do not emit a warning when a `switch` expression is constant

- ir/loop-visitor.cpp
- ir/pattern.h
- midend/def_use.cpp
- midend/def_use.h
- midend/unrollLoops.cpp
- testdata/p4_16_samples/forloop8.p4
- testdata/p4_16_samples/forloop9.p4
- testdata/p4_16_samples_outputs/forloop8-first.p4
- testdata/p4_16_samples_outputs/forloop8-frontend.p4
- testdata/p4_16_samples_outputs/forloop8-midend.p4
- testdata/p4_16_samples_outputs/forloop8.p4
- testdata/p4_16_samples_outputs/forloop8.p4-stderr
- testdata/p4_16_samples_outputs/forloop9-first.p4
- testdata/p4_16_samples_outputs/forloop9-frontend.p4
- testdata/p4_16_samples_outputs/forloop9-midend.p4
- testdata/p4_16_samples_outputs/forloop9.p4
- testdata/p4_16_samples_outputs/forloop9.p4-stderr
Discovered a problem with loop unrolling where the update was an opAssign that had not been expanded.  Also some Pattern improvements for matching AssignmentStatements.
> Fixes and improvements for loop unrolling

- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
- backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
- ir/irutils.cpp
StructExpression entries are NamedExpressions, so we might peel to underlying expression to recurse further.
> Fix copy & paste typo in flattenStructExpression

- README.md
- backends/p4fmt/attach.h
- backends/tofino/bf-asm/parser-tofino-jbay.h
- backends/tofino/bf-asm/vector.h
- backends/tofino/bf-p4c/common/merge_pov_bits.cpp
- backends/tofino/bf-p4c/midend/eliminate_tuples.h
- backends/tofino/bf-p4c/midend/initialize_mirror_io_select.h
- backends/tofino/bf-p4c/p4c-barefoot.cpp
- backends/tofino/bf-p4c/phv/solver/action_constraint_solver.h
- backends/tofino/bf-p4c/phv/v2/allocator_base.h
- backends/tofino/bf-p4c/phv/v2/greedy_allocator.h
- frontends/p4/parseAnnotations.h
- pyproject.toml
`ninja clang-format` currently fails on `main` branch when run locally. Perhaps the CI is not enforcing clang-formatting for these files?
> Upgrade `clang-format` to v18.1.8

- backends/tofino/bf-p4c/driver/barefoot.py
- tools/driver/p4c_src/driver.py
- tools/driver/p4c_src/main.py
The --Werror/--Wdisable/--gdb/--cgbd/--lldb arguments were in the barefoot.py driver program, which meant that for all targets except tofino, they would be accepted but ignored.  This moves them to the top-level driver so they are usable by all targets.
> Make useful driver arguments available on all targets

- frontends/p4/evaluator/substituteParameters.cpp
- testdata/p4_16_samples/issue5331_srcinfo.p4
- testdata/p4_16_samples_outputs/gauntlet_short_circuit-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/gauntlet_side_effect_order_1-bmv2.p4-stderr
- testdata/p4_16_samples_outputs/issue1717.p4-stderr
- testdata/p4_16_samples_outputs/issue5331_srcinfo-first.p4
- testdata/p4_16_samples_outputs/issue5331_srcinfo-frontend.p4
- testdata/p4_16_samples_outputs/issue5331_srcinfo-midend.p4
- testdata/p4_16_samples_outputs/issue5331_srcinfo.p4
- testdata/p4_16_samples_outputs/issue5331_srcinfo.p4-stderr
Addresses the issue of propagating source info during action and function inlining, discussed in #5331.
> [#5331] Propagate source info when substituting parameters during inlining

- frontends/p4/typeChecking/typeCheckTypes.cpp
- testdata/p4_16_errors/enumcrash1.p4
- testdata/p4_16_errors_outputs/enumcrash1.p4
- testdata/p4_16_errors_outputs/enumcrash1.p4-stderr
A corner case where after an error, we keep running typechecking in a slightly invalid state, so we could hit this BUG
> Avoid crash after error in typechecking

- backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
- backends/p4tools/modules/testgen/core/small_step/table_stepper.h
Attempting to implement an extern function within testgen that returns `true` if the action this function was called from was executed as the result of a hit, `false` otherwise. In other words, `false` if taking the default action, otherwise `true`.
This would require to have access to the table context, or some way to access the already existing `TableStepper::getTableHitVar()` within the relevant target's `expr_stepper` file. This would mean we would have to propagate the `P4Table` from `TableStepper::evalTargetTable()` to our `TargetExprStepper::evalExternMethodCall()`
Instead, I added this `TableStepper::getGlobalTableHitVar()` to be able to tell within testgen whether the current action being executed was a result of a table hit or miss.
@fruffy would you possibly know a better way …
> [P4Testgen] Add global table hit variable to testgen table stepper

- frontends/p4/typeChecking/typeCheckExpr.cpp
- frontends/p4/typeChecking/typeUnification.cpp
- testdata/p4_16_errors/enumcrash2.p4
- testdata/p4_16_errors_outputs/enumCast.p4-stderr
- testdata/p4_16_errors_outputs/enumcrash2.p4
- testdata/p4_16_errors_outputs/enumcrash2.p4-stderr
- testdata/p4_16_errors_outputs/issue2220.p4-stderr
- testdata/p4_16_errors_outputs/issue3534.p4-stderr
- testdata/p4_16_errors_outputs/serEnumImplCast.p4-stderr
- testdata/p4_16_errors_outputs/serenum-type.p4-stderr
- testdata/p4_16_errors_outputs/serenum-typedef.p4-stderr
- implicit casts FROM the underlying type TO the serializable enum type are not allowed, so should be errors
- when matching a serializable enum in a select/case, use the underlying type for unification, as case tags may be either the serenum type or the underlying type.
> Fix unification of serializable enums

- frontends/p4/sideEffects.cpp
- testdata/p4_16_samples_outputs/issue2176-bmv2.p4-stderr
The following code will print warnings for each `e` in `modifies` in a non-deterministic order:
```
for (auto p : *mi->substitution.getParametersInArgumentOrder()) {
if (useTemporary.find(p) != useTemporary.end()) continue;
auto arg = mi->substitution.lookup(p);
if (typeMap->isCompileTimeConstant(arg->expression)) continue;
for (auto e : modifies) {
// Here we use just raw equality: equivalent but not equal expressions
// should be compared.
if (e != arg->expression && mayAlias(arg->expression, e, getContext())) {
LOG3("Using temporary for " << dbp(mce) << " param " << dbp(p) << " aliasing"
<< dbp(e));
if (p->hasOut())
warn(ErrorType::WARN_ORDERING,
"%1%: 'out' argument has fields in common with %2%", arg, e);
useTemporary.emplace(p);
break;
}
}
}
```
> Print warnings in a deterministic order

- midend/interpreter.cpp
- testdata/p4_16_samples/parser-unroll-test1.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1-first.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1-frontend.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1-midend.p4
- testdata/p4_16_samples_outputs/parser-unroll-test1.p4
Extended `ExpressionEvaluator` to correctly evaluate `Type_InfInt` type and operations.
> Extended Type_InfInt handling in ExpressionEvaluator

- backends/ebpf/ebpfType.cpp
- backends/ebpf/ebpfType.h
- backends/tc/ebpfCodeGen.cpp
- backends/tc/ebpfCodeGen.h
- testdata/p4tc_samples_outputs/digest_parser.h
- testdata/p4tc_samples_outputs/digest_parser_meta_parser.h
The p4tc control path expects the digest message to be packed
For example, in testdata/p4tc_samples/digest.p4 we have the following
struct being sent throught digest pack:
```
struct mac_learn_digest_t {
@tc_type("macaddr") bit<48> srcAddr;
@tc_type("dev") PortId_t ingress_port;
};
```
As an eBPF C struct, this will be:
```
struct mac_learn_digest_t {
u8 srcAddr[6]; /* bit<48> */
u32 ingress_port; /* PortId_t */
};
```
Notice that this will create padding between srcAddr
and ingress_port. To avoid this we are making structs associated with
digest messages packed. So the previous struct will become:
```
struct __attribute__((__packed__)) mac_learn_digest_t {
u8 srcAddr[6]; /* bit<48> */
u32 ingress_port; /* PortId_t */
};
```
> Make struct used by digest in p4tc packed 

- frontends/p4/simplifySwitch.cpp
- testdata/p4_16_samples/issue2617.p4
- testdata/p4_16_samples_outputs/issue2617-first.p4
- testdata/p4_16_samples_outputs/issue2617-frontend.p4
- testdata/p4_16_samples_outputs/issue2617-midend.p4
- testdata/p4_16_samples_outputs/issue2617.p4
- testdata/p4_16_samples_outputs/issue2617.p4-stderr
We have this nice `EnumInstance` stuff for resolving enums of all kinds, so we should use it.
fixes #5269
> Fix simplifySwitch handling of enums
